### ISSUE TITLE
LF not matched in Body extraction

### ISSUE THREAD

**Issue by ldjvc** [amabnl/amadeus-ws-client#10]
Hi Dieter, I found a small issue in Amadeus\Client\Util\MsgBodyExtractor.php

I haven't seen this before but in one PNR that I retrieved I got a single Line Feed char near the start of a <longFreeText> node. This caused the regex in the body extraction function to not match and the function returns a null messageBody. By applying the 's' modifier to the regex it works. As I said, I haven't seen anything like that before, normally I don't get any newlines or other control chars in the responses.

In MsgBodyExtractor.php I changed line 38 from:

`const REGEXP_SOAP_ENVELOPE_CONTENTS = "|\\<SOAP-ENV:Body\\>(.*?)\\<\\/SOAP-ENV:Body\\>|";`

To:

`const REGEXP_SOAP_ENVELOPE_CONTENTS = "|\\<SOAP-ENV:Body\\>(.*?)\\<\\/SOAP-ENV:Body\\>|s";`

I don't see any particular restriction in the WSDL on the return type for longFreeText so maybe this should be handled by the regex. If it's a bad char and shouldn't be in the response then I guess that would up to the application to trap.

**Comment by DerMika** [comment]
Good catch! Your solution looks fine for me. 

Do you want to to submit a PR and a testcase of a sample PNR to validate? Make sure you. Remove any sensitive information from it such as office ID's, passenger names & contact info etc.

**Comment by ldjvc** [comment]
Hi Dieter,

my apologies, meant to get back to you sooner. I can't submit a pull 
request, the GIT repo I am using is in a secured dev area with no 
Internet access. Sorry about that. It's contract, I don't have much say 
in how the environment is set up.

Regards,

David.

**Comment by DerMika** [comment]
In that case can you at least give some information about how I could reproduce the issue you encountered? 

> one PNR that I retrieved I got a single Line Feed char near the start of a node

Where in the PNR_reply did you get line feed characters? Was it for example a hotel segment? A Remark? ... I've never seen such a PNR so I'd like to get an actual sample of one to throw in my unittests.

**Comment by ldjvc** [comment]
This may be more of a Selling Platform end-user issue. The text involved was generated by a "Smart Key" or "Smart Flow" within the Selling Platform so maybe it's not a GDS issue as such. I tried pasting the XML response into this message in a code section but the linefeed is removed when I do that. The linefeed is (or was) directly after the "*" in the longFreetext node shown below. Part of an itineraryInfo node from a response to PNR_Retrieve. The segment was a non-automated Tour that was being generated via a SmartKey.

`<longFreetext>*
?-SU-SYD/PUA1-200 GEORGE ST/PUT-0830/SUP INFO 1-DAY TOUR GREATER SYDNEY/SUP INFO 2-REFRESHMENTS &amp; LUNCH/DOT-1700/DOA1-200 GEORGE ST/CF-3574562</longFreetext>`

**Comment by DerMika** [comment]
The fix for this issue has been pushed to the develop branch. It will be merged to master soon<sup>(tm)</sup>
