### ISSUE TITLE
PNR Not Preset Error

### ISSUE THREAD

**Issue by mostafaahamidmanon** [amabnl/amadeus-ws-client#100]
Hello,
I received the response that follows:
![screenshot from 2017-10-08 12 32 09](https://user-images.githubusercontent.com/6308541/31316021-d37f839c-ac24-11e7-9bfb-a25cde84f906.png)

And here is my opts:

$pricingResponse = $client->farePricePnrWithBookingClass(
            new FarePricePnrWithBookingClassOptions([
                'pricingsFareBasis' => [
                        new FareBasis([
                            'fareBasisCode' => 'QNC469W2',
                            'references' => [
                                new PaxSegRef([
                                    'reference' => 1,
                                    'type' => PaxSegRef::TYPE_SEGMENT
                                ]),
                                new PaxSegRef([
                                    'reference' => 2,
                                    'type' => PaxSegRef::TYPE_SEGMENT
                                ])
                            ]
                        ])
                    ]
            ])
        );

I have created and saved the PNR in the previous step but received this response...
May I know what is the problem?

**Comment by DerMika** [comment]
Are you using a [stateful session](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#switching-between-stateful-stateless-messages-soap-header-4)?

**Comment by mostafaahamidmanon** [comment]
No, I am using stateless session

**Comment by DerMika** [comment]
Well then that is your problem. 

As soon as you start using messages that interact with a PNR, you need to use stateful sessions, place the PNR in the session context (with a PNR_Retrieve for example) and then perform your messages inside the stateful session.

**Comment by mostafaahamidmanon** [comment]
I will try that.

**Comment by mostafaahamidmanon** [comment]
I have switched to stateful session, created the PNR, retreived the PNR, but if I price the PNR, still tells me PNR NOT PRESENT, and I have another error when I issue an e-ticket with NEED NAMES error.

**Comment by DerMika** [comment]
The moment you create the PNR, you should be in a stateful session. If you save the PNR with `ACTION_END_TRANSACT_RETRIEVE`, and stay in context, you should still have the PNR in context at that point. Then you can immediately price the PNR in context. 

Of course, a (stateful) session does not persist between instances of the `Amadeus\Client`! If you need to persist session data, you need to get the session data from the client with `$client->getSessionData();`, store that array somewhere, and then when re-instantiating your client, provide that array again to the client with `$client->setSessionData($previousSessionData);`.

**Comment by mostafaahamidmanon** [comment]
Yes, I figured out that.
Now, it is working so fine.
You are really helpful and fast.

**Comment by dilshanvitte** [comment]
Hi DerMika,

I am also getting stuck on this error, im using Codeigniter HMVC, i just check my request and response, in in all the my request TransactionStatusCode is "Start", i have applied above your solutions also, im using stateful request for all request. i got response from PNR_AddMultiElements option code with 0, but i cant go ahead with farePricePnrWithBookingClass.

My Client
`$par = new Params([
          'authParams' => [
                'officeId' => $this->layout->config_info('List_of_offices'),
                'originatorTypeCode' => $this->layout->config_info('originatorTypeCode'),
                'userId' => $this->layout->config_info('WBS_User_ID'),
                'passwordData' => base64_encode($this->layout->config_info('Clear_Password'))
            ],
            'sessionHandlerParams' => [
                'wsdl' => $this->layout->config_info('WSDL_URL'),
                'soapHeaderVersion' => Client::HEADER_V4,
                'stateful' => true,
                'logger' => '',
            ],
            'requestCreatorParams' => [
                'receivedFrom' => 'Travels IBE'
            ]
        ]);
        $this->client = new Client($par);`

**Comment by DerMika** [comment]
If your transactionStatusCode for the `Fare_PricePnrWithBookingClass` message is 'start', that means the message initiates a new session instead of continuing in an existing session (`transactionStatusCode=InSeries`). 

You will likely have to preserve the session state between requests to your application, since each time the `Amadeus\Client` is initialized, it will start a new session by default.

You can do this by getting session information from the client after it made a request with `$client->getSessionData();` and then on subsequent requests continue this session like this: 

```php
$previousSessionData = [
    'sessionId' => 'XFHZEKLRZHREJ',
    'sequenceNumber' => 5,
    'securityToken' => 'RKLERJEZLKRHZEJKLRHEZJKLREZRHEZK'
];

$client->setSessionData($previousSessionData);
```

**Comment by dilshanvitte** [comment]
Do you say, when i get response in that time store session data using getSessionData(), in the second request again set previous stored session data by using setSessionData(),

i checked not setting any values for getSessionData()

**Comment by DerMika** [comment]
I'm not sure what you're trying to say.

**Comment by dilshanvitte** [comment]
Thank you DerMika, Solved my Issue,
I have managed session in application level.

Thank you so much for you quick response.
