### ISSUE TITLE
Need Names Error

### ISSUE THREAD

**Issue by mostafaahamidmanon** [amabnl/amadeus-ws-client#101]
Hello,
While working on DocIssuance, I faced the attached error:
![screenshot from 2017-10-08 13 35 33](https://user-images.githubusercontent.com/6308541/31316436-97a46fa0-ac2d-11e7-93e2-cd40ec00dbba.png)
and here is my $opts:

```php
$issueTicketResponse = $client->docIssuanceIssueTicket(
            new DocIssuanceIssueTicketOptions([
                'options' => [
                    DocIssuanceIssueTicketOptions::OPTION_ETICKET
                ],
                'compoundOptions' => [
                    new CompoundOption([
                        'type' => CompoundOption::TYPE_ET_CONSOLIDATOR,
                        'details' => '1A'
                    ])
                ],
                'travellers' => [
                    new Traveller([
                        'number' => 1,
                        'lastName' => 'Manon',
                        'firstName' => 'Niazi',
                        'telephone' => '+201281971948',
                    ])
                ],
                'elements' => [
                    new Contact([
                        'type' => Contact::TYPE_EMAIL,
                        'value' => 'cyberteen_de@yahoo.com'
                    ]),
                    new Contact([
                        'type' => Contact::TYPE_PHONE_MOBILE,
                        'value' => '+3222222222'
                    ]),
                    new Contact([
                        'type' => Contact::TYPE_PHONE_GENERAL,
                        'value' => '003222222222'
                    ]),
                ],
                'passengers' => [
                    new MPPassenger([
                        'type' => MPPassenger::TYPE_ADULT,
                        'count' => 1
                    ]),
                    new MPPassenger([
                        'type' => MPPassenger::TYPE_CHILD,
                        'count' => 1
                    ])
                ],
                'flightOptions' => [
                    TicketAtcShopperMpTbSearchOptions::FLIGHTOPT_PUBLISHED,
                    TicketAtcShopperMpTbSearchOptions::FLIGHTOPT_UNIFARES
                ],
                'itinerary' => [
                    new MPItinerary([
                        'segmentReference' => 1,
                        'departureLocation' => new MPLocation(['city' => 'MAD']),
                        'arrivalLocation' => new MPLocation(['city' => 'LHR']),
                        'date' => new MPDate([
                            'date' => new \DateTime('2013-08-12T00:00:00+0000', new \DateTimeZone('UTC'))
                        ])
                    ]),
                    new MPItinerary([
                        'segmentReference' => 2,
                        'departureLocation' => new MPLocation(['city' => 'LHR']),
                        'arrivalLocation' => new MPLocation(['city' => 'MAD']),
                        'date' => new MPDate([
                            'date' => new \DateTime('2013-12-12T00:00:00+0000', new \DateTimeZone('UTC'))
                        ])
                    ])
                ],
            ])
        );
```
Do you have an idea

**Comment by mostafaahamidmanon** [comment]
Now, I have created the PNR with ACTION_END_TRANSACT_RETRIEVE with the following $opts

$createPnrOptions = new PnrCreatePnrOptions([
            'travellers' => [
                new Traveller([
                    'number' => 1,
                    'lastName' => 'Manon',
                    'firstName' => 'Niazi',
                    'telephone' => '+201281971948',
                ])
            ],
            'actionCode' => PnrCreatePnrOptions::ACTION_END_TRANSACT_RETRIEVE,
            'itineraries' => [
                new Itinerary([
                    'origin' => 'CAI',
                    'destination' => 'TUN',
                    'segments' => [
                        new Air([
                            'date' => \DateTime::createFromFormat('Y-m-d His', "2017-10-10 000000", new \DateTimeZone('UTC')),
                            'origin' => 'CAI',
                            'destination' => 'TUN',
                            'flightNumber' => '814',
                            'bookingClass' => 'M',
                            'company' => 'TU'
                        ])
                    ]
                ])
            ],
            'elements' => [
                new \Amadeus\Client\RequestOptions\Pnr\Element\Ticketing([
                    'ticketMode' => Ticketing::TICKETMODE_OK
                ]),
                new Contact([
                    'type' => Contact::TYPE_EMAIL,
                    'value' => 'cyberteen_de@yahoo.com'
                ]),
                new Contact([
                    'type' => Contact::TYPE_PHONE_MOBILE,
                    'value' => '+3222222222'
                ]),
                new Contact([
                    'type' => Contact::TYPE_PHONE_GENERAL,
                    'value' => '003222222222'
                ]),
            ],
        ]);

And the response is okay as attached.
But, when I issue an e-ticket, it gets me this error, NEED NAMES

**Comment by DerMika** [comment]
Are you using a stateful session between the PNR creation and the Docissuance message?

**Comment by mostafaahamidmanon** [comment]
No, I am using stateless session

**Comment by mostafaahamidmanon** [comment]
Is it a must to switch to stateful session?

**Comment by DerMika** [comment]
Yes.

**Comment by mostafaahamidmanon** [comment]
I have switched to stateful session, created the PNR, retreived the PNR, but if I price the PNR, still tells me PNR NOT PRESENT, and I have another error when I issue an e-ticket with NEED NAMES error.

**Comment by mostafaahamidmanon** [comment]
Solved it with you response on the other issue and the same issue is here because of the same reason and solved.

Thanks
