### ISSUE TITLE
adding options 

### ISSUE THREAD

**Issue by ahmedeltokhy** [amabnl/amadeus-ws-client#103]
Hello 
I have a problem in adding options of the ticket pricing to get the lowest fares I need to put the options like the following XML in the function Fare_MasterPricerCalendar
```
<fareOptions>
      <pricingTickInfo>
         <pricingTicketing>
            <priceType>RP</priceType>
            <priceType>RU</priceType>
            <priceType>TAC</priceType>
         </pricingTicketing>
      </pricingTickInfo>
   </fareOptions>
```
your support is really appreciated.

Thanks & best regards

**Comment by DerMika** [comment]
Look at [this sample](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/masterpricertravelboard.rst#fare-types--corporate-codes) for `MasterPricerTravelBoardSearch`. This option is the same for both messages _(in general the MasterPricer Calendar request message is identical to the MasterPricer Travelboard Search)_: 

```php
use Amadeus\Client\RequestOptions\FareMasterPricerCalendarOptions;

$opt = new FareMasterPricerCalendarOptions([
    //Other options removed for demo
    'flightOptions' => [
        FareMasterPricerCalendarOptions::FLIGHTOPT_PUBLISHED,
        FareMasterPricerCalendarOptions::FLIGHTOPT_UNIFARES,
        'TAC',
    ],
]);
````
_The library does not have a constant for 'TAC' yet, but you can just use a literal string too if you need to._

**Comment by DerMika** [comment]
On the Master branch I've added the masterpricer constant for ticket availability check. If you're running version `dev-master` you can now use

```php
use Amadeus\Client\RequestOptions\FareMasterPricerCalendarOptions;

$opt = new FareMasterPricerCalendarOptions([
    //Other options removed for demo
    'flightOptions' => [
        FareMasterPricerCalendarOptions::FLIGHTOPT_PUBLISHED,
        FareMasterPricerCalendarOptions::FLIGHTOPT_UNIFARES,
        FareMasterPricerCalendarOptions:: FLIGHTOPT_TICKET_AVAILABILITY_CHECK,
    ],
]);
```
This will be released with version 1.5.

**Comment by ahmedeltokhy** [comment]
yes, it is worked fine.

Thanks a lot.

**Comment by DerMika** [comment]
version 1.5.0 is released, so you can now use the constant I mentioned above if you do a `composer upgrade`.
