### ISSUE TITLE
I need to print the current session id

### ISSUE THREAD

**Issue by mostafaahamidmanon** [amabnl/amadeus-ws-client#104]
Greetings,
I need to print the current session id of my current request.
Thanks

**Comment by DerMika** [comment]
[This section of the docs](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#handling-sessions-with-soap-header-2) provides the info you need:

```php
$client->getSessionData();
```
will return an array containing Session ID, Sequence Number and Security token of the active session.

**Comment by mostafaahamidmanon** [comment]
Thanks
