### ISSUE TITLE
Documentation on SalesReports_DisplayQueryReport

### ISSUE THREAD

**Issue by keyur-padalia** [amabnl/amadeus-ws-client#106]
I am trying to get some documentation on this Amadeus' SalesReports_DisplayQueryReport API, when I access my Amadeus extranet it doesn't show any documentation link to this API.

If anyone has access to these documentations please share with me.

**Comment by DerMika** [comment]
You can ask Amadeus to get access to the docs for this message in your Extranet access.

**Comment by keyur-padalia** [comment]
Thanks DerMika, I did last week and I just got my extranet updated and now I have access to those docs.

**Comment by DerMika** [comment]
Ok, then I'll close this issue
