### ISSUE TITLE
Security Signout

### ISSUE THREAD

**Issue by mostafaahamidmanon** [amabnl/amadeus-ws-client#107]
Hello and Greetings,
How can I make a security signout to close the session?
Thanks

**Comment by DerMika** [comment]
`$client->securitySignOut();`should do it. 

This is all written down nicely [in the docs](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#ending-a-stateful-session-soap-header-4) ;)

**Comment by DerMika** [comment]
Added a section to the page with examples for all messages too now: https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples.rst#security

**Comment by mostafaahamidmanon** [comment]
Thanks
