### ISSUE TITLE
DocIssuance_IssueTicket function error response

### ISSUE THREAD

**Issue by ahmedeltokhy** [amabnl/amadeus-ws-client#109]
Hello All 
I used the function "DocIssuance_IssueTicket" to issue ticket but I received the following error response

> {"status":"ERR","messages":[{"code":"82","text":"DUPLICATE SEGMENT 2\/3\nWARNING: SECURE FLT PASSENGER DATA REQUIRED FOR TICKETING PAX 1\nWARNING: SV REQUIRES TICKET ON OR BEFORE 25OCT:1200\/S2-3","level":null}],"response":{"processingStatus":{"statusCode":"X"},"errorGroup":{"errorOrWarningCodeDetails":{"errorDetails":{"errorCode":"82"}},"errorWarningDescription":{"freeTextDetails":{"textSubjectQualifier":"3","source":"M","encoding":"1"},"freeText":"DUPLICATE SEGMENT 2\/3\nWARNING: SECURE FLT PASSENGER DATA REQUIRED FOR TICKETING PAX 1\nWARNING: SV REQUIRES TICKET ON OR BEFORE 25OCT:1200\/S2-3"}}},"responseXml":"X<\/statusCode><\/processingStatus>82<\/errorCode><\/errorDetails><\/errorOrWarningCodeDetails>3<\/textSubjectQualifier>M<\/source>1<\/encoding><\/freeTextDetails>DUPLICATE SEGMENT 2\/3\nWARNING: SECURE FLT PASSENGER DATA REQUIRED FOR TICKETING PAX 1\nWARNING: SV REQUIRES TICKET ON OR BEFORE 25OCT:1200\/S2-3<\/freeText><\/errorWarningDescription><\/errorGroup><\/DocIssuance_IssueTicketReply>"}

**Comment by ahmedeltokhy** [comment]
I already fixed the error still the warning "SECURE FLT PASSENGER DATA REQUIRED FOR TICKETING PAX 1\nWARNING: SV REQUIRES TICKET ON OR BEFORE 25OCT:1300\/S2"

**Comment by DerMika** [comment]
Hi, 

Sometimes you can actually find the answer on Google! ;) Here is the Amadeus Service hub article I find when googling your first error: https://servicehub.amadeus.com/c/portal/view-solution/935734/en_US/warning-secure-flt-passenger-data-required-for-ticketing-pax

(a sample how to add APIS using this library [can be found here](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/pnr-create-modify.rst#apis-passport-or-identity-card)).

The last warning isn't very important, it's just a message from the airline telling you that you have to issue a ticket before a certain date if you want to be guaranteed of the priced fare.

**Comment by ahmedeltokhy** [comment]
thanks very much for your continuous support.
actually, i need help in issuing a ticket, can you tell me the procedures to issue a ticket and get ticket number the following is my usage of the methods to release a ticket

- AirSellFromRecommendationOptions

- pnrCreatePnr

- pnrAddMultiElements

- ticketCreateTSTFromPricing

- docIssuanceIssueTicket

is that the right way to release the ticket.

**Comment by DerMika** [comment]
Yes, that's the right way. you should try to get a hold of the document `Amadeus WBS Implementation Guide - Internet Booking Engine with Master Pricer`, which explains how to build a booking engine with the complete steps until ticket issuance. It should answer many of your questions.

If your problem is solved, you can close this issue.

**Comment by ahmedeltokhy** [comment]
thanks for your continuous support but I have another error "TICKETING INHIBITED-SSR DOCS MISSING FOR P1" I am searching for it but till now I didn't reach the right solution

**Comment by DerMika** [comment]
Still the same problem, you need SSR docs (also called APIS information) - which is identifying information for travellers - in your PNR if you travel to certain countries (for example the US). This is required by the US. You have to supply for example an ID card number that allows the US to identify your passengers.

See the servicehub link I mentioned above.

For more information I suggest you contact Amadeus Support.
