### ISSUE TITLE
DocIssuance_IssueTicket - FOP and the final flow

### ISSUE THREAD

**Issue by MyDcode** [amabnl/amadeus-ws-client#113]
Hi, once again I need your support to understand the workflow.

Currently I have the entire cycle completed up-to `DocIssuance_IssueTicket` service in the following order,

> MPTB->PNR_M(0)->Air_Sell->PNR_M->Fare_PNR->TST->PNR_M(11)

while sending the 3rd `PNR_M(11)` I am including the FOP element as shown below (in life this values will be dynamic, and while testing I am giving an actual card detail),

![image](https://user-images.githubusercontent.com/12951157/32211219-85a99430-be37-11e7-84c1-b90db847f61d.png)

Once I receive the OK from `PNR_M` then using the `DocIssuance_IssueTicket` service to issue the ticket, and I am getting multiple outcome for it.

> 1. OK ETICKET NO PRINTERS DEFINED IN OFFICE PROFILE PLEASE CALL HELP DESK
> 2. FOP RJT: MANDATORY FIELDS MISSING OR INVALID
> 3. TST PRICING CONTEXT MODIFIED : PLS REPRICE AIRLINE FEES WITH TTX
> 4. FOP RJT: INVALID CVV NUMBER - CHECK THE NUMBER AND TRY AGAIN

in the case of No.1 all good but the email is not sent to the given email address, I have logged a help and awaiting for a respond from Amadeus. What might be the possible problem?
![image](https://user-images.githubusercontent.com/12951157/32211430-7ae95930-be38-11e7-907e-089f3a9bb388.png)

No2. I couldn't understand the problem, but the Problem occurs whenever I use CMB to KUL or CMB to SIN, is this a SSR problem?

No3. Do I need to reprice and check after doing `PNR_M(11)`? or how to solve this 

No4. I am giving the actual card information, though sometime this error occurs.

**Request**
Can you help me understand the final process during `DocIssuance_IssueTicket`, and the best way to do this.

As per the document's [this](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/pnr-create-modify.rst#form-of-payment-fp) section, the payment is going through Amadeus system when using `FormOfPayment`. But what we wanted to do is, that the passenger will be paying to our IPG and later we will be settling to the Airline. Is that what happens with `FormOfPayment` (Amadeus just get the CC records) or some other process?
 
**Please help me understand the flow and the operations involved.**

**Comment by DerMika** [comment]
In the case of 1 it will probably be a configuration on your Office ID. Should be solvable by Amadeus.

For 2 it may be dependent on the airline you're booking with. To be checked with Amadeus

3. Something happened in your PNR that requires a re-pricing. The error mentions airline fees? May again be dependant on airline. To be checked with Amadeus.

4. Again, to be checked with Amadeus.

Basically, all the questions you are asking me, you should be asking Amadeus Support. I think by adding a FOP CC element, amadeus will do some validations on it and then it is dependant on your Office settings what happens with that - if Amadeus tries to charge the credit card or not. 

These are not questions I can help you with as they are (way) beyond the scope of this library.

**Comment by MyDcode** [comment]
Thank you very much for the continues support, and the time you spend to reply me. I will check with the Amadeus support as you suggested.

**Comment by ikukhar** [comment]
@MyDcode Did you solve the problem of NO PRINTERS by contacting support?

**Comment by DerMika** [comment]
If you get the error "NO PRINTERS DEFINED IN OFFICE PROFILE" then this is something that has to be configured for you by Amadeus.

**Comment by ikukhar** [comment]
@DerMika Thanks!

**Comment by MyDcode** [comment]
@ikukhar yes, and It has been resolved after support did the right configurations. Took a while though.

**Comment by MyDcode** [comment]
@DerMika thank you very much for your suggestions and contribution, all the problems has been resolved after explaining to them to the support and after their configurations for our office id.
