### ISSUE TITLE
I need to print the request XML data for the certification, Can I?

### ISSUE THREAD

**Issue by mostafaahamidmanon** [amabnl/amadeus-ws-client#114]
May you please tell me how can I print the XML request being sent to Amadeus servers?

**Comment by DerMika** [comment]
There are 2 ways to do this. Both are explained in the docs: 

- [Log every request and response to a logfile](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#logging-request-and-response)
- [Get the last request or response XML for specific messages](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#getting-individual-requests-and-responses)

**Comment by mostafaahamidmanon** [comment]
Thank you so much
