### ISSUE TITLE
Hotel branch

### ISSUE THREAD

**Issue by Defunktt1** [amabnl/amadeus-ws-client#116]
Hello! I found 'hotel' branch in your repository. Can I use It in production, or this branch has some bugs?

**Comment by DerMika** [comment]
Hi! Unfortunately, it has bugs indeed. 

I was working on implementing Hotel booking support earlier this year, but I ran into a problem and didn't pick it up anymore later. The status is described in issue #70 

At the moment only the MultiSingleAvailability call has been partially implemented - but it had the bug described in the issue above. And unfortunately I don't have the time to implement hotel support anymore at the moment.

**Comment by Defunktt1** [comment]
Thank you for response

**Comment by DerMika** [comment]
You are welcome to contribute ;)
