### ISSUE TITLE
Master Pricer TravelBoard  add TAC option and pricing options 

### ISSUE THREAD

**Issue by FarahHourani** [amabnl/amadeus-ws-client#117]
hello 

I'm trying to add Ticketing option and Pricing option TAC RP and RU to my travel board search query but couldn't can you please help 

Also i have another question : 
what's the deference between MasterPricerTravelBoardSearch and FareMasterPricerTbSearch 
And thanks

**Comment by DerMika** [comment]
For your first question: look at [this comment](https://github.com/amabnl/amadeus-ws-client/issues/103#issuecomment-337237629). It's the same option in the `Fare_MasterPricerTravelBoardSearch` message.

`Amadeus\Client\RequestOptions\FareMasterPricerTbSearch` is a class in this library used to provide all the options you want to send when calling the `Fare_MasterPricerTravelBoardSearch` message. You need to use this class and fill it with the options necessary to send the message.

`Amadeus\Client\Struct\Fare\MasterPricerTravelBoardSearch` is the class that represents the XML message in PHP format. It will be converted to XML by the library to send the SOAP call, but you shouldn't use it in your code. 

To use the MasterPricer messages, see the samples in the documentation: https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/masterpricertravelboard.rst

**Comment by FarahHourani** [comment]
Thank uu it's working now
