### ISSUE TITLE
How can I add more prices options in the Fare_MasterPricerTravelBoardSearch

### ISSUE THREAD

**Issue by mostafaahamidmanon** [amabnl/amadeus-ws-client#120]
I need to add the following pricing options to the Fare_MasterPricerTravelBoardSearch process:
 ```
        <priceType>TAC</priceType>

        <priceType>RU</priceType>

        <priceType>RP</priceType>
```

Thank you so much for your interest

**Comment by DerMika** [comment]
If you do a search through the existing issues that were previously opened, you'll find 2 identical issues which have already been answered!

**Comment by mostafaahamidmanon** [comment]
Thanks, I found it
