### ISSUE TITLE
TravelBoard : remove departure time from the query

### ISSUE THREAD

**Issue by FarahHourani** [amabnl/amadeus-ws-client#121]
Hello.. 
is there a way to remove the departure time from the travelBoard query and just send the date. 

```xml
                 <timeDetails>
                    <firstDateTimeDetail>
                        <timeQualifier>TD</timeQualifier>
                        <date>151117</date>
                        <time>2028</time>
                    </firstDateTimeDetail>
                </timeDetails>
```

**Comment by DerMika** [comment]
Yes, this is [mentioned in the docs here](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/masterpricertravelboard.rst#one-way-flight-with-flight-types-option):

> Note that the `dateTime` property of the requested flight has the time part set to `00:00:00` - the result will be that the message will only send a requested date, and will not specify a time. If you specify a time which is different from 00:00:00, a time will be specified as well. 

So all you have to do is specify a time part that will become "00:00:00" when formatted as string.

**Comment by DerMika** [comment]
Be aware that if you don't specify a time component in a datetime string, the current time will be used, and not 00:00:00. You have to specifically use the time 00:00:00

**Comment by FarahHourani** [comment]
i will.. Thank u

**Comment by DerMika** [comment]
You can close this issue if your problem was solved!
