### ISSUE TITLE
Add support for MiniRule_GetFromETicket 

### ISSUE THREAD

**Issue by ahmedeltokhy** [amabnl/amadeus-ws-client#122]
Hello All,
I am want to use the function "MiniRule_GetFromETicket" but it is not implemented in the repository, kindly do you have any document or reference to help me implementing this function.

**Comment by DerMika** [comment]
Doesn't look like it's a lot of work. I will implement it myself, unless you insist ;)

**Comment by DerMika** [comment]
This message is now implemented on the `master` branch. [Documentation here](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples.rst#minirule-getfrometicket).

You can test it by switching your `composer.json` to `dev-master`. The message will be released with version `1.6.0`.

**Comment by ahmedeltokhy** [comment]
Hi DerMika,
Thanks for your appreciated work on implementing this function, I think you keep insist to do all the work leave something for us to cooperate with ;).
