### ISSUE TITLE
Fare Check Rules

### ISSUE THREAD

**Issue by mostafaahamidmanon** [amabnl/amadeus-ws-client#125]
Hello and Greetings,
I need to add the FC1 or FC2 to the fare check rules options
Here is my $opts
```
       $rulesResponse = $client->fareCheckRules(
            new FareCheckRulesOptions([
                'recommendations' => [1]
            ])
        );
```

**Comment by DerMika** [comment]
Do you mean Fare Component 1 and 2?

If so, that's explained in the second example [here](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples.rst#fare-checkrules).

**Comment by mostafaahamidmanon** [comment]
I did this with your help
