### ISSUE TITLE
Ticket_ProcessEDoc Request 

### ISSUE THREAD

**Issue by FarahHourani** [amabnl/amadeus-ws-client#127]
Hello
Can u provide me with some tips or the steps to create new Ticket_ProcessEDoc request?

Thanks.

**Comment by DerMika** [comment]
Certainly!

I've written some explanation on how to implement a new message [here](https://github.com/amabnl/amadeus-ws-client/issues/79#issuecomment-311026268) and [here](https://github.com/amabnl/amadeus-ws-client/issues/93#issuecomment-331443917). You can also check an implementation of a message I've implemented recently, for example [this commit](https://github.com/amabnl/amadeus-ws-client/commit/addc497ebb68d13f63fc622f2101419136bb3ef2).

Hopefully these comments shed some light into the internal workings of the library. Let me know if you need any help!

**Comment by DerMika** [comment]
I will add that the hardest part of implementing a message is:

1. Generating all the classes needed for the XML request structure
2. Figuring out how to create the easiest possible RequestOptions class and how to translate those options into the XML message that must be sent. 

For the second part, this is really a matter of studying all the samples for that message on the Amadeus Extranet and implement from there.

**Comment by FarahHourani** [comment]
Thank u so much for your answer and help.. Finally it's done now :D 💃

**Comment by DerMika** [comment]
I'm looking forward to the Pull Request! :)

**Comment by FarahHourani** [comment]
The problem is that i didn't implement the response handler i'm handling the error from my side for now i thought it's easier.. but i after implement it i will create a pull request

**Comment by DerMika** [comment]
Luckily the response handler isn't that much work compared to the rest. I wouldn't mind doing that myself (rather than risk not having this message implemented ;) ).

**Comment by FarahHourani** [comment]
I pushed my updates, if you want any fix tell me. https://github.com/amabnl/amadeus-ws-client/pull/135

**Comment by DerMika** [comment]
Thanks a lot for your contribution! 

Do you prefer that I ask you to add the missing items (Response handler, unittests, docs), or would you rather have me do it?

**Comment by FarahHourani** [comment]
Most welcome, I guess these things are gonna take a lot of time from me since i have a lot of other priorities right now so i guess u doing them is so much better

**Comment by FarahHourani** [comment]
Is it a hard part ?

**Comment by DerMika** [comment]
Not really, but I don't mind doing it.

**Comment by FarahHourani** [comment]
Cool, for me i have to figure out how to them, maybe in another message i'll be able to do them.

**Comment by DerMika** [comment]
I will merge your PR tonight and then make the necessary fixes.

Thanks again for the contribution!

**Comment by FarahHourani** [comment]
Okay, Thanks to u too 👍

**Comment by DerMika** [comment]
I've just merged #135, thanks again!
