### ISSUE TITLE
Requesting Fare_InformativePricingWithoutPNR

### ISSUE THREAD

**Issue by fayax** [amabnl/amadeus-ws-client#13]
Would appreciate if you can include Fare_InformativePricingWithoutPNR function as this is pretty useful.

**Comment by DerMika** [comment]
Hi, I'll try to implement this call on develop branch asap (I plan to merge soon too).

Is there any option that you're specifically interested in using with this call?

**Comment by fayax** [comment]
with default options it will be fine

**Comment by DerMika** [comment]
Hi @fayax, I've implemented the `Fare_InformativePricingWithoutPNR` message on the [develop](https://github.com/amabnl/amadeus-ws-client/tree/develop) branch. 

For the pricing options, I've mirrorred the pricing options I have currently implemented in `Fare_PricePnrWithBookingClass ` _(which are rather limited - work in progress)_.

Let me know if the message as currently implemented is enough for your use, or if you're missing specific features. I'm closing this issue - you can open a new one if you're missing anything.
