### ISSUE TITLE
I want to make currency override to USD or EGP for the process fareInformativePricingWithoutPnr

### ISSUE THREAD

**Issue by mostafaahamidmanon** [amabnl/amadeus-ws-client#132]
How can I make the currency override to USD or EGP or SAR of the fareInformativePricingWithoutPnr?
Thanks

**Comment by DerMika** [comment]
In the docs for farepricepnrwithbookingclass it is explained how to do a currency override. It's the same for informative pricing messages.

**Comment by DerMika** [comment]
Sample added [here](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/pricepnr.rst#currency-override). Don't forget that for the InformativePricing message, this must be placed inside the `pricingOptions` property of `FareInformativePricingWithoutPnrOptions`.

**Comment by mostafaahamidmanon** [comment]
This should be the $opts right?
```
$informativePricingResponseAdult = $client->fareInformativePricingWithoutPnr(
            new FareInformativePricingWithoutPnrOptions([
                'passengers' => [
                    new PassInfo([
                        'tattoos' => $arrTattoos,
                        'type' => PassInfo::TYPE_ADULT
                    ])
                ],
                'segments' => $arrSegments,
                'pricingOptions' => [
                    'currencyOverride' => $msg_decoded->currency,
                ]
            ])
        );
```

**Comment by DerMika** [comment]
No, pricingoptions is an object. Check the informative pricing docs

**Comment by mostafaahamidmanon** [comment]
Also, when I tried this, I found the same result (no change in the price)


$informativePricingResponseAdult = $client->fareInformativePricingWithoutPnr(
            new FareInformativePricingWithoutPnrOptions([
                'passengers' => [
                    new PassInfo([
                        'tattoos' => $arrTattoos,
                        'type' => PassInfo::TYPE_ADULT
                    ])
                ],
                'segments' => $arrSegments,
                new FarePricePnrWithBookingClassOptions([
                    'currencyOverride' => 'USD', // or GBP or EUR
                ]),
            ])
        );

**Comment by mostafaahamidmanon** [comment]
Yes, I found it, it should be like this right?

'pricingOptions' => new PricingOptions([
                    'overrideOptions' => [
                        PricingOptions::OVERRIDE_FARETYPE_PUB,
                        PricingOptions::OVERRIDE_FARETYPE_UNI
                    ],
                    'currencyOverride' => 'USD', // or GBP or EUR
                ]),

**Comment by mostafaahamidmanon** [comment]
Yes, it is working fine...
Thank you so much.

**Comment by DerMika** [comment]
Exactly!
