### ISSUE TITLE
Assigning passengers to segments in Fare_InformativePricingWithoutPnr?

### ISSUE THREAD

**Issue by mostafaahamidmanon** [amabnl/amadeus-ws-client#133]
I have performed the Fare_InformativePricingWithoutPnr with the following $opts:

```
$informativePricingResponse = $client->fareInformativePricingWithoutPnr(
            new FareInformativePricingWithoutPnrOptions([
                'pricingOptions' => new PricingOptions([
                    'overrideOptions' => [
                        PricingOptions::OVERRIDE_FARETYPE_PUB,
                        PricingOptions::OVERRIDE_FARETYPE_UNI
                    ],
                ]),
                'passengers' => [
                    new PassInfo([
                        'tattoos' => [1, 2],
                        'type' => PassInfo::TYPE_ADULT
                    ]),
                    new PassInfo([
                        'tattoos' => [1, 2],
                        'type' => PassInfo::TYPE_ADULT
                    ]),
                    new PassInfo([
                        'tattoos' => [1, 2],
                        'type' => PassInfo::TYPE_CHILD
                    ]),
                    new PassInfo([
                        'tattoos' => [1, 2],
                        'type' => PassInfo::TYPE_INFANT
                    ]),
                ],
                'segments' => [
                    new SegInfo([
                        'departureDate' => \DateTime::createFromFormat('Y-m-d H:i:s', '2017-12-20 09:15:00'),
                        'from' => 'CAI',
                        'to' => 'AMM',
                        'marketingCompany' => 'RJ',
                        'flightNumber' => '508',
                        'bookingClass' => 'Q',
                        'segmentTattoo' => 1,
                        'groupNumber' => 1
                    ]),
                    new SegInfo([
                        'departureDate' => \DateTime::createFromFormat('Y-m-d H:i:s', '2017-11-30 14:20:00'),
                        'from' => 'AMM',
                        'to' => 'CAI',
                        'marketingCompany' => 'RJ',
                        'flightNumber' => '501',
                        'bookingClass' => 'Q',
                        'segmentTattoo' => 2,
                        'groupNumber' => 2
                    ]),
                ]
            ])
        );
```
And I have received the following error:
```
<Fare_InformativePricingWithoutPNRReply xmlns="http://xml.amadeus.com/TIPNRR_15_1_1A"><messageDetails><messageFunctionDetails><businessFunction>1</businessFunction><messageFunction>741</messageFunction><responsibleAgency>1A</responsibleAgency></messageFunctionDetails><responseType>8</responseType></messageDetails><errorGroup><errorOrWarningCodeDetails><errorDetails><errorCode>911</errorCode><errorCategory>EC</errorCategory></errorDetails></errorOrWarningCodeDetails><errorWarningDescription><freeTextDetails><textSubjectQualifier>3</textSubjectQualifier><source>M</source><encoding>1</encoding></freeTextDetails><freeText>Check Passenger Association</freeText></errorWarningDescription></errorGroup></Fare_InformativePricingWithoutPNRReply>
```

How can I associate the passengers to the segments?

**Comment by DerMika** [comment]
Your passengers are the problem. What you have asked for is: 

- 2 adults with tattoos 1 and 2
- 2 adults with tattoos 1 and 2
- 2 children with tattoos 1 and 2
- 2 infants with tattoos 1 and 2

First of all make sure your tattoos are unique for all passengers.
Second, Why do you request  2 adults _twice_?

**Comment by mostafaahamidmanon** [comment]
So it should be like this right?

$informativePricingResponse = $client->fareInformativePricingWithoutPnr(
            new FareInformativePricingWithoutPnrOptions([
                'pricingOptions' => new PricingOptions([
                    'overrideOptions' => [
                        PricingOptions::OVERRIDE_FARETYPE_PUB,
                        PricingOptions::OVERRIDE_FARETYPE_UNI
                    ],
                ]),
                'passengers' => [
                    new PassInfo([
                        'tattoos' => [1],
                        'type' => PassInfo::TYPE_ADULT
                    ]),
                    new PassInfo([
                        'tattoos' => [2],
                        'type' => PassInfo::TYPE_ADULT
                    ]),
                    new PassInfo([
                        'tattoos' => [3],
                        'type' => PassInfo::TYPE_CHILD
                    ]),
                    new PassInfo([
                        'tattoos' => [4],
                        'type' => PassInfo::TYPE_INFANT
                    ]),
                ],
                'segments' => [
                    new SegInfo([
                        'departureDate' => \DateTime::createFromFormat('Y-m-d H:i:s', '2017-12-20 09:15:00'),
                        'from' => 'CAI',
                        'to' => 'AMM',
                        'marketingCompany' => 'RJ',
                        'flightNumber' => '508',
                        'bookingClass' => 'Q',
                        'segmentTattoo' => 1,
                        'groupNumber' => 1
                    ]),
                    new SegInfo([
                        'departureDate' => \DateTime::createFromFormat('Y-m-d H:i:s', '2017-11-30 14:20:00'),
                        'from' => 'AMM',
                        'to' => 'CAI',
                        'marketingCompany' => 'RJ',
                        'flightNumber' => '501',
                        'bookingClass' => 'Q',
                        'segmentTattoo' => 2,
                        'groupNumber' => 2
                    ]),
                ]
            ])
        );

And how do I make the reference in the segments?

**Comment by DerMika** [comment]
I don't think you need to make pax associations in the segments. I think the Informative Pricing message assumes the segments you provide are for all passengers.

You can provide passenger associations in your pricing options if you need though, just like you would do for `Fare_PricePNRWithBookingClass`.

**Comment by mostafaahamidmanon** [comment]
Thank you so much.

**Comment by mostafaahamidmanon** [comment]
Thank you for your effort
