### ISSUE TITLE
Security_SignOut for the same session 

### ISSUE THREAD

**Issue by FarahHourani** [amabnl/amadeus-ws-client#134]
Hello..
How can i make the application use the active sessionId to send the Security_SignOut instead creating a new session ?

Thanks

**Comment by DerMika** [comment]
You first need to tell the client to re-use a previous session. By default it will initialize a new session each time.

There's some info in the how to docs about getting current session information and restoring session info.

**Comment by FarahHourani** [comment]
I've tried this but if an error occurs the getSessionData() returns null While the main problem for is handling the session when an error occurs

**Comment by DerMika** [comment]
If `getSessionData()` returns null, then there is no valid session initialized in the Client's current instance. 

This can happen when your initial message fails to properly authenticate. But in all other cases, there should be session information available.

Don't forget that _sessions do not persist between instantiations of the client_. If you wish this to be the case, you must implement it yourself.

**Comment by FarahHourani** [comment]
Actually i have Ticketing Session which has 3 requests PNRretrieve, DocIssuance, PNRretrieve. 
I'm testing for Invalid recordLocator so i need to handle the session from the first step! 

can't i do any request before the first PNRretrieve call? or even just send a header ?

**Comment by DerMika** [comment]
I don't really understand what you're trying to accomplish. 

Basically every time the client gets instantiated, it starts without session context. If you need it to continue in a previously used session, you must make sure the session data to be restored was saved somewhere. On instantiating a new client, you have to provide it the previously used session data with `setSessionData()`.

While in the context of a client instance, a client will keep working in the same session if it is configured to run in stateful mode.

**Comment by FarahHourani** [comment]
Ok.. Thank u so much :)
