### ISSUE TITLE
pnrCreatePnr does not throw error in case of invalid name of passenger

### ISSUE THREAD

**Issue by bimusiek** [amabnl/amadeus-ws-client#139]
Hey, 
long time no see 😄 

I was investigating an issue that pricing was throwing an error with `[1908] CHECK PASSENGER NUMBER`. Upon further investigation, I realised that `PnrAddMultipleElements` returns error on travellers level.

<img width="595" alt="screenshot 2018-01-05 17 40 49" src="https://user-images.githubusercontent.com/1025588/34618958-c46e1c08-f240-11e7-9b8a-b6a610b6851a.png">

However, the SDK does not throw an exception. I guess error handling does not look at travellers for this call 👍

**Comment by bimusiek** [comment]
Just verified that the first name can have 1 char, but the last name needs to have at least 2. 
What do you think about doing validation when building options as well?

**Comment by DerMika** [comment]
I will add checks for passenger errors. Is it possible to provide me a sample XML I can throw in a unittest? :)

I'm a little bit hesitant to start checking input before sending. The library doesn't do that anywhere at the moment (as far as I can remember). Once you start pre-validating input _(which would in itself definitely be a good thing)_ you'd have to make that behavior consistent across messages. Which would mean you'd eventually have to add input validation to all messages. 

If many people are interested in adding this feature to the library, i'm fine with adding it. But at the moment I'd like to hold it off until we can implement it in a consistent manner.

**Comment by DerMika** [comment]
There was a sample in the Extranet with such a pax error, so I used that. 

Issue should be fixed now on Master!
