### ISSUE TITLE
MasterPricer In-Flight services

### ISSUE THREAD

**Issue by bimusiek** [amabnl/amadeus-ws-client#140]
Hey, did anyone ever tried to get in-flight services? 
I am sending `IFS` in flight options however I am not getting proper response back.

```
5.96 Operation: 09.4 Output Option - In-Flight Services
The user has the ability to request by input option (IFS) the display of the in-flight services for each flight.

The example bellow illustrates a query with in-flight services option (IFS) and a reply with Wi-Fi on board (18), Lie Flat Seat (16), Television (5), In-Seat Power Source (12).
```

And response should be:

```
<flightIndex>
        <requestedSegmentRef>
            <segRef>1</segRef>
        </requestedSegmentRef>
        <groupOfFlights>
            <propFlightGrDetail>
[...]
            </propFlightGrDetail>
            <flightDetails>
                <flightInformation>
[...]
                </flightInformation>
                <flightCharacteristics>
                    <inFlightSrv>18</inFlightSrv>
                    <inFlightSrv>16</inFlightSrv>
                    <inFlightSrv>5</inFlightSrv>
                    <inFlightSrv>12</inFlightSrv>
                </flightCharacteristics>
            </flightDetails>
        </groupOfFlights>
    </flightIndex>
```

There is no `flightCharacteristics` in any element 😢 
Could someone try it on your OID please? I reported it to Amadeus and they said it could be because airlines did not fill this info, however when I check it in SellingPlatform at least I am getting `no-smoking`

**Comment by DerMika** [comment]
Hi, I just tested it on a test environment (Amadeus PDT backend), and on a BRU-LON request there were no `flightCharacteristics` in the response, but on a LON-MIA request ([flightcharacteristicstestrequest.txt](https://github.com/amabnl/amadeus-ws-client/files/1629135/flightcharacteristicstestrequest.txt)), I got some: [flightcharacteristicstestreply.txt](https://github.com/amabnl/amadeus-ws-client/files/1629132/flightcharacteristicstestreply.txt)

Are you sure it's not a setting on your Office ID?

**Comment by bimusiek** [comment]
@DerMika Thanks a lot! I don't know why I missed it, but I get it for some flights (especially long-haul)
