### ISSUE TITLE
Prevent wait list segments

### ISSUE THREAD

**Issue by XYNOMEX** [amabnl/amadeus-ws-client#142]
Hello,

Please, I need to prevent the wait list flights from appearing in the search results, I need only the available flights to be shown.

Thanks

**Comment by DerMika** [comment]
This is a question to ask the Amadeus support contact who should be assigned to your project.

**Comment by XYNOMEX** [comment]
I already raised an ACSP to AMADEUS support, but I'm just asking if there is any function/option I can use to do that.

**Comment by DerMika** [comment]
I don't now. I can't find anything in the masterpricer docs on the intranet that indicates there is a possibility to do this in a MasterPricer call, so I would guess the answer is "no". But again, to be certain, you should ask Amadeus.

**Comment by XYNOMEX** [comment]
Thank you, I'm waiting for Amadeus's answer.

**Comment by bimusiek** [comment]
@XYNOMEX MasterPricer returns you list of availability, so you can filter it on your own.
https://servicehub.amadeus.com/c/portal/view-solution/783251/en_US/how-to-waitlist-a-flight

Just hide flights with availability `0` or `L`

**Comment by DerMika** [comment]
thanks @bimusiek, considering this issue closed. 

You can re-open if necessary
