### ISSUE TITLE
Created PNR price and MPTB price is sometimes different

### ISSUE THREAD

**Issue by RaviSouza** [amabnl/amadeus-ws-client#144]
I'm having a problem that sometimes the price registered at Amadeus when placing the PNR is different than the price that was shown on the MPTB.

is there a way to make sure that the PNR is made with the price from the MPTB?

after choosing the flight I'm running the code on that order:
①Air_SellFromRecommendation
②PNR_AddMultiElements
③Fare_PricePNRWithBookingClass
④Ticket_CreateTSTFromPricing
⑤PNR_AddMultiElements
⑥Queue_PlacePNR
⑦Security_SignOut

I'm still lacking in knowledge about the Amadeus API, so I would appreciate a detailed answer.

**Comment by DerMika** [comment]
Hi, first of all Amadeus Support should be able to help you with such questions about the Amadeus Web Services API. I am not able to offer this kind of support.

However, a similar question was asked before, and I've written out some answers which  could be useful to you: Check out issue #97 and maybe you'll find your answers there. 

In any case the most important piece of information to use when pricing a PNR after selling a MasterPricer recommendation is to use the same fare basis from the MasterPricer recommendation in your pricing. But all that is explained in issue #97

**Comment by RaviSouza** [comment]
Thanks! I will try it!
