### ISSUE TITLE
Message "Security_Authenticate

### ISSUE THREAD

**Issue by AmiinosEddagh** [amabnl/amadeus-ws-client#147]
hi,
i'm starting to use your sdk but i always get this error message

```
Fatal error:  Uncaught exception 'Amadeus\Client\InvalidMessageException' with message 'Message "Security_Authenticate" is not in WDSL' in /home/dev/work/amadeus/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/RequestCreator/Base.php:108
Stack trace:
-0 /home/dev/work/amadeus/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/RequestCreator/Base.php(88): Amadeus\Client\RequestCreator\Base->checkMessageIsInWsdl('Security_Authen...')
-1 /home/dev/work/amadeus/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client.php(1197): Amadeus\Client\RequestCreator\Base->createRequest('Security_Authen...', Object(Amadeus\Client\RequestOptions\SecurityAuthenticateOptions))
-2 /home/dev/work/amadeus/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client.php(192): Amadeus\Client->callMessage('Security_Authen...', Object(Amadeus\Client\RequestOptions\SecurityAuthenticateOptions), Array, false)
-3 /home/dev/work/amadeus/test.php(31): Amadeus\Client->securityAuthenticate()
-4 {main}
  thrown in /home/dev/work/amadeus/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/RequestCreator/Base.php on line 108
```

thanks in advance

**Comment by DerMika** [comment]
Hi, 

Do you _have_ the Security_Authenticate message in your WSDL?

However, often it's not necessary to call Security_Authenticate explicitly when you have a WSAP configured with SoapHeader 4. If that is the case, just call the message you want to call, and the library will handle authentication and  session management automatically.

**Comment by AmiinosEddagh** [comment]
hi,

i've got from amadeus only the credentials to access the extranet.
i'm new to this, can you help me with an example to start with?

**Comment by DerMika** [comment]
Well, what do you want to do?

Do you want to build an online booking engine? In that case you can look at [this comment I made previously](https://github.com/amabnl/amadeus-ws-client/issues/87#issuecomment-321473214), which gives some recommendations on how to start building one.

**Comment by AmiinosEddagh** [comment]
ok
so now i'm having this error

Fatal error: Uncaught exception 'Amadeus\Client\Session\Handler\InvalidSessionException' with message 'No active session' in /home/dev/work/amadeus/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/Session/Handler/SoapHeader2.php:68 Stack trace: #0 /home/dev/work/amadeus/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/Session/Handler/Base.php(191): Amadeus\Client\Session\Handler\SoapHeader2->prepareForNextMessage('Air_MultiAvaila...', Array) #1 /home/dev/work/amadeus/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client.php(1199): Amadeus\Client\Session\Handler\Base->sendMessage('Air_MultiAvaila...', Object(Amadeus\Client\Struct\Air\MultiAvailability16), Array) #2 /home/dev/work/amadeus/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client.php(630): Amadeus\Client->callMessage('Air_MultiAvaila...', Object(Amadeus\Client\RequestOptions\AirMultiAvailabilityOptions), Array) #3 /home/dev/work/amadeus/test.php(56): Amadeus\Client->airMultiAvailability(Object(Amadeus\Client\RequestOptions\AirMultiAvailabilityOptions)) #4 {main} in /home/dev/work/amadeus/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/Session/Handler/SoapHeader2.php on line 68

**Comment by DerMika** [comment]
You have configured your client to use SoapHeader 2. For SoapHeader 2, you _have_ to send your own authentication message.

Are you sure the WSDL that was given to you is a SoapHeader 2 WSDL? You can ask Amadeus which SoapHeader version it uses.

if the WSDL is for SoapHeader 4, you have to configure the client to use SoapHeader 4: https://github.com/amabnl/amadeus-ws-client/blob/master/docs/about-get-started.rst#set-up-a-test-client:

```php
    'soapHeaderVersion' => Client::HEADER_V4,

```

**Comment by AmiinosEddagh** [comment]
i'm waiting for their response

**Comment by AmiinosEddagh** [comment]
and i have this erroe

Fatal error:  Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing Schema: can't import schema from '/home/dev/work/amadeus/WSDL/Ticket_ValidateCreditCard_05_3_1A.xsd' in /home/dev/work/amadeus/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/SoapClient.php:59
Stack trace:
#0 /home/dev/work/amadeus/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/SoapClient.php(59): SoapClient->SoapClient('WSDL/1ASIWPOC1A...', Array)
#1 /home/dev/work/amadeus/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/Session/Handler/Base.php(401): Amadeus\Client\SoapClient->__construct('WSDL/1ASIWPOC1A...', Array, Object(Psr\Log\NullLogger))
#2 /home/dev/work/amadeus/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/Session/Handler/Base.php(378): Amadeus\Client\Session\Handler\Base->initSoapClient('7d6b99d4')
#3 /home/dev/work/amadeus/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/Session/Handler/SoapHeader4.php(93): Amadeus\Client\Session\Handler\Base->getSoapClient('Air_MultiAvaila...')
#4 /home/dev/work/amadeus/vendor/amabnl/amadeu in /home/dev/work/amadeus/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/SoapClient.php on line 59

**Comment by DerMika** [comment]
Looks like your WSDL file is including an XSD file which it can't find. 

You have to extract the zip file you got from Amadeus, put it somewhere the client can read it, and make sure all the XSD's in the zip file are also present as they were in the zip file.

It's also possible that the XSD you mention just isn't present in the WSDL:
- ask Amadeus to fix this and give you a new WSDL
- meanwhile, remove the import of this XSD from your WSDL so you can start testing.

**Comment by AmiinosEddagh** [comment]
thanks but now i have no result when using

$opt = new AirMultiAvailabilityOptions([
    'actionCode' => AirMultiAvailabilityOptions::ACTION_AVAILABILITY,
    'requestOptions' => [
        new RequestOptions([
            'departureDate' => \DateTime::createFromFormat('Ymd-His', '20180320-000000', new \DateTimeZone('UTC')),
            'from' => 'BRU',
            'to' => 'LIS',
            'requestType' => RequestOptions::REQ_TYPE_NEUTRAL_ORDER
        ])
    ]
]);

$availabilityResult = $client->airMultiAvailability($opt);

**Comment by DerMika** [comment]
Have you provided the password correctly (base_64 encoded)? 

This error is also returned when it's an authentication failure.

**Comment by AmiinosEddagh** [comment]
Hi and sorry for the late reply,
i'm waiting for the new WSDL files from Amadeus.
will keep you posted if there is any news.
thank you

**Comment by AmiinosEddagh** [comment]
hi @DerMika 
i have got the new WSDL files from Amadeus.

i have a couple of questions for you if you don't mind;
-the **userId** and **passwordData** are the credentials to access the Extranet?
-which Message should i start with? the **FareMasterPricerTbSearch** ?

thank you

**Comment by DerMika** [comment]
Yes, they are the credentials.

I don't know, what do you want to do? Build an on-line booking engine? If so, then the Fare_MasterPricerTravelBoardSearch is probably the best message to start with.

But before you start doing that, maybe ask Amadeus some directions. They have some implementation guides and flowcharts they can provide that you can use as a guideline.

**Comment by DerMika** [comment]
Is your problem fixed now? If so, can you close this issue?

**Comment by AmiinosEddagh** [comment]
yes thank you for your support.
i'm moving forward with the development.
i'll open a ticket if i encounter other issues.
best regards.
