### ISSUE TITLE
Documentation typo in MasterPricer docs

### ISSUE THREAD

**Issue by vTrip** [amabnl/amadeus-ws-client#148]
Seems as though any `MP...` packages cannot be found

**Comment by DerMika** [comment]
Can you explain in a little bit more detail what you're trying to do? 

The class to include is `Amadeus\Client\RequestOptions\Fare\MPPassenger`, and not `Amadeus\Client\RequestOptionsFare\MPPassenger`

**Comment by vTrip** [comment]
@DerMika - my apologies for not seeing the typo you pointed out. I will rephrase this issue as a documentation error as I copy pasted straight from the examples. Turns out there is a typo which you have now made clear.

Cheers!

**Comment by vTrip** [comment]
There is a typo in the documentation at the following link.

[https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/masterpricertravelboard.rst](url)

Please see @DerMika comment for typo + fix

**Comment by DerMika** [comment]
I fixed the docs. Thanks for letting me know!
