### ISSUE TITLE
Air_RebookAirSegment

### ISSUE THREAD

**Issue by nepster-web** [amabnl/amadeus-ws-client#149]
Hello.
Thank you for supporting this library.

Is there a plan to implement the request **Air_RebookAirSegment** in near future ?

**Comment by DerMika** [comment]
Hi, 

I guess that depends when you mean "near future". If there's a need for this message, I can start working on it. However, it's in my free time so I can't give any promises as to when it'll be ready.

**Comment by nepster-web** [comment]
"near future" - it's about 2 to 3 weeks.

So, if I will get this task earlier, with your help I'll try to make a pull request.

**Comment by DerMika** [comment]
Looking at the documentation, it seems quite similar to `Air_SellFromRecommendation`, which is already implemented. So it looks doable - if I can find the time. I'll try to work on it later this week. _No promises though_

**Comment by nepster-web** [comment]
I understand and respect this. Thank you.

**Comment by bimusiek** [comment]
@nepster-web You can achieve exactly the same outcome using `Air_SellFromRecommendation` together with `PNR_Cancel`. 👍

**Comment by nepster-web** [comment]
@bimusiek Thank you. Earlier I found a recommendation here:
https://github.com/amabnl/amadeus-ws-client/issues/67#issuecomment-295695271

So it's just a matter of convenience.

**Comment by DerMika** [comment]
I will implement the message. It's still a useful message, since it allows you to do the same with fewer messages. Especially since some people pay to Amadeus depending on the amount of requests they make.

**Comment by DerMika** [comment]
Implemented in #159

**Comment by DerMika** [comment]
Will be included in v 1.7.0

**Comment by nepster-web** [comment]
Many thanks.
We have not yet had time to use it, but we are very close to this.

**Comment by DerMika** [comment]
Version 1.7.0 has just been released!
