### ISSUE TITLE
How to get flight duration at segment level

### ISSUE THREAD

**Issue by RaviSouza** [amabnl/amadeus-ws-client#155]
Reading the documentation, I found out that it is possible to get the flight duration at segment level.
It displays inside the `<flightInformation>` tag as an `<attributeDetails>`

```
<attributeDetails>
    <attributeType>EFT</attributeType>
    <attributeDescription>0600</attributeDescription>
</attributeDetails>
```

I wonder if its possible to achieve this with this library.
Could someone help me?

**Comment by DerMika** [comment]
For which message is this?

**Comment by DerMika** [comment]
Ah right, this is for `Fare_MasterPricerTravelBoardSearch`.

I don't know the answer. It could be that this information only shows for some airlines, or for some connections. It could be a setting on your Office Id to enable this feature.

You should contact Amadeus Support and ask them this question. They should be able to help you. 

I'm also interested in hearing what they answer!

**Comment by RaviSouza** [comment]
Thank you for your answer!
Sorry for the lack of detail in the question.
I'll contact them and post here when I get a reply.

**Comment by therealartz** [comment]
I've had the same question. 
Contacting Amadeus support was the solution.
And as Dieter said, this is a setting at Office ID

**Comment by DerMika** [comment]
Did you get a response from Amadeus yet?

**Comment by RaviSouza** [comment]
Amadeus support is taking a long time to answer my question this time.
I'm still waiting, but since @therealartz  confirmed that its a setting at Office ID I believe its safe to close this issue.
If I have any problems I will ask again.
Thank you for the support!
