### ISSUE TITLE
typeOfDocument

### ISSUE THREAD

**Issue by yosafuni** [amabnl/amadeus-ws-client#156]
Dear, How can i pass typeOfDocument reference No. in PNR_AddMultiElements

**Comment by DerMika** [comment]
Can you please provide some more information of what exactly you're trying to do? I can't find `typeOfDocument` in the documentation of PNR_AddMultiElements.

**Comment by yosafuni** [comment]
i want to add traveller information i can add last name and first name and birthdate
now how can i pass passenger gender type (M|F) and his/her passport No. and validate date or ID 
ect.... more information

**Comment by DerMika** [comment]
I think you are probably talking about adding SRDOCS to the PNR: https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/pnr-create-modify.rst#apis-passport-or-identity-card

You should get in touch with Amadeus to determine the exact format of the SRDOCS data you need to provide.

**Comment by DerMika** [comment]
Is your issue solved? If so, can you please close this?

**Comment by yosafuni** [comment]
no till now i can't solve it

**Comment by DerMika** [comment]
Have you talked to your Amadeus Support contact? 

They should be able to help you with these kinds of functional questions. 

I have built this library, but I do not have the time to help people understand how to work with the Amadeus Web Services. All I can do is bridge the gap from how this library works to how the Web Services work functionally.

**Comment by shaiby** [comment]
yosafuni have you figure out how to use SRD in PNR_addMultiElements. I have done this couple of days ago using this library. It worked like a charm. I can help if you still need!

**Comment by yosafuni** [comment]
thanks all for your support

hello shaiby please if you can help me give me example

**Comment by DerMika** [comment]
Please see if the format given in #195 works for you. If not, there is only Amadeus Support.

**Comment by DerMika** [comment]
Closing due to lack of feedback
