### ISSUE TITLE
FlightInfo looks missing to use at itinerary level in Fare_MasterPriceTravelBoardSearch

### ISSUE THREAD

**Issue by shaiby** [amabnl/amadeus-ws-client#158]
In Amadeus documentation, it is mentioned we can use direct indirect, exclude or include airline at travelFlightInfo that will be used for all segments. But same thing we can use at itinerary level in any segment using flightInfo tag. But I am uanble to use this option using this application. Is this possible or amadeus-ws-client don't support flightInfo.

**Comment by DerMika** [comment]
You're correct, the library doesn't support this option yet. I'll put it on my to-do list.

**Comment by shaiby** [comment]
Thanks for consideration

**Comment by DerMika** [comment]
I've implemented the features you requested, check out the documentation [here](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/masterpricertravelboard.rst#exclude-include-airlines-at-segment-level). 

Let me know if there are other options you need. 

These changes are currently only available on the master branch, they'll be included in the 1.7.0 release. If you want to test them out, point your `composer.json` to `dev-master`.

**Comment by shaiby** [comment]
Dear DerMika...
perfect and thumbs up for your quick consideration. I respect your help in this regard.

I have already installed this on my server. How I can use these new features. I mean need to re download package using composer?

**Comment by DerMika** [comment]
yes, just change the `composer.json` line to "version" `dev-master` and then run `composer update`.

That will switch you to the latest commit on the master branch. As soon as version 1.7.0 is released, you should switch back to the production version.

**Comment by shaiby** [comment]
perferct...got it....

Thanks a lot..

**Comment by DerMika** [comment]
Version 1.7.0 has just been released!
