### ISSUE TITLE
FOP per pax

### ISSUE THREAD

**Issue by andreigogu** [amabnl/amadeus-ws-client#160]
Hi,
please help me to understand how to add FOP (using FOP_CreateFormOfPayment), for each passenger.

Example:
I have 
passengers: 2 ADT, 1 CHD & 1 INF 
FOP: 2 Credit Cards
..........................................................................
ADT1 & INF => Credit Card 1
ADT2 & CHD => Credit Card 2

Thank you

**Comment by DerMika** [comment]
I don't know myself, but there is an example on the Amadeus Extranet --> Functional Docs for FOP_CreateFormOfPayment --> Version 15.4 --> Examples

> Adding a form of payment for multiple passengers, each with their own credit card

Which seems to do what you want to do, with the difference that you'll have to group 2 passengers together per FOP.

If in doubt for these kinds of functional questions, it's best to ask Amadeus Support. I made this library, but I'm not an expert on using these messages.

**Comment by andreigogu** [comment]
you are right, there is a type(PAX) which is not mentioned in the documentation

`<pnrElementAssociation>
<referenceDetails>
<type>PAX</type>
<value>3</value>
</referenceDetails>
</pnrElementAssociation>`

I will try it and after that, I will add an example, may be useful for somebody

**Comment by DerMika** [comment]
Great, thanks, I'm looking forward to the contribution!

**Comment by bimusiek** [comment]
@andreigogu  If you want to add FOP simply to whole PNR, I recommend doing it through PNR_AddMultiElements, it is much easier and straightforward. 

FOP_CreateFormOfPayment is for special cases when u want to assign FOP to EMD element for example.

**Comment by andreigogu** [comment]
Hi @bimusiek,
totally agree with you, I did it with PNR_AddMultiElements, while I had only one FOP per PNR, but now I need multiple FOPs per PNR. For example, I have 3 paxes and 2 CC, so you can do it only with FOP_CreateFormOfPayment.

here is an example, if somebody needs multiple FOP on Amadeus

`foreach ($this->cardPax[$fopKey] as $cardPax) {
                        $paxRefs[] = new ElementRef([
                            'type' => 'PAX',
                            'value' => $cardPax
                        ]);
                    }
                    $fopGroup = new Group([
                        'elementRef' => $paxRefs,
                        'mopInfo' => [
                            new MopInfo([
                                'sequenceNr' => 1,
                                'fopCode' => 'CC'.$CreditCard->Type,
                                'fopType' => MopInfo::FOPTYPE_FP_ELEMENT,
                                'payMerchant' =>$this->parsedPNR['priceChecked'][0]['validatingCarrier'],
                                'mopPaymentType' => MopInfo::MOP_PAY_TYPE_CREDIT_CARD,
                                'creditCardInfo' => new CreditCardInfo([
                                    'vendorCode' => $CreditCard->Type,
                                    'cardNumber' => $CreditCard->Number,
                                    'expiryDate' => $CreditCard->ExpirationMonth.$CreditCard->ExpirationYear,
                                    'securityId' => $CreditCard->CVV,
                                    'name' => $CreditCard->HolderName
                                ])
                            ])
                        ]
                    ]);

                    $reqOptions = new FopCreateFopOptions([
                        'transactionCode' => FopCreateFopOptions::TRANS_CREATE_FORM_OF_PAYMENT,
                        'fopGroup' => [$fopGroup]
                    ]);

                    $result = Service::client()->fopCreateFormOfPayment($reqOptions);
`

**Comment by DerMika** [comment]
Closing this issue, assuming it's solved. You can re-open if needed.
