### ISSUE TITLE
Is there any search option

### ISSUE THREAD

**Issue by ichtrojan** [amabnl/amadeus-ws-client#164]
I've been going through the options and i still cant find Flights search option

**Comment by DerMika** [comment]
Have you received any documentation from Amadeus? It's not my goal to provide this kind of basic support, that's what you're paying Amadeus for.

Anyway, `Air_MultiAvailability` can be used to search for flights, and `Fare_MasterPricerTravelBoardSearch` is commonly used to find flights and prices at the same time.

Usually an online booking engine uses the MasterPricer call as the method of searching for flights.

**Comment by ichtrojan** [comment]
Thanks
