### ISSUE TITLE
"Fare_MasterPricerTravelBoardSearch" is not in WDSL

### ISSUE THREAD

**Issue by Dsaint109** [amabnl/amadeus-ws-client#167]
But in my Params 
```
'sessionHandlerParams' => [
    'soapHeaderVersion' => Client::HEADER_V4, //This is the default value, can be omitted.
    'wsdl' => 'https://staging-ws.epower.amadeus.com/wshbl/EpowerService.asmx?WSDL', //Points to the location of the WSDL file for your WSAP. Make sure the associated XSD's are also available.
    'stateful' => false, //Enable stateful messages by default - can be changed at will to switch between stateless & stateful.
    // 'logger' => new Psr\Log\NullLogger()
],
```

**Comment by DerMika** [comment]
The WSDL you are pointing towards is the e-Power SOAP WSDL. This is a different Amadeus product which uses a different SOAP interface. 

This library doesn't support the e-Power SOAP interface, and it doesn't plan to do so. Sorry.

**Comment by ichtrojan** [comment]
@DerMika if Epower is now support which is?

**Comment by DerMika** [comment]
As the [readme](https://github.com/amabnl/amadeus-ws-client/blob/master/README.md) says, the Amadeus Web Services SOAP interface.
