### ISSUE TITLE
How to create Requests for MasterPricerExpertSearch

### ISSUE THREAD

**Issue by m0veax** [amabnl/amadeus-ws-client#168]
Hey,

i am just looking through your Codebase and asking myself what steps would be needed to support the MasterPricer Expert Search endpoint? Maybe you could give me a short summary?

**Comment by DerMika** [comment]
Hi,

I've written a Contributing guide which links to some explanations i've done in the past about implementing new messages: https://github.com/amabnl/amadeus-ws-client/blob/master/CONTRIBUTING.md#when-adding-a-new-message

If you haven't read that yet, it could be a good start.

I haven't examined the MP Expert messages yet, but when I implemented MasterPricerCalendar I found that the request message was identical to the MasterPricerTravelBoardSearch message, so implementing that message was quite easy to do. You should definitely check out if that is the case for `Fare_MasterPricerExpertSearch`.

**Comment by m0veax** [comment]
Hey,

thanks for your answer. As i see ExpertSearch requires less Attributes in the Message itself then the Travelboard Search. Maybe i can do a quick copy and remove what is not needed. Just checking out your Link too.

**Comment by DerMika** [comment]
When you copy and paste, try to create as little as possible duplicate code please :)

**Comment by m0veax** [comment]
Hey, please see my Pull Request :) It is not finished yet, but it is returning results as needed right now. Any thoughts?

**Comment by humanyu** [comment]
How to create nonce and hashpassword using php. Please help me out

**Comment by DerMika** [comment]
Why do you need to do that? If you're using this library, it will do all that for you. Also, could you please open a new ticket if you need to ask such a question?

**Comment by humanyu** [comment]
Can i use this library for multicity, alternate airport, alternate date etc.
I have created a new ticket please help me out

Thank you in advance

**Comment by humanyu** [comment]
I am getting this error while using library. Please have a look my RQ and RS

ERROR----
Fatal error: Uncaught Amadeus\Client\InvalidMessageException: Message "Security_Authenticate" is not in WDSL in C:\Users\Voyages Booth\vendor\amabnl\amadeus-ws-client\src\Amadeus\Client\RequestCreator\Base.php:108 Stack trace: #0 C:\Users\Voyages Booth\vendor\amabnl\amadeus-ws-client\src\Amadeus\Client\RequestCreator\Base.php(88): Amadeus\Client\RequestCreator\Base->checkMessageIsInWsdl('Security_Authen...') #1 C:\Users\Voyages Booth\vendor\amabnl\amadeus-ws-client\src\Amadeus\Client.php(1532): Amadeus\Client\RequestCreator\Base->createRequest('Security_Authen...', Object(Amadeus\Client\RequestOptions\SecurityAuthenticateOptions)) #2 C:\Users\Voyages Booth\vendor\amabnl\amadeus-ws-client\src\Amadeus\Client.php(215): Amadeus\Client->callMessage('Security_Authen...', Object(Amadeus\Client\RequestOptions\SecurityAuthenticateOptions), Array, false) #3 C:\xampp\htdocs\amadeus2\index.php(35): Amadeus\Client->securityAuthenticate() #4 {main} thrown in C:\Users\Voyages Booth\vendor\amabnl\amadeus-ws-client\src\Amadeus\Client\RequestCreator\Base.php on line 108  








USING THIS CODE--

include 'C:\Users\vendor\autoload.php';

use Amadeus\Client;
use Amadeus\Client\Params;
use Amadeus\Client\Result;
use Amadeus\Client\RequestOptions\PnrRetrieveOptions;

//Set up the client with necessary parameters:

$params = new Params([
    'authParams' => [
        'officeId' => 'xxxxxxxxxxx', //The Amadeus Office Id you want to sign in to - must be open on your WSAP.
        'userId' => 'yyyyyyyyyy', //Also known as 'Originator' for Soap Header 1 & 2 WSDL's
        'passwordData' => base64_encode('zzzzzzzzzzzzzz'), // **base 64 encoded** password
        'passwordLength' => 8,
        'dutyCode' => 'SU',
        'organizationId' => 'xxxxxxxxxxx',
    ],
    'sessionHandlerParams' => [
        'soapHeaderVersion' => Client::HEADER_V4,
        'wsdl' => 'PocWSDL/1ASIWPOC1A_PDT_20180522_160552.wsdl', //Points to the location of the WSDL file for your WSAP. Make sure the associated XSD's are also available.
        'logger' => new Psr\Log\NullLogger()
    ],
    'requestCreatorParams' => [
        'receivedFrom' => 'my test project' // The "Received From" string that will be visible in PNR History
    ]
]);

use Amadeus\Client\RequestOptions\AirMultiAvailabilityOptions;
use Amadeus\Client\RequestOptions\Air\MultiAvailability\RequestOptions;
use Amadeus\Client\RequestOptions\Air\MultiAvailability\FrequentTraveller;

$client = new Client($params);
$authResult = $client->securityAuthenticate();
echo "<pre>";
print_r($authResult);die;












INCLUDED WSDL FILE

<?xml version="1.0" encoding="UTF-8"?>


<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://xml.amadeus.com" xmlns:awsse="http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd" xmlns:air_rebookairsegment_14_1="http://xml.amadeus.com/ARBKUQ_14_1_1A" xmlns:air_rebookairsegmentreply_14_1="http://xml.amadeus.com/ARBKUR_14_1_1A" xmlns:ticket_validatecreditcard_5_3="http://xml.amadeus.com/CCARQT_05_3_1A" xmlns:ticket_validatecreditcardreply_5_3="http://xml.amadeus.com/CCARSP_05_3_1A" xmlns:ticket_validatedescbilldata_2_1="http://xml.amadeus.com/CCDRQT_02_1_1A" xmlns:ticket_validatedescbilldatareply_2_1="http://xml.amadeus.com/CCDRSP_02_1_1A" xmlns:ticket_creditcardcheck_6_1="http://xml.amadeus.com/CCVRQT_06_1_1A" xmlns:ticket_creditcardcheckreply_6_1="http://xml.amadeus.com/CCVRSP_06_1_1A" xmlns:air_flightinfo_7_1="http://xml.amadeus.com/FLIREQ_07_1_1A" xmlns:air_flightinforeply_7_1="http://xml.amadeus.com/FLIRES_07_1_1A" xmlns:pnr_displayhistory_16_1="http://xml.amadeus.com/PHIDRQ_16_1_1A" xmlns:pnr_displayhistoryreply_16_1="http://xml.amadeus.com/PHIDRR_16_1_1A" xmlns:pnr_transferownership_14_1="http://xml.amadeus.com/POWNUQ_14_1_1A" xmlns:pnr_transferownershipreply_14_1="http://xml.amadeus.com/POWNUR_14_1_1A" xmlns:pnr_reducenip_4_1="http://xml.amadeus.com/PRNPUQ_04_1_1A" xmlns:pnr_reducenipreply_4_1="http://xml.amadeus.com/PRNPUR_04_1_1A" xmlns:air_multiavailability_16_1="http://xml.amadeus.com/SATRQT_16_1_1A" xmlns:air_multiavailabilityreply_16_1="http://xml.amadeus.com/SATRSP_16_1_1A" xmlns:air_tlagetavailability_15_1="http://xml.amadeus.com/SLCCRQ_15_1_1A" xmlns:air_tlagetavailabilityreply_15_1="http://xml.amadeus.com/SLCCRR_15_1_1A" xmlns:fare_tlagetfarerules_5_1="http://xml.amadeus.com/TFRURQ_05_1_1A" xmlns:fare_tlagetfarerulesreply_5_1="http://xml.amadeus.com/TFRURR_05_1_1A" xmlns:pnr_listtsm_7_3="http://xml.amadeus.com/TMCLRQ_07_3_1A" xmlns:pnr_listtsmreply_7_3="http://xml.amadeus.com/TMCLRR_07_3_1A" xmlns:pnr_createtsm_7_3="http://xml.amadeus.com/TMCOCQ_07_3_1A" xmlns:pnr_createtsmreply_7_3="http://xml.amadeus.com/TMCOCR_07_3_1A" xmlns:pnr_displaytsm_7_3="http://xml.amadeus.com/TMCORQ_07_3_1A" xmlns:pnr_displaytsmreply_7_3="http://xml.amadeus.com/TMCORR_07_3_1A" xmlns:pnr_updatetsm_7_3="http://xml.amadeus.com/TMCOUQ_07_3_1A" xmlns:pnr_updatetsmreply_7_3="http://xml.amadeus.com/TMCOUR_07_3_1A" targetNamespace="http://xml.amadeus.com">
  <wsdl:types>
    <xs:schema>
      <xs:import namespace="http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd" schemaLocation="WBS_Session-2.0.xsd" />
      <xs:import namespace="http://xml.amadeus.com/ARBKUQ_14_1_1A" schemaLocation="Air_RebookAirSegment_14_1_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/ARBKUR_14_1_1A" schemaLocation="Air_RebookAirSegmentReply_14_1_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/CCARQT_05_3_1A" schemaLocation="Ticket_ValidateCreditCard_05_3_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/CCARSP_05_3_1A" schemaLocation="Ticket_ValidateCreditCardReply_05_3_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/CCDRQT_02_1_1A" schemaLocation="Ticket_ValidateDescBillData_02_1_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/CCDRSP_02_1_1A" schemaLocation="Ticket_ValidateDescBillDataReply_02_1_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/CCVRQT_06_1_1A" schemaLocation="Ticket_CreditCardCheck_06_1_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/CCVRSP_06_1_1A" schemaLocation="Ticket_CreditCardCheckReply_06_1_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/FLIREQ_07_1_1A" schemaLocation="Air_FlightInfo_07_1_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/FLIRES_07_1_1A" schemaLocation="Air_FlightInfoReply_07_1_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/PHIDRQ_16_1_1A" schemaLocation="PNR_DisplayHistory_16_1_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/PHIDRR_16_1_1A" schemaLocation="PNR_DisplayHistoryReply_16_1_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/POWNUQ_14_1_1A" schemaLocation="PNR_TransferOwnership_14_1_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/POWNUR_14_1_1A" schemaLocation="PNR_TransferOwnershipReply_14_1_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/PRNPUQ_04_1_1A" schemaLocation="PNR_ReduceNIP_04_1_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/PRNPUR_04_1_1A" schemaLocation="PNR_ReduceNIPReply_04_1_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/SATRQT_16_1_1A" schemaLocation="Air_MultiAvailability_16_1_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/SATRSP_16_1_1A" schemaLocation="Air_MultiAvailabilityReply_16_1_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/SLCCRQ_15_1_1A" schemaLocation="Air_TLAGetAvailability_15_1_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/SLCCRR_15_1_1A" schemaLocation="Air_TLAGetAvailabilityReply_15_1_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/TFRURQ_05_1_1A" schemaLocation="Fare_TLAGetFareRules_05_1_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/TFRURR_05_1_1A" schemaLocation="Fare_TLAGetFareRulesReply_05_1_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/TMCLRQ_07_3_1A" schemaLocation="PNR_ListTSM_07_3_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/TMCLRR_07_3_1A" schemaLocation="PNR_ListTSMReply_07_3_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/TMCOCQ_07_3_1A" schemaLocation="PNR_CreateTSM_07_3_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/TMCOCR_07_3_1A" schemaLocation="PNR_CreateTSMReply_07_3_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/TMCORQ_07_3_1A" schemaLocation="PNR_DisplayTSM_07_3_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/TMCORR_07_3_1A" schemaLocation="PNR_DisplayTSMReply_07_3_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/TMCOUQ_07_3_1A" schemaLocation="PNR_UpdateTSM_07_3_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/TMCOUR_07_3_1A" schemaLocation="PNR_UpdateTSMReply_07_3_1A.xsd" />
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="Session_2.0">
    <wsdl:part element="awsse:Session" name="session" />
  </wsdl:message>
  <wsdl:message name="Air_FlightInfo_7_1">
    <wsdl:part element="air_flightinfo_7_1:Air_FlightInfo" name="Air_FlightInfo_7_1" />
  </wsdl:message>
  <wsdl:message name="Air_FlightInfoReply_7_1">
    <wsdl:part element="air_flightinforeply_7_1:Air_FlightInfoReply" name="Air_FlightInfoReply_7_1" />
  </wsdl:message>
  <wsdl:message name="Air_MultiAvailability_16_1">
    <wsdl:part element="air_multiavailability_16_1:Air_MultiAvailability" name="Air_MultiAvailability_16_1" />
  </wsdl:message>
  <wsdl:message name="Air_MultiAvailabilityReply_16_1">
    <wsdl:part element="air_multiavailabilityreply_16_1:Air_MultiAvailabilityReply" name="Air_MultiAvailabilityReply_16_1" />
  </wsdl:message>
  <wsdl:message name="Air_RebookAirSegment_14_1">
    <wsdl:part element="air_rebookairsegment_14_1:Air_RebookAirSegment" name="Air_RebookAirSegment_14_1" />
  </wsdl:message>
  <wsdl:message name="Air_RebookAirSegmentReply_14_1">
    <wsdl:part element="air_rebookairsegmentreply_14_1:Air_RebookAirSegmentReply" name="Air_RebookAirSegmentReply_14_1" />
  </wsdl:message>
  <wsdl:message name="Air_TLAGetAvailability_15_1">
    <wsdl:part element="air_tlagetavailability_15_1:Air_TLAGetAvailability" name="Air_TLAGetAvailability_15_1" />
  </wsdl:message>
  <wsdl:message name="Air_TLAGetAvailabilityReply_15_1">
    <wsdl:part element="air_tlagetavailabilityreply_15_1:Air_TLAGetAvailabilityReply" name="Air_TLAGetAvailabilityReply_15_1" />
  </wsdl:message>
  <wsdl:message name="Fare_TLAGetFareRules_5_1">
    <wsdl:part element="fare_tlagetfarerules_5_1:Fare_TLAGetFareRules" name="Fare_TLAGetFareRules_5_1" />
  </wsdl:message>
  <wsdl:message name="Fare_TLAGetFareRulesReply_5_1">
    <wsdl:part element="fare_tlagetfarerulesreply_5_1:Fare_TLAGetFareRulesReply" name="Fare_TLAGetFareRulesReply_5_1" />
  </wsdl:message>
  <wsdl:message name="PNR_CreateTSM_7_3">
    <wsdl:part element="pnr_createtsm_7_3:PNR_CreateTSM" name="PNR_CreateTSM_7_3" />
  </wsdl:message>
  <wsdl:message name="PNR_CreateTSMReply_7_3">
    <wsdl:part element="pnr_createtsmreply_7_3:PNR_CreateTSMReply" name="PNR_CreateTSMReply_7_3" />
  </wsdl:message>
  <wsdl:message name="PNR_DisplayHistory_16_1">
    <wsdl:part element="pnr_displayhistory_16_1:PNR_DisplayHistory" name="PNR_DisplayHistory_16_1" />
  </wsdl:message>
  <wsdl:message name="PNR_DisplayHistoryReply_16_1">
    <wsdl:part element="pnr_displayhistoryreply_16_1:PNR_DisplayHistoryReply" name="PNR_DisplayHistoryReply_16_1" />
  </wsdl:message>
  <wsdl:message name="PNR_DisplayTSM_7_3">
    <wsdl:part element="pnr_displaytsm_7_3:PNR_DisplayTSM" name="PNR_DisplayTSM_7_3" />
  </wsdl:message>
  <wsdl:message name="PNR_DisplayTSMReply_7_3">
    <wsdl:part element="pnr_displaytsmreply_7_3:PNR_DisplayTSMReply" name="PNR_DisplayTSMReply_7_3" />
  </wsdl:message>
  <wsdl:message name="PNR_ListTSM_7_3">
    <wsdl:part element="pnr_listtsm_7_3:PNR_ListTSM" name="PNR_ListTSM_7_3" />
  </wsdl:message>
  <wsdl:message name="PNR_ListTSMReply_7_3">
    <wsdl:part element="pnr_listtsmreply_7_3:PNR_ListTSMReply" name="PNR_ListTSMReply_7_3" />
  </wsdl:message>
  <wsdl:message name="PNR_ReduceNIP_4_1">
    <wsdl:part element="pnr_reducenip_4_1:PNR_ReduceNIP" name="PNR_ReduceNIP_4_1" />
  </wsdl:message>
  <wsdl:message name="PNR_ReduceNIPReply_4_1">
    <wsdl:part element="pnr_reducenipreply_4_1:PNR_ReduceNIPReply" name="PNR_ReduceNIPReply_4_1" />
  </wsdl:message>
  <wsdl:message name="PNR_TransferOwnership_14_1">
    <wsdl:part element="pnr_transferownership_14_1:PNR_TransferOwnership" name="PNR_TransferOwnership_14_1" />
  </wsdl:message>
  <wsdl:message name="PNR_TransferOwnershipReply_14_1">
    <wsdl:part element="pnr_transferownershipreply_14_1:PNR_TransferOwnershipReply" name="PNR_TransferOwnershipReply_14_1" />
  </wsdl:message>
  <wsdl:message name="PNR_UpdateTSM_7_3">
    <wsdl:part element="pnr_updatetsm_7_3:PNR_UpdateTSM" name="PNR_UpdateTSM_7_3" />
  </wsdl:message>
  <wsdl:message name="PNR_UpdateTSMReply_7_3">
    <wsdl:part element="pnr_updatetsmreply_7_3:PNR_UpdateTSMReply" name="PNR_UpdateTSMReply_7_3" />
  </wsdl:message>
  <wsdl:message name="Ticket_CreditCardCheck_6_1">
    <wsdl:part element="ticket_creditcardcheck_6_1:Ticket_CreditCardCheck" name="Ticket_CreditCardCheck_6_1" />
  </wsdl:message>
  <wsdl:message name="Ticket_CreditCardCheckReply_6_1">
    <wsdl:part element="ticket_creditcardcheckreply_6_1:Ticket_CreditCardCheckReply" name="Ticket_CreditCardCheckReply_6_1" />
  </wsdl:message>
  <wsdl:message name="Ticket_ValidateCreditCard_5_3">
    <wsdl:part element="ticket_validatecreditcard_5_3:Ticket_ValidateCreditCard" name="Ticket_ValidateCreditCard_5_3" />
  </wsdl:message>
  <wsdl:message name="Ticket_ValidateCreditCardReply_5_3">
    <wsdl:part element="ticket_validatecreditcardreply_5_3:Ticket_ValidateCreditCardReply" name="Ticket_ValidateCreditCardReply_5_3" />
  </wsdl:message>
  <wsdl:message name="Ticket_ValidateDescBillData_2_1">
    <wsdl:part element="ticket_validatedescbilldata_2_1:Ticket_ValidateDescBillData" name="Ticket_ValidateDescBillData_2_1" />
  </wsdl:message>
  <wsdl:message name="Ticket_ValidateDescBillDataReply_2_1">
    <wsdl:part element="ticket_validatedescbilldatareply_2_1:Ticket_ValidateDescBillDataReply" name="Ticket_ValidateDescBillDataReply_2_1" />
  </wsdl:message>
  <wsdl:portType name="AmadeusWebServicesPT">
    <wsdl:operation name="Air_FlightInfo">
      <wsdl:input message="tns:Air_FlightInfo_7_1" />
      <wsdl:output message="tns:Air_FlightInfoReply_7_1" />
    </wsdl:operation>
    <wsdl:operation name="Air_MultiAvailability">
      <wsdl:input message="tns:Air_MultiAvailability_16_1" />
      <wsdl:output message="tns:Air_MultiAvailabilityReply_16_1" />
    </wsdl:operation>
    <wsdl:operation name="Air_RebookAirSegment">
      <wsdl:input message="tns:Air_RebookAirSegment_14_1" />
      <wsdl:output message="tns:Air_RebookAirSegmentReply_14_1" />
    </wsdl:operation>
    <wsdl:operation name="Air_TLAGetAvailability">
      <wsdl:input message="tns:Air_TLAGetAvailability_15_1" />
      <wsdl:output message="tns:Air_TLAGetAvailabilityReply_15_1" />
    </wsdl:operation>
    <wsdl:operation name="Fare_TLAGetFareRules">
      <wsdl:input message="tns:Fare_TLAGetFareRules_5_1" />
      <wsdl:output message="tns:Fare_TLAGetFareRulesReply_5_1" />
    </wsdl:operation>
    <wsdl:operation name="PNR_CreateTSM">
      <wsdl:input message="tns:PNR_CreateTSM_7_3" />
      <wsdl:output message="tns:PNR_CreateTSMReply_7_3" />
    </wsdl:operation>
    <wsdl:operation name="PNR_DisplayHistory">
      <wsdl:input message="tns:PNR_DisplayHistory_16_1" />
      <wsdl:output message="tns:PNR_DisplayHistoryReply_16_1" />
    </wsdl:operation>
    <wsdl:operation name="PNR_DisplayTSM">
      <wsdl:input message="tns:PNR_DisplayTSM_7_3" />
      <wsdl:output message="tns:PNR_DisplayTSMReply_7_3" />
    </wsdl:operation>
    <wsdl:operation name="PNR_ListTSM">
      <wsdl:input message="tns:PNR_ListTSM_7_3" />
      <wsdl:output message="tns:PNR_ListTSMReply_7_3" />
    </wsdl:operation>
    <wsdl:operation name="PNR_ReduceNIP">
      <wsdl:input message="tns:PNR_ReduceNIP_4_1" />
      <wsdl:output message="tns:PNR_ReduceNIPReply_4_1" />
    </wsdl:operation>
    <wsdl:operation name="PNR_TransferOwnership">
      <wsdl:input message="tns:PNR_TransferOwnership_14_1" />
      <wsdl:output message="tns:PNR_TransferOwnershipReply_14_1" />
    </wsdl:operation>
    <wsdl:operation name="PNR_UpdateTSM">
      <wsdl:input message="tns:PNR_UpdateTSM_7_3" />
      <wsdl:output message="tns:PNR_UpdateTSMReply_7_3" />
    </wsdl:operation>
    <wsdl:operation name="Ticket_CreditCardCheck">
      <wsdl:input message="tns:Ticket_CreditCardCheck_6_1" />
      <wsdl:output message="tns:Ticket_CreditCardCheckReply_6_1" />
    </wsdl:operation>
    <wsdl:operation name="Ticket_ValidateCreditCard">
      <wsdl:input message="tns:Ticket_ValidateCreditCard_5_3" />
      <wsdl:output message="tns:Ticket_ValidateCreditCardReply_5_3" />
    </wsdl:operation>
    <wsdl:operation name="Ticket_ValidateDescBillData">
      <wsdl:input message="tns:Ticket_ValidateDescBillData_2_1" />
      <wsdl:output message="tns:Ticket_ValidateDescBillDataReply_2_1" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding type="tns:AmadeusWebServicesPT" name="AmadeusWebServicesBinding">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="Air_FlightInfo">
      <soap:operation soapAction="http://webservices.amadeus.com/1ASIWPOC1A/FLIREQ_07_1_1A" />
      <wsdl:input>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Air_MultiAvailability">
      <soap:operation soapAction="http://webservices.amadeus.com/1ASIWPOC1A/SATRQT_16_1_1A" />
      <wsdl:input>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Air_RebookAirSegment">
      <soap:operation soapAction="http://webservices.amadeus.com/1ASIWPOC1A/ARBKUQ_14_1_1A" />
      <wsdl:input>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Air_TLAGetAvailability">
      <soap:operation soapAction="http://webservices.amadeus.com/1ASIWPOC1A/SLCCRQ_15_1_1A" />
      <wsdl:input>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Fare_TLAGetFareRules">
      <soap:operation soapAction="http://webservices.amadeus.com/1ASIWPOC1A/TFRURQ_05_1_1A" />
      <wsdl:input>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="PNR_CreateTSM">
      <soap:operation soapAction="http://webservices.amadeus.com/1ASIWPOC1A/TMCOCQ_07_3_1A" />
      <wsdl:input>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="PNR_DisplayHistory">
      <soap:operation soapAction="http://webservices.amadeus.com/1ASIWPOC1A/PHIDRQ_16_1_1A" />
      <wsdl:input>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="PNR_DisplayTSM">
      <soap:operation soapAction="http://webservices.amadeus.com/1ASIWPOC1A/TMCORQ_07_3_1A" />
      <wsdl:input>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="PNR_ListTSM">
      <soap:operation soapAction="http://webservices.amadeus.com/1ASIWPOC1A/TMCLRQ_07_3_1A" />
      <wsdl:input>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="PNR_ReduceNIP">
      <soap:operation soapAction="http://webservices.amadeus.com/1ASIWPOC1A/PRNPUQ_04_1_1A" />
      <wsdl:input>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="PNR_TransferOwnership">
      <soap:operation soapAction="http://webservices.amadeus.com/1ASIWPOC1A/POWNUQ_14_1_1A" />
      <wsdl:input>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="PNR_UpdateTSM">
      <soap:operation soapAction="http://webservices.amadeus.com/1ASIWPOC1A/TMCOUQ_07_3_1A" />
      <wsdl:input>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Ticket_CreditCardCheck">
      <soap:operation soapAction="http://webservices.amadeus.com/1ASIWPOC1A/CCVRQT_06_1_1A" />
      <wsdl:input>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Ticket_ValidateCreditCard">
      <soap:operation soapAction="http://webservices.amadeus.com/1ASIWPOC1A/CCARQT_05_3_1A" />
      <wsdl:input>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Ticket_ValidateDescBillData">
      <soap:operation soapAction="http://webservices.amadeus.com/1ASIWPOC1A/CCDRQT_02_1_1A" />
      <wsdl:input>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
        <soap:header use="literal" message="tns:Session_2.0" part="session" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="AmadeusWebServices">
    <wsdl:port name="AmadeusWebServicesPort" binding="tns:AmadeusWebServicesBinding">
      <soap:address location="https://nodeD1.test.webservices.amadeus.com" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>

**Comment by humanyu** [comment]
Let me know where I can see soap request code.

One more thing i am geting seperate response for airline segment and price also while passing multiple itinerary in faremasterpricetbsearch.
May I ask if i am fetching result for DEL to BOM with return flight in SAME DATE.
Is there need to arrenge according to departure time respectly arrival time

**Comment by DerMika** [comment]
Merged PR, thanks again!

**Comment by m0veax** [comment]
Thanks for you support while working on the pull request.

I've learned a lot about unit tests and had fun implementing :)
