### ISSUE TITLE
The infant associated to another passenger.

### ISSUE THREAD

**Issue by jcarriquiry** [amabnl/amadeus-ws-client#17]
I need add an infant associated to another passenger. I need generate the following XML's structure, where the infant is in the same travellerInfo block:

`<travellerInfo>
<elementManagementPassenger>
<reference>
<qualifier>PR</qualifier>
<number>2</number>
</reference>
<segmentName>NM</segmentName>
</elementManagementPassenger>
<passengerData>
<travellerInformation>
<traveller>
<surname>SMITH</surname>
<quantity>2</quantity>
</traveller>
<passenger>
<firstName>A MRS</firstName>
<type>ADT</type>
<infantIndicator>3</infantIndicator>
</passenger>
</travellerInformation>
</passengerData>
<passengerData>
<travellerInformation>
<traveller>
<surname>BROWN</surname>
</traveller>
<passenger>
<firstName>JIMMY</firstName>
<type>INF</type>
</passenger>
</travellerInformation>
<dateOfBirth>
<dateAndTimeDetails>
<date>10JAN08</date>
</dateAndTimeDetails>
</dateOfBirth>
</passengerData>
</travellerInfo>`

In the code say that this is not supported. Do you have plans to add this?

Thanks

**Comment by jcarriquiry** [comment]
DerMika, I developed a solution to add an infant associated to another passenger.

I had modified de **_createTraveller_** funtion in _src\Amadeus\Client\Struct\Pnr\AddMultiElements.php_:

` protected function createTraveller($traveller)
    {
        $createdTraveller = new TravellerInfo(
            ElementManagementPassenger::SEG_NAME,
            $traveller->lastName
        );
        if (!is_null($traveller->number)) {
            $createdTraveller->elementManagementPassenger->reference = new Reference(
                Reference::QUAL_PASSENGER,
                $traveller->number
            );
        }
        if ($traveller->dateOfBirth instanceof \DateTime) {
            $createdTraveller->passengerData[0]->dateOfBirth = new DateOfBirth(
                $traveller->dateOfBirth->format('dmY')
            );
        }
        if ($traveller->firstName !== null || $traveller->travellerType !== null) {
            $createdTraveller->passengerData[0]->travellerInformation->passenger[] = new Passenger(
                $traveller->firstName,
                $traveller->travellerType
            );
        }

	    if ($traveller->withInfant === true || ($traveller->infant !== null && count($traveller->infant) > 0 ) ) {
            //throw new \RuntimeException('Adding Infants is not yet supported');
			
			$createdTraveller->passengerData[0]->travellerInformation->traveller->quantity = 2;
			$createdTraveller->passengerData[0]->travellerInformation->passenger[0]->infantIndicator = 3;
		
			$createdTraveller->passengerData[1] = new AddMultiElements\PassengerData($traveller->infant->lastName);	
			$createdTraveller->passengerData[1]->travellerInformation->passenger[] = new Passenger(
                $traveller->infant->firstName,
                $traveller->infant->travellerType
            );        
		
		}


        return $createdTraveller;
    }`

To make the call I did this: 

` $aTravelers[] = array('number' => 1,
                      'lastName' => 'Doe', 
					  'firstName' => 'John', 
					  'travellerType' => 'ADT',
					  'withInfant' => true,
					  'infant' => array('number' => 5,'lastName' => 'Doe', 'firstName' => 'Baby', 'travellerType' => 'INF', 'dateOfBirth' => '03052016')					  
					  );`
And then

` foreach( $aTravelers as $traveler ) {
	$traveller_inf = array();	
	if ($traveler["withInfant"]) {

		$traveller_inf = new Traveller(['lastName' => $traveler["infant"]["lastName"],
										'firstName' => $traveler["infant"]["firstName"],
										'travellerType' => $traveler["infant"]["travellerType"],
										'dateOfBirth' => $traveler["infant"]["dateOfBirth"],
										'withInfant' => false 
										]);
	}															
	
	$createPnrOptions->travellers[] = new Traveller([
											'number' => $traveler["number"],
											'lastName' => $traveler["lastName"],
											'firstName' => $traveler["firstName"],
											'travellerType' => $traveler["travellerType"],
											'withInfant' => $traveler["withInfant"],
											'infant' => $traveller_inf
										]);

	$aReferences[] = new Reference([
                    'type' => Reference::TYPE_PASSENGER_TATTOO,
                    'id' => $traveler["number"]
                ]); }`

If you wish, I could send you the entire source code.

Best regards

**Comment by DerMika** [comment]
Hi @jcarriquiry, I _was_ planning to add infant support, but I hadn't gotten around to it yet. 

I wanted to make sure I could support all the infant scenarios mentioned in the `PNR_AddMultiElements` docs. There are different ways to add infants depending on what information you have of them (last name, first name, date of birth,...). 

I will add support for infants before I release the first version. Or if you have a pull request, don't hesitate to contribute ;)

**Comment by DerMika** [comment]
Implemented support for 3 scenario's of Infant passengers (No infant information, only first name, or first name, last name and date of birth). 

See the updated docs on how to add them to your requests: https://github.com/amabnl/amadeus-ws-client/blob/develop/docs/samples/pnr-create-modify.rst#passengers-infants

If you find any problems, feel free to open a new ticket!
