### ISSUE TITLE
Special Seat Request in Pnr_addMultiElemenst

### ISSUE THREAD

**Issue by shaiby** [amabnl/amadeus-ws-client#174]
I was trying to send special seat request. Here is what amadeus respond with the new preference
-------------------
In this scenario, the issue is the NSSW (Non-smoking window seat) request. This is no longer supported by most airlines. In order to make a request for a preferred seat, please use the STR as below:
```xml
   <dataElementsIndiv>
      <elementManagementData>
        <reference>
          <qualifier>OT</qualifier>
          <number>1</number>
        </reference>
        <segmentName>STR</segmentName>
      </elementManagementData>
      <seatGroup>
        <seatRequest>
         <special>
            <seatType>A</seatType>
          </special>
        </seatRequest>
      </seatGroup>
      <referenceForDataElement>
        <reference>
          <qualifier>PT</qualifier>
          <number>1</number>
        </reference>
      </referenceForDataElement>
    </dataElementsIndiv>
```

In the seatType node, you can send the following:

A | Aisle seat
-- | --
H | Seat with facilities for Handicapped/incapacitated
I | Seat suitable for adult with an infant
K | Bulkhead seat (B in customer profile)
MA | Medically OK for travel
N | No smoking seat
S | Smoking seat
U | Seat suitable for unaccompanied minor
W | Window seat
----------------------------------------

But using class preference, it never  add the <special> tag in seat request...that's what cause the response to invalid. Is there any luck regarding this. Here is class generated XML in request that differ from Amadeus recommendation.

```xml
<ns1:dataElementsIndiv>
    <ns1:elementManagementData>
        <ns1:reference>
            <ns1:qualifier>OT</ns1:qualifier>
            <ns1:number>2</ns1:number>
        </ns1:reference>
        <ns1:segmentName>STR</ns1:segmentName>
    </ns1:elementManagementData>
    <ns1:seatGroup>
        <ns1:seatRequest>
            <ns1:seat>
                <ns1:type>A</ns1:type>
            </ns1:seat>
        </ns1:seatRequest>
    </ns1:seatGroup>
    <ns1:referenceForDataElement>
        <ns1:reference>
            <ns1:qualifier>PT</ns1:qualifier>
            <ns1:number>2</ns1:number>
        </ns1:reference>
        <ns1:reference>
            <ns1:qualifier>ST</ns1:qualifier>
            <ns1:number>1</ns1:number>
        </ns1:reference>
        <ns1:reference>
            <ns1:qualifier>ST</ns1:qualifier>
            <ns1:number>2</ns1:number>
        </ns1:reference>
    </ns1:referenceForDataElement>
</ns1:dataElementsIndiv> 
```

**Comment by DerMika** [comment]
Which version of `PNR_AddMultiElements` do you have in your WSAP?

**Comment by shaiby** [comment]
this is I think PNRADD_16_1_1A

**Comment by DerMika** [comment]
The problem  is that I don't find any samples on Amadeus' Extranet . What I have implemented is sample: 

> 5.41 Operation: Seat Request

in the `PNR_AddMultiElements` user guide.

Can you point me to some Amadeus documentation regarding this new way to add Seat requests to the PNR?

**Comment by DerMika** [comment]
I've implemented it, calling it "Special Seat Type" for now. It's available on `dev-master`

I'm waiting to see if you can dig up any documentation which could give me a clue as to how to name this feature better.

**Comment by shaiby** [comment]
I am sorry for being late in response...Yes you are correct...its name should be Special Seat Type Request. The help documentation is same as I post in issue statement.

**Comment by DerMika** [comment]
In that case you can test the new feature on the master. I'll release it with 1.7.0.

**Comment by DerMika** [comment]
Version 1.7.0 has been released!
