### ISSUE TITLE
FareMasterPricerCalendarOptions Pricing

### ISSUE THREAD

**Issue by tafensw2810** [amabnl/amadeus-ws-client#180]
Hi All,

Thank you for reading my message.  I am successfully calling the FareMasterPricerCalendarOptions function.  It returns information however it does seem to be missing the actual fair price.  How do I get that information as part of this call?

Thank you!

**Comment by DerMika** [comment]
Have you checked the Fare_MasterPricerCalendar documentation on the Amadeus Extranet to verify where you could expect price nodes to show up in the XML? Could you post a sample request and response _(hide any personal information such as WSAP endpoint and session data when you do)_

See [this part in the documentation](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#logging-request-and-response) where you can provide a logger object to the client.

**Comment by DerMika** [comment]
Closing due to lack of feedback
