### ISSUE TITLE
How to add baggage and insurance to the reservation

### ISSUE THREAD

**Issue by DmitryUtkin** [amabnl/amadeus-ws-client#182]
Hello! I'll be happy if you help me.

I have some requests in SOAPUI:
Security_Authenticate;
PNR_AddMultiElements;
Fare_PricePNRWithBookingClass;
Ticket_CreateTSTFromPricing;
PNR_AddMultiElements: Commit;
Payment for the reservation is made from the external system.

How can I add to the reservation?
- add baggage;
- paid place;
- transportation of an animal - a parrot;
- add passenger insurance;

Example query PNR_AddMultiElements in the attachment.
[PNR_AddMultiElements.txt](https://github.com/amabnl/amadeus-ws-client/files/1919655/PNR_AddMultiElements.txt)

**Comment by DerMika** [comment]
Add baggage: Is this paid baggage (as in, an ancillary service)? If so, you need to look at the Service_* messages. There is an implementation guid on the Amadeus Web Services Extranet called "Amadeus WBS Implementation Guide for Bags" which probably explains this flow.

Paid seat: there is an implementation guide on the Amadeus Web Services Extranet which explains selling seats using Air_RetrieveSeatMap and booking them into the PNR. This library supports that flow.

Transport of an animal: I don't know the answer to that. You should contact Amadeus Support for that. 

Passenger Insurance: I've never worked with Insurance myself. I suggect you ask Amadeus Support, they should be able to provide the necessary docs. If this library is missing some messages for you to implement Insurance, let me know and I can help.

**Comment by bimusiek** [comment]
I am in certification process of Ancillary Services and transport of animal is part of the service that airlines provide. 

> This request shows you how to add a Special Service Request (SSR) to your Passenger Name Record (PNR) to carry a cat in the passenger cabin, with maximum weight 5Kg (cat and container weight) and dimensions of 40x20x20 (length, width and height).
> 
> This assumes that the Pets in Passenger Cabin (PETC) service was returned in a previous ancillary service catalogue response (Service_StandaloneCatalogue or Service_IntegratedCatalogue).

**Comment by DerMika** [comment]
Let me know if this issue is solved for you now.

**Comment by DerMika** [comment]
Closing due to lack of feedback - you can re-open if needed.
