### ISSUE TITLE
On Hold Booking

### ISSUE THREAD

**Issue by XYNOMEX** [amabnl/amadeus-ws-client#183]
If I want to put the booking on hold and then after 48 hours confirm it and issue the ticket.
how can I do it ?? @DerMika

**Comment by XYNOMEX** [comment]
Thx, Is There any example i can see how to do it "Create PNR with seat reserved" ?

**Comment by DerMika** [comment]
What he means is the airline will reserve a seat on the airplane on PNR creation, but will sell it again to someone else if the PNR isn't ticketed before the ticketing deadline.

**Comment by DerMika** [comment]
Also, if you wait longer than a day (again, depending on the airline) before ticketing, you may need to re-price the PNR before you can issue a ticket. Meaning the price could have changed.

**Comment by XYNOMEX** [comment]
thank you @DerMika @bimusiek
