### ISSUE TITLE
Console emulator by Command Cryptic example

### ISSUE THREAD

**Issue by smgladkovskiy** [amabnl/amadeus-ws-client#19]
Hi!

For our team needs we make a [console emulator based on amadeus-ws-client](https://github.com/tmconsulting/amadeus-console-emulator) implementation. Maybe it would be interesting to show in docs as example? :)

![2016-09-16 11 19 20](https://cloud.githubusercontent.com/assets/128070/18579616/71f06930-7bff-11e6-9aa3-a9c86aae8704.png)

**Comment by DerMika** [comment]
Sure, why not! I've added a section "Example applications" to the README which points to [this page](https://github.com/amabnl/amadeus-ws-client/blob/develop/docs/sample-applications.rst) ;)

**Comment by nikhildeshmukh** [comment]
i had seen some terminal on the webpage how can we achive that ?
