### ISSUE TITLE
SOTO Ticket TST for particular currency

### ISSUE THREAD

**Issue by muzaffarkamil86** [amabnl/amadeus-ws-client#190]
How to display tst in particular currency for eg INR.

**Comment by DerMika** [comment]
Perhaps Amadeus will be able to answer more thoroughly than I can, but here is what I believe the situation is:

The TST will be in the currency that the airline has offered the flight recommendation in. So this means the traveller will have to pay for the flight in that currency too. 

All you can do is informatively convert that currency into another currency and say to the user "This flight of $400 would cost you INR 27000 with today's exchange rates". 

For this you can use the `Fare_ConvertCurrency` message: [see samples here](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples.rst#fare-convertcurrency)

**Comment by muzaffarkamil86** [comment]
Please suggest that is any webservice is required to add in my wsdl file to use that Fare_ConvertCurrency. Or you use any other webservice to get exchange rates like yahoo or google api.

**Comment by DerMika** [comment]
Well if you want to use Fare_ConvertCurrency, that's the message you should have added to your WSDL by Amadeus...

That message will provide currency conversion through several methods. You should investigate its documentation or ask Amadeus to help you understand how their currency conversion message works (to decide if it's useful to you).

It's your own choice whether you want to use the Amadeus WS message or an external service to perform currency conversion. I'm not able to give you any advice on that, as you

**Comment by DerMika** [comment]
Is your question solved? If so, please close this issue.

**Comment by muzaffarkamil86** [comment]
thanks
