### ISSUE TITLE
Problem with the passenger tattoo reference number

### ISSUE THREAD

**Issue by arosha445** [amabnl/amadeus-ws-client#191]
When i tried to add 2 passenger details using PNR_AddMultiElements with PR number 1 and 2 but in the PNR_Reply response their PT numbers has changed to 2 and 3.

Please refer below link:
[PNR_multiAdd Request and Response](https://gist.github.com/arosha445/a20ba88ff30a0980b5dc6478a4371bb1.js)

**Comment by DerMika** [comment]
Yes, that is normal. 

You define your own PR (passenger request) numbers when you send your message, but the Amadeus system will assign its own internal number to each passenger. It's even possible the order of passengers is changed in the `PNR_Reply`!

You should write your code to be able to deal with this problem.

**Comment by arosha445** [comment]
Oh that's a pity. Anyway thanks a lot for the info @DerMika I'll implement a way around it.

**Comment by DerMika** [comment]
Good luck. I know it's a pain to have to deal with :(
