### ISSUE TITLE
SSR DOCS passport data issue

### ISSUE THREAD

**Issue by ahmedeltokhy** [amabnl/amadeus-ws-client#195]
Hello All,
I am trying to insert the passport data (number, country, and expiry) or the ServiceRequest but I am getting Error wrong free text the following is the free text value I am inserting and the error received:
Free text
----P-EGY-1312312312-EGY-04FEB87-09MAR22-M-HASSAN-AHMED
Error
{
            "code": "463",
            "text": "INVALID TEXT DATA - INVALID TEXT DATA - INVALID TEXT DATA - INVALID TEXT DATA",
            "level": "element"
        }

**Comment by bimusiek** [comment]
`P-POL-EB6353535-POL-06MAY93-M-12DEC20-HERNAS-JOHN-`
Thats correct format.

Corresponding code:
```php
 return  new ServiceRequest([
            'type' => 'DOCS',
            // 'company' => $this->marketingCarrier,
            'status' => ServiceRequest::STATUS_HOLD_CONFIRMED,
            'quantity' => 1,
            'freeText' => [
                'P-'.$this->issuingCountry.'-'.$this->passportNo.'-'.$this->citizenship.'-'.$this->birthday->format('dMy').'-'.$this->gender.'-'.$this->expirationDate->format('dMy').'-'.$this->lastName.'-'.$this->firstName.'-'.$this->middleName
            ],
            'references' => [
                new Reference([
                    'type' => $requestRef ? Reference::TYPE_PASSENGER_REQUEST : Reference::TYPE_PASSENGER_TATTOO,
                    'id' => $requestRef ? $requestRef : $this->getRef($passengers)
                ])
            ]
        ]);
```

**Comment by ahmedeltokhy** [comment]
@bimusiek  Thanks a lot your format made it working
