### ISSUE TITLE
How to get TST Number on ticketCreateTSTFromPricing?

### ISSUE THREAD

**Issue by mhrahul** [amabnl/amadeus-ws-client#196]
Dear @DerMika, I can retrieve PNR and successfully get controlNumber. But a bit confused about the TST_number, where to get it? Without it, I cant use the function ticketCreateTSTFromPricing to create tickets. Please need urgent help!

**Comment by DerMika** [comment]
You need a pricing to create a TST from. To create a pricing, call `Fare_PricePNRwithBookingClass` or an associated message (such as `Fare_PricePNRwithLowestFare`).

This message will return one or more possible pricings, which you then have to turn into a TST with Ticket_CreateTSTFromPricing.

You should probably read the "Amadeus WBS Implementation Guide - Internet Booking Engine with Master Pricer", which can be downloaded on the Amadeus Extranet. It shows you the entire flow needed to create an online booking engine.

**Comment by DerMika** [comment]
Either you're not using a Stateful session, or you're re-instantiating the client object between different messages. 

For the first, [see here](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#switching-between-stateful-stateless-messages-soap-header-4)

For the second: you can get the currently active session and restore that session when re-instantiating the client [as explained here](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#handling-sessions-with-soap-header-2)

**Comment by mhrahul** [comment]
ow my Stateful session was false.
 `'stateful' => false, //Enable stateful messages by default - can be changed at will to switch between stateless & stateful.
                'logger' => null`

Trying with enabling it.

**Comment by mhrahul** [comment]
well I have enabled 
`'sessionHandlerParams' => [
                'soapHeaderVersion' => Client::HEADER_V4, //This is the default value, can be omitted.
                'wsdl' => 'amadusWSDL/1ASIWGHUKKK_PDT_20180327_045112.wsdl', //Points to the location of the WSDL file for your WSAP. Make sure the associated XSD's are also available.
                'stateful' => true, //Enable stateful messages by default - can be changed at will to switch between stateless & stateful.
                'logger' => null
            ],`
Still successfully `$pnrRet = $this->retrivePNR($replayData);`
but error with 
`$pricingResponse = $this->client->farePricePnrWithBookingClass(
                new FarePricePnrWithBookingClassOptions([
            'pricingsFareBasis' => [
                new FareBasis([
                    'fareBasisCode' => $farebasis,
                    'references' => [
                        new PaxSegRef([
                            'reference' => 1,
                            'type' => PaxSegRef::TYPE_SEGMENT
                                ])                        
                    ]
                        ])
            ]
                ])
        );`
need help :(

**Comment by DerMika** [comment]
Which error?

**Comment by mhrahul** [comment]
`Amadeus\Client\Result Object
(
    [status] => ERR
    [messages] => Array
        (
            [0] => Amadeus\Client\Result\NotOk Object
                (
                    [code] => 1383
                    [text] => PNR NOT PRESENT
                    [level] => 
                )

        )`

same error as before.

**Comment by DerMika** [comment]
What happens between PNR_Reply and your calling of Fare_PricePNRWithBookingClass?

Is there a user interface in between? If so: when the request comes back to the server, are you re-initializing the previous session? See [the second item on my response here](https://github.com/amabnl/amadeus-ws-client/issues/196#issuecomment-391098593)

**Comment by mhrahul** [comment]
well, I am using two functions for each.
`  public function createAPI(Request $request) {
        //'Y-m-d His', "2013-10-02 000000"
        //'+3223456789'
        $firstName = $request->input('first_name');
        $lastName = $request->input('last_name');
        $phoneNo = $request->input('phone_no');
        $companyName = $request->input('flight_name');
        $flightNo = $request->input('flight_no');
        $departDate = $request->input('depart_date');
        $departCity = $request->input('depart_city');
        $arrivalCity = $request->input('arrive_city');
        $bookingClass = $request->input('booking_class');

        $pnrReplay = $this->createPnrAPI($firstName, $lastName, $phoneNo, $companyName, $flightNo, $departDate, $departCity, $arrivalCity, $bookingClass);

        $replayData = $pnrReplay['pnrHeader']['reservationInfo']['reservation']['controlNumber'];

        $pnrRet = $this->retrivePNR($replayData);
//        $createTstResponse = $this->client->ticketCreateTSTFromPricing(
//                new TicketCreateTstFromPricingOptions([
//            'pricings' => [
//                new Pricing([
//                    'tstNumber' => 1
//                        ])
//            ]
//                ])
//        );
//
//        print_r($createTstResponse);
        return response()->json($pnrRet);
    }`
`public function fareForPNR(Request $request) {
        $farebasis = $request->input('farebasis');
        
        $pricingResponse = $this->client->farePricePnrWithBookingClass(
                new FarePricePnrWithBookingClassOptions([
            'pricingsFareBasis' => [
                new FareBasis([
                    'fareBasisCode' => $farebasis,
                    'references' => [
                        new PaxSegRef([
                            'reference' => 1,
                            'type' => PaxSegRef::TYPE_SEGMENT
                                ])                        
                    ]
                        ])
            ]
                ])
        );
        
        print_r($pricingResponse);
    }`

**Comment by DerMika** [comment]
Again, what happens beween our call to `createAPI` and `fareForPNR`? They seem to be in a controller of some kind?

If these are separate HTTP requests to your backend, your code will probably re-instantiate the Amadeus\Client object between the 2 calls. If that happens, you have to make sure to restore the previous session. 

This means: before returning `return response()->json($pnrRet);` in your first action, make sure to store the Amadeus\Client session data in a session variable or something similar. ANd then when re-instantiating the client later on, check if a session variable is set with Amadeus\Client session data and if so, restore the session data to the client with that information.

Still the same issue I mentioned above.

**Comment by mhrahul** [comment]
Understood the problem. After retrieving same session it provides me the following output:
`
    "fareList": {
        "pricingInformation": {
            "tstInformation": {
                "tstIndicator": "O"
            },
            "fcmi": "W"
        },
        "fareReference": {
            "referenceType": "TST",
            "uniqueReference": 1
        },
        "lastTktDate": {
            "businessSemantic": "LT",
            "dateTime": {
                "year": 2018,
                "month": "6",
                "day": "6"
            }
        },
        "validatingCarrier": {
            "carrierInformation": {
                "carrierCode": "AI"
            }
        },
        "paxSegReference": {
            "refDetails": {
                "refQualifier": "PA",
                "refNumber": 2
            }
        },
        "fareDataInformation": {
            "fareDataMainInformation": {
                "fareDataQualifier": "F"
            },`
can't understand where to find TST number form here!

**Comment by mhrahul** [comment]
@DerMika I am getting the same issue now that #118 had. Please need help on it.

**Comment by mhrahul** [comment]
Thanks a lot. I am contacting them now for it. Will let you know their answer. :)

**Comment by mhrahul** [comment]
Hi @DerMika, as the Amadeus said for my last thread it was a server end problem. 

Now I think, I have done the full process but didn't find the e-ticket number. I asked their support and their replay was, "Ticket item can be obtained by reading FA item for PNR.". I didn't find any FA item. Where can I find it?

**Comment by DerMika** [comment]
If you retrieve the PNR again after ticket issuance, you should find an FA element under the dataElementsMaster node. If not, something probably went wrong during ticket issuance. Or perhaps the airline only writes the FA element to the PNR with a certain delay? This is something to ask Amadeus.

**Comment by bimusiek** [comment]
After you issue the ticket, close the session, wait 10s and with session-less request retrieve PNR again. FA element should be there.

**Comment by mhrahul** [comment]
@bimusiek i have tried as you mentioned but it give me output:
`"dataElementsMaster": {
        "marker2": [],
        "dataElementsIndiv": [
            {
                "elementManagementData": {
                    "reference": {
                        "qualifier": "OT",
                        "number": 1
                    },
                    "segmentName": "AP",
                    "lineNumber": 3
                },
                "otherDataFreetext": {
                    "freetextDetail": {
                        "subjectQualifier": "3",
                        "type": "5"
                    },
                    "longFreetext": "8801922527441"
                }
            },
            {
                "elementManagementData": {
                    "reference": {
                        "qualifier": "OT",
                        "number": 3
                    },
                    "segmentName": "TK",
                    "lineNumber": 4
                },
                "ticketElement": {
                    "passengerType": "PAX",
                    "ticket": {
                        "indicator": "OK",
                        "date": "260518",
                        "officeId": "DACVS32LN"
                    }
                }
            },
            {
                "elementManagementData": {
                    "reference": {
                        "qualifier": "OT",
                        "number": 9
                    },
                    "segmentName": "SSR",
                    "lineNumber": 5
                },
                "serviceRequest": {
                    "ssr": {
                        "type": "OTHS",
                        "status": " ",
                        "companyId": "1A",
                        "freeText": "AUTO XX IF SSR TKNA/E/M/C NOT RCVD BY BG BY 1242/26MAY/DAC LT"
                    }
                }
            },
            {
                "elementManagementData": {
                    "reference": {
                        "qualifier": "OT",
                        "number": 4
                    },
                    "segmentName": "FE",
                    "lineNumber": 6
                },
                "otherDataFreetext": {
                    "freetextDetail": {
                        "subjectQualifier": "3",
                        "type": "10"
                    },
                    "longFreetext": "PAX NONEND/NONREF- VALID ON BG ONLY"
                },
                "referenceForDataElement": {
                    "reference": [
                        {
                            "qualifier": "ST",
                            "number": "1"
                        },
                        {
                            "qualifier": "PT",
                            "number": "2"
                        }
                    ]
                }
            },
            {
                "elementManagementData": {
                    "reference": {
                        "qualifier": "OT",
                        "number": 2
                    },
                    "segmentName": "FP",
                    "lineNumber": 7
                },
                "otherDataFreetext": {
                    "freetextDetail": {
                        "subjectQualifier": "3",
                        "type": "16"
                    },
                    "longFreetext": "CASH"
                }
            },
            {
                "elementManagementData": {
                    "reference": {
                        "qualifier": "OT",
                        "number": 5
                    },
                    "segmentName": "FV",
                    "lineNumber": 8
                },
                "otherDataFreetext": {
                    "freetextDetail": {
                        "subjectQualifier": "3",
                        "type": "P18"
                    },
                    "longFreetext": "PAX BG"
                },
                "referenceForDataElement": {
                    "reference": [
                        {
                            "qualifier": "ST",
                            "number": "1"
                        },
                        {
                            "qualifier": "PT",
                            "number": "2"
                        }
                    ]
                }
            }
        ]
    },`
is it for I am using a demo user? or am I missing something?

using 
`$pnrResult = $this->client->pnrRetrieve(
                new PnrRetrieveOptions(['recordLocator' => $recordLoc])
        );
`
for PNR retrive. Please guide.

**Comment by mhrahul** [comment]
@bimusiek I have used below code for  ticket booking. 
`$createTstResponse = $this->client->ticketCreateTSTFromPricing(
                new TicketCreateTstFromPricingOptions([
            'pricings' => [
                new Pricing([
                    'tstNumber' => 1,
                        ])
            ]
                ])
        );
        
        $issueTicketResponse = $this->client->docIssuanceIssueTicket(
                new DocIssuanceIssueTicketOptions([
            'options' => [
                DocIssuanceIssueTicketOptions::OPTION_ETICKET,
                DocIssuanceIssueTicketOptions::OPTION_RETRIEVE_PNR
            ]
                ])
        );
        
        $pnrReply_end = $this->client->pnrAddMultiElements(
                new PnrAddMultiElementsOptions([
            'actionCode' => PnrAddMultiElementsOptions::ACTION_END_TRANSACT_RETRIEVE,
                ])
        );`

And the output for ticket_create is:
`{
    "processingStatus": {
        "statusCode": "W"
    },
    "errorGroup": {
        "errorOrWarningCodeDetails": {
            "errorDetails": {
                "errorCode": "0"
            }
        },
        "errorWarningDescription": {
            "freeTextDetails": {
                "textSubjectQualifier": "3",
                "source": "M",
                "encoding": "1"
            },
            "freeText": "IT'S TIME TO BOOK TRAVEL INSURANCE"
        }
    }
}`
What did I miss?

**Comment by mhrahul** [comment]
@DerMika after long struggle finally I have got some result. But sometimes it gives me 
`    "elementManagementData": {
                    "reference": {
                        "qualifier": "OT",
                        "number": 10
                    },
                    "segmentName": "SSR",
                    "lineNumber": 6
                },
                "serviceRequest": {
                    "ssr": {
                        "type": "OTHS",
                        "status": " ",
                        "companyId": "1A",
                        "freeText": "AUTO XX IF SSR TKNA/E/M/C NOT RCVD BY BG BY 0517/29MAY/DAC LT"
                    }
                }
            }, `
and sometimes 
` {
                "elementManagementData": {
                    "reference": {
                        "qualifier": "OT",
                        "number": 12
                    },
                    "segmentName": "FA",
                    "lineNumber": 5
                },
                "otherDataFreetext": {
                    "freetextDetail": {
                        "subjectQualifier": "3",
                        "type": "P06"
                    },
                    "longFreetext": "PAX 098-5119491666/ETAI/BDT15433/28MAY18/DACVS32LN/42305734"
                },
                "referenceForDataElement": {
                    "reference": [
                        {
                            "qualifier": "ST",
                            "number": "1"
                        },
                        {
                            "qualifier": "PT",
                            "number": "2"
                        }
                    ]
                }
            }, `

Please need help what is wrong here?

**Comment by DerMika** [comment]
The first seems to indicate the airline still requires extra information. You should contact Amadeus support to help you explain what is going on.

**Comment by mhrahul** [comment]
Thanks a lot. I already mailed to their support. One More thing to mention that I got the ticket I'd at local Host but when at live server it's missing. Using HostGator shared hosting.

**Comment by DerMika** [comment]
I cannot imagine 2 instances running the same code producing different results. Either you get an error from Amadeus or not. Of course each airline could have specific needs to issue tickets. Usually in a travel agency these messages are followed up by a travel agent with Amadeus knowledge...

**Comment by mhrahul** [comment]
Ya I surprised too and it kill my day. But on local it gives me FA item and in saver FA is missing. Anyway hope Amadeus has some good explanation on it.

**Comment by mhrahul** [comment]
sometime in the test environment problem occurred - it was the replay form Amadeus.

**Comment by mhrahul** [comment]
I have one last problem I think need help. 
My log serves: 
`<ns1:PNR_AddMultiElements><ns1:pnrActions><ns1:optionCode>11</ns1:optionCode>`
But Amadeus  recommend to save the changes with option code 10 rather than 11. **How can I do it?** 

`$pnrReply_end = $this->client->pnrAddMultiElements(
                new PnrAddMultiElementsOptions([
            'actionCode' => PnrAddMultiElementsOptions::ACTION_END_TRANSACT_RETRIEVE,
                ])
        );`

So far I am using it.

**Comment by DerMika** [comment]
Look in the source of the class `PnrAddMultiElementsOptions`, it contains the list of action code constants.

**Comment by mhrahul** [comment]
@DerMika Thanks a lot. Got it. :)

**Comment by mhrahul** [comment]
Hi @DerMika, I was using
`PnrAddMultiElementsOptions::ACTION_END_TRANSACT_RETRIEVE`
but as per Amadeus, they recommended using
`PnrAddMultiElementsOptions::ACTION_END_TRANSACT`

(Amadeus recommend to save the changes with option code 10 rather than 11)

But with the returned controlNumber, I can't find any result. Its return blank on pnrRetrieve. How to fetch?

**Comment by DerMika** [comment]
I don't know why Amadeus recommends that, but an End Transact is a save without a re-retrieve. You'll get errors if the save went wrong, but you won't get the PNR contents back. For that you'd have to re-retrieve the PNR.

If you can't find the controlNumber you got back, something might have gone wrong during the save. Check with Amadeus.

**Comment by mhrahul** [comment]
Well, I have got the controllerNumber back. But with that number, I don't get anything on re-retrieve. I think I need to mail Amadeus on it.

**Comment by mhrahul** [comment]
Hello, @DerMika thanks for the continuous help.  I am almost done with my integration as Amadeus has some wired issues to solve.  Anyway, one last favor I need. I have got 2 SSR message.
1. `"ssr": {
                        "type": "OTHS",
                        "status": " ",
                        "companyId": "1A",
                        "freeText": "PLS ADD CUSTOMER CONTACT DETAILS"
                    }`
2. `"serviceRequest": {
                    "ssr": {
                        "type": "OTHS",
                        "status": " ",
                        "companyId": "1A",
                        "freeText": "UPDATE DOCS DETAIL FOR ALL PAX WITH FULL NAME AS INPASSPORT"
                    }
                }`
But I am providing all the customer details 
`$servReq = new ServiceRequest();`
`$servReq->freeText[] = ['----' . $bd . '-' . $gen . '--' . $td['firstName'] . '-' . $td['lastName']];`
`$otp->travellers[] = new Traveller([
                'number' => 1,
                'lastName' => $td['lastName'],
                'firstName' => $td['firstName'],
                'type' => Traveller::TRAV_TYPE_ADULT,
                'dateOfBirth' => \DateTime::createFromFormat('Y-m-d', $td['dob']),
            ]);`

SO do I missed anything?

**Comment by DerMika** [comment]
Sorry for the late answer, I've been busy. 

Do you still need help with this? 

It could be that the airline requires extra information, like a passport number, or a birth date in the SSR. 

If it's an APIS format you are looking for, check the format mentioned [here](https://github.com/amabnl/amadeus-ws-client/issues/195#issuecomment-389520926) by @bimusiek

**Comment by mhrahul** [comment]
Thank @DerMika. Checking on it. But I stuck on very dump problem. I cant send multiple pricing for multiple passengers. It always sends 1 tst for tst pricing. If I going to send multiple like
` new TicketCreateTstFromPricingOptions([
'pricings' => [
                new Pricing([
                    'tstNumber' => 1,
                        ]),
 new Pricing([
                    'tstNumber' => 2,
                        ])
            ]);`
it always send me one pricing for tickets. I also tried with 
` new Pricing([
                    'tstNumber' => [1,2],
                        ])`
for two adults but no luck!

**Comment by DerMika** [comment]
As far as I know, you can only create 1 TST at a time, since it depends on a pricing in context. But I may be wrong. To be sure... contact Amadeus ;)

**Comment by DerMika** [comment]
Hmm, seems like I'm wrong on that, the Implementation guide mentions multiple TST's: 

```xml
<Ticket_CreateTSTFromPricing>
  <psaList>
    <itemReference>
      <referenceType>TST</referenceType>
      <uniqueReference>1</uniqueReference>
    </itemReference>
  </psaList>
  <psaList>
    <itemReference>
      <referenceType>TST</referenceType>
      <uniqueReference>2</uniqueReference>
    </itemReference>
  </psaList>
  <psaList>
    <itemReference>
      <referenceType>TST</referenceType>
      <uniqueReference>3</uniqueReference>
    </itemReference>
  </psaList>
</Ticket_CreateTSTFromPricing>
```

What XML structure does the library generate when you do `new Pricing([ 'tstNumber' => [1,2], ])`?

**Comment by mhrahul** [comment]
@DerMika so for 2 adults, 1 child and one infant what might be the structure? I have ued
`new Pricing([ 'tstNumber' => [1,2]]); new Pricing([ 'tstNumber' => [3]]); new Pricing([ 'tstNumber' => [4]]);`

but it gives me an error in pricing. What will be the actual format in PHP?

**Comment by DerMika** [comment]
I just added a new testcase which should build the correct message, See the commit above. Can you try that?

**Comment by mhrahul** [comment]
using
`$createTstResponse = $this->client->ticketCreateTSTFromPricing(
                new TicketCreateTstFromPricingOptions([
            'pricings' => [
                new Pricing([
                    'tstNumber' => 1
                        ])
            ]
                ])
        );`

if I use "$this->client->CreateTSTFromPricing" it shows error!

**Comment by DerMika** [comment]
You'll have to give me a bit more context. What error? Wat are you trying to achieve? What is the session context before the last call you made?

**Comment by mhrahul** [comment]
Actually, I am stuck on pricing problem. When I try to generate tickets for multiple passengers, it only sent the ticket price for one person. Review from Amadeus below.

3.       You are passing 2 ADT but we are getting only 1 ADT. Kindly check and fix.
![image](https://user-images.githubusercontent.com/3182632/42440306-2ee2e082-8387-11e8-8076-5a64c97f8050.png)
7.       TSTs have been not created
![image](https://user-images.githubusercontent.com/3182632/42440358-5c8275b6-8387-11e8-9b3f-2517b44c90d8.png)

**Comment by DerMika** [comment]
Closing issue because it's an old one without feedback. You can re-open if needed
