### ISSUE TITLE
NEED TST

### ISSUE THREAD

**Issue by XYNOMEX** [amabnl/amadeus-ws-client#199]
Hey,
Since I tried to book online with Amadeus this is the first time I'm getting this error  "NEED TST", I'm already calling "farePricePnrWithBookingClass", "ticketCreateTSTFromPricing" and "ticketDisplayTST" before issuing the ticket.
I'm getting this error when calling "docIssuanceIssueTicket", what could be the issue? knowing that I was able to complete many bookings before but only on this specific flight, I'm getting this error. @DerMika @bimusiek

**Comment by XYNOMEX** [comment]
I got a reply from Amadeu saying that i am missing TST for 1 Pax since i have 2 paxes (1 Adult and 1 Child).
I am using the below function to Create TST:

$createTstResponse = $client->ticketCreateTSTFromPricing(
    new TicketCreateTstFromPricingOptions([
        'pricings' => [
            new Pricing([
                'tstNumber' => 1
            ])
        ]
    ])
);
Should i set 'tstNumber' to 2 instead of one since i have 2 paxes? @DerMika  @bimusiek @zervel

**Comment by DerMika** [comment]
When you have multiple pax types, you have to make sure to price all passengers. You may get multiple pricings in this case, and you'll have to make sure you get a test for all passengers.

This is a flow you'll have to implement yourself.

**Comment by XYNOMEX** [comment]
Hey,
Is there any example showing how to price multiple passengers?

**Comment by mhrahul** [comment]
Please give example. I also stuck on this problem. @XYNOMEX did you solve the issue?

**Comment by DerMika** [comment]
This is something to ask Amadeus Support, really. 

There are many possibilities. 

For example, when performing a pricing for a PNR with multiple pax types, you can get a list of multiple pricings per pax type, and you'll have to pick a pricing per pax type. 

Or you can specifically request a separate pricing entry per pax type in your PNR, and process each pax type separately. 

I am not an expert on the best way to approach this issue, and it also depends on your application. You should get in touch with Amadeus Support and ask them to provide you with a sample flow to handle multiple pax type pricing.

**Comment by XYNOMEX** [comment]
@mhrahul No, not yet, I will be working on this case next week, if you succeed to solve it please let us know.
thanks,

**Comment by DerMika** [comment]
Closing due to lack of feedback.
