### ISSUE TITLE
PnrCreatePnrOptions and It should be FopCreateFopOptions

### ISSUE THREAD

**Issue by mostafaahamidmanon** [amabnl/amadeus-ws-client#205]
Hello and Greetings @DerMika 
Please correct the documentation as it has PnrCreatePnrOptions in the request for the FOP_CreateFormOfPayment and it should be FopCreateFopOptions.
Thank you so much for your help

**Comment by DerMika** [comment]
Where exactly?

**Comment by mostafaahamidmanon** [comment]
Here:
https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/pnr-create-modify.rst#form-of-payment-fp

**Comment by DerMika** [comment]
The documentation you are linking to is not for `FOP_CreateFormOfPayment`. It is for creating an FP element through `PNR_AddMultiElements`.

The docs for `FOP_CreateFormOfPayment` are here: https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/fop-createfop.rst

**Comment by mostafaahamidmanon** [comment]
Thanks
