### ISSUE TITLE
Could not connect to host

### ISSUE THREAD

**Issue by XYNOMEX** [amabnl/amadeus-ws-client#206]
@DerMika Hey Is there any link I can ping to check if I can go through? I think this is a network issue but i need to be sure before requesting any changes

Thanks,

**Comment by DerMika** [comment]
You should ask Amadeus, but the only link you hat to be able to reach is the SOAP Endpoint which you can find in your WSDL.

Also, make sure you have an up-to-date PHP and OpenSSL version. Sometimes the problem isn't the network connection, but rather the SSL handshake.

**Comment by XYNOMEX** [comment]
Thank I will try to update OpenSSL since I have the same PHP version and it's working for me.

**Comment by DerMika** [comment]
You can also ask Amadeus which handshake is accepted by the servers.

**Comment by DerMika** [comment]
Closing this issue due to lack of feedback. You can re-open if needed.
