### ISSUE TITLE
How to remove the range of date with its qualifier from the Fare_MasterPricerTravelBoardSearch request

### ISSUE THREAD

**Issue by mostafaahamidmanon** [amabnl/amadeus-ws-client#207]
Please, @DerMika 
I want the remove the following portion from the XML which is Fare_MasterPricerTravelBoardSearch range of date from the request

```
          <ns1:rangeOfDate>
            <ns1:rangeQualifier>P</ns1:rangeQualifier>
            <ns1:dayInterval>1</ns1:dayInterval>
          </ns1:rangeOfDate>

```

I think it is required by the certificate to remove it from the request.

**Comment by sahuhardic** [comment]
hey brother where i get office id

**Comment by DerMika** [comment]
This node should be removed from the request if you do not set the following parameters of the `Amadeus\Client\RequestOptions\Fare\MPDate` request options object: 

* `range` 
* `rangeMode`

(See the source of `Amadeus\Client\Struct\Fare\MasterPricer\TimeDetails`)

**Comment by mostafaahamidmanon** [comment]
Thanks @DerMika 
It is working now.
