### ISSUE TITLE
Amadeus Issue

### ISSUE THREAD

**Issue by sahuhardic** [amabnl/amadeus-ws-client#209]
hyy i am getting error soap message header incorrect.
and what is office id and form where i get this.
and where I request for new  WSDL files . Thanks in advance

**Comment by DerMika** [comment]
It's mentioned in the README.MD of this project: 

> This client library provides access to the Amadeus GDS SOAP Web Service interface.
> 
> To use this client, you must first obtain your personal access to the Web Service interface through an Amadeus Sales channel of your choice.
> 
> The Amadeus documentation portal can be found at https://webservices.amadeus.com/

You have to contact Amadeus and start a project with them. This will involve signing an agreement with Amadeus.
