### ISSUE TITLE
fareCheckRules

### ISSUE THREAD

**Issue by fayax** [amabnl/amadeus-ws-client#21]
I have a doubt on how to get fare components and to check fare rules for FC.
Would be great if you can give an example.

**Comment by DerMika** [comment]
Hi, If you are really talking about Fare Components, then you're talking about the cryptic entry `FQQ`, correct?

I do not have the structured equivalent of `FQQ `implemented in the library yet (this is the message `Fare_DisplayTicketImage`).

These (`FQQ `and `FQN `- `Fare_CheckRules`) can all be called in the context of a previous pricing entry. So to get any information from these messages, the message before calling this message should be for example a `Fare_PricePnrWithBookingClass` message. A successful pricing result will get a number assigned to it, so you should call the follow-up messages like Fare_CheckRules by providing that number: https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples.rst#fare-checkrules. 

Will you have a need for the `Fare_DisplayTicketImage`? If so, please open a separate issue requesting for its implementation!

**Comment by fayax** [comment]
I'm not sure if this is the cryptic entry. As per Aamdeus provided recommendation workflow to check fare rule, the steps are:
1. Apply Fare_PricePNRwithBookingClass 
2. Apply Fare_CheckRules
3. Apply Fare_CheckRules for each Fare Components (with FC reference from step 2).

I'm kind of confused with step 2 and 3.

**Comment by DerMika** [comment]
Ehm. Maybe they mean if your Fare_PricePNRWithBookingClass returns multiple pricings? This can happen when you have adults and children in the same PNR, they will likely get a different fare.

**Comment by DerMika** [comment]
One thing I can think of is that they tell you to first request which categories of Fare Rules are available for a given pricing, and then request the rules for those specific categories:

First, you do a Fare_CheckRules and request a list of rule categories by doing this: 

```
$client->fareCheckRules(
    new FareCheckRulesOptions([
            'recommendations' => [1],
            'categoryList' => true
        ])
);
```

The response will be something like this:

```
<Fare_CheckRulesReply xmlns="http://xml.amadeus.com/FARQNR_07_1_1A">
	<transactionType>
		<messageFunctionDetails>
			<messageFunction>712</messageFunction>
		</messageFunctionDetails>
	</transactionType>
	<flightDetails>
		<nbOfSegments/>
		<qualificationFareDetails>
			<fareDetails>
				<qualifier>ADT</qualifier>
				<fareCategory>NIT</fareCategory>
			</fareDetails>
			<additionalFareDetails>
				<fareClass>MNR2MBE</fareClass>
			</additionalFareDetails>
		</qualificationFareDetails>
		<flightErrorCode>
			<freeTextQualification>
				<textSubjectQualifier>3</textSubjectQualifier>
				<informationType>PTC</informationType>
			</freeTextQualification>
			<freeText>ADULT</freeText>
		</flightErrorCode>
		<flightErrorCode>
			<freeTextQualification>
				<textSubjectQualifier>3</textSubjectQualifier>
				<informationType>FTC</informationType>
			</freeTextQualification>
			<freeText>NEGO IIT</freeText>
		</flightErrorCode>
		<productInfo>
			<productDetails>
				<bookingClassDetails>
					<designator>M</designator>
				</bookingClassDetails>
			</productDetails>
		</productInfo>
		<travellerGrp>
			<travellerIdentRef>
				<referenceDetails>
					<type>RU</type>
					<value>00M0</value>
				</referenceDetails>
			</travellerIdentRef>
			<fareRulesDetails>
				<ruleSectionId>MX</ruleSectionId>
				<ruleSectionId>SE</ruleSectionId>
				<ruleSectionId>SR</ruleSectionId>
				<ruleSectionId>AP</ruleSectionId>
				<ruleSectionId>FL</ruleSectionId>
				<ruleSectionId>CD</ruleSectionId>
				<ruleSectionId>SO</ruleSectionId>
				<ruleSectionId>SU</ruleSectionId>
			</fareRulesDetails>
		</travellerGrp>
	</flightDetails>
</Fare_CheckRulesReply>
```

And then you can call Fare_CheckRules again and request the rules for the `travellerGrp/fareRulesDetails/ruleSectionId` nodes that were returned earlier: 

```
$client->fareCheckRules(
    new FareCheckRulesOptions([
            'recommendations' => [1],
            'categories' => ['MX', 'SE', 'SR', 'AP', 'FL', 'CD', 'SO', 'SU']
        ])
);
```

Not sure if that is what they mean. If not: do you have an Amadeus support contact which is assigned to assist with your project?

**Comment by fayax** [comment]
Yes, that's what they are referring to.
It doesn't return the categories (MX, SE, AP, etc..) even if I set `'categoryList' => true`.
If I put the categories one at a time it returns the rule for that category. But it doesn't return the rule if I put all the categories in an array as mentioned in your post.

**Comment by DerMika** [comment]
I will check if there's a bug. Hold on.

**Comment by DerMika** [comment]
Hi @fayax , I can't reproduce this issue. I'm generating the correct message here and I'm getting the correct response.

Maybe it's related to the specific fare you're trying to get info for, maybe it's a setting on the Amadeus Office you're working on. I suggest you contact your Amadeus support contact to help you figure out what's wrong.

**Comment by fayax** [comment]
@DerMika Thanks! How can I display the SOAP request?

**Comment by DerMika** [comment]
If you provide a logger on instantiation it will log each request & response to the logfile.

**Comment by fayax** [comment]
Thanks

**Comment by fayax** [comment]
I have been discussing this with Amadeus support and they said since I'm getting only FC reference after generic fareCheckRules request, I should send a follow up query with that FC reference. Here is the sample follow up query from them:

`<Fare_CheckRules>
  <msgType>
    <messageFunctionDetails>
      <messageFunction>712</messageFunction>
    </messageFunctionDetails>
  </msgType>
  <itemNumber>
    <itemNumberDetails>
      <number>1</number>
    </itemNumberDetails>
    <itemNumberDetails>
      <number>1</number>
      <type>FC</type>
    </itemNumberDetails>
  </itemNumber>
</Fare_CheckRules>`

How do I send this kind of query?

**Comment by DerMika** [comment]
This is not yet possible with the current library. I'll push a fix tonight or tomorrow.

**Comment by DerMika** [comment]
Ok, i've now added support for requesting rules for specific fare components of a pricing request. 

For an example of how to do this, check the second example here: https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples.rst#fare-checkrules

Please let me know if that fixes your problem!

**Comment by DerMika** [comment]
Hey @fayax were you able to check if this fix solves your problem?

**Comment by fayax** [comment]
Hi, Sorry for the late response. That fix solves the problems. It is working fine now.
Thank you

**Comment by DerMika** [comment]
Good to hear, thanks
