### ISSUE TITLE
Price Fare with more than one flight in a segment

### ISSUE THREAD

**Issue by vTrip** [amabnl/amadeus-ws-client#210]
The following example taken from the docs shows two segments ( BRU -> LIS, LIS -> BRU ). Looks like a return trip.

```php
fareInformativePricingWithoutPnr(
        new FareInformativePricingWithoutPnrOptions([
            'passengers' => [
                new Passenger([
                    'tattoos' => [1, 2],
                    'type' => Passenger::TYPE_ADULT
                ])
            ],
            'segments' => [
                new Segment([
                    'departureDate' => \DateTime::createFromFormat('Y-m-d H:i:s', '2016-11-21 09:15:00'),
                    'from' => 'BRU',
                    'to' => 'LIS',
                    'marketingCompany' => 'TP',
                    'flightNumber' => '4652',
                    'bookingClass' => 'Y',
                    'segmentTattoo' => 1,
                    'groupNumber' => 1
                ]),
                new Segment([
                    'departureDate' => \DateTime::createFromFormat('Y-m-d H:i:s', '2016-11-28 14:20:00'),
                    'from' => 'LIS',
                    'to' => 'BRU',
                    'marketingCompany' => 'TP',
                    'flightNumber' => '3581',
                    'bookingClass' => 'C',
                    'segmentTattoo' => 2,
                    'groupNumber' => 2
               ])
      ]
 ])
```
I notice it gives one flight number for each segment, assuming then that the segment is a direct flight.

What happens when a segment has multiple flights (or legs). How is the flight number chosen?

For example a trip consisting of flying [ SYD -> LAX, LAX -> SYD ]. But each segment is actually a 1 stop flight (i.e. a stop over in Incheon) therefore the breakdown is [ SYD -> ICN -> LAX, LAX -> ICN -> SYD

**Comment by DerMika** [comment]
Flight number is chosen when booking a recommendation from MasterPricer or availability. So it really just depends on what information the airline provides. But usually, when the same airplane is being used, the flight number will be the same for multiple flight segments.

By the way, these are questions you can also ask Amadeus Support.
