### ISSUE TITLE
Problem during authentication

### ISSUE THREAD

**Issue by gabrythe23** [amabnl/amadeus-ws-client#211]
thanks for the amazing module, we develop an Amadeus based ticketing system and your work is amazing for us! 

we have a bit of problem during authentication, 

soap:Client 12|Presentation|soap message header incorrectSI:

this is our client params
 ```php
$params = new Params([
        'authParams' => [
            'officeId' => 'OUR_OFFICE_ID', //The Amadeus Office Id you want to sign in to - must be open on your WSAP.
            'userId' => 'OUR_USERID', //Also known as 'Originator' for Soap Header 1 & 2 WSDL's
            'passwordData' => base64_encode('PLAIN_TEXT_PWD') // **base 64 encoded** password
        ],
        'sessionHandlerParams' => [
            'soapHeaderVersion' => Client::HEADER_V4, //This is the default value, can be omitted.
            'wsdl' => '../wsdl/PRD/XXXXXX_PRD_20180612_145310.wsdl', //Points to the location of the WSDL file for your WSAP. Make sure the associated XSD's are also available.
            'stateful' => false, //Enable stateful messages by default - can be changed at will to switch between stateless & stateful.
            'logger' => new Psr\Log\NullLogger()
        ],
        'requestCreatorParams' => [
            'receivedFrom' => 'APP' // The "Received From" string that will be visible in PNR History
        ]
    ])
```

we also have profile wsdl, could I use that in the module?

**Comment by DerMika** [comment]
Can you try by providing a full path to the WSDL (with the `realpath()` function for example)

The library supports an array of WSDL files too, and will send each message through its appropriate WSDL depending on in which WSDL file a specific message was  defined. But none of the `Profile_*` messages have been implemented so far. 

You are welcome to make a contribution ;)

**Comment by gabrythe23** [comment]
I've fixed my params object but still same error!

```php 
    $params = new Params([
        'authParams' => [
            'officeId' => 'OUR_OFFICE_ID', //The Amadeus Office Id you want to sign in to - must be open on your WSAP.
            'userId' => 'OUR_USERID', //Also known as 'Originator' for Soap Header 1 & 2 WSDL's
            'passwordData' => base64_encode('PLAIN_TEXT_PWD') // **base 64 encoded** password
        ],
        'sessionHandlerParams' => [
            'soapHeaderVersion' => Client::HEADER_V4, //This is the default value, can be omitted.
            'wsdl' => [
                'FULL_PATH_TO_WSDL_FOLDER/PRD/1ASIWLER1LR_PRD_20180612_145310.wsdl',
                'FULL_PATH_TO_WSDL_FOLDER/1ASIWLER1LR_PRD_DistributionProfileAccess_12.2_3.0.wsdl',
                'FULL_PATH_TO_WSDL_FOLDER/1ASIWLER1LR_PRD_ServiceBookAndPrice_1.0_3.0.wsdl',
             ], //Points to the location of the WSDL file for your WSAP. Make sure the associated XSD's are also available.
            'stateful' => false, //Enable stateful messages by default - can be changed at will to switch between stateless & stateful.
            'logger' => new Psr\Log\NullLogger()
        ],
        'requestCreatorParams' => [
            'receivedFrom' => 'flyleo' // The "Received From" string that will be visible in PNR History
        ]
    ])
```


I really don't know what's wrong!

thanks for your help!

**Comment by DerMika** [comment]
You'll have to ask Amadeus to help you trace the error. 

Are you sure the WSAP you were provided is using Soap Header version 4 (which is how you've now configured it)? Amadeus should be able to tell you that. 

Also, maybe these are just dummy values you're using in your example, but I would really recommend you start development with a PDT (test platform) WSDL, and not a PRD (production) WSDL.

**Comment by gabrythe23** [comment]
I'm pretty sure about soap headers v4, we use that since last year (but under nodejs).

if I call 
```php 
$client->getLastRequestHeaders()
```
is always empty, same error as before.  

soap:Client 12|Presentation|soap message header incorrectSI: muxDZ2


I really don't know where is the error 😢 

thanks for your help!

ps yes, are dummy values 👍

**Comment by gabrythe23** [comment]
still there sir?

after resolving this problem i would like to contribute with my team for the Profile_* messages.

**Comment by gabrythe23** [comment]
very strange. it was a corrupted wsdl, once deleted and re-downloaded from amadeus all works great. sorry for the problem, see you soon for the profile messages!

good bye

**Comment by DerMika** [comment]
Ok, good to hear. 

Sorry I couldn't respond quicker.
