### ISSUE TITLE
new message

### ISSUE THREAD

**Issue by LeoTravel** [amabnl/amadeus-ws-client#213]
hi, 

we would like to start an implementation for Profile_* and Fare_PriceUpsellPNR can you link us the implementation guide? sorry but we've search that but we coul'd figured out where's yet!

have a nice day

**Comment by DerMika** [comment]
Do you mean the implementation guide on the Amadeus Extranet?

**Comment by DerMika** [comment]
Did you find what you needed?

**Comment by LeoTravel** [comment]
sorry for delays, completly forgot, anyway yes, i've find your implementation guid
