### ISSUE TITLE
fare_InformativeBestPricingWithouthPNR add optionDetail to pricingOptionKey

### ISSUE THREAD

**Issue by LeoTravel** [amabnl/amadeus-ws-client#216]
Hi I need to get tariff with baggage Allowance using Fare_InformativeBestPricingWithoutPNR like following:
```
pricingOptionKey : { pricingOptionKey : 'SBF' },
     optionDetail : {
         criteriaDetails : {
               attributeType : 1,
        },
   },
}
```
How can I do?
Thanks

**Comment by DerMika** [comment]
The second [sample in the docs here](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples.rst#fare-informativepricingwithoutpnr) shows you can use a PricingOptions object as request parameter which has exactly the same structure as the pricing message (with all the same options of the pricing message).

**Comment by LeoTravel** [comment]
yes, we've added SBF as string params and works but, we can't add the optionDetail/criteriaDetails/attributeType 1 (only with SBF), can we do that or not? have we to develop that? 


our xml is
```xml
<ns1:pricingOptionGroup>
	<ns1:pricingOptionKey>
		<ns1:pricingOptionKey>RLA</ns1:pricingOptionKey>
	</ns1:pricingOptionKey>
</ns1:pricingOptionGroup>
<ns1:pricingOptionGroup>
	<ns1:pricingOptionKey>
		<ns1:pricingOptionKey>NS</ns1:pricingOptionKey>
	</ns1:pricingOptionKey>
</ns1:pricingOptionGroup>
<ns1:pricingOptionGroup>
	<ns1:pricingOptionKey>
		<ns1:pricingOptionKey>RU</ns1:pricingOptionKey>
	</ns1:pricingOptionKey>
</ns1:pricingOptionGroup>
<ns1:pricingOptionGroup>
	<ns1:pricingOptionKey>
		<ns1:pricingOptionKey>RP</ns1:pricingOptionKey>
	</ns1:pricingOptionKey>
</ns1:pricingOptionGroup>
<ns1:pricingOptionGroup>
	<ns1:pricingOptionKey>
		<ns1:pricingOptionKey>SBF</ns1:pricingOptionKey>
</ns1:pricingOptionGroup>
```

instead of 
```xml
<ns1:pricingOptionGroup>
	<ns1:pricingOptionKey>
		<ns1:pricingOptionKey>RLA</ns1:pricingOptionKey>
	</ns1:pricingOptionKey>
</ns1:pricingOptionGroup>
<ns1:pricingOptionGroup>
	<ns1:pricingOptionKey>
		<ns1:pricingOptionKey>NS</ns1:pricingOptionKey>
	</ns1:pricingOptionKey>
</ns1:pricingOptionGroup>
<ns1:pricingOptionGroup>
	<ns1:pricingOptionKey>
		<ns1:pricingOptionKey>RU</ns1:pricingOptionKey>
	</ns1:pricingOptionKey>
</ns1:pricingOptionGroup>
<ns1:pricingOptionGroup>
	<ns1:pricingOptionKey>
		<ns1:pricingOptionKey>RP</ns1:pricingOptionKey>
	</ns1:pricingOptionKey>
</ns1:pricingOptionGroup>
<ns1:pricingOptionGroup>
	<ns1:pricingOptionKey>
		<ns1:pricingOptionKey>SBF</ns1:pricingOptionKey>
		<optionDetail>
			<criteriaDetails>
				<attributeType>1</attributeType>
			</criteriaDetails>
		</optionDetail>
	</ns1:pricingOptionKey>
</ns1:pricingOptionGroup>
```

**Comment by DerMika** [comment]
No, that's not supported yet I'm afraid. 

And in fact, I'm wondering how we can best add this functionality in a useful way without breaking BC.

Perhaps the easiest way would be to add a new property in the Request Options file `FarePricePnrWithBookingClassOptions` like `$overrideOptionsWithCriteria`, which would be an array of objects where you can pass an override option string (SBF) and then some extra parameters such as the attribute type you want to pass.

**Comment by DerMika** [comment]
If you want to implement this in a pull request, go ahead. I can maybe do this tonight, but I can't promise it.

**Comment by LeoTravel** [comment]
if you can see that tonight would be amazing, otherwise no problem we'll try this week too.

**Comment by LeoTravel** [comment]
Any update about?

**Comment by LeoTravel** [comment]
I've implemented the params, but i'm not the best in php but i would like to contribute 

https://github.com/LeoTravel/amadeus-ws-client/commit/47c1986d4bbc2d4e964a7d3450db4f65cf2b483b

**Comment by DerMika** [comment]
PR is merged, closing this issue.
