### ISSUE TITLE
Air_RetrieveSeatMap option to provide record locator doesn't work

### ISSUE THREAD

**Issue by DerMika** [amabnl/amadeus-ws-client#219]
Apparently when providing a PNR Record Locator, you also have to provide a companyId, otherwise you'll get an error `18|Application|The backend didn't understand the incoming query`.

**Comment by zhaonan0218** [comment]
Based on the reply from Amadeus tech support, there are 2 modes in seatmap retrieve request:
- non-retrieval PNR mode
- PNR mode

and **companyId** (carrier) was in the **itineraryInfo** block along with the **controlNumber** (recordLocator) in the **PNR_reply** response

**Comment by DerMika** [comment]
Fix is merged to the master branch. 

You can check it out by switching to `dev-master` in composer.json. 

This fix will be released with the 1.8.0 release.
