### ISSUE TITLE
Fare_MasterPricerTravelBoardSearchReply: Map flight segment with Price

### ISSUE THREAD

**Issue by ratheepan** [amabnl/amadeus-ws-client#22]
Hello Sir,\

i have created a round trip search( from CMB to MAA and MAA to CMB).

`i` am confusing with  relationship between pricing and flight segments.
    
                                            [segmentFlightRef] => stdClass Object
                                (
                                    [referencingDetail] => Array
                                        (
                                            [0] => stdClass Object
                                                (
                                                    [refQualifier] => S
                                                    [refNumber] => 1
                                                )[1] => stdClass Object
                                                (
                                                    [refQualifier] => S
                                                    [refNumber] => 1
                                                )

                                            [2] => stdClass Object
                                                (
                                                    [refQualifier] => B
                                                    [refNumber] => 1
                                                )

                                        )

                                )`
Above scenario relate with flight segments?
And  
Could you kind explain the logic and relationship  [between]([url]([url](url))) pricing  and proposed flight segments.?

Here i attached Full sample response
https://docs.google.com/document/d/1IAFxEA-TLZ_SQiD7HQQJEeKPfnaPuO58AGMlkdaS1gI/edit

Thanks in Advance

**Comment by DerMika** [comment]
Hi, 

First of all, I cannot provide support for interpreting the responses received from the Amadeus Web Services. If you have started a project with the Amadeus Web Services, should have a dedicated support contact to ask these kinds of implementation questions. 

However, just this once, I'll quickly explain the general structure of the `Fare_MasterPricerTravelBoardSearch` message here: 

The various recommendations returned by this message can be found in `/Fare_MasterPricerTravelBoardSearchReply/recommendation` nodes. These contain references to the flight segments of which the recommendations consist. You can match the flight segment references by looking up the corresponding flights from `/Fare_MasterPricerTravelBoardSearchReply/recommendation/segmentFlightRef/referencingDetail/refNumber` with the matching flight segment under `/Fare_MasterPricerTravelBoardSearchReply/flightIndex/groupOfFlights/propFlightGrDetail/flightProposal/ref`: The first `flightProposal/ref` node's value matches with the `segmentFlightRef/referencingDetail/refNumber` node from the recommendation.

As for the pricing of a recommendation, those can simply be found in the `paxFareProduct` node under the recommendation.

I hope this helps. If it doesn't, I advise you to contact your Amadeus support contact to get some more in-depth information as I said, I cannot provide support for the content of the responses.

**Comment by munna316** [comment]
Could you kind explain the logic and relationship between pricing and proposed flight segments.?

![image](https://user-images.githubusercontent.com/25523794/30578996-51770cd4-9d34-11e7-9ef6-87b49f1f1a02.png)
