### ISSUE TITLE
Show headers

### ISSUE THREAD

**Issue by kmotillo** [amabnl/amadeus-ws-client#224]
I want to show the headers of the requests, how can I get the header of every request??

I want to get something like this:

<soap:Header xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <add:MessageID xmlns:add="http://www.w3.org/2005/08/addressing">5c8067c1-e305-4ef6-738-9699b725df92</add:MessageID>
  <add:Action xmlns:add="http://www.w3.org/2005/08/addressing">http://webservices.amadeus.com/FMPTBQ_14_3_1A</add:Action>
  <add:To xmlns:add="http://www.w3.org/2005/08/addressing">https://nodeD2.test.webservices.amadeus.com/1ASIWALMOOV</add:To>
  <link:TransactionFlowLink xmlns:link="http://wsdl.amadeus.com/2010/06/ws/Link_v1">

**Comment by DerMika** [comment]
https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#getting-individual-requests-and-responses

```php
$lastRequestHeaders = $client->getLastRequestHeaders();

$lastResponseHeaders = $client->getLastResponseHeaders();
```

This only works if the request was successful. If not, you'll have to set up logging to get the headers: https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#logging-request-and-response

**Comment by kmotillo** [comment]
that's geat, and how about the request query and the session request?

**Comment by kmotillo** [comment]
Using this $lastRequest = $client->getLastRequest(); I get last Request, and thats Great, 
but is there a way to get session request? in the same format ?

**Comment by DerMika** [comment]
Assuming your issue is solved now. You can re-open if not.
