### ISSUE TITLE
Ticket Void

### ISSUE THREAD

**Issue by muzaffarkamil86** [amabnl/amadeus-ws-client#225]
Hi mika i am not able  find anything in docs how to void a ticket using this library.
Please advise how can we do that

**Comment by DerMika** [comment]
You are probably looking for `Ticket_CancelDocument` or the Refund methods [found here](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples.rst#docrefund) (depending on whether you need to do a refund or not).

**Comment by muzaffarkamil86** [comment]
thanks
