### ISSUE TITLE
New Message ServiceBookPriceService 

### ISSUE THREAD

**Issue by arvind-pandey** [amabnl/amadeus-ws-client#228]
In order to book Ancillary Service like Baggage, Meal etc we need  ServiceBookPriceService message. Same is missing in this library. Amadeus Documentation suggest this functionality build  according Open Travel Alliance (OTA) XML Standard. For this we need to use another wsdl file. So it  is possible to implement this message in same way? Changing wsdl file point at the time of calling this message will work? Kindly suggest.

**Comment by DerMika** [comment]
Yes, you can provide an array of WSDL files on client instantiation, the library will use the correct WSDL depending on which message is defined in which WSDL.

[Mentioned in the docs here.](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#wsap-s-with-multiple-wsdl-s)

**Comment by arvind-pandey** [comment]
Hi,
Is the implementation of  Service_BookPriceService Message is same?

**Comment by DerMika** [comment]
I'm not sure what you are asking?

**Comment by humanyu** [comment]
I cannot see raw soap xml request or response. Please guide me. I need to send request and response to our amadeus product manager.

Another question is I am unable to search multicity in  fareMasterPriceTravelTbSearch. May I ask is there any other WSDL for multiCity


Thank you in advance

**Comment by DerMika** [comment]
Can you please stop adding questions to random tickets, and ask your question in one ticket? I am not inclined to respond faster if you ask the same question in 3 separate issues.

**Comment by bimusiek** [comment]
When https://github.com/amabnl/amadeus-ws-client/pull/324 is merged, you will have access to the `Service_BookPriceService`.
