### ISSUE TITLE
Work with date/time

### ISSUE THREAD

**Issue by valerion1** [amabnl/amadeus-ws-client#229]
Hi guys!
When communicating with Amadeus, I learned that the date in all requests to their api should be of the format _dMy_ (ex. _15AUG92_) and time must be 4 digits. This is not error, but may work incorrectly.

This library supported in some request only _dMy_, [example](https://github.com/amabnl/amadeus-ws-client/blob/master/src/Amadeus/Client/Struct/Pnr/AddMultiElements/TravellerInfo.php#L113). 

Example in my request _PNR_AddMultiElements_ with passengers data:
```xml
<ns1:date>15081990</ns1:date>
```
but must be:
```xml
<ns1:date>15AUG90</ns1:date>
```

Can you write which other request support only such a date format? And is there a time format not 4 digits? Someone familiar with this problem?

**Comment by nepster-web** [comment]
Yes, I confirm. I have the same problem.

**Comment by troitskyA** [comment]
Hello! I have the same issue, our implementation guy says on Amadeus side that this is a blocking bug.

**Comment by DerMika** [comment]
I've just released version 1.7.1 which fixes this bug. Thanks for reporting, thanks for fixing it @therealartz , and sorry for the delay.

**Comment by nepster-web** [comment]
Thank you very much.

**Comment by a2zdk** [comment]
Can you contact me on following contact detail


With Kind Regards / Hilsen

*Aftab Muhammad*    A2Z Travel Technology IVS

<https://mail.google.com/>
Mobile/ WhatsApps/SMS: +45 51461324 <+45+51461324>
Email: am@a2ztraveltechnology.com <am@a2ztravelsolutions.dk>
Skype: am.a2z <http://am.a2z/>
Website: www.a2ztraveltechnology.com <http://a2ztraveltechnology.com/>
Address:Valbygårdsvej 27, 2500 Valby Denmark
<https://goo.gl/maps/csasnU98HeB2>
         Danske Bank Account no.:3409-11789927
         IBAN: DK3930000011789927
         BIC (SWIFT): DABADKKK
         CVR/ORG No: 37141542

If you are not the intended recipient of this e-mail message, please notify
the sender and delete all copies immediately. The sender believes this
message and any attachments were sent free of any virus, worm, Trojan
horse, and other forms of malicious code. This message and its attachments
could have been infected during transmission. The recipient opens any
attachments at the recipient's own risk, and in so doing, the recipient
accepts full responsibility for such actions and agrees to take protective
and remedial action relating to any malicious code. A2Z Travel Technology
IVS. is not liable for any loss or damage arising from this message or its
attachments.
