### ISSUE TITLE
soap message header incorrect

### ISSUE THREAD

**Issue by skills-up** [amabnl/amadeus-ws-client#233]
Hi, I've recently started using this library, and on the [first message](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples.rst#fare-masterpricertravelboardsearch) itself I keep getting the below error:
`<soap:Fault><faultcode>soap:Client</faultcode><faultstring> 12|Presentation|soap message header incorrect</faultstring><faultactor>SI:muxDZ2</faultactor></soap:Fault>`

I talked to amadeus support in this regard, and according to them the SOAP header format is incorrect. They have also suggested the header format to use, which is a bit different from the current header format being generated in the XML.

**Generated Format**
```
<SOAP-ENV:Header><ns2:MessageID>562414B5-27AA-57B0-507A-xxxxxxxxxxxx</ns2:MessageID><ns2:Action>http://webservices.amadeus.com/1ASIWITP1AI/FMPTBQ_14_3_1A</ns2:Action><ns2:To>https://nodeD1.test.webservices.amadeus.com</ns2:To><oas:Security xmlns:oas="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
	<oas:UsernameToken xmlns:oas1="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" oas1:Id="UsernameToken-1">
		<oas:Username>xxxxxxxx</oas:Username>
		<oas:Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">xxxxxxxxxxxxxxxxxxxxxx==</oas:Nonce>
		<oas:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">xxxxxxxxxxxxxxxxxxxxxxxxxxxx=</oas:Password>
		<oas1:Created>2018-09-20T11:06:06:135Z</oas1:Created>
	</oas:UsernameToken>
</oas:Security><ns4:AMA_SecurityHostedUser><UserID><RequestorType>U</RequestorType><PseudoCityCode>xxxxxxxx</PseudoCityCode><POS_Type>1</POS_Type><AgentDutyCode>SU</AgentDutyCode></UserID></ns4:AMA_SecurityHostedUser></SOAP-ENV:Header>
```

**Suggested Format**
```
<soapenv:Header>
                <add:MessageID xmlns:add="http://www.w3.org/2005/08/addressing">6c1c75b6-f03a-4f43-7ed4-xxxxxxxxxxxx</add:MessageID>
                <add:Action xmlns:add="http://www.w3.org/2005/08/addressing">http://webservices.amadeus.com/FMPTBQ_14_3_1A</add:Action>
                <add:To xmlns:add="http://www.w3.org/2005/08/addressing">https://nodeD1.test.webservices.amadeus.com/xxxxxxxxxxx</add:To>
                <link:TransactionFlowLink xmlns:link="http://wsdl.amadeus.com/2010/06/ws/Link_v1"/>
                <oas:Security xmlns:oas="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
                                <oas:UsernameToken oas1:Id="UsernameToken-1" xmlns:oas1="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
                                                <oas:Username>xxxxxxxx</oas:Username>
                                                <oas:Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">xxxxxxxxxxxxxxxxxxxxxx==</oas:Nonce>
                                                <oas:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">xxxxxxxxxxxxxxxxxxxxxxxxxxx=</oas:Password>
                                                <oas1:Created>2018-09-20T10:57:33:741Z</oas1:Created>
                                </oas:UsernameToken>
                </oas:Security>
                <AMA_SecurityHostedUser xmlns="http://xml.amadeus.com/2010/06/Security_v1">
                                <UserID AgentDutyCode="SU" POS_Type="1" PseudoCityCode="xxxxxxxxx" RequestorType="U"/>
                </AMA_SecurityHostedUser>
</soapenv:Header>
```

The difference basically lies in the format for children of AMA_SecurityHostedUser node.

Now, I've two questions here:
1. Is the header format defined by WSDL, or it is being set by this library?
2. If it is being set by the library, where can I modify it?

**Comment by therealartz** [comment]
Library generates XML accordingly to schemas.

You downloaded WSDL schemes for soap header v4 from amadeus extranet?

**Comment by skills-up** [comment]
Yes. I don't know what the support team was thinking. They claimed that my code was generating incorrect errors, and denied any association with (or knowledge of) this repository.

However, later on they provided a different wsdl, and now the headers are getting generated correctly.

PS: Closing this issue, as it was clearly wsdl problem.

**Comment by yspef** [comment]
¿ where can I download the SOAP4 wsdl file from ?
thanks.

**Comment by Wizard2436829** [comment]
@skills-up 
I tried using the same header format and made a request using postman to one of the test URL's but the error still persists. Also, I think a Session section that is missing from the above-suggested format which comprises of the Security Token which is crucial for authentication of the request.

Can you please send a link where we can download a WSDL that has the updated SOAP 4.0 header format so as to avoid this error.

**Comment by skills-up** [comment]
The WSDL is created by Amadeus Support team with messages enabled on your account. So you'll have to talk to the support team for the same. I'd recommend contacting the person that created your test credentials.

**Comment by zainmobashar** [comment]
Hi skills-up ,

Hope you are well ! 

I have just started working on Amadeus WS and i am struggling to understand the header 4.0 . I would like to request any helpful data on this please as i am also getting "12|Presentation|soap message header incorrect" . If a source that can help me please so that i can rectify my issue.
Thanks

**Comment by skills-up** [comment]
Hello @zainmobashar,

This issue is about 5 years old now, and thus my memory of the resolution is foggy at best. Based on my own replies above, I believe the best way is to contact Amadeus support team and ask them for latest WSDL.
