### ISSUE TITLE
connecting recommendation with flighs & baggage info 

### ISSUE THREAD

**Issue by rifkydj** [amabnl/amadeus-ws-client#235]
Hi guys,

Im using Fare_MasterPricerTravelboardSearch API,

I want to know how to connect recommendations with flights & baggage info .Im using laravel . if someone provide me explanation with code it will be a great help for me.

Thanks

**Comment by therealartz** [comment]
Here are response from Amadeus support (which You should be contact when facing difficulties in work with Amadeus).
This answer helped me understand how to work with MPTB response.

A Recommendation is a combination of groupOfFlights. If we consider a Round Trip itinerary as an example (Master Pricer Response attached), we’ll have:
 - segRef: 1 for the outbound and 2 for the Inbound
 - Each segRef has groupOfFlights and in flightDetails you can find the details in terms of Carrier(s), Time(s) of Departure, location(s), etc. Here’s an example of an outbound connecting flight (number 15 in the Outbound groupOfFlights):

[attachment 1](https://lh6.googleusercontent.com/lqE8_xF50ygr6zn2dEMiZgzqkZfkKjnLSNTLWe5WVlgDTs2KTLAKRNDaCA85bi9f0_UfWYUCyX7qvw=w1920-h953)

- As mentioned before, a Recommendation is a combination of groupOfFlights. Per definition, one recommendation is composed by a Fare + flights. However, two recommendations may have the same Fare but different combination of flights.

- As an example, the Recommendation number 7 (with a total Fare of USD 324.00) has 4 possible combination of flights. The first one makes reference to groupOfFlights 15 for the Outbound and 7 for the Inbound (refQualifier S = 15 and S = 7 respectively).

[attachment 2](https://lh5.googleusercontent.com/0DHPqb_LYtLfP4iCjLwyJX3z2XRNpqoOwcqfXlpNG0IrtGxuMHSWvG_AsJ9qvkxAsBxmmbSiR6jnhA=w1920-h953-rw)

**Comment by rifkydj** [comment]
Hi i dont have access to open attachments. please grant permissions.
Thanks

**Comment by therealartz** [comment]
@rifkydj links updated. Check them now.

**Comment by therealartz** [comment]
1) It means that you've search the recommendations for two segments and the given recommendation consists of two segments (itineraries).
S 1 - `flightIndex[0]->groupOfFlights[0] // First flight from flightIndex for first segment.`
S 1 - `flightIndex[1]->groupOfFlights[0] // First flight from flightIndex for second segment.`
B 1 - "B" stands for "Baggage coverage reference". It referencing to `reply->serviceFeesGrp->freeBagAllowanceGrp` where you should find baggage allowance under this ref number.
Codes description can be find at reply structure of message at extranet.

2) I am not an Amadeus expert, but perhaps you are looking for refNumber in the wrong flightIndex (which is related this to your first question).

If you really wish to develop with using Amadeus WS you should learn to navigate in messages documentation at extranet.

**Comment by rifkydj** [comment]
@therealartz thanks broo. ill try .
