### ISSUE TITLE
Special pricing and ticketing 

### ISSUE THREAD

**Issue by baraayyash** [amabnl/amadeus-ws-client#239]
Hi, 

we have an issue when trying to issue a ticket for a specific airline, they told us that in pricing request we need to add `FXB/R,VC-NE` 
and for ticketing request we need to add : `Ttp\v*ne`

how can i do that using this library?

Thanks for the help !

**Comment by DerMika** [comment]
You are looking for the option "validating carrier" as explained in the docs here: https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples.rst#fare-pricepnrwithbookingclass (first example)

and are you sure you need to provide a validating carrier when issuing a ticket? I'm pretty sure the system will just use the validating carrier used for pricing.

**Comment by baraayyash** [comment]
thanks for your fast answer.. i have already tried that, the error still the same when issuing the ticket

`INVALID TICKETING CARRIER-REENTER TICKETING CARRIER`

**Comment by baraayyash** [comment]
@DerMika ... any idea please?

**Comment by DerMika** [comment]
You should take this up with Amadeus Support, they will know precisely how to translate the cryptic pricing entry to the correct verb. Once you know what XML you should be sending, you can let me know and I can help you build that message with this library.

**Comment by baraayyash** [comment]
@therealartz  , i have contacted amadues, and they told for that airline ('NA'), i should user another airline code to price the pnr which was 'NE' .. so i used `validatingCarrier => 'NE` 

and it worked! 

thanks for the help
