### ISSUE TITLE
PNR_AddMultiElements : add special service request

### ISSUE THREAD

**Issue by ratheepan** [amabnl/amadeus-ws-client#24]
Hello Sir,  

Could you kindly share me the example of  special service request(SSR) (eg wheel chair request, Spacial meal request) with PNR_AddMultiElements request?

Thanks in Advance
s ratheepan

**Comment by DerMika** [comment]
Hi, 

I have one example of adding an SSR to a PNR [here](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/pnr-create-modify.rst#service-request-srdocs). 

But to add for example a meal request, you need to know what the SSR code is to add to the PNR. 

For example, the code for a diabetic meal is "DBML", so here is how you could add a diabetic meal to the PNR: 

```
use Amadeus\Client\RequestOptions\PnrCreatePnrOptions;
use Amadeus\Client\RequestOptions\Pnr\Element\ServiceRequest;
use Amadeus\Client\RequestOptions\Pnr\Reference;

$opt = new PnrCreatePnrOptions([
    'elements' => [
        new ServiceRequest([
            'type' => 'DBML', 
            'references' => [
                new Reference([
                    'type' => Reference::TYPE_PASSENGER_TATTOO,
                    'id' => 1
                ])
            ]
        ])
    ]
]);
```

I don't know the code for a wheelchair request, but for all these kinds of questions, you should be able to either check the SSR help pages in Selling Platform, or request support from your Amadeus support contact assigned to your project.

**Comment by DerMika** [comment]
I just checked how you can request a wheelchair, it's pretty similar. You just need to know the correct code:

THe following is an example to reques wheelchair for passenger 1 on flight 2:

```
use Amadeus\Client\RequestOptions\PnrCreatePnrOptions;
use Amadeus\Client\RequestOptions\Pnr\Element\ServiceRequest;
use Amadeus\Client\RequestOptions\Pnr\Reference;

$opt = new PnrCreatePnrOptions([
    'elements' => [
        new ServiceRequest([
            'type' => 'WHCR', 
            'references' => [
                new Reference([
                    'type' => Reference::TYPE_PASSENGER_TATTOO,
                    'id' => 1
                ]),
                new Reference([
                    'type' => Reference::TYPE_SEGMENT_TATTOO,
                    'id' => 2
                ])
            ]
        ])
    ]
]);
```

**Comment by ratheepan** [comment]
Hello DerMika ,  thank you  very much.

**Comment by socialimpulse** [comment]
Hello there, 

Could you please let me know how to add the frequent traveler to a Car Segment ?

Thanks in advance.
