### ISSUE TITLE
Regarding FareCheckRules

### ISSUE THREAD

**Issue by rifkydj** [amabnl/amadeus-ws-client#240]
Hi Guys,

The regarding Fare_CheckRules,

Im using Fare_MasterPricerTravelboardSearch for get results,

So i want to get penalty information. 
My question is after getting Fare_MasterPricerTravelboardSearch response  how can i get penalties ? what are the parameters require to get penalties using Fare_CheckRules?? This will be a great help for me. 
Thanks

**Comment by therealartz** [comment]
After selecting some recommendation from search, first you need to make call [Fare_InformativePricingWithoutPnr](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples.rst#fare-informativepricingwithoutpnr).

After it, you can call [Fare_CheckRules](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples.rst#fare-checkrules) without specifying any flight attributes.

It that sequence CheckRules will show you rules for recommendation from previous request (Informative Pricing). This is a part of Amadeus booking flow.

If you want standalone method to get rules, you should use [Fare_GetFareRules](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples.rst#fare-getfarerules).

**Comment by rifkydj** [comment]
when i use Fare_InformativePricingWithoutPnr. it says Undefined property: Amadeus\Client\RequestOptions\Pnr\Segment::$segmentTattoo.
![fireshot capture 14 - whoops there was an error - http___amadeus d_fare_rules](https://user-images.githubusercontent.com/36004655/46661511-fcd41f00-cbd6-11e8-89a5-6180746c3285.png)

**Comment by therealartz** [comment]
@rifkydj show your request options.

**Comment by rifkydj** [comment]
$informativePricingResponse = $client->fareInformativePricingWithoutPnr(
    new FareInformativePricingWithoutPnrOptions([
        'passengers' => [
            new Passenger([
                'tattoos' => [1, 2],
                'type' => Passenger::TYPE_ADULT
            ])
        ],
        'segments' => [
            new Segment([
                'departureDate' => \DateTime::createFromFormat('Y-m-d H:i:s', '2018-10-25 05:25:00'),
                'from' => 'CMB',
                'to' => 'BAH',
                'marketingCompany' => 'GF',
                'flightNumber' => '139',
                'bookingClass' => 'Y',
                'segmentTattoo' => 1,
                'groupNumber' => 1
            ]),
            new Segment([
                'departureDate' => \DateTime::createFromFormat('Y-m-d H:i:s', '2018-10-25 10:35:00'),
                'from' => 'BAH',
                'to' => 'LHR',
                'marketingCompany' => 'GF',
                'flightNumber' => '3',
                'bookingClass' => 'C',
                'segmentTattoo' => 2,
                'groupNumber' => 2
            ])
        ]
    ])
);

**Comment by therealartz** [comment]
@rifkydj you are using namespace for another request.

Correct namespaces:

```
use Amadeus\Client\RequestOptions\Fare\InformativePricing\Passenger;
use Amadeus\Client\RequestOptions\Fare\InformativePricing\Segment;
```

**Comment by rifkydj** [comment]
@therealartz  thanks. i got response . ill add my response. may i know what are the parameters to pass Fare_CheckRules ? i mean from this response which parameters should i pass to this Fare_CheckRules??

`{"status":"OK","messages":[],"response":{"messageDetails":{"messageFunctionDetails":{"businessFunction":"1","messageFunction":"741","responsibleAgency":"1A"},"responseType":"A"},"mainGroup":{"dummySegment":[],"convertionRate":{"conversionRateDetails":{"rateType":"USR","pricingAmount":"162.369800","dutyTaxFeeType":"LK"}},"generalIndicatorsGroup":{"generalIndicators":{"priceTicketDetails":{"indicators":"I"}}},"pricingGroupLevelGroup":{"numberOfPax":{"segmentControlDetails":{"quantity":1,"numberOfUnits":2}},"passengersID":{"travellerDetails":[{"measurementValue":1},{"measurementValue":2}]},"fareInfoGroup":{"emptySegment":[],"pricingIndicators":{"priceTicketDetails":{"indicators":"703"},"priceTariffType":"I","productDateTimeDetails":{"departureDate":"251018"},"companyDetails":{"otherCompany":"GF"}},"fareAmount":{"monetaryDetails":{"typeQualifier":"B","amount":"479700","currency":"LKR"},"otherMonetaryDetails":{"typeQualifier":"712","amount":"489214","currency":"LKR"}},"textData":[{"freeTextQualification":{"textSubjectQualifier":"4","informationType":"15"},"freeText":["25OCT18CMB GF X\/BAH GF LON1071.62D BAHLON1882.48NUC2954.10END ROE162.3","69800"]},{"freeTextQualification":{"textSubjectQualifier":"1","informationType":"1P3"},"freeText":"PENALTY APPLIES"},{"freeTextQualification":{"textSubjectQualifier":"1","informationType":"10"},"freeText":"NON END - VALID ON GF ONLY"},{"freeTextQualification":{"textSubjectQualifier":"1","informationType":"1A49"},"freeText":" - DATE OF ORIGIN"},{"freeTextQualification":{"textSubjectQualifier":"1","informationType":"1A0"},"freeText":"NO CHARGEABLE ANCILLARY SERVICE"},{"freeTextQualification":{"textSubjectQualifier":"1","informationType":"1A0"},"freeText":"TICKET STOCK RESTRICTION"},{"freeTextQualification":{"textSubjectQualifier":"1","informationType":"1A0"},"freeText":"BG CXR: 2*GF"},{"freeTextQualification":{"textSubjectQualifier":"1","informationType":"1A0"},"freeText":"PRICED WITH VALIDATING CARRIER GF - REPRICE IF DIFFERENT VC"}],"surchargesGroup":{"taxesAmount":{"taxDetails":[{"rate":"509","countryCode":"YR","type":"VB"},{"rate":"8485","countryCode":"LK","type":"EM"},{"rate":"452","countryCode":"BH","type":"DP"},{"rate":"68","countryCode":"HM","type":"AP"}]},"penaltiesAmount":{"discountPenaltyQualifier":"700","discountPenaltyDetails":{"amount":"11900","currency":"LKR"}}},"segmentLevelGroup":[{"segmentInformation":{"flightDate":{"departureDate":"251018"},"boardPointDetails":{"trueLocationId":"CMB"},"offpointDetails":{"trueLocationId":"BAH"},"companyDetails":{"marketingCompany":"GF"},"flightIdentification":{"flightNumber":"139","bookingClass":"Y","operationalSuffix":"X"},"flightTypeDetails":{"flightIndicator":"T"},"itemNumber":1},"fareBasis":{"additionalFareDetails":{"rateClass":"YOWLK","secondRateClass":"Y"}},"cabinGroup":{"cabinSegment":{"bookingClassDetails":{"designator":"Y","option":"M"}}},"baggageAllowance":{"baggageDetails":{"freeAllowance":30,"quantityCode":"700"}},"ptcSegment":{"quantityDetails":{"numberOfUnit":1,"unitQualifier":"ADT"}}},{"segmentInformation":{"flightDate":{"departureDate":"251018"},"boardPointDetails":{"trueLocationId":"BAH"},"offpointDetails":{"trueLocationId":"LHR"},"companyDetails":{"marketingCompany":"GF"},"flightIdentification":{"flightNumber":"3","bookingClass":"C","operationalSuffix":"X"},"itemNumber":2},"fareBasis":{"additionalFareDetails":{"rateClass":"CLOWBH5","secondRateClass":"C"}},"cabinGroup":{"cabinSegment":{"bookingClassDetails":{"designator":"C","option":"C"}}},"baggageAllowance":{"baggageDetails":{"freeAllowance":30,"quantityCode":"700"}},"ptcSegment":{"quantityDetails":{"numberOfUnit":1,"unitQualifier":"ADT"}}}],"fareComponentDetailsGroup":{"fareComponentID":{"itemNumberDetails":{"number":"1"}},"marketFareComponent":{"boardPointDetails":{"trueLocationId":"CMB"},"offpointDetails":{"trueLocationId":"LON"}},"monetaryInformation":{"monetaryDetails":{"typeQualifier":"TFC","amount":"1071.62","currency":"NUC"}},"componentClassInfo":{"fareBasisDetails":{"rateTariffClass":"YOWLK"}},"fareQualifiersDetail":{"discountDetails":{"fareQualifier":"756"}},"couponDetailsGroup":[{"productId":{"referenceDetails":{"type":"ST","value":"1"}}},{"productId":{"referenceDetails":{"type":"ST","value":"2"}}}]}}}}},"responseXml":null}`

**Comment by therealartz** [comment]
@rifkydj 

`$response->mainGroup->pricingGroupLevelGroup->fareInfoGroup->fareComponentDetailsGroup->fareComponentID->itemNumberDetails->number`

In this particular case **_Informative Pricing_** returned only one recommendation.
Frequently **_Informative Pricing_** may return an array of pricing recommendations. 
But it is not necessary to make a request for all recommendations that **_Informative Pricing_** returned.
It depends on your business requirements.

For simple implementation just use request options from [example](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples.rst#fare-checkrules).

**Comment by rifkydj** [comment]
@therealartz  according to the response i posted in above comment the number is 1.

so i passed the number for fare_checkrules . 

i got this response `{"status":"ERR","messages":[{"code":"84","text":"ENTRY REQUIRES PREVIOUS PRICING\/FARE DISPLAY REQUEST","level":null}],"response":{"transactionType":{"messageFunctionDetails":{"messageFunction":"712"}},"errorInfo":{"rejectErrorCode":{"errorDetails":{"errorCode":"84"}},"errorFreeText":{"freeText":"ENTRY REQUIRES PREVIOUS PRICING\/FARE DISPLAY REQUEST"}}},"responseXml":null}` 

where i gone wrong????
i sent my both code segments.

`

$informativePricingResponse = $client->fareInformativePricingWithoutPnr(
    new FareInformativePricingWithoutPnrOptions([

        'passengers' => [
            new Passenger([
                'tattoos' => [1, 2],
                'type' => Passenger::TYPE_ADULT
            ])
        ],
        'segments' => [
            new Segment([
                'departureDate' => \DateTime::createFromFormat('Y-m-d H:i:s', '2018-10-25 05:25:00'),
                'from' => 'CMB',
                'to' => 'BAH',
                'marketingCompany' => 'GF',
                'flightNumber' => '139',
                'bookingClass' => 'Y',
                'segmentTattoo' => 1,
                'groupNumber' => 1
            ]),
            new Segment([
                'departureDate' => \DateTime::createFromFormat('Y-m-d H:i:s', '2018-10-25 10:35:00'),
                'from' => 'BAH',
                'to' => 'LHR',
                'marketingCompany' => 'GF',
                'flightNumber' => '3',
                'bookingClass' => 'C',
                'segmentTattoo' => 2,
                'groupNumber' => 2
            ])
        ],
        'currencyOverride' => "INR",
    ])
);`

`$rulesResponse = $client->fareCheckRules(
    new FareCheckRulesOptions([
        'recommendations' => [1] //Pricing nr 1
    ])
); `

**Comment by therealartz** [comment]
You must call these requests in one session context.

Library have good implementation of stateful context.
https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#switching-between-stateful-stateless-messages-soap-header-4

On extranet you can find implementation guide for stateful and stateless contexts.

**Comment by therealartz** [comment]
You should contact to Amadeus for they give an access to any of the web services.

**Comment by rifkydj** [comment]
@therealartz im already using one session . ill show my code.

`namespace App\Library;

use Amadeus\Client;
use Amadeus\Client\Params;
use Amadeus\Client\Result;
use Psr\Log\NullLogger;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Storage;

class AmadeusWsseHeader{

    public function get_header(){
        $storagePath  = Storage::disk('wsdl')->getDriver()->getAdapter()->getPathPrefix();
        $params = new Params([
           'returnXml' => false,
            'authParams' => [
                'officeId' => "",
                'userId' => "",
                //'passwordLength' => 8,
                'passwordData' => ""
            ],
            'sessionHandlerParams' => [
                'soapHeaderVersion' => Client::HEADER_V4,                
                'wsdl' => $storagePath.'/1ASIWTPLSHP_PDT_20170804_120038.wsdl',
                                                            
                'logger' => new NullLogger
            ],
            'requestCreatorParams' => [
                'receivedFrom' => ''
            ]
        ]);

        return $params;
    }

  
}`

and im calling them as 
`$header=new AmadeusWsseHeader();
$params=$header->get_header();

$client = new Client($params);`

this is how i made session. is it ok????

**Comment by therealartz** [comment]
First of all you MUST get acquainted with the mechanism of the Amadeus sessions.
After it take a look on these answers from another issues:
https://github.com/amabnl/amadeus-ws-client/issues/92#issuecomment-327722085
https://github.com/amabnl/amadeus-ws-client/issues/9#issuecomment-262794581
They may help you to organize your work.

**Comment by rifkydj** [comment]
@therealartz hi again, im stuck with amadeus sessions.
i cannot set session data before this line of text.
`$rec = $client->fareMasterPricerTravelBoardSearch($opt); `
it gives an error.

after that line i can set session data. but when i call Fare_InformativePricingWithoutPnr. it gives diffrent session data. i got session data by $client->getSessionData();

it gives something different than what i sent in fareMasterPricerTravelBoardSearch;

i call fareMasterPricerTravelBoardSearch like this,
`
$rec = $client->fareMasterPricerTravelBoardSearch($opt); // call result
 $previousSessionData = [
                        'sessionId' => 'MgOf70sHGx',
                        'sequenceNumber' => 5,
                        'securityToken' => 'GyiI9T9YarZcYbiI1af22z2cS6MlVLZO'
                    ];
$client->setSessionData($previousSessionData);`

i call Fare_InformativePricingWithoutPnr like this

`
$client = new Client($params);


 $options=new FareInformativePricingWithoutPnrOptions([

        'passengers' => [
            new Passenger([
                'tattoos' => [1, 2],
                'type' => Passenger::TYPE_ADULT
            ])
        ],
        'segments' => [
            new Segment([
                'departureDate' => \DateTime::createFromFormat('Y-m-d H:i:s', '2018-10-25 05:25:00'),
                'from' => 'CMB',
                'to' => 'BAH',
                'marketingCompany' => 'GF',
                'flightNumber' => '139',
                'bookingClass' => 'Y',
                'segmentTattoo' => 1,
                'groupNumber' => 1
            ]),
            new Segment([
                'departureDate' => \DateTime::createFromFormat('Y-m-d H:i:s', '2018-10-25 10:35:00'),
                'from' => 'BAH',
                'to' => 'LHR',
                'marketingCompany' => 'GF',
                'flightNumber' => '3',
                'bookingClass' => 'C',
                'segmentTattoo' => 2,
                'groupNumber' => 2
            ])
        ],
        'currencyOverride' => "INR",
    ]);  
$informativePricingResponse = $client->fareInformativePricingWithoutPnr($options);`

but different session data;
where i gone wrong???
please help me,
thanks

**Comment by therealartz** [comment]
@rifkydj `Fare_MasterPricerTravelBoardSearch` is a stateless service. You shouldn't use session data for him.

**Comment by rifkydj** [comment]
oh ok then Fare_InformativePricingWithoutPnr & Fare_CheckRules stateful????

**Comment by therealartz** [comment]
Yes.

**Comment by therealartz** [comment]
```
private $client;

public function __construct() {
    $this->client = new Client(); // Create client with your settings
    $sessionDataArray = getFromCache(); // / Session data array should be loaded from somewhere/your cache
    $this->client->setSessionData($sessionDataArray); /
}

public function fareInformativePricing() {
    // Do your message call
    $sessionDataArray = $this->client->getSessionData();
    // You have session data and you must store it in your cache
}

public function fareCheckRules() {
    // Do your message call
}
```

In this example when constructing class your `$client` will have loaded session data from cache.
So when you calling InformativePricing and getting session data you must store it somewhere.

At the next call Client will have $sessionData from previous request.

This is just an abstract example without any checks and other stuff.
Same logic explained in two links I sent earlier:
https://github.com/amabnl/amadeus-ws-client/issues/92#issuecomment-327722085
https://github.com/amabnl/amadeus-ws-client/issues/9#issuecomment-262794581

**Comment by rifkydj** [comment]
@therealartz Thanks Bro Ill try it. Thanks Very much

**Comment by rifkydj** [comment]
@therealartz i have tried it it says 
`{"status":"FATAL","messages":[{"code":" 17","text":"No agreement on destination","level":"Session"}],"response":null,"responseXml":null}`
it works fine if i dont include   $this->client->setSessionData($previousSessionData);
i called it like this , 

`  private $client;
    

    public function __construct() {


     // Create client with your settings
    $header=new AmadeusWsseHeader();
	$params=$header->get_stateful_header();
	
    $previousSessionData = [
                        'sessionId' => 'MgOf70sHGx',
                        'sequenceNumber' => 5,
                        'securityToken' => 'GyiI9T9YarZcYbiI1af22z2cS6MlVLZO'
                    ];
    $this->client = new Client($params);	
    $this->client->setSessionData($previousSessionData);
  }`

`$options=new FareInformativePricingWithoutPnrOptions([
                    'passengers' => [
                        new Passenger([
                            'tattoos' => [1, 2],
                            'type' => Passenger::TYPE_ADULT
                        ])
                    ],
                    'segments' => [
                        new Segment([
                            'departureDate' => \DateTime::createFromFormat('Y-m-d H:i:s', '2018-10-25 05:25:00'),
                            'from' => 'CMB',
                            'to' => 'BAH',
                            'marketingCompany' => 'GF',
                            'flightNumber' => '139',
                            'bookingClass' => 'Y',
                            'segmentTattoo' => 1,
                            'groupNumber' => 1
                        ]),
                        new Segment([
                            'departureDate' => \DateTime::createFromFormat('Y-m-d H:i:s', '2018-10-25 10:35:00'),
                            'from' => 'BAH',
                            'to' => 'LHR',
                            'marketingCompany' => 'GF',
                            'flightNumber' => '3',
                            'bookingClass' => 'C',
                            'segmentTattoo' => 2,
                            'groupNumber' => 2
                        ])
                    ],
                    'currencyOverride' => "INR",
                ]);  
            $informativePricingResponse = $this->client->fareInformativePricingWithoutPnr($options);
           `

**Comment by therealartz** [comment]
Error "No agreement on destination" means that currently you are not yet authorized to use that service.  

Changes needs to be applied on the Amadeus side that update a configuration indicating this service is available.

**Comment by rifkydj** [comment]
@therealartz im using a testing officeID so can it be a problem ???? do i need to assign permissions for that specific user id by asking amadeus.????

**Comment by therealartz** [comment]
Ask Amadeus about this error. They can respond more openly about this error.

**Comment by rifkydj** [comment]
@therealartz  thanks bro. your help is very much appreciated.

**Comment by rifkydj** [comment]
@therealartz they said ,
 An incorrect version could cause this error.
![image](https://user-images.githubusercontent.com/36004655/46846859-38513200-cdff-11e8-8552-e6285ab9377a.png)

**Comment by therealartz** [comment]
@rifkydj https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#logging-request-and-response

**Comment by rifkydj** [comment]
when i call Fare_InformativePricingWithoutPnr with session as u mentioned in previous comments . but it said  `{"status":"FATAL","messages":[{"code":" 17","text":"No agreement on destination","level":"Session"}],"response":null,"responseXml":null}` 
after i asked amadeus they said about An incorrect version could cause this error. 13.2 is up & running ? 
what is the problem @therealartz

**Comment by therealartz** [comment]
Send here xml request log

**Comment by rifkydj** [comment]
[requestresponse.txt](https://github.com/amabnl/amadeus-ws-client/files/2472325/requestresponse.txt)

**Comment by therealartz** [comment]
```
<SOAP-ENV:Envelope
    xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:ns1="http://xml.amadeus.com/TIPNRQ_13_2_1A"
    xmlns:ns2="http://www.w3.org/2005/08/addressing"
    xmlns:ns3="http://xml.amadeus.com/2010/06/Session_v3">
    <SOAP-ENV:Header>
        <ns2:MessageID>ABEF863E-EB62-CA2E-2383-27F871AB9AFC</ns2:MessageID>
        <ns2:Action>http://webservices.amadeus.com/TIPNRQ_13_2_1A</ns2:Action>
```

TIPNRQ_13_2_1A - you are using version 13.2.

Send logs to Amadeus support and keep asking what is wrong.
This problem is not related to the library.

Or try to re-download wsdl from extranet.

**Comment by rifkydj** [comment]
@therealartz ill try. thanks

**Comment by rifkydj** [comment]
@therealartz hi .
I have contacted with amadeus . They said nothing is wrong with API. They said to check correct Soap Action and end URL at application level.

![image001](https://user-images.githubusercontent.com/36004655/46951730-6f953c80-d0a6-11e8-8ac7-a48d5c226695.png)

can u guide me please.

**Comment by therealartz** [comment]
Have you tried to redownload WSDL?

**Comment by rifkydj** [comment]
Yes I tried.

**Comment by therealartz** [comment]
You can try to call message with pure PHP's `\SoapClient` to be sure that this is a problem inside this library and investigate further.

**Comment by rifkydj** [comment]
@therealartz  ok ill try it ... Thank u very much...

**Comment by therealartz** [comment]
You should read Amadeus WBS Implementation Guide. There is point "Flows" pages 15-17.
[SOAP 4.0 Amadeus WBS Implementation Guide.pdf](https://github.com/amabnl/amadeus-ws-client/files/2481580/SOAP.4.0.Amadeus.WBS.Implementation.Guide.pdf)

Answering your questions:
1. For Fare_MasterPricerTravelboardSearch you must use stateless session as it is required Amadeus rule for certification. And so, this means you shoudn't use session data returned by it, cause they are invalid.
2. Learn the guide that I've attached.
3. Take a look at user guide for this message on extranet.

**Comment by rifkydj** [comment]
@therealartz i got response. i can close this issue. thanks

**Comment by DerMika** [comment]
Ok, i'm going to step in here. 

You have a web services project with Amadeus. This means they gave you a support contact to ask functional questions about Amadeus and the Amadeus web services. You should always use them as the first resource to ask functional questions about using the Amadeus web services. You are in fact paying them for that. 

This library provides an interface to the Amadeus web services, but it is not an Amadeus product and the people behind them do not work for Amadeus. 

Issues opened here on this Github repo should be about using this library to do a specific thing on Amadeus. Not about asking how to do a specific thing on Amadeus. For that you have your support contact. 

I am very grateful to people like @therealartz who are trying to help you (and frankly I don't have the time to do what he does right now), but he shouldn't have to do this. 

The people to ask your question above are Amadeus Support, not us.

**Comment by rifkydj** [comment]
@DerMika Thanks for your help . ill try to contact amadeus .
