### ISSUE TITLE
FareMasterPricerTbSearch

### ISSUE THREAD

**Issue by saaqeb** [amabnl/amadeus-ws-client#245]
FareMasterPricerTbSearch

What is the logic of combination of price recommendation array with groupOfFlights array

**Comment by therealartz** [comment]
https://github.com/amabnl/amadeus-ws-client/issues/235#issuecomment-425126326

**Comment by saaqeb** [comment]
Can you biref little bit regarding seat class

**Comment by therealartz** [comment]
Cabin class or booking class?

**Comment by saaqeb** [comment]
booking class

**Comment by therealartz** [comment]
Open Amadeus extranet.
Find MasterPricerTravelBoardSearch page.
Open "Browse structure".
There you can find descriptions for most of fields and codes.

![screenshot_20181020-182506](https://user-images.githubusercontent.com/21292595/47257408-ff1b6080-d495-11e8-96d8-6526be8ca704.png)

**Comment by AmiinosEddagh** [comment]
the MCX code is for **Majority carrier**
[https://i.imgur.com/ZCsiJM5.png](https://i.imgur.com/ZCsiJM5.png)

**Comment by DerMika** [comment]
Assuming issue is fixed with the above comments.
