### ISSUE TITLE
Regarding FareInformativePricingWithoutPNR

### ISSUE THREAD

**Issue by rifkydj** [amabnl/amadeus-ws-client#246]
Hi Guys, 
i Got correct response of FareInformativePricingWithoutPNR for 2 Adults.
But i stucked with to add infants and child.  can you give example for adding infants & children.

this is my code for getting adult info. if u give me same code for adding 1 adult and 1 child and 1 infant it will be great  help.
`$options=new FareInformativePricingWithoutPnrOptions([

                    'passengers' => [
                        new Passenger([
                            'tattoos' => [1],
                            'type' => Passenger::TYPE_ADULT
                        ]),
                         new Passenger([
                             
                            'type' => Passenger::TYPE_CHILD
                        ]),
                         new Passenger([
                          
                            'type' => Passenger::TYPE_INFANT
                        ])
                    ],
                    'segments' => [
                        new Segment([
                            'departureDate' => \DateTime::createFromFormat('Y-m-d H:i:s', '2018-10-25 00:25:00'),
                            'from' => 'CMB',
                            'to' => 'KUL',
                            'marketingCompany' => 'OD',
                            'flightNumber' => '186',
                            'bookingClass' => 'Y',
                            'segmentTattoo' => 1,
                            'groupNumber' => 1
                        ]),
                        new Segment([
                            'departureDate' => \DateTime::createFromFormat('Y-m-d H:i:s', '2018-10-25 08:15:00'),
                            'from' => 'KUL',
                            'to' => 'SIN',
                            'marketingCompany' => 'OD',
                            'flightNumber' => '801',
                            'bookingClass' => 'Y',
                            'segmentTattoo' => 2,
                            'groupNumber' => 1
                        ]),
                       
                    ],
                    'pricingOptions' => new PricingOptions([
            'overrideOptions' => [
                PricingOptions::OVERRIDE_FARETYPE_PUB,
                PricingOptions::OVERRIDE_FARETYPE_UNI
            ],
            'currencyOverride' => 'USD',
            
            
        ])
                   
                ]);  `

in this code there is a parameter called 'tattoos' => [1],? what is it??

**Comment by therealartz** [comment]
Tattoo is like a reference number to a passenger. You must provide tattoo number for each passenger.

Correct request options for 2 adults, 1 child and 1 infant:

```
$opt = new FareInformativePricingWithoutPnrOptions([
    'passengers' => [
        new Passenger([
            'tattoos' => [1, 2],
            'type' => Passenger::TYPE_ADULT
        ]),
        new Passenger([
            'tattoos' => [3],
            'type' => Passenger::TYPE_CHILD
        ]),
        new Passenger([
            'tattoos' => [4],
            'type' => Passenger::TYPE_INFANT
        ])
    ],
    'segments' => [
        new Segment([
            'departureDate' => \DateTime::createFromFormat('Y-m-d H:i:s', '2018-10-25 00:25:00'),
            'from' => 'CMB',
            'to' => 'KUL',
            'marketingCompany' => 'OD',
            'flightNumber' => '186',
            'bookingClass' => 'Y',
            'segmentTattoo' => 1,
            'groupNumber' => 1
        ]),
        new Segment([
            'departureDate' => \DateTime::createFromFormat('Y-m-d H:i:s', '2018-10-25 08:15:00'),
            'from' => 'KUL',
            'to' => 'SIN',
            'marketingCompany' => 'OD',
            'flightNumber' => '801',
            'bookingClass' => 'Y',
            'segmentTattoo' => 2,
            'groupNumber' => 1
        ]),
    ],
]);
```

**Comment by rifkydj** [comment]
@therealartz thanks Very much . this will be great help. i can close this issue now.
