### ISSUE TITLE
Fare_MasterPricerTravelBoardSearch Flights Order

### ISSUE THREAD

**Issue by AmiinosEddagh** [amabnl/amadeus-ws-client#247]
Hi,
is there an option to order the flights by duration or number of stops instead of price?
thank you.

**Comment by therealartz** [comment]
As I know MasterPricerTravelBoard return results in price order.
Did you investigate your question in extranet docs or ask support?

However I think that sorting of complete results is better than make calls to Amadeus with ordering of 250 results (maximum count of results that MPTB can return at all by default).

**Comment by AmiinosEddagh** [comment]
yes i just wanted to know if its possible.
thanks for your reply.
