### ISSUE TITLE
DocIssuance_IssueCombined issue

### ISSUE THREAD

**Issue by saaqeb** [amabnl/amadeus-ws-client#249]
I am doing the following step when i need call DocIssuance_IssueCombined

1. airSellFromRecommendation
2. PnrCreatePnrOptions
3. farePricePnrWithBookingClass
4. ticketCreateTSTFromPricing
5. fopCreateFormOfPayment
6. pnrCreatePnr
7. queuePlacePnr
8. PnrRetrieveOptions

is my flow ok? and where need to call DocIssuance_IssueCombined

**Comment by saaqeb** [comment]
how to get the ticket number?

**Comment by therealartz** [comment]
Use `DocIssuance_IssueTicket`

**Comment by saaqeb** [comment]
i am getting this err

[status] => ERR
            [action] => docIssuanceIssueTicket
            [messages] => Array
                (
                    [0] => Array
                        (
                            [code] => 374
                            [text] => CMC RJT : NEED COMMISSION
                            [level] => 
                        )

                )

**Comment by saaqeb** [comment]
I am getting this err

`[status] => ERR
            [action] => docIssuanceIssueTicket
            [messages] => Array
                (
                    [0] => Array
                        (
                            [code] => 374
                            [text] => CMC RJT : NEED COMMISSION
                            [level] => 
                        )

                )
`

**Comment by therealartz** [comment]
First of all, please, read this message from creator of this library: https://github.com/amabnl/amadeus-ws-client/issues/240#issuecomment-432620090 and don't create new issues that are not related to this library.

Anyway, I guess that there is a very common mistake for beginner.
You should add commission element into PNR when creating:
```
    ...
    'elements' => [
        new ManualCommission([
            'passengerType' => ManualCommission::PAXTYPE_PASSENGER,
            'indicator' => ManualCommission::INDICATOR_COMMISSION,
            'amount' => 0,
        ]),
        ...
    ]
```
