### ISSUE TITLE
PNR_AddMultiElements : need help to solve  the error on1 Adult and1Child 

### ISSUE THREAD

**Issue by ratheepan** [amabnl/amadeus-ws-client#25]
Hello Sir,

Thank you very  for your support.

i needsome help for "PNR_AddMultiElements  with one adult and one child".

i am getting following errors "    [text] => Array
                                (
                                    [0] => ERROR AT END OF TRANSACTION TIME
                                    [1] => ERROR AT EOT TIME                                                     
                                    [2] => NEED PASSENGER/SEGMENT ASSOC.                                         
Could you kindly help me sir?

Here i included search object

Thanks in Advanced.
                                

    Amadeus\Client\RequestOptions\PnrCreatePnrOptions Object
    (
        [travellerGroup] => 
        [travellers] => Array
            (
                [0] => Amadeus\Client\RequestOptions\Pnr\Traveller Object
                (
                    [number] => 1
                    [withInfant] => 
                    [travellerType] => ADT
                    [firstName] => madhavan
                    [lastName] => Jayje
                    [dateOfBirth] => DateTime Object
                        (
                            [date] => 1986-10-08 16:09:25
                            [timezone_type] => 3
                            [timezone] => Asia/Colombo
                        )

                    [infant] => 
                )

            [1] => Amadeus\Client\RequestOptions\Pnr\Traveller Object
                (
                    [number] => 2
                    [withInfant] => 
                    [travellerType] => CHD
                    [firstName] => sivagjhdnd
                    [lastName] => jkekejnfefkf
                    [dateOfBirth] => DateTime Object
                        (
                            [date] => 2010-10-01 16:09:25
                            [timezone_type] => 3
                            [timezone] => Asia/Colombo
                        )

                    [infant] => 
                )

        )

    [tripSegments] => Array
        (
        )

    [itineraries] => Array
        (
            [0] => Amadeus\Client\RequestOptions\Pnr\Itinerary Object
                (
                    [origin] => CMB
                    [destination] => MAA
                    [segments] => Array
                        (
                            [0] => Amadeus\Client\RequestOptions\Pnr\Segment\Air Object
                                (
                                    [status] => NN
                                    [flightNumber] => 274
                                    [date] => DateTime Object
                                        (
                                            [date] => 2016-11-28 17:05:00
                                            [timezone_type] => 3
                                            [timezone] => Asia/Colombo
                                        )

                                    [origin] => CMB
                                    [destination] => MAA
                                    [bookingClass] => S
                                    [sellType] => 0
                                    [quantity] => 1
                                    [company] => AI
                                    [references] => Array
                                        (
                                        )

                                )

                        )

                )

        )

    [elements] => Array
        (
            [0] => Amadeus\Client\RequestOptions\Pnr\Element\FormOfPayment Object
                (
                    [type] => CA
                    [creditCardType] => 
                    [creditCardNumber] => 
                    [creditCardExpiry] => 
                    [creditCardCvcCode] => 
                    [freeText] => 
                    [references] => Array
                        (
                        )

                )

            [1] => Amadeus\Client\RequestOptions\Pnr\Element\Ticketing Object
                (
                    [ticketMode] => OK
                    [date] => DateTime Object
                        (
                            [date] => 2016-10-20 10:39:25
                            [timezone_type] => 3
                            [timezone] => UTC
                        )

                    [ticketQueue] => 
                    [references] => Array
                        (
                        )

                )

            [2] => Amadeus\Client\RequestOptions\Pnr\Element\Contact Object
                (
                    [type] => 7
                    [value] => 001111111111
                    [references] => Array
                        (
                        )

                )

        )

    [actionCode] => 11
    [receivedFrom] => AmaduesAIrproject
)

**Comment by DerMika** [comment]
Hi, 

You'll have to check the response XML message to see where the error `NEED PASSENGER/SEGMENT ASSOC` occurs.

From the message you are constructing, it seems to me like you've entered the wrong passenger count in your AIR segment: it says `[quantity] => 1`, but since there are 2 passengers in your PNR, the system doesn't know for which passenger this segment is.

So either you need to set the quantity of the AIR segment to 2, or you need to associate the AIR segment with the correct passenger.

Also, it is generally not a good idea to create segments in the PNR that aren't flown by all the passengers in the PNR - this is not supported by many airlines, or it can trigger a PNR split at End Transact.

**Comment by DerMika** [comment]
Hi @ratheepan, did the explanation above solve your problem? Can we this issue be closed?

**Comment by ratheepan** [comment]
Hello DerMika ,

Yes, You can close it.  Thank you very much
