### ISSUE TITLE
Not getting a session

### ISSUE THREAD

**Issue by Lourad** [amabnl/amadeus-ws-client#250]
Hello, thank you for this very helpful library.

I need help on farePricePnrWithBookingClass with this error :
`{ code: '1383', text: 'PNR NOT PRESENT', level: null }`

I'm currently doing :
- fareMasterPricerTravelBoardSearch (Stateless)
- airSellFromRecommendation
- pnrAddMultiElements (ACTION_END_TRANSACT_RETRIEVE)
- farePricePnrWithBookingClass

Also tried it on pnrRetrieve and I am having the same error. I am certain that I am on **stateful** when I'm sending this messages. I even checked it using isStateful() and it is returning **true**. Reading through posted issues here that has same problem with me makes me understand that when I'm on stateful I should have a session details but when I checked it using getSessionData() it will give me

`{ sessionId: null, sequenceNumber: null, securityToken: null }`

**Comment by therealartz** [comment]
Take a look at this helpful comment: https://github.com/amabnl/amadeus-ws-client/issues/9#issuecomment-262794581

**Comment by Lourad** [comment]
Thanks for the reply. My problem is I can't seem to get a session data on pnrAddMultiElements using getSessionData to store it manually in my own created session to use on farePricePnrWithBookingClass.

Also in my understanding with the documentation it says I don't need to set new session using my previous session as long as I'm using ACTION_END_TRANSACT_RETRIEVE with a stateful  pnrAddMultiElements.

**Comment by therealartz** [comment]
Code `ACTION_END_TRANSACT_RETRIEVE` does not closes the session.

**Comment by therealartz** [comment]
Here two ways to end session
https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#ending-a-stateful-session-soap-header-4

**Comment by therealartz** [comment]
Also it is not a good practice to store PNR without pricing.

**Comment by Lourad** [comment]
Yes. I don't need to close it though.  I need to have or start a session. What are the other things that needs to be done to start a session besides using a stateful message?  Cause I'm certain that I'm calling the messages using stateful.

**Comment by therealartz** [comment]
Show request/response xml logs.

**Comment by Lourad** [comment]
**PNR REQUEST**
`<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://xml.amadeus.com/PNRADD_16_1_1A" xmlns:ns2="http://www.w3.org/2005/08/addressing" xmlns:ns3="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wsswssecurity-secext-1.0.xsd" xmlns:ns4="http://xml.amadeus.com/2010/06/Session_v3" xmlns:ns5="http://xml.amadeus.com/2010/06/Security_v1">
<SOAP-ENV:Header>
	<ns2:MessageID>1374976F-9934-CCAD-F137-E9626EB1C19B</ns2:MessageID>
	<ns2:Action>http://webservices.amadeus.com/PNRADD_16_1_1A</ns2:Action>
	<ns2:To>https://nodeD2.test.webservices.amadeus.com/1ASIWCTYLVV</ns2:To>
	<oas:Security xmlns:oas="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"> 	
		<oas:UsernameToken xmlns:oas1="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" oas1:Id="UsernameToken-1"> 		
			<oas:Username>XXX</oas:Username> 		
			<oas:Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">XXX</oas:Nonce> 	
			<oas:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">XXX</oas:Password> 	
			<oas1:Created>2018-10-26T02:56:22:893Z</oas1:Created> 
		</oas:UsernameToken> 
	</oas:Security>
	<ns4:Session TransactionStatusCode="Start">
		<ns4:SessionId/><ns4:SequenceNumber/><ns4:SecurityToken/>
	</ns4:Session>
	<ns5:AMA_SecurityHostedUser>
		<ns5:UserID POS_Type="1" PseudoCityCode="CGYPH2116" AgentDutyCode="SU" RequestorType="U"/>
	</ns5:AMA_SecurityHostedUser>
</SOAP-ENV:Header>
<SOAP-ENV:Body>
	<ns1:PNR_AddMultiElements>
		<ns1:pnrActions>
			<ns1:optionCode>11</ns1:optionCode>
		</ns1:pnrActions>
		<ns1:travellerInfo>
			<ns1:elementManagementPassenger>
				<ns1:reference>
					<ns1:qualifier>PR</ns1:qualifier>
					<ns1:number>1</ns1:number>
				</ns1:reference>
				<ns1:segmentName>NM</ns1:segmentName>
			</ns1:elementManagementPassenger>
			<ns1:passengerData>
				<ns1:travellerInformation>
					<ns1:traveller>
						<ns1:surname>Soriano</ns1:surname>
					</ns1:traveller>
					<ns1:passenger>
						<ns1:firstName>Lou Ard MR</ns1:firstName>
						<ns1:type>ADT</ns1:type></ns1:passenger>
					</ns1:travellerInformation>
				</ns1:passengerData>
			</ns1:travellerInfo>
			<ns1:originDestinationDetails>
				<ns1:originDestination>
					<ns1:origin>HKG</ns1:origin>
					<ns1:destination>MNL</ns1:destination>
				</ns1:originDestination>
				<ns1:itineraryInfo>
					<ns1:elementManagementItinerary>
						<ns1:reference>
							<ns1:qualifier>OT</ns1:qualifier>
							<ns1:number>1</ns1:number>
						</ns1:reference>
						<ns1:segmentName>AIR</ns1:segmentName>
					</ns1:elementManagementItinerary>
					<ns1:airAuxItinerary>
						<ns1:travelProduct>
							<ns1:product>
								<ns1:depDate>271018</ns1:depDate>
							</ns1:product>
							<ns1:boardpointDetail>
								<ns1:cityCode>HKG</ns1:cityCode>
							</ns1:boardpointDetail>
							<ns1:offpointDetail>
								<ns1:cityCode>MNL</ns1:cityCode>
							</ns1:offpointDetail>
							<ns1:company>
								<ns1:identification>PR</ns1:identification>
							</ns1:company>
							<ns1:productDetails>
								<ns1:identification>313</ns1:identification>
								<ns1:classOfService>M</ns1:classOfService>
							</ns1:productDetails>
						</ns1:travelProduct>
						<ns1:messageAction>
							<ns1:business>
								<ns1:function>1</ns1:function>
							</ns1:business>
						</ns1:messageAction>
						<ns1:relatedProduct>
							<ns1:quantity>1</ns1:quantity>
							<ns1:status>NN</ns1:status>
						</ns1:relatedProduct>
						<ns1:selectionDetailsAir>
							<ns1:selection>
								<ns1:option>0</ns1:option>
							</ns1:selection>
						</ns1:selectionDetailsAir>
					</ns1:airAuxItinerary>
				</ns1:itineraryInfo>
			</ns1:originDestinationDetails>
			<ns1:dataElementsMaster>
				<ns1:marker1/>
				<ns1:dataElementsIndiv>
					<ns1:elementManagementData>
						<ns1:reference>
							<ns1:qualifier>OT</ns1:qualifier>
							<ns1:number>2</ns1:number>
						</ns1:reference>
						<ns1:segmentName>AP</ns1:segmentName>
					</ns1:elementManagementData>
					<ns1:freetextData>
						<ns1:freetextDetail>
							<ns1:subjectQualifier>3</ns1:subjectQualifier>
							<ns1:type>5</ns1:type>
						</ns1:freetextDetail>
					</ns1:freetextData>
				</ns1:dataElementsIndiv>
				<ns1:dataElementsIndiv>
					<ns1:elementManagementData>
						<ns1:reference>
							<ns1:qualifier>OT</ns1:qualifier>
							<ns1:number>3</ns1:number>
						</ns1:reference>
						<ns1:segmentName>AP</ns1:segmentName>
					</ns1:elementManagementData>
					<ns1:freetextData>
						<ns1:freetextDetail>
							<ns1:subjectQualifier>3</ns1:subjectQualifier>
							<ns1:type>7</ns1:type>
						</ns1:freetextDetail>
						<ns1:longFreetext>09123213213</ns1:longFreetext>
					</ns1:freetextData>
					<ns1:referenceForDataElement>
						<ns1:reference>
							<ns1:qualifier>PR</ns1:qualifier>
							<ns1:number>1</ns1:number>
						</ns1:reference>
					</ns1:referenceForDataElement>
				</ns1:dataElementsIndiv>
				<ns1:dataElementsIndiv>
					<ns1:elementManagementData>
						<ns1:reference>
							<ns1:qualifier>OT</ns1:qualifier>
							<ns1:number>4</ns1:number>
						</ns1:reference>
						<ns1:segmentName>TK</ns1:segmentName>
					</ns1:elementManagementData>
					<ns1:ticketElement>
						<ns1:passengerType>PAX</ns1:passengerType>
						<ns1:ticket>
							<ns1:indicator>OK</ns1:indicator>
						</ns1:ticket>
					</ns1:ticketElement>
				</ns1:dataElementsIndiv>
				<ns1:dataElementsIndiv>
					<ns1:elementManagementData>
						<ns1:reference>
							<ns1:qualifier>OT</ns1:qualifier>
							<ns1:number>6</ns1:number>
						</ns1:reference>
						<ns1:segmentName>RF</ns1:segmentName>
					</ns1:elementManagementData>
					<ns1:freetextData>
						<ns1:freetextDetail>
							<ns1:subjectQualifier>3</ns1:subjectQualifier>
							<ns1:type>P22</ns1:type>
						</ns1:freetextDetail>
						<ns1:longFreetext>Lou Ard Soriano</ns1:longFreetext>
					</ns1:freetextData>
				</ns1:dataElementsIndiv>
			</ns1:dataElementsMaster>
		</ns1:PNR_AddMultiElements>
	</SOAP-ENV:Body>
</SOAP-ENV:Envelope>`

**RESPONSE**
`<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:awsse="http://xml.amadeus.com/2010/06/Session_v3" xmlns:wsa="http://www.w3.org/2005/08/addressing">
<SOAP-ENV:Header>
	<wsa:To>http://www.w3.org/2005/08/addressing/anonymous</wsa:To>
	<wsa:From>
		<wsa:Address>https://nodeD2.test.webservices.amadeus.com/XXX</wsa:Address>
	</wsa:From>
	<wsa:Action>http://webservices.amadeus.com/PNRADD_16_1_1A</wsa:Action>
	<wsa:MessageID>urn:uuid:2f5debec-c4ad-3b04-65b8-2570b0fc96cf</wsa:MessageID>
	<wsa:RelatesTo RelationshipType="http://www.w3.org/2005/08/addressing/reply">1374976F-9934-CCAD-F137-E9626EB1C19B</wsa:RelatesTo>
	<awsse:Session TransactionStatusCode="InSeries">
		<awsse:SessionId>00KIDMXCYI</awsse:SessionId>
		<awsse:SequenceNumber>1</awsse:SequenceNumber>
		<awsse:SecurityToken>AV2406LTKKOX3FD7FC9MSFJHT</awsse:SecurityToken>
	</awsse:Session>
</SOAP-ENV:Header>
<SOAP-ENV:Body>
	<PNR_Reply xmlns="http://xml.amadeus.com/PNRACC_16_1_1A">
	<pnrHeader>
		<reservationInfo>
			<reservation>
				<companyId>1A</companyId>
				<controlNumber>MKR8BR</controlNumber>
				<date>261018</date>
				<time>0256</time>
			</reservation>
		</reservationInfo>
	</pnrHeader>
	<securityInformation>
		<responsibilityInformation>
			<typeOfPnrElement>RP</typeOfPnrElement>
			<agentId>WSSU</agentId>
			<officeId>CGYPH2116</officeId>
			<iataCode>28000335</iataCode>
		</responsibilityInformation>
		<queueingInformation>
			<queueingOfficeId>CGYPH2116</queueingOfficeId>
		</queueingInformation>
		<cityCode>CGY</cityCode>
		<secondRpInformation>
			<creationOfficeId>CGYPH2116</creationOfficeId>
			<agentSignature>9998WS</agentSignature>
			<creationDate>261018</creationDate>
			<creatorIataCode>28000335</creatorIataCode>
			<creationTime>0256</creationTime></secondRpInformation>
		</securityInformation>
		<freetextData>
			<freetextDetail>
				<subjectQualifier>3</subjectQualifier>
				<type>P12</type>
			</freetextDetail>
			<longFreetext>--- RLR ---</longFreetext>
		</freetextData>
		<pnrHeaderTag>
			<statusInformation>
				<indicator>RLR</indicator>
			</statusInformation>
		</pnrHeaderTag>
		<sbrPOSDetails>
			<sbrUserIdentificationOwn>
				<originIdentification>
					<originatorId>28000335</originatorId>
					<inHouseIdentification1>CGYPH2116</inHouseIdentification1>
				</originIdentification>
				<originatorTypeCode>N</originatorTypeCode>
			</sbrUserIdentificationOwn>
			<sbrSystemDetails>
				<deliveringSystem>
					<companyId>1A</companyId>
					<locationId>CGY</locationId>
				</deliveringSystem>
			</sbrSystemDetails>
			<sbrPreferences>
				<userPreferences>
					<codedCountry>PH</codedCountry>
				</userPreferences>
			</sbrPreferences>
		</sbrPOSDetails>
		<sbrCreationPosDetails>
			<sbrUserIdentificationOwn>
				<originIdentification>
					<originatorId>28000335</originatorId>
					<inHouseIdentification1>CGYPH2116</inHouseIdentification1>
				</originIdentification>
				<originatorTypeCode>N</originatorTypeCode>
			</sbrUserIdentificationOwn>
			<sbrSystemDetails>
				<deliveringSystem>
					<companyId>1A</companyId>
					<locationId>CGY</locationId>
				</deliveringSystem>
			</sbrSystemDetails>
			<sbrPreferences>
				<userPreferences>
					<codedCountry>PH</codedCountry>
				</userPreferences></sbrPreferences>
			</sbrCreationPosDetails>
			<sbrUpdatorPosDetails>
				<sbrUserIdentificationOwn>
					<originIdentification>
						<originatorId>28000335</originatorId>
						<inHouseIdentification1>CGYPH2116</inHouseIdentification1>
					</originIdentification>
					<originatorTypeCode>N</originatorTypeCode>
				</sbrUserIdentificationOwn>
				<sbrSystemDetails>
					<deliveringSystem>
						<companyId>1A</companyId>
						<locationId>CGY</locationId>
					</deliveringSystem>
				</sbrSystemDetails>
				<sbrPreferences>
					<userPreferences>
						<codedCountry>PH</codedCountry>
					</userPreferences>
				</sbrPreferences>
			</sbrUpdatorPosDetails>
			<technicalData>
				<enveloppeNumberData>
					<sequenceDetails>
						<number>1</number>
					</sequenceDetails>
				</enveloppeNumberData>
				<lastTransmittedEnvelopeNumber>
					<currentRecord>0</currentRecord>
				</lastTransmittedEnvelopeNumber>
				<purgeDateData>
					<dateTime>
						<year>2018</year>
						<month>10</month>
						<day>31</day>
					</dateTime>
				</purgeDateData>
			</technicalData>
			<travellerInfo>
				<elementManagementPassenger>
					<reference>
						<qualifier>PT</qualifier>
						<number>2</number>
					</reference>
					<segmentName>NM</segmentName>
					<lineNumber>1</lineNumber>
				</elementManagementPassenger>
				<passengerData>
					<travellerInformation>
						<traveller>
							<surname>SORIANO</surname>
							<quantity>1</quantity>
						</traveller>
						<passenger>
							<firstName>LOU ARD MR</firstName>
							<type>ADT</type>
						</passenger>
					</travellerInformation>
				</passengerData>
				<enhancedPassengerData>
					<enhancedTravellerInformation>
						<travellerNameInfo>
							<quantity>1</quantity>
							<type>ADT</type>
						</travellerNameInfo>
						<otherPaxNamesDetails>
							<nameType>UN</nameType>
							<referenceName>Y</referenceName>
							<displayedName>Y</displayedName>
							<surname>SORIANO</surname>
							<givenName>LOU ARD MR</givenName>
						</otherPaxNamesDetails>
					</enhancedTravellerInformation>
				</enhancedPassengerData>
			</travellerInfo>
			<originDestinationDetails>
				<originDestination></originDestination>
				<itineraryInfo>
					<elementManagementItinerary>
						<reference>
							<qualifier>ST</qualifier>
							<number>1</number>
						</reference>
						<segmentName>AIR</segmentName>
						<lineNumber>2</lineNumber>
					</elementManagementItinerary>
					<travelProduct>
						<product>
							<depDate>271018</depDate>
							<depTime>0805</depTime>
							<arrDate>271018</arrDate>
							<arrTime>1010</arrTime>
						</product>
						<boardpointDetail>
							<cityCode>HKG</cityCode>
						</boardpointDetail>
						<offpointDetail>
							<cityCode>MNL</cityCode>
						</offpointDetail>
						<companyDetail>
							<identification>PR</identification>
						</companyDetail>
						<productDetails>
							<identification>313</identification>
							<classOfService>M</classOfService>
						</productDetails>
						<typeDetail>
							<detail>ET</detail>
						</typeDetail>
					</travelProduct>
					<itineraryMessageAction>
						<business>
							<function>1</function>
						</business>
					</itineraryMessageAction>
					<itineraryReservationInfo>
						<reservation>
							<companyId>PR</companyId>
							<controlNumber>MKR8BR</controlNumber>
						</reservation>
					</itineraryReservationInfo>
					<relatedProduct>
						<quantity>1</quantity>
						<status>HK</status>
					</relatedProduct>
					<flightDetail>
						<productDetails>
							<equipment>321</equipment>
							<numOfStops>0</numOfStops>
							<weekDay>6</weekDay>
						</productDetails>
						<departureInformation>
							<departTerminal>1</departTerminal>
						</departureInformation>
						<arrivalStationInfo>
							<terminal>2</terminal>
						</arrivalStationInfo>
						<facilities>
							<entertainement>M</entertainement>
							<entertainementDescription>B</entertainementDescription>
						</facilities>
					</flightDetail>
					<selectionDetails>
						<selection>
							<option>P2</option>
						</selection>
					</selectionDetails>
					<carbonDioxydeInfo>
						<carbonDioxydeAmount>
							<quantityDetails>
								<qualifier>COE</qualifier>
								<value>97.684854</value>
								<unit>KPP</unit>
							</quantityDetails>
						</carbonDioxydeAmount>
						<carbonDioxydeInfoSource>
							<freeTextDetails>
								<textSubjectQualifier>3</textSubjectQualifier>
								<source>S</source>
								<encoding>7</encoding>
							</freeTextDetails>
							<freeText>SOURCE:ICAO CARBON EMISSIONS CALCULATOR</freeText>
						</carbonDioxydeInfoSource>
					</carbonDioxydeInfo>
					<markerRailTour></markerRailTour>
				</itineraryInfo>
			</originDestinationDetails>
			<dataElementsMaster>
				<marker2></marker2>
				<dataElementsIndiv>
					<elementManagementData>
						<reference>
							<qualifier>OT</qualifier>
							<number>2</number>
						</reference>
						<segmentName>AP</segmentName>
						<lineNumber>3</lineNumber>
					</elementManagementData>
					<otherDataFreetext>
						<freetextDetail>
							<subjectQualifier>3</subjectQualifier>
							<type>5</type>
						</freetextDetail>
						<longFreetext>CGY 888575704 - LIMCON TRAVEL - A</longFreetext>
					</otherDataFreetext>
				</dataElementsIndiv>
				<dataElementsIndiv>
					<elementManagementData>
						<reference>
							<qualifier>OT</qualifier>
							<number>3</number>
						</reference>
						<segmentName>AP</segmentName>
						<lineNumber>4</lineNumber>
					</elementManagementData>
					<otherDataFreetext>
						<freetextDetail>
							<subjectQualifier>3</subjectQualifier>
							<type>7</type>
						</freetextDetail>
						<longFreetext>09123213213</longFreetext>
					</otherDataFreetext>
					<referenceForDataElement>
						<reference>
							<qualifier>PT</qualifier>
							<number>2</number>
						</reference>
					</referenceForDataElement>
				</dataElementsIndiv>
				<dataElementsIndiv>
					<elementManagementData>
						<reference>
							<qualifier>OT</qualifier>
							<number>4</number>
						</reference>
						<segmentName>TK</segmentName>
						<lineNumber>5</lineNumber>
					</elementManagementData>
					<ticketElement>
						<passengerType>PAX</passengerType>
						<ticket>
							<indicator>OK</indicator>
							<date>261018</date>
							<officeId>CGYPH2116</officeId>
						</ticket>
					</ticketElement>
				</dataElementsIndiv>
			</dataElementsMaster>
		</PNR_Reply>
	</SOAP-ENV:Body>
</SOAP-ENV:Envelope>`

**Comment by Lourad** [comment]
**farePricePnrWithBookingClass REQUEST**
`<?xml version="1.0" encoding="UTF-8"?> 
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://xml.amadeus.com/TPCBRQ_18_1_1A" xmlns:ns2="http://www.w3.org/2005/08/addressing" xmlns:ns3="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wsswssecurity-secext-1.0.xsd" xmlns:ns4="http://xml.amadeus.com/2010/06/Session_v3" xmlns:ns5="http://xml.amadeus.com/2010/06/Security_v1">
	<SOAP-ENV:Header>
		<ns2:MessageID>9B32717D-0564-87A8-5279-853401BAE998</ns2:MessageID>
		<ns2:Action>http://webservices.amadeus.com/TPCBRQ_18_1_1A</ns2:Action>
		<ns2:To>https://nodeD2.test.webservices.amadeus.com/1ASIWCTYLVV</ns2:To>
		<oas:Security xmlns:oas="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"> 	 
			<oas:UsernameToken xmlns:oas1="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" oas1:Id="UsernameToken-1">
				<oas:Username>XXX</oas:Username> 		
				<oas:Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">XXX</oas:Nonce>
				<oas:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">XXX</oas:Password> 		
				<oas1:Created>2018-10-26T02:56:25:340Z</oas1:Created> 	
			</oas:UsernameToken> 
		</oas:Security>
		<ns4:Session TransactionStatusCode="Start">
			<ns4:SessionId/><ns4:SequenceNumber/><ns4:SecurityToken/>		
		</ns4:Session>
		<ns5:AMA_SecurityHostedUser>
			<ns5:UserID POS_Type="1" PseudoCityCode="CGYPH2116" AgentDutyCode="SU" RequestorType="U"/>	
		</ns5:AMA_SecurityHostedUser>
	</SOAP-ENV:Header>
	<SOAP-ENV:Body>
		<ns1:Fare_PricePNRWithBookingClass>
			<ns1:pricingOptionGroup>
				<ns1:pricingOptionKey>
					<ns1:pricingOptionKey>NOP</ns1:pricingOptionKey>
				</ns1:pricingOptionKey>
			</ns1:pricingOptionGroup>
		</ns1:Fare_PricePNRWithBookingClass>
	</SOAP-ENV:Body>
</SOAP-ENV:Envelope>`

**farePricePnrWithBookingClass RESPONSE**
`<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:awsse="http://xml.amadeus.com/2010/06/Session_v3" xmlns:wsa="http://www.w3.org/2005/08/addressing">
<SOAPENV:Header>
	<wsa:To>http://www.w3.org/2005/08/addressing/anonymous</wsa:To>
	<wsa:From><wsa:Address>https://nodeD2.test.webservices.amadeus.com/XXX</wsa:Address></wsa:From>
	<wsa:Action>http://webservices.amadeus.com/TPCBRQ_18_1_1A</wsa:Action>
	<wsa:MessageID>urn:uuid:b88533a3-bb14-fdd4-51f6-4bc4782d7a8c</wsa:MessageID>
	<wsa:RelatesTo RelationshipType="http://www.w3.org/2005/08/addressing/reply">9B32717D-0564-87A8-5279-853401BAE998</wsa:RelatesTo>
	<awsse:Session TransactionStatusCode="InSeries">
		<awsse:SessionId>017B42GAE9</awsse:SessionId>
		<awsse:SequenceNumber>1</awsse:SequenceNumber>
		<awsse:SecurityToken>1SZW52H8WX0ZY1QN7L9YRV2IVP</awsse:SecurityToken>
	</awsse:Session>
</SOAP-ENV:Header>
<SOAP-ENV:Body>
	<Fare_PricePNRWithBookingClassReply xmlns="http://xml.amadeus.com/TPCBRR_18_1_1A">
		<applicationError>
			<errorOrWarningCodeDetails>
				<errorDetails>
					<errorCode>1383</errorCode>
					<errorCategory>EC</errorCategory>
					<errorCodeOwner>1A</errorCodeOwner>
				</errorDetails>
			</errorOrWarningCodeDetails>
			<errorWarningDescription>
				<freeText>PNR NOT PRESENT</freeText>
			</errorWarningDescription>
		</applicationError>
	</Fare_PricePNRWithBookingClassReply>
</SOAP-ENV:Body></SOAP-ENV:Envelope>`

**Comment by Lourad** [comment]
Yes, I called `getSessionData()` right after API request is completed. My xml log shows I'm getting a session but I'm still getting the error on farePricePnrWithBookingClass 
`<awsse:Session TransactionStatusCode="InSeries">
	<awsse:SessionId>017B42GAE9</awsse:SessionId>
	<awsse:SequenceNumber>1</awsse:SequenceNumber>
	<awsse:SecurityToken>1SZW52H8WX0ZY1QN7L9YRV2IVP</awsse:SecurityToken>
</awsse:Session>`

**Comment by therealartz** [comment]
Woah, that's strange.
Can't even imagine what is wrong.

You don't mind to show your code from creation of `Amadeus/Client` instance and till calling `PNR_AddMultiElements`?

**Comment by therealartz** [comment]
Ok, then next, show please code where you making API calls.

**Comment by Lourad** [comment]
**calling pnrAddMultiElements**
```
$opt = // PNR details with ACTION_END_TRANSACT_RETRIEVE as actionCode
$createdPnr = $this->client(true)->pnrAddMultiElements($opt);
```
```
$createdPnr = $this->client()->pnrAddMultiElements($opt);`
$req  = $this->client()->getLastRequest(); // returns undefined
$res  = $this->client()->getLastResponse(); // returns undefined
$test = $this->client()->isStateful(); // returns true
$info = $this->client()->getSessionData(); //returns empty session
```
**calling farePricePnrWithBookingClass right after**
```
$pricingResponse = $this->client(true)->farePricePnrWithBookingClass(
	new FarePricePnrWithBookingClassOptions()
);
```

**Comment by therealartz** [comment]
You creating new `Client` every time. This is a big mistake.

**Comment by therealartz** [comment]
Take a look at this "dirty" example: https://github.com/amabnl/amadeus-ws-client/issues/240#issuecomment-428490653 Here are correct using of `Client` instance and also "caching" of session data.

**Comment by DerMika** [comment]
Exactly.

Each time you instantiate `Amadeus\Client`, it will be initialized without session context. Before your Client object gets destroyed, you MUST extract session information from it to persist and use again, or it'll be lost.

**Comment by Lourad** [comment]
I see that's what causing it. Thank you very much for the help guys, much appreciated.
