### ISSUE TITLE
regarding MiniRule_GetFromPricing

### ISSUE THREAD

**Issue by infernoray** [amabnl/amadeus-ws-client#251]
I need help on MiniRule_GetFromPricing.
 before i use MiniRule_GetFromPricing message should i give a call to Fare_InformativePricingWithoutPNR mesage ?

**Comment by DerMika** [comment]
This is a functional message to which the answer you can probably find on the Amadeus Extranet documentation. 

A quote from the extranet docs: 

> MiniRule_GetFromPricing function should be used as a follow up of one of transactions below:
> 
> PNR pricing transactions (Ex: PricePNRWithBookingClass)
> Best pricing transactions (Ex: PricePNRWithLowerFares)
> Amadeus Ticket Changer transactions (Ex: RePricePNRWithBookingClass)
> Informative standalone pricing transactions (EX: InformativePricingWithoutPNR)
> If no pricing/re-pricing transaction has been processed before calling fucntion MiniRule_GetFromPricing, an error will be returned (See errors section for more details).

So yes, you need to have a pricing in session context before calling MiniRule_GetFromPricing.

**Comment by infernoray** [comment]
thanks very much @DerMika . i can close this issue now.
