### ISSUE TITLE
About Amadeus Workflow and Sessions

### ISSUE THREAD

**Issue by AmiinosEddagh** [amabnl/amadeus-ws-client#252]
Hi,
should I use the same session(getSessionData) for the entire Workflow?
I mean I have to extract it after the Fare_MasterPricerTravelBoardSearch and set the $Client with it in the rest of the Workflow?

1- Fare_MasterPricerTravelBoardSearch
2- Air_FlightInfo
3- Fare_CheckRules
4- Fare_InformativePricingWithoutPNR
5- PNR_AddMultiElements
6- Ticket_CreateTSTFromPricing
7- Ticket_ProcessETicket

Thank you

**Comment by therealartz** [comment]
No, you don't have to use one session for entire flow.

`Fare_MasterPricerTravelBoardSearch` **must be used in stateless** connection and `Air_FlightInfo` **can be used** in stateless connection.

**Comment by therealartz** [comment]
In general, this question is not related to the library.

I understand that for a someone new to Amadeus is difficult. I had a similar troubles a year ago. Anyway, such questions are best to deal with Amadeus technical support. Explain them the objectives of your project/your flow/what you want to get in a result, and probably they will answer to you how better to use sessions.

**Comment by AmiinosEddagh** [comment]
actualy i've passed the certification process but just wanted to know that

**Comment by therealartz** [comment]
You want to say that you passed the certification with using stateful connection from MPTB till ticket issuing? :worried:

**Comment by AmiinosEddagh** [comment]
i didin't say that. 
i used the correct session for each needed message in the workflow

**Comment by therealartz** [comment]
What exactly you wanted to know?

**Comment by AmiinosEddagh** [comment]
hi
i wanted to know if its mandatory to use the same session (getSessionData) in the messages which require a statefull session

**Comment by therealartz** [comment]
No. You shouldn't use one session for ALL messages, but it is mandatory when session context required.

You can separate your flows to some sections.

For example lets a look at flow of pricing and booking (from WBS implementation guide):

1. Fare_InformativePricingWithoutPNR
2. Fare_CheckRules
3. Air_SellFromRecommendation
4. PNR_AddMultiElements (action code 0)
5. Fare_PricePNRWithBookingClass
6. Ticket_CreateTSTFromPricing
7. PNR_AddMultiElements (action code 10 + end session header)

All this messages completed under one session (started with `Fare_InformativePricingWithoutPNR` call, and ended with `PNR_AddMultiElements (action code 10)`) , and now session is closed and all is fine.

For example next step we want to issue ticket, so we start a new session, and flow will be like (similar example is at implementation guide):
1. PNR_Retrieve
2. FOP_CreateFormOfPayment
3. DocIssuance_IssueTicket
4. PNR_Retrieve (end session header) to get issued ticket number

For these four calls we use another session and it is pretty good.

Hope it answers your question :)

**Comment by AmiinosEddagh** [comment]
yep
thank you so much for your support

**Comment by Gaurav191** [comment]
Can you tell me what exactly done in Amadeus certification process? Will they test my real time application or just want url of my application for registration? Thanks in advance.

**Comment by AmiinosEddagh** [comment]
> Can you tell me what exactly done in Amadeus certification process? Will they test my real time application or just want url of my application for registration? Thanks in advance.

they will ask you for the logs of each operation present in the workflow until you succeed booking a ticket

**Comment by Gaurav191** [comment]
Hi Thanks for reply. Yes I have successfully booked one way ticket with ADT and CHD. I want to add Infant and I am implementing it in Java.
