### ISSUE TITLE
Why the header needs 4.0 record locator?

### ISSUE THREAD

**Issue by montenegroraabe** [amabnl/amadeus-ws-client#253]
Hello! Could you help me?

I'm trying to accomplish the implementation of header 4.0 for my project of Amadeus. 

However, I would like to understand why you need the record locator and where I could capture that information, because I couldn't find in the documentation.

**Comment by therealartz** [comment]
In which moment record locator needed?
Explain more detailed what you can't do.

**Comment by montenegroraabe** [comment]
Hi!

What's happening: I'm trying to configure 4.0 header configuration for use in the project. 

However, following the related step that link [here](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/about-get-started.rst#set-up-a-test-client), says it's necessary to use the record locator, but didn't understand why or where to get this information.

My code is equal to the referenced in the link.

**Comment by therealartz** [comment]
Soap header 4 does not need record locator.
In provided link is only example of call to Amadeus web service `PNR_Retrieve`.

I guess you've just started to work with Amadeus. What you want to implement at all?

**Comment by montenegroraabe** [comment]
Exactly! Is my first attempt at setting and just been informed, by the support of Amadeus, which was necessary to setup header 4.0. 

But I don't know where to start, I confess. I need to call airline services, as a search engine: search the itinerary, get rates, select the offer and booking. It takes the header? It's used for these searches, correct?

**Comment by therealartz** [comment]
Start with learning of Amadeus session management: [header implementation guide](https://webservices.amadeus.com/extranet/viewFlavour.do?id=1&menuId=technical), [sessions best practices](https://webservices.amadeus.com/extranet/best_practices_session_management.do).

Then I guess is the best to start with Amadeus WBS Implementation Guide which you can find at `Fare_MasterPricerTravelBoardSearch` documentation page on [extranet](https://webservices.amadeus.com/extranet/viewService.do?id=581&flavourId=1&menuId=functional).

Also you should know some things, so read this comment from creator of this repo: https://github.com/amabnl/amadeus-ws-client/issues/240#issuecomment-432620090,  and this may be helpful to you when implementing Search with `TravelBoardSearch`: https://github.com/amabnl/amadeus-ws-client/issues/235#issuecomment-425126326

**Comment by montenegroraabe** [comment]
@therealartz, thank you!! 

I'll start this study to make the correct implementations.

**Comment by DerMika** [comment]
Hi, 

If your original question is answered, you may close this issue.
