### ISSUE TITLE
regarding pnr creation

### ISSUE THREAD

**Issue by infernoray** [amabnl/amadeus-ws-client#255]
Hi Guys,

1. In PNR creation there is array called contact & inside it there is something called reference. what will be it?? 
i was trying to create PNR with 1 adult and 1 child and 1 infant. when i include  1 adult and 1 infant it works fine. 

 ` new Contact([
            'type' => Contact::TYPE_PHONE_GENERAL,
            'value' => '+22345454545454',
            'references' => [
                new Reference([
                    'type' => Reference::TYPE_PASSENGER_REQUEST,
                    'id' => 0
                ]), ]`

2. After Extracting data from MPTB then next step will be airSellFromRecommendation. after it should i use same session data what  i extracted from airSellFromRecommendation to PNR_AddMultiElements ?

**Comment by infernoray** [comment]
thank you very much. i have another question. using this plugin how can i switch between test & production platforms ? is it related to login credentials or any way to switch between them.

**Comment by therealartz** [comment]
As I know this library do not provide such ability.

**Comment by DerMika** [comment]
You need a different WSDL to switch to production environment, as well as different credentials. 

You will receive that WSDL and associated credentials after your application passes Amadeus' certification process.

**Comment by DerMika** [comment]
And you can close this issue if your original question is answered.

**Comment by infernoray** [comment]
Thanks Alot guys for help and you guys doing a great job. i can close this issue now.
