### ISSUE TITLE
new message Service_BookPriceProduct

### ISSUE THREAD

**Issue by gabrythe23** [amabnl/amadeus-ws-client#256]
hi, 
we're trying to add the new message to the project but we have some issue with wsdl: 

`SOAP-ERROR: Parsing Schema: attributeGroup 'http://www.opentravel.org/OTA/2003/05/OTA2010B:AcceptablePaymentCardGroup' already defined`

before call the method, when the wsdl is loaded into php, we have downloaded all the wsdl files fresh before start coding!

any help about it?

**Comment by DerMika** [comment]
Hi, 

Are you trying to implement a new message into this library?

Unfortunately I have also experienced incompatibilities between the WSDL from Amadeus and the PHP XML/SOAP implementation in the past. If re-downloading the WSDL from Amadeus again did not solve your problem, you have probably run into such an issue.

The only courses of action I can recommend is: 

1. Which version of PHP are you running? Have you tried the latest version and checked if that solves the problem?
2. Report the issue to Amadeus and ask them to fix the WSDL so it's compatible with the PHP SOAP extension.
3. If all else fails - or the response from Amadeus takes too long - you will have to manually edit the offending WSDL/XSD file which is causing the error. If you do that, be sure to note what you changed so you can do it again when you re-download your WSDL at a later point.

**Comment by gabrythe23** [comment]
we have just found a trick. instead download wsdl for 'Default' framework, try with "Axis2". Without change php version, soap client read the method smooth! 🤙🤙

**Comment by bimusiek** [comment]
We had exactly same issue.

With new Amadeus developer platform, you have to download now WSDL with compatibility option (for .NET frameworks). Then, all WSDLs will work as expected. 

As this is resolved & answered by the author, I am closing this issue.
