### ISSUE TITLE
Regarding Fare_CheckRules

### ISSUE THREAD

**Issue by AmiinosEddagh** [amabnl/amadeus-ws-client#257]
Hi,
Sometimes when I execute the message **Fare_CheckRules**, I get an error **CHECK SEQUENCE NUMBER** .

Any idea what's causing that?

**Comment by therealartz** [comment]
Something wrong with yours session management.
Check out your request/response logs, you should find `sequenceNumber` header in each stateful request and response pair. They must be consistent.

**Comment by AmiinosEddagh** [comment]
sorry but can you be more specific?
may be can you attach an example?

**Comment by therealartz** [comment]
Example for what?

I think that you have a wrong session management. Show your code.

**Comment by AmiinosEddagh** [comment]
sorry for the late reply
i'll explain more:

1. after choosing the flight i send a request with message **apiFareInfoNotPNR**,
2. after that i retrieve the session with **$client->getSessionData()**
3. i set the session with the retrieved one with $client->setSessionData() before sending a request with message **fareCheckRules**

**Comment by AmiinosEddagh** [comment]
<itemNumberDetails> is refering to wich node?

**Comment by therealartz** [comment]
Fare_CheckRules->itemNumber->itemNumberDetails

**Comment by AmiinosEddagh** [comment]
ok, now i have this Reply

`<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:awsse="http://xml.amadeus.com/2010/06/Session_v3" xmlns:awsl="http://wsdl.amadeus.com/2010/06/ws/Link_v1" xmlns:wsa="http://www.w3.org/2005/08/addressing">
    <SOAP-ENV:Header>
        <wsa:To>http://www.w3.org/2005/08/addressing/anonymous</wsa:To>
        <wsa:From>
            <wsa:Address>https://nodeD2.production.webservices.amadeus.com/1ASIWEMNEYU</wsa:Address>
        </wsa:From>
        <wsa:Action>http://webservices.amadeus.com/FARQNQ_07_1_1A</wsa:Action>
        <wsa:MessageID>urn:uuid:c9c6c3fd-5dfc-8324-01ae-3a33bab4947b</wsa:MessageID>
        <wsa:RelatesTo RelationshipType="http://www.w3.org/2005/08/addressing/reply">C901DC75-5602-463A-2668-E437B94A033C</wsa:RelatesTo>
        <awsl:TransactionFlowLink>
            <awsl:Consumer>
                <awsl:UniqueID>3932F684-3CF7-E4B1-E1E0-0C81E4E57806</awsl:UniqueID>
            </awsl:Consumer>
            <awsl:Receiver>
                <awsl:ServerID>urn:uuid:1401f6a2-9835-5dfb-b017-f8cbf6aaf937</awsl:ServerID>
            </awsl:Receiver>
        </awsl:TransactionFlowLink>
        <awsse:Session TransactionStatusCode="InSeries">
            <awsse:SessionId>SessionId</awsse:SessionId>
            <awsse:SequenceNumber>3</awsse:SequenceNumber>
            <awsse:SecurityToken>SecurityToken</awsse:SecurityToken>
        </awsse:Session>
    </SOAP-ENV:Header>
    <SOAP-ENV:Body>
        <Fare_CheckRulesReply xmlns="http://xml.amadeus.com/FARQNR_07_1_1A">
            <transactionType>
                <messageFunctionDetails>
                    <messageFunction>712</messageFunction>
                </messageFunctionDetails>
            </transactionType>
            <flightDetails>
                <nbOfSegments></nbOfSegments>
                <qualificationFareDetails>
                    <fareCategories>
                        <fareType>701</fareType>
                    </fareCategories>
                    <fareDetails>
                        <qualifier>ADT</qualifier>
                        <fareCategory>XPX</fareCategory>
                    </fareDetails>
                    <additionalFareDetails>
                        <rateClass>TLY1PX1M</rateClass>
                        <fareClass>TLY1PX1M</fareClass>
                    </additionalFareDetails>
                </qualificationFareDetails>
                <transportService>
                    <companyIdentification>
                        <marketingCompany>TK</marketingCompany>
                    </companyIdentification>
                </transportService>
                <flightErrorCode>
                    <freeTextQualification>
                        <textSubjectQualifier>3</textSubjectQualifier>
                        <informationType>PTC</informationType>
                    </freeTextQualification>
                    <freeText>ADULT</freeText>
                </flightErrorCode>
                <flightErrorCode>
                    <freeTextQualification>
                        <textSubjectQualifier>3</textSubjectQualifier>
                        <informationType>FTC</informationType>
                    </freeTextQualification>
                    <freeText>INSTANT PURCHASE EXCURSION</freeText>
                </flightErrorCode>
                <productInfo>
                    <productDetails>
                        <bookingClassDetails>
                            <designator>T</designator>
                        </bookingClassDetails>
                    </productDetails>
                </productInfo>
                <fareDetailInfo>
                    <nbOfUnits>
                        <quantityDetails>
                            <numberOfUnit>1</numberOfUnit>
                            <unitQualifier>ND</unitQualifier>
                        </quantityDetails>
                    </nbOfUnits>
                    <fareDeatilInfo>
                        <fareTypeGrouping>
                            <pricingGroup>ADT</pricingGroup>
                        </fareTypeGrouping>
                    </fareDeatilInfo>
                </fareDetailInfo>
                <odiGrp>
                    <originDestination>
                        <origin>IST</origin>
                        <destination>TUN</destination>
                    </originDestination>
                </odiGrp>
                <travellerGrp>
                    <travellerIdentRef>
                        <referenceDetails>
                            <type>FC</type>
                            <value>2</value>
                        </referenceDetails>
                        <referenceDetails>
                            <type>PU</type>
                            <value>1</value>
                        </referenceDetails>
                        <referenceDetails>
                            <type>RU</type>
                            <value>PXT1</value>
                        </referenceDetails>
                    </travellerIdentRef>
                    <fareRulesDetails>
                        <tariffClassId>21</tariffClassId>
                        <ruleSectionId>(50)</ruleSectionId>
                        <ruleSectionId>(6)</ruleSectionId>
                        <ruleSectionId>(7)</ruleSectionId>
                        <ruleSectionId>(3)</ruleSectionId>
                        <ruleSectionId>(15)</ruleSectionId>
                        <ruleSectionId>(14)</ruleSectionId>
                        <ruleSectionId>(5)</ruleSectionId>
                        <ruleSectionId>(4)</ruleSectionId>
                        <ruleSectionId>(19)</ruleSectionId>
                        <ruleSectionId>(22)</ruleSectionId>
                        <ruleSectionId>(8)</ruleSectionId>
                        <ruleSectionId>(9)</ruleSectionId>
                        <ruleSectionId>(16)</ruleSectionId>
                        <ruleSectionId>(10)</ruleSectionId>
                        <ruleSectionId>(17)</ruleSectionId>
                        <ruleSectionId>(23)</ruleSectionId>
                        <ruleSectionId>(31)</ruleSectionId>
                        <ruleSectionId>(33)</ruleSectionId>
                    </fareRulesDetails>
                </travellerGrp>
                <travellerGrp>
                    <travellerIdentRef>
                        <referenceDetails>
                            <type>RU</type>
                            <value>PXT1</value>
                        </referenceDetails>
                    </travellerIdentRef>
                    <fareRulesDetails>
                        <ruleSectionId>RU</ruleSectionId>
                        <ruleSectionId>MN</ruleSectionId>
                        <ruleSectionId>MX</ruleSectionId>
                        <ruleSectionId>SE</ruleSectionId>
                        <ruleSectionId>SR</ruleSectionId>
                        <ruleSectionId>TR</ruleSectionId>
                        <ruleSectionId>AP</ruleSectionId>
                        <ruleSectionId>FL</ruleSectionId>
                        <ruleSectionId>CD</ruleSectionId>
                        <ruleSectionId>OD</ruleSectionId>
                        <ruleSectionId>SO</ruleSectionId>
                        <ruleSectionId>TF</ruleSectionId>
                        <ruleSectionId>PE</ruleSectionId>
                        <ruleSectionId>CO</ruleSectionId>
                        <ruleSectionId>HI</ruleSectionId>
                        <ruleSectionId>MD</ruleSectionId>
                        <ruleSectionId>VC</ruleSectionId>
                        <ruleSectionId>VR</ruleSectionId>
                    </fareRulesDetails>
                </travellerGrp>
                <itemGrp>
                    <itemNb>
                        <itemNumberDetails>
                            <number>1</number>
                        </itemNumberDetails>
                    </itemNb>
                    <unitGrp>
                        <nbOfUnits>
                            <quantityDetails>
                                <numberOfUnit>1</numberOfUnit>
                                <unitQualifier>PR</unitQualifier>
                            </quantityDetails>
                        </nbOfUnits>
                        <unitFareDetails>
                            <fareTypeGrouping>
                                <pricingGroup>ADT</pricingGroup>
                            </fareTypeGrouping>
                        </unitFareDetails>
                    </unitGrp>
                </itemGrp>
            </flightDetails>
        </Fare_CheckRulesReply>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>`

**Comment by AmiinosEddagh** [comment]
should i use the below example to get the rules ?
`$rulesResponse = $client->fareCheckRules(
    new FareCheckRulesOptions([
        'recommendations' => [1], //Pricing nr 1
        'categories' => ['MX', 'SE', 'SR', 'AP', 'FL', 'CD', 'SO', 'SU']
    ])
);`

**Comment by therealartz** [comment]
This is success response of `Fare_CheckRules`.

I don't know which categories you should request. It depends on you business task.

**Comment by AmiinosEddagh** [comment]
thank you for your support
