### ISSUE TITLE
regarding PNR APIS passport card & withInfant option

### ISSUE THREAD

**Issue by infernoray** [amabnl/amadeus-ws-client#258]
Hi Guys, 
I have a question regarding PNR creation  APIS passport.

1.  How can i make passport reference for Infants. because infants are depend on a adult. 
my array looks like this. adult's number is 1. how can i add APIS passport details to both?
Can u provide me example code to add both details ?
`$travllers[]= new Traveller([
            'number' => 1,
            'lastName' => 'Amaya',
            'firstName' => 'Helen',
            'travellerType' => Traveller::TRAV_TYPE_ADULT,
            'infant' => new Traveller([
                'firstName' => 'Jake',
                'lastName' => 'Sully',
                'dateOfBirth' => \DateTime::createFromFormat('Y-m-d', '2018-04-08'),
                'travellerType' => Traveller::TRAV_TYPE_INFANT,
            ])
]);`
2. When i include an infant to adult should i add object as withInfant = true ???

**Comment by therealartz** [comment]
1. When adding infant's docs set reference to adult passenger which is associated to infant:

```
'elements' => [
    new ServiceRequest([
        'type' => 'DOCS',
        'status' => ServiceRequest::STATUS_HOLD_CONFIRMED,
        'company' => 'YY',
        'quantity' => 1,
        'freeText' => [
            '----08JAN90-M--ADULT-PASSENGER
        ],
        'references' => [
            new Reference([
                'type' => Reference::TYPE_PASSENGER_TATTOO,
                'id' => 1
            ])
        ]
    ]),
    new ServiceRequest([
        'type' => 'DOCS',
        'status' => ServiceRequest::STATUS_HOLD_CONFIRMED,
        'company' => 'YY',
        'quantity' => 1,
        'freeText' => [
            '----10DEC17-M--INFANT-PASSENGER
        ],
        'references' => [
            new Reference([
                'type' => Reference::TYPE_PASSENGER_TATTOO,
                 'id' => 1
             ])
        ]
    ])
]
```

2. If you providing infant data (first name, last name, date of birth) then you set `$infant` property as in [examples](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/pnr-create-modify.rst#passengers-infants). If you don't - you may not provide information and just use `'withInfant' => true`.

**Comment by rifkydj** [comment]
thanks @therealartz . this is a big help. i can close this issue.

**Comment by infernoray** [comment]
thanks @therealartz . this is a big help. i can close this issue.
