### ISSUE TITLE
tripDetails-search

### ISSUE THREAD

**Issue by joakim-malmquist** [amabnl/amadeus-ws-client#259]
See https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/masterpricertravelboard.rst#return-flight-multiple-passengers-date-range

I try to get the date-range to work:

'date' => new MPDate([
    'rangeMode' => MPDate::RANGEMODE_MINUS_PLUS,
    'range' => 1
])

As I understand it should generate the following xml:

<timeDetails>
    <rangeOfDate>
        <rangeQualifier>C</rangeQualifier>
        <dayInterval>1</dayInterval>
    </rangeOfDate>
<timeDetails>

In the Amadeus xml, under <timeDetails> it should also be possible to use <tripDetails> instead, to search journeys with set length.

If you ara flexible with the outbound date, but want to travel exactly 7 days, the xml should look like this:

<timeDetails>
    <tripDetails>
        <flexibilityQualifier>C</flexivbilityQualifier>
        <tripInterval>1</tripInterval>
        <tripDuration>7</tripDuration>
    </tripDetails>
<timeDetails>

Is it possible to do a tripDetails-search with amadeus-ws-client?

**Comment by joakim-malmquist** [comment]
Sorry, I seem to hav problem posting code examples, I try again.

`<timeDetails>
  <rangeOfDate>
    <rangeQualifier>C</rangeQualifier>
    <dayInterval>1</dayInterval>
  </rangeOfDate>
<timeDetails>`

`<timeDetails>
  <tripDetails>
    <flexibilityQualifier>C</flexivbilityQualifier>
    <tripInterval>1</tripInterval>
    <tripDuration>7</tripDuration>
  </tripDetails>
<timeDetails>`

**Comment by therealartz** [comment]
Actually no, but this isn't a problem.

I will make pull request with this feature tomorrow.
Are you able to wait a little bit?

**Comment by joakim-malmquist** [comment]
No problem.
I can wait a week or so.

**Comment by therealartz** [comment]
@joakim-malmquist

I've contacted Amadeus support regarding this option.

Their answer:
> Currently we are not using that node.
> Sometimes, the product team designs the schema for the future version.
> It might be designed for the future versions.

Anyway I already opened pull request with this property, and in future you will be able to use it like this:

```
use Amadeus\Client\RequestOptions\Fare\MPDate;
use Amadeus\Client\RequestOptions\Fare\MPItinerary;
use Amadeus\Client\RequestOptions\Fare\MPLocation;
use Amadeus\Client\RequestOptions\Fare\MPPassenger;
use Amadeus\Client\RequestOptions\Fare\MPTripDetails;
use Amadeus\Client\RequestOptions\FareMasterPricerCalendarOptions;

new FareMasterPricerCalendarOptions([
    'nrOfRequestedPassengers' => 1,
    'passengers' => [
        new MPPassenger([
            'type' => MPPassenger::TYPE_ADULT,
            'count' => 1
        ])
    ],
    'itinerary' => [
        new MPItinerary([
            'departureLocation' => new MPLocation(['city' => 'KBP']),
            'arrivalLocation' => new MPLocation(['city' => 'JFK']),
            'date' => new MPDate([
                'date' => new \DateTime('2018-11-16T00:00:00+0000', new \DateTimeZone('UTC')),
                'rangeMode' => MPDate::RANGEMODE_MINUS_PLUS,
                'range' => 3,
                'tripDetails' => new MPTripDetails([
                    'flexibilityQualifier' => MPTripDetails::FLEXIBILITY_COMBINED,
                ])
            ])
        ])
    ]
]);
```
