### ISSUE TITLE
Fare_CheckRules  request with Fare_InformativePricingWithoutPNR

### ISSUE THREAD

**Issue by Jaymaady** [amabnl/amadeus-ws-client#26]
Hello Friend,  can i send Fare_CheckRules  request after "Fare_InformativePricingWithoutPNR"?

Can you please confirm following request flow?

      $informativePricingResponse = $client->fareInformativePricingWithoutPnr(
    new FareInformativePricingWithoutPnrOptions([
        'passengers' => [
            new Passenger([
                'tattoos' => [1, 2],
                'type' => Passenger::TYPE_ADULT
            ])
        ],
        'segments' => [
            new Segment([
                'departureDate' => \DateTime::createFromFormat('Y-m-d H:i:s', '2016-11-21 09:15:00'),
                'from' => 'BRU',
                'to' => 'LIS',
                'marketingCompany' => 'TP',
                'flightNumber' => '4652',
                'bookingClass' => 'Y',
                'segmentTattoo' => 1,
                'groupNumber' => 1
            ]),
            new Segment([
                'departureDate' => \DateTime::createFromFormat('Y-m-d H:i:s', '2016-11-28 14:20:00'),
                'from' => 'LIS',
                'to' => 'BRU',
                'marketingCompany' => 'TP',
                'flightNumber' => '3581',
                'bookingClass' => 'C',
                'segmentTattoo' => 2,
                'groupNumber' => 2
            ])
        ]
    ])
    );

After that can i send  following request?  And "recommendations" is  return  from Fare_InformativePricingWithoutPNRReply?

     use Amadeus\Client\RequestOptions\FareCheckRulesOptions;
     $rulesResponse = $client->fareCheckRules(
    new FareCheckRulesOptions([
        'recommendations' => [1] 
    ])
    );

**Comment by DerMika** [comment]
Hi, 

Yes, I believe that it should be possible to send  a `Fare_CheckRules` message following a `Fare_InformativePricingWithoutPNR` message and by providing the recommendation number of the correct pricing returned (from the node `/Fare_InformativePricingWithoutPNRReply/mainGroup/pricingGroupLevelGroup/numberOfPax/segmentControlDetails/quantity`) in the `Fare_CheckRules` message as you describe.

However, I have not tested this. So if you are in doubt, I suggest you talk to your Amadeus support contact to validate your workflow. This is something that I do not provide support for. I can only provide support to translate the Amadeus workflow you want to do to a specific implementation with this library.
