### ISSUE TITLE
How to call Fare_PricePnrWithBookingClass and fare families

### ISSUE THREAD

**Issue by darkmatus** [amabnl/amadeus-ws-client#262]
Hello,
is it possible to call Fare_PricePnrWithBookingClass and set FarePricePnrWithBookingClassOptions with FareFamilies? I can't find any thing related that helps me. Does it works as the same as at the MPrice?
And is it possible to price with a fare family given by program logic?

Thanks for your help.

**Comment by DerMika** [comment]
With the merge of #264 this is now supported. You can test it out by switching to the master branch in your composer.json.
