### ISSUE TITLE
Query: How can we add FormOfPayment in MPTB Search?

### ISSUE THREAD

**Issue by skills-up** [amabnl/amadeus-ws-client#273]
Hi,

I repeatedly get a price difference between MPTB search price and price at the time of PNR pricing, as PNR pricing takes into the account the form of payment (credit card in this case). Look like I need to specify the form of payment in the MPTB query itself to get the prices inclusive of credit card fees.

However, I failed to find corresponding option in the sample docs, as well as during code inspection. Is this option implemented in MPTB search? If yes, then could you please point me to the option name which can be used for this? If an example is available, it will be immensely helpful.

Thanks,
Gaurav

**Comment by therealartz** [comment]
In reply of `Fare_PricePNRWithBookingClass`?

**Comment by skills-up** [comment]
Yes

**Comment by therealartz** [comment]
In this repository no such option for MPTB.
You can create it by yourself and always able to open a PR :)

Or wait a few days until I will add this option.

**Comment by skills-up** [comment]
Thanks, I'll prefer to wait, as I've very little experience with this API.
Meanwhile, I've worked around with hardcoded values, as the fee applied is fixed per segment, and specific to airlines.

**Comment by therealartz** [comment]
Good.
You will be notified about updates :)

**Comment by therealartz** [comment]
Hi, 
I have created new PR. When it will be merged to `master` branch, you should do a 
`composer update amabnl/amadeus-ws-client` to get a fresh version and you will be able to use this feature.

This sample will be also added to docs:

```php
use Amadeus\Client\RequestOptions\FareMasterPricerTbSearch;
use Amadeus\Client\RequestOptions\Fare\MPItinerary;
use Amadeus\Client\RequestOptions\Fare\MPLocation;
use Amadeus\Client\RequestOptions\Fare\MPPassenger;
use Amadeus\Client\RequestOptions\Fare\MPDate;
use Amadeus\Client\RequestOptions\Fare\MasterPricer\FormOfPaymentDetails;

$opt = new FareMasterPricerTbSearch([
    'nrOfRequestedPassengers' => 1,
    'passengers' => [
        new MPPassenger([
            'type' => MPPassenger::TYPE_ADULT,
            'count' => 1
        ])
    ],
    'itinerary' => [
        new MPItinerary([
            'departureLocation' => new MPLocation(['city' => 'NYC']),
            'arrivalLocation' => new MPLocation(['city' => 'LAX']),
            'date' => new MPDate([
                'dateTime' => new \DateTime('2018-07-05T00:00:00+0000', new \DateTimeZone('UTC'))
            ]),
        ]),
    ],
    'formOfPayment' => [
        new FormOfPaymentDetails([
            'type' => FormOfPaymentDetails::TYPE_CREDIT_CARD,
            'chargedAmount' => 100,
            'creditCardNumber' => '123456'
        ])
    ]
]);
```

**Comment by DerMika** [comment]
The PR above is now merged to the master branch
