### ISSUE TITLE
Regarding DocIssuance_IssueTicket

### ISSUE THREAD

**Issue by rifkydj** [amabnl/amadeus-ws-client#275]
Hi Guys,
This Library did a great help for my booking engine project. Thanks to @DerMika & @therealartz  who helped me a lot. 
i have another questions. 

1. When i  use DocIssuance_IssueTicket message it says "PAX 0000000000 TTP/ET OK ETICKET NO PRINTERS DEFINED IN OFFICE PROFILE ".
Does this need to configure in my project or this should be done in my office id setting by contacting Amadeus?

2. In Amadeus Blue screen after ticket issuing there is a entry for get ticket as E-Ticket in email. can i get it like same way to my inbox ? if it possible how can i do it?

**Comment by therealartz** [comment]
1. Which options you use to issue ticket?
(constants from `\Amadeus\Client\RequestOptionsDocIssuanceIssueTicketOptions`)
2. Generating and sending emails must be implemented by yours application.

**Comment by rifkydj** [comment]
i used Amadeus\Client\RequestOptions\DocIssuanceIssueTicketOptions;

**Comment by therealartz** [comment]
Did you send some `*PRINT*` options in request?

**Comment by therealartz** [comment]
Ok then I guess it all depends on your office id settings

**Comment by rifkydj** [comment]
@therealartz thank you very much. i can close this issue now.
