### ISSUE TITLE
Adding OSI To Passanger & General remark

### ISSUE THREAD

**Issue by rifkydj** [amabnl/amadeus-ws-client#278]
Hi guys ,
I have 2 questions.

1. How can i send OSR elements (free text) for passangers?
2. How can i add general remark for entire PNR.  in library docs it mentions only Confidential RC confidential remark .

**Comment by rifkydj** [comment]
@therealartz im sorry. it should be OSI element.  mean free text about passenger. like this passenger is  VIP COMPANY CEO. etc...
This is the entry in blue screen.
`Create an OSI element OS QF VIP COMPANY CEO/P2`
`Create an OSI for specified passengers OS KL TEXT/P1,3-6 `. 
can i do this?

**Comment by therealartz** [comment]
```php
$osiElement = new \Amadeus\Client\RequestOptions\Pnr\Element\OtherServiceInfo([
    'airline' => 'AA',
    'freeText' => 'free text',
    'references' => [
        new Reference([
            'type' => Reference::TYPE_PASSENGER_REQUEST,
            'id' => 1,
        ]),
    ],
]);
```

**Comment by rifkydj** [comment]
thanks @therealartz , this will be a great help.

**Comment by rifkydj** [comment]
@therealartz  please add this info to the Samples for specific PNR Creation / modification scenario's Docs & this will useful for some 1.
