### ISSUE TITLE
Regarding PNR Retrieve by office Id & last name

### ISSUE THREAD

**Issue by rifkydj** [amabnl/amadeus-ws-client#280]
Hi guys,
I have encountered a problem when i use PNR Retrieve using below code.

`use Amadeus\Client\RequestOptions\PnrRetrieveOptions;
$pnrContent = $client->pnrRetrieve(new PnrRetrieveOptions([
    'officeId' => 'MIA1S213F',
    'lastName' => 'childs'
]));`

When use this the response comes as 
`{"status":"OK","messages":[],"response":null,"responseXml":null}`

But the xml comes correctly. What will be the error Guys. ???

**Comment by therealartz** [comment]
Could you please provide response XML log?

**Comment by rifkydj** [comment]
Sure

**Comment by rifkydj** [comment]
[Pnr Search.txt](https://github.com/amabnl/amadeus-ws-client/files/2681245/Pnr.Search.txt)

**Comment by DerMika** [comment]
Response XML isn't null in this case... Which PHP version are you running?

**Comment by rifkydj** [comment]
PHP Version 7.2.4 on Nginx server.

**Comment by therealartz** [comment]
Unfortunately I don't have idea.
It is something going wrong inside `SoapClient`.

As a fast and dirty workaround you can call this to get response object and work with it like with others:

`$responseObject = json_decode(json_encode(simplexml_load_string($result->responseXml)))`;

**Comment by rifkydj** [comment]
yes im currently using same method. and i always appreciate your help. i can close this issue..
