### ISSUE TITLE
We are getting high price rate compare to others flight booking agency although they are using Same API  

### ISSUE THREAD

**Issue by najmulcse** [amabnl/amadeus-ws-client#281]
We are using Amadeus API, But we are getting the high price compare to other flight booking site. How can we get base price rate from Amadues using Fare_MasterPricerTravelBoardSearch? 

Please help me.

**Comment by rifkydj** [comment]
This is something regarding your office ID. Please Check that with your amadeus agent.

**Comment by DerMika** [comment]
Many travel agents will negotiate special fares with airlines, meaning they will get different content when calling master pricer (look for negotiated fares, unifares, corporate contracts,...)

This is something for the travel agency to arrange and beyond the scope of this library.

**Comment by najmulcse** [comment]
Thanks
