### ISSUE TITLE
Error 10609  MANDATORY SSRFOID MISSING FOR CARRIER

### ISSUE THREAD

**Issue by troitskyA** [amabnl/amadeus-ws-client#282]
We receive next error for some of carriers while issuing tickets:
10609  MANDATORY SSRFOID MISSING FOR CARRIER

We found that some companies need SR FOID MU HK1-PP12345678/P1 like command to alternatively add passenger data. Is it possible to do that by amadeus-ws-client now? I did not found any mentions of FOID in this repository except https://github.com/amabnl/amadeus-ws-client/blob/6ad41e1c9df340ce03e92c475e73f08a1b8db121/src/Amadeus/Client/ResponseHandler/Air/HandlerRetrieveSeatMap.php

**Comment by DerMika** [comment]
You need this: https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/pnr-create-modify.rst#special-service-requests-sr

Type of the SSR is "FOID" in this case.

**Comment by valerion1** [comment]
@DerMika i try to use "FOID" in request from link, but i got error `8110 element INVALID SSR`. Can you help me?

**Comment by troitskyA** [comment]
@DerMika Can you please help with this issue?

**Comment by DerMika** [comment]
You'd better ask Amadeus Support how you should send the SSRFOID to Amadeus in order to achieve what it is you want to achieve.

After you have that information, I'll be able to help you how to do that using this library. 

It may depend on the specific requirements the airline has and that's beyond the scope of this library.

**Comment by valerion1** [comment]
@DerMika Amadeus support answered that in amadeus console the request for add ssr should look like this
`SR FOID IB HK1-PP12345678/P1`

if I understand correctly, we need to send in the following format the passenger documents data:
`HK1-PP12345678`

maybe you can suggest something?

**Comment by troitskyA** [comment]
Hello, @DerMika. Can you please help us with this issue?

**Comment by DerMika** [comment]
Hi, sorry for the delay, looking into it right now.

**Comment by DerMika** [comment]
So the element to add to the PNR is probably this: 

```php
use Amadeus\Client\RequestOptions\Pnr\Element\ServiceRequest;
use Amadeus\Client\RequestOptions\Pnr\Reference;

new ServiceRequest([
    'status' => 'HK',
    'type' => 'FOID',
    'company' => 'IB',
    'freeText' => 'PP12345678',
    'references' => [
        new Reference([
            'type' => Reference::TYPE_PASSENGER_REQUEST,
            'id' => 1
        ])
    ]
])
```
depending on your usecase, you could need either `TYPE_PASSENGER_REQUEST` or `TYPE_PASSENGER_TATTOO`.

**Comment by DerMika** [comment]
Closing due to lack of feedback. you can re-open if needed
