### ISSUE TITLE
TourCode on pricing 

### ISSUE THREAD

**Issue by baraayyash** [amabnl/amadeus-ws-client#284]
Hi, 

i need to price a PNR using a tourCode, is this available in the library?

if not, how i can go around it? 

Thanks,
Baraa

**Comment by therealartz** [comment]
Hi! I guess it handled automatically by Amadeus when PNR has related element with tour code.

**Comment by DerMika** [comment]
Given you sent a pull request (#283), I assume you figured it out? 

Closing this issue

**Comment by baraayyash** [comment]
Hi @DerMika, 

actually no, it didn't work.. i am using PnrCreatePnrOptions class, and here how i add the tourCode

`        $createPnrOptions->elements[] = new TourCode([
            'passengerType' => TourCode::PAX_PASSENGER,
            'freeText' => 'fxp/r,@#%@#'
        ]);
`

And here the request payload : 

`<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://xml.amadeus.com/PNRADD_15_1_1A" xmlns:ns2="http://www.w3.org/2005/08/addressing" xmlns:ns3="http://xml.amadeus.com/2010/06/Session_v3"><SOAP-ENV:Header><ns2:MessageID>B745A6A5-FE43-64C0-B514-77789C84C7A8</ns2:MessageID><ns2:Action>http://webservices.amadeus.com/PNRADD_15_1_1A</ns2:Action><ns2:To>https://nodeD1.test.webservices.amadeus.com/1ASIWHTMQFY</ns2:To><ns3:Session TransactionStatusCode="InSeries"><ns3:SessionId>00MDFROPKQ</ns3:SessionId><ns3:SequenceNumber>2</ns3:SequenceNumber><ns3:SecurityToken>4SULX1DER7S11TOMZRLG006SX</ns3:SecurityToken></ns3:Session></SOAP-ENV:Header><SOAP-ENV:Body><ns1:PNR_AddMultiElements><ns1:pnrActions><ns1:optionCode>0</ns1:optionCode></ns1:pnrActions><ns1:travellerInfo><ns1:elementManagementPassenger><ns1:reference><ns1:qualifier>PR</ns1:qualifier><ns1:number>1</ns1:number></ns1:reference><ns1:segmentName>NM</ns1:segmentName></ns1:elementManagementPassenger><ns1:passengerData><ns1:travellerInformation><ns1:traveller><ns1:surname>Baraaa</ns1:surname></ns1:traveller><ns1:passenger><ns1:firstName>Baraaa</ns1:firstName><ns1:type>ADT</ns1:type></ns1:passenger></ns1:travellerInformation></ns1:passengerData></ns1:travellerInfo><ns1:dataElementsMaster><ns1:marker1/><ns1:dataElementsIndiv><ns1:elementManagementData><ns1:reference><ns1:qualifier>OT</ns1:qualifier><ns1:number>1</ns1:number></ns1:reference><ns1:segmentName>SSR</ns1:segmentName></ns1:elementManagementData><ns1:serviceRequest><ns1:ssr><ns1:type>DOCS</ns1:type><ns1:status>HK</ns1:status><ns1:quantity>1</ns1:quantity><ns1:companyId>TK</ns1:companyId><ns1:freetext>P-SA-1031210115789-SA-11SEP93-M-22SEP21-Baraaa-Baraaa-Ayyaash</ns1:freetext></ns1:ssr></ns1:serviceRequest><ns1:referenceForDataElement><ns1:reference><ns1:qualifier>PR</ns1:qualifier><ns1:number>1</ns1:number></ns1:reference></ns1:referenceForDataElement></ns1:dataElementsIndiv><ns1:dataElementsIndiv><ns1:elementManagementData><ns1:reference><ns1:qualifier>OT</ns1:qualifier><ns1:number>2</ns1:number></ns1:reference><ns1:segmentName>FT</ns1:segmentName></ns1:elementManagementData><ns1:tourCode><ns1:passengerType>PAX</ns1:passengerType><ns1:freeFormatTour><ns1:indicator>FF</ns1:indicator><ns1:freetext>fxp/r,@#%@#</ns1:freetext></ns1:freeFormatTour></ns1:tourCode></ns1:dataElementsIndiv><ns1:dataElementsIndiv><ns1:elementManagementData><ns1:reference><ns1:qualifier>OT</ns1:qualifier><ns1:number>3</ns1:number></ns1:reference><ns1:segmentName>TK</ns1:segmentName></ns1:elementManagementData><ns1:ticketElement><ns1:passengerType>PAX</ns1:passengerType><ns1:ticket><ns1:indicator>OK</ns1:indicator></ns1:ticket></ns1:ticketElement></ns1:dataElementsIndiv><ns1:dataElementsIndiv><ns1:elementManagementData><ns1:reference><ns1:qualifier>OT</ns1:qualifier><ns1:number>4</ns1:number></ns1:reference><ns1:segmentName>AP</ns1:segmentName></ns1:elementManagementData><ns1:freetextData><ns1:freetextDetail><ns1:subjectQualifier>3</ns1:subjectQualifier><ns1:type>7</ns1:type></ns1:freetextDetail><ns1:longFreetext>52101413641</ns1:longFreetext></ns1:freetextData></ns1:dataElementsIndiv><ns1:dataElementsIndiv><ns1:elementManagementData><ns1:reference><ns1:qualifier>OT</ns1:qualifier><ns1:number>5</ns1:number></ns1:reference><ns1:segmentName>AP</ns1:segmentName></ns1:elementManagementData><ns1:freetextData><ns1:freetextDetail><ns1:subjectQualifier>3</ns1:subjectQualifier><ns1:type>P02</ns1:type></ns1:freetextDetail><ns1:longFreetext>al11317@gmail.com</ns1:longFreetext></ns1:freetextData></ns1:dataElementsIndiv><ns1:dataElementsIndiv><ns1:elementManagementData><ns1:reference><ns1:qualifier>OT</ns1:qualifier><ns1:number>7</ns1:number></ns1:reference><ns1:segmentName>RF</ns1:segmentName></ns1:elementManagementData><ns1:freetextData><ns1:freetextDetail><ns1:subjectQualifier>3</ns1:subjectQualifier><ns1:type>P22</ns1:type></ns1:freetextDetail><ns1:longFreetext>Laravel amabnl-amadeus-ws-client-1.7.1</ns1:longFreetext></ns1:freetextData></ns1:dataElementsIndiv></ns1:dataElementsMaster></ns1:PNR_AddMultiElements></SOAP-ENV:Body></SOAP-ENV:Envelope>
`

but the tourCode was not applied on the price.. i mean the ticket were issued with the normal price. How i can know what is the issue? 

Thanks,
Baraa
