### ISSUE TITLE
INVALID FARE when ticketCreateTSTFromPricing for two adults

### ISSUE THREAD

**Issue by baraayyash** [amabnl/amadeus-ws-client#285]
Hi, 

i have an issue when trying to send ticketCreateTSTFromPricing request for two adults, its working fine for one adult! 

this is what i get from `Ticket_CreateTSTFromPricingReply` request:

`<Ticket_CreateTSTFromPricingReply xmlns="http://xml.amadeus.com/TAUTCR_04_1_1A"><applicationError><applicationErrorInfo><applicationErrorDetail><applicationErrorCode>2063</applicationErrorCode><codeListQualifier>EC</codeListQualifier><codeListResponsibleAgency>1A</codeListResponsibleAgency></applicationErrorDetail></applicationErrorInfo><errorText><errorFreeText>INVALID FARE</errorFreeText></errorText></applicationError></Ticket_CreateTSTFromPricingReply>  `

this is the response for `pnrCreatePnr` request : 

`<?xml version="1.0" encoding="UTF-8"?>
<PNR_Reply xmlns="http://xml.amadeus.com/PNRACC_15_1_1A">
   <pnrHeader>
      <reservationInfo>
         <reservation>
            <companyId>1A</companyId>
         </reservation>
      </reservationInfo>
   </pnrHeader>
   <securityInformation>
      <responsibilityInformation>
         <typeOfPnrElement>RP</typeOfPnrElement>
         <officeId>QCAS228WD</officeId>
         <iataCode>71221216</iataCode>
      </responsibilityInformation>
      <queueingInformation>
         <queueingOfficeId>QCAS228WD</queueingOfficeId>
      </queueingInformation>
      <cityCode>QCA</cityCode>
   </securityInformation>
   <freetextData>
      <freetextDetail>
         <subjectQualifier>3</subjectQualifier>
         <type>P12</type>
      </freetextDetail>
      <longFreetext>--- SFP ---</longFreetext>
   </freetextData>
   <pnrHeaderTag>
      <statusInformation>
         <indicator>SFP</indicator>
      </statusInformation>
   </pnrHeaderTag>
   <sbrPOSDetails>
      <sbrUserIdentificationOwn>
         <originIdentification>
            <inHouseIdentification1 />
         </originIdentification>
      </sbrUserIdentificationOwn>
      <sbrSystemDetails>
         <deliveringSystem>
            <companyId />
         </deliveringSystem>
      </sbrSystemDetails>
      <sbrPreferences>
         <userPreferences>
            <codedCountry />
         </userPreferences>
      </sbrPreferences>
   </sbrPOSDetails>
   <sbrCreationPosDetails>
      <sbrUserIdentificationOwn>
         <originIdentification>
            <inHouseIdentification1 />
         </originIdentification>
      </sbrUserIdentificationOwn>
      <sbrSystemDetails>
         <deliveringSystem>
            <companyId />
         </deliveringSystem>
      </sbrSystemDetails>
      <sbrPreferences>
         <userPreferences>
            <codedCountry />
         </userPreferences>
      </sbrPreferences>
   </sbrCreationPosDetails>
   <sbrUpdatorPosDetails>
      <sbrUserIdentificationOwn>
         <originIdentification>
            <originatorId>71221216</originatorId>
            <inHouseIdentification1>QCAS228WD</inHouseIdentification1>
         </originIdentification>
         <originatorTypeCode>T</originatorTypeCode>
      </sbrUserIdentificationOwn>
      <sbrSystemDetails>
         <deliveringSystem>
            <companyId>1A</companyId>
            <locationId>QCA</locationId>
         </deliveringSystem>
      </sbrSystemDetails>
      <sbrPreferences>
         <userPreferences>
            <codedCountry>SA</codedCountry>
         </userPreferences>
      </sbrPreferences>
   </sbrUpdatorPosDetails>
   <travellerInfo>
      <elementManagementPassenger>
         <reference>
            <qualifier>PT</qualifier>
            <number>3</number>
         </reference>
         <segmentName>NM</segmentName>
         <lineNumber>1</lineNumber>
      </elementManagementPassenger>
      <passengerData>
         <travellerInformation>
            <traveller>
               <surname>ABUAYYASH</surname>
               <quantity>1</quantity>
            </traveller>
            <passenger>
               <firstName>AHMAD</firstName>
               <type>ADT</type>
            </passenger>
         </travellerInformation>
      </passengerData>
      <enhancedPassengerData>
         <enhancedTravellerInformation>
            <travellerNameInfo>
               <quantity>1</quantity>
               <type>ADT</type>
            </travellerNameInfo>
            <otherPaxNamesDetails>
               <nameType>UN</nameType>
               <referenceName>Y</referenceName>
               <displayedName>Y</displayedName>
               <surname>ABUAYYASH</surname>
               <givenName>AHMAD</givenName>
            </otherPaxNamesDetails>
         </enhancedTravellerInformation>
      </enhancedPassengerData>
   </travellerInfo>
   <travellerInfo>
      <elementManagementPassenger>
         <reference>
            <qualifier>PT</qualifier>
            <number>2</number>
         </reference>
         <segmentName>NM</segmentName>
         <lineNumber>2</lineNumber>
      </elementManagementPassenger>
      <passengerData>
         <travellerInformation>
            <traveller>
               <surname>ABUAYYASH</surname>
               <quantity>1</quantity>
            </traveller>
            <passenger>
               <firstName>IBRAHIM</firstName>
               <type>ADT</type>
            </passenger>
         </travellerInformation>
      </passengerData>
      <enhancedPassengerData>
         <enhancedTravellerInformation>
            <travellerNameInfo>
               <quantity>1</quantity>
               <type>ADT</type>
            </travellerNameInfo>
            <otherPaxNamesDetails>
               <nameType>UN</nameType>
               <referenceName>Y</referenceName>
               <displayedName>Y</displayedName>
               <surname>ABUAYYASH</surname>
               <givenName>IBRAHIM</givenName>
            </otherPaxNamesDetails>
         </enhancedTravellerInformation>
      </enhancedPassengerData>
   </travellerInfo>
   <originDestinationDetails>
      <originDestination />
      <itineraryInfo>
         <elementManagementItinerary>
            <reference>
               <qualifier>ST</qualifier>
               <number>1</number>
            </reference>
            <segmentName>AIR</segmentName>
            <lineNumber>3</lineNumber>
         </elementManagementItinerary>
         <travelProduct>
            <product>
               <depDate>110119</depDate>
               <depTime>1300</depTime>
               <arrDate>110119</arrDate>
               <arrTime>1605</arrTime>
            </product>
            <boardpointDetail>
               <cityCode>AMM</cityCode>
            </boardpointDetail>
            <offpointDetail>
               <cityCode>JED</cityCode>
            </offpointDetail>
            <companyDetail>
               <identification>SV</identification>
            </companyDetail>
            <productDetails>
               <identification>632</identification>
               <classOfService>T</classOfService>
            </productDetails>
            <typeDetail>
               <detail>ET</detail>
            </typeDetail>
         </travelProduct>
         <itineraryMessageAction>
            <business>
               <function>1</function>
            </business>
         </itineraryMessageAction>
         <relatedProduct>
            <quantity>2</quantity>
            <status>HK</status>
         </relatedProduct>
         <elementsIndicators>
            <statusInformation>
               <indicator>TSA</indicator>
            </statusInformation>
         </elementsIndicators>
         <flightDetail>
            <productDetails>
               <equipment>321</equipment>
               <numOfStops>0</numOfStops>
               <weekDay>5</weekDay>
            </productDetails>
            <arrivalStationInfo>
               <terminal>S</terminal>
            </arrivalStationInfo>
            <facilities>
               <entertainement>M</entertainement>
            </facilities>
         </flightDetail>
         <selectionDetails>
            <selection>
               <option>P2</option>
            </selection>
         </selectionDetails>
         <itineraryfreeFormText>
            <freeTextQualification>
               <textSubjectQualifier>3</textSubjectQualifier>
            </freeTextQualification>
            <freeText>MAX CONNECTION TIME IS 12 HRS</freeText>
            <freeText>KSA LAW REQD FULL APIS IN SSR DOCS 72 HBD</freeText>
            <freeText>VISA REQUIRED FOR DOUBLE DOMESTIC STOPOVER PAX</freeText>
            <freeText>SEE RTSVC</freeText>
         </itineraryfreeFormText>
         <markerRailTour />
      </itineraryInfo>
   </originDestinationDetails>
   <dataElementsMaster>
      <marker2 />
      <dataElementsIndiv>
         <elementManagementData>
            <segmentName>RF</segmentName>
         </elementManagementData>
         <otherDataFreetext>
            <freetextDetail>
               <subjectQualifier>3</subjectQualifier>
               <type>P22</type>
            </freetextDetail>
            <longFreetext>LARAVEL AMABNL-AMADEUS-WS-CLIENT-1.7.1-NMC-SAUDI/WSQFYHTM</longFreetext>
         </otherDataFreetext>
      </dataElementsIndiv>
      <dataElementsIndiv>
         <elementManagementData>
            <reference>
               <qualifier>OT</qualifier>
               <number>4</number>
            </reference>
            <segmentName>AP</segmentName>
            <lineNumber>4</lineNumber>
         </elementManagementData>
         <otherDataFreetext>
            <freetextDetail>
               <subjectQualifier>3</subjectQualifier>
               <type>P02</type>
            </freetextDetail>
            <longFreetext>ABU_AY4SH1978YAHOO.COM</longFreetext>
         </otherDataFreetext>
      </dataElementsIndiv>
      <dataElementsIndiv>
         <elementManagementData>
            <reference>
               <qualifier>OT</qualifier>
               <number>3</number>
            </reference>
            <segmentName>AP</segmentName>
            <lineNumber>5</lineNumber>
         </elementManagementData>
         <otherDataFreetext>
            <freetextDetail>
               <subjectQualifier>3</subjectQualifier>
               <type>7</type>
            </freetextDetail>
            <longFreetext>966506047052</longFreetext>
         </otherDataFreetext>
      </dataElementsIndiv>
      <dataElementsIndiv>
         <elementManagementData>
            <reference>
               <qualifier>OT</qualifier>
               <number>7</number>
            </reference>
            <segmentName>TK</segmentName>
            <lineNumber>6</lineNumber>
         </elementManagementData>
         <ticketElement>
            <passengerType>PAX</passengerType>
            <ticket>
               <indicator>OK</indicator>
               <date>090119</date>
               <officeId>QCAS228WD</officeId>
            </ticket>
         </ticketElement>
      </dataElementsIndiv>
      <dataElementsIndiv>
         <elementManagementData>
            <reference>
               <qualifier>OT</qualifier>
               <number>5</number>
            </reference>
            <segmentName>SSR</segmentName>
            <lineNumber>7</lineNumber>
         </elementManagementData>
         <serviceRequest>
            <ssr>
               <type>DOCS</type>
               <status>HK</status>
               <quantity>1</quantity>
               <companyId>SV</companyId>
               <freeText>P/SA/89070/SA/26AUG78/M/21APR93/ABUAYYASH/IBRAHIM/BADER</freeText>
            </ssr>
         </serviceRequest>
         <referenceForDataElement>
            <reference>
               <qualifier>PT</qualifier>
               <number>2</number>
            </reference>
         </referenceForDataElement>
      </dataElementsIndiv>
      <dataElementsIndiv>
         <elementManagementData>
            <reference>
               <qualifier>OT</qualifier>
               <number>6</number>
            </reference>
            <segmentName>SSR</segmentName>
            <lineNumber>8</lineNumber>
         </elementManagementData>
         <serviceRequest>
            <ssr>
               <type>DOCS</type>
               <status>HK</status>
               <quantity>1</quantity>
               <companyId>SV</companyId>
               <freeText>P/SA/89010/SA/26AUG78/M/21APR19/ABUAYYASH/AHMAD/BADER</freeText>
            </ssr>
         </serviceRequest>
         <referenceForDataElement>
            <reference>
               <qualifier>PT</qualifier>
               <number>3</number>
            </reference>
         </referenceForDataElement>
      </dataElementsIndiv>
   </dataElementsMaster>
</PNR_Reply>`

`Fare_PricePNRWithBookingClassReply` request response : 

`<?xml version="1.0" encoding="UTF-8"?>
<Fare_PricePNRWithBookingClassReply xmlns="http://xml.amadeus.com/TPCBRR_16_1_1A">
   <fareList>
      <pricingInformation>
         <tstInformation>
            <tstIndicator>I</tstIndicator>
         </tstInformation>
         <fcmi>0</fcmi>
      </pricingInformation>
      <fareReference>
         <referenceType>TST</referenceType>
         <uniqueReference>1</uniqueReference>
      </fareReference>
      <lastTktDate>
         <businessSemantic>LT</businessSemantic>
         <dateTime>
            <year>2019</year>
            <month>1</month>
            <day>11</day>
         </dateTime>
      </lastTktDate>
      <validatingCarrier>
         <carrierInformation>
            <carrierCode>SV</carrierCode>
         </carrierInformation>
      </validatingCarrier>
      <paxSegReference>
         <refDetails>
            <refQualifier>PA</refQualifier>
            <refNumber>3</refNumber>
         </refDetails>
         <refDetails>
            <refQualifier>PA</refQualifier>
            <refNumber>2</refNumber>
         </refDetails>
      </paxSegReference>
      <fareDataInformation>
         <fareDataMainInformation>
            <fareDataQualifier>F</fareDataQualifier>
         </fareDataMainInformation>
         <fareDataSupInformation>
            <fareDataQualifier>B</fareDataQualifier>
            <fareAmount>150.00</fareAmount>
            <fareCurrency>JOD</fareCurrency>
         </fareDataSupInformation>
         <fareDataSupInformation>
            <fareDataQualifier>E</fareDataQualifier>
            <fareAmount>795.00</fareAmount>
            <fareCurrency>SAR</fareCurrency>
         </fareDataSupInformation>
         <fareDataSupInformation>
            <fareDataQualifier>712</fareDataQualifier>
            <fareAmount>1166.00</fareAmount>
            <fareCurrency>SAR</fareCurrency>
         </fareDataSupInformation>
      </fareDataInformation>
      <taxInformation>
         <taxDetails>
            <taxQualifier>7</taxQualifier>
            <taxIdentification>
               <taxIdentifier>X</taxIdentifier>
            </taxIdentification>
            <taxType>
               <isoCountry>E3</isoCountry>
            </taxType>
            <taxNature>SE</taxNature>
         </taxDetails>
         <amountDetails>
            <fareDataMainInformation>
               <fareDataQualifier>TAX</fareDataQualifier>
               <fareAmount>8.00</fareAmount>
               <fareCurrency>SAR</fareCurrency>
            </fareDataMainInformation>
         </amountDetails>
      </taxInformation>
      <taxInformation>
         <taxDetails>
            <taxQualifier>7</taxQualifier>
            <taxIdentification>
               <taxIdentifier>X</taxIdentifier>
            </taxIdentification>
            <taxType>
               <isoCountry>IO</isoCountry>
            </taxType>
            <taxNature>VZ</taxNature>
         </taxDetails>
         <amountDetails>
            <fareDataMainInformation>
               <fareDataQualifier>TAX</fareDataQualifier>
               <fareAmount>87.00</fareAmount>
               <fareCurrency>SAR</fareCurrency>
            </fareDataMainInformation>
         </amountDetails>
      </taxInformation>
      <taxInformation>
         <taxDetails>
            <taxQualifier>7</taxQualifier>
            <taxIdentification>
               <taxIdentifier>X</taxIdentifier>
            </taxIdentification>
            <taxType>
               <isoCountry>D9</isoCountry>
            </taxType>
            <taxNature>DP</taxNature>
         </taxDetails>
         <amountDetails>
            <fareDataMainInformation>
               <fareDataQualifier>TAX</fareDataQualifier>
               <fareAmount>11.00</fareAmount>
               <fareCurrency>SAR</fareCurrency>
            </fareDataMainInformation>
         </amountDetails>
      </taxInformation>
      <taxInformation>
         <taxDetails>
            <taxQualifier>7</taxQualifier>
            <taxIdentification>
               <taxIdentifier>X</taxIdentifier>
            </taxIdentification>
            <taxType>
               <isoCountry>HQ</isoCountry>
            </taxType>
            <taxNature>AE</taxNature>
         </taxDetails>
         <amountDetails>
            <fareDataMainInformation>
               <fareDataQualifier>TAX</fareDataQualifier>
               <fareAmount>212.00</fareAmount>
               <fareCurrency>SAR</fareCurrency>
            </fareDataMainInformation>
         </amountDetails>
      </taxInformation>
      <taxInformation>
         <taxDetails>
            <taxQualifier>7</taxQualifier>
            <taxIdentification>
               <taxIdentifier>X</taxIdentifier>
            </taxIdentification>
            <taxType>
               <isoCountry>NH</isoCountry>
            </taxType>
            <taxNature>TA</taxNature>
         </taxDetails>
         <amountDetails>
            <fareDataMainInformation>
               <fareDataQualifier>TAX</fareDataQualifier>
               <fareAmount>53.00</fareAmount>
               <fareCurrency>SAR</fareCurrency>
            </fareDataMainInformation>
         </amountDetails>
      </taxInformation>
      <bankerRates>
         <firstRateDetail>
            <amount>5.297602</amount>
         </firstRateDetail>
      </bankerRates>
      <originDestination>
         <cityCode>AMM</cityCode>
         <cityCode>JED</cityCode>
      </originDestination>
      <segmentInformation>
         <connexInformation>
            <connecDetails>
               <connexType>O</connexType>
            </connecDetails>
         </connexInformation>
         <segDetails>
            <segmentDetail>
               <identification>AIR</identification>
               <classOfService>T</classOfService>
            </segmentDetail>
         </segDetails>
         <fareQualifier>
            <fareBasisDetails>
               <primaryCode>TOW</primaryCode>
               <fareBasisCode>JO</fareBasisCode>
               <discTktDesignator>ADT</discTktDesignator>
            </fareBasisDetails>
         </fareQualifier>
         <validityInformation>
            <businessSemantic>A</businessSemantic>
            <dateTime>
               <year>2019</year>
               <month>1</month>
               <day>11</day>
            </dateTime>
         </validityInformation>
         <validityInformation>
            <businessSemantic>B</businessSemantic>
            <dateTime>
               <year>2019</year>
               <month>1</month>
               <day>11</day>
            </dateTime>
         </validityInformation>
         <bagAllowanceInformation>
            <bagAllowanceDetails>
               <baggageQuantity>2</baggageQuantity>
               <baggageType>N</baggageType>
            </bagAllowanceDetails>
         </bagAllowanceInformation>
         <segmentReference>
            <refDetails>
               <refQualifier>S</refQualifier>
               <refNumber>1</refNumber>
            </refDetails>
         </segmentReference>
         <sequenceInformation>
            <sequenceSection>
               <sequenceNumber>1</sequenceNumber>
            </sequenceSection>
         </sequenceInformation>
      </segmentInformation>
      <otherPricingInfo>
         <attributeDetails>
            <attributeType>END</attributeType>
            <attributeDescription>TKT VALD 1Y FRM ISSUE DATE</attributeDescription>
         </attributeDetails>
         <attributeDetails>
            <attributeType>FCA</attributeType>
            <attributeDescription>AMM SV JED211.56NUC211.56END ROE0.709000</attributeDescription>
         </attributeDetails>
      </otherPricingInfo>
      <warningInformation>
         <warningCode>
            <applicationErrorDetail>
               <applicationErrorCode>PEN</applicationErrorCode>
               <codeListQualifier>WEC</codeListQualifier>
               <codeListResponsibleAgency>1A</codeListResponsibleAgency>
            </applicationErrorDetail>
         </warningCode>
         <warningText>
            <errorFreeText>PENALTY APPLIES</errorFreeText>
         </warningText>
      </warningInformation>
      <warningInformation>
         <warningCode>
            <applicationErrorDetail>
               <applicationErrorCode>LTD</applicationErrorCode>
               <codeListQualifier>WEC</codeListQualifier>
               <codeListResponsibleAgency>1A</codeListResponsibleAgency>
            </applicationErrorDetail>
         </warningCode>
         <warningText>
            <errorFreeText>- DATE OF ORIGIN</errorFreeText>
         </warningText>
      </warningInformation>
      <warningInformation>
         <warningCode>
            <applicationErrorDetail>
               <applicationErrorCode>0</applicationErrorCode>
               <codeListQualifier>WEC</codeListQualifier>
               <codeListResponsibleAgency>1A</codeListResponsibleAgency>
            </applicationErrorDetail>
         </warningCode>
         <warningText>
            <errorFreeText>FARE VALID FOR E TICKET ONLY</errorFreeText>
         </warningText>
      </warningInformation>
      <warningInformation>
         <warningCode>
            <applicationErrorDetail>
               <applicationErrorCode>0</applicationErrorCode>
               <codeListQualifier>WEC</codeListQualifier>
               <codeListResponsibleAgency>1A</codeListResponsibleAgency>
            </applicationErrorDetail>
         </warningCode>
         <warningText>
            <errorFreeText>BAG/SEAT/SERVICES AT A CHARGE MAY BE AVAILABLE-ENTER FXK</errorFreeText>
         </warningText>
      </warningInformation>
      <warningInformation>
         <warningCode>
            <applicationErrorDetail>
               <applicationErrorCode>0</applicationErrorCode>
               <codeListQualifier>WEC</codeListQualifier>
               <codeListResponsibleAgency>1A</codeListResponsibleAgency>
            </applicationErrorDetail>
         </warningCode>
         <warningText>
            <errorFreeText>TICKET STOCK RESTRICTION</errorFreeText>
         </warningText>
      </warningInformation>
      <warningInformation>
         <warningCode>
            <applicationErrorDetail>
               <applicationErrorCode>0</applicationErrorCode>
               <codeListQualifier>WEC</codeListQualifier>
               <codeListResponsibleAgency>1A</codeListResponsibleAgency>
            </applicationErrorDetail>
         </warningCode>
         <warningText>
            <errorFreeText>BG CXR: SV</errorFreeText>
         </warningText>
      </warningInformation>
      <warningInformation>
         <warningCode>
            <applicationErrorDetail>
               <applicationErrorCode>0</applicationErrorCode>
               <codeListQualifier>WEC</codeListQualifier>
               <codeListResponsibleAgency>1A</codeListResponsibleAgency>
            </applicationErrorDetail>
         </warningCode>
         <warningText>
            <errorFreeText>PRICED WITH VALIDATING CARRIER SV - REPRICE IF DIFFERENT VC</errorFreeText>
         </warningText>
      </warningInformation>
      <fareComponentDetailsGroup>
         <fareComponentID>
            <itemNumberDetails>
               <number>1</number>
               <type>FC</type>
            </itemNumberDetails>
         </fareComponentID>
         <marketFareComponent>
            <boardPointDetails>
               <trueLocationId>AMM</trueLocationId>
            </boardPointDetails>
            <offpointDetails>
               <trueLocationId>JED</trueLocationId>
            </offpointDetails>
         </marketFareComponent>
         <monetaryInformation>
            <monetaryDetails>
               <typeQualifier>TFC</typeQualifier>
               <amount>211.56</amount>
               <currency>NUC</currency>
            </monetaryDetails>
         </monetaryInformation>
         <componentClassInfo>
            <fareBasisDetails>
               <rateTariffClass>TOWJO</rateTariffClass>
            </fareBasisDetails>
         </componentClassInfo>
         <fareQualifiersDetail>
            <discountDetails>
               <fareQualifier>756</fareQualifier>
            </discountDetails>
         </fareQualifiersDetail>
         <couponDetailsGroup>
            <productId>
               <referenceDetails>
                  <type>ST</type>
                  <value>1</value>
               </referenceDetails>
            </productId>
         </couponDetailsGroup>
      </fareComponentDetailsGroup>
      <endFareList />
   </fareList>
</Fare_PricePNRWithBookingClassReply>`

am i doing something wrong? 

Thanks !

**Comment by therealartz** [comment]
Which options you send in `Ticket_CreateTSTFromPricing` request?

**Comment by baraayyash** [comment]
i am using this code : 

`		return $this->client->ticketCreateTSTFromPricing(
            new TicketCreateTstFromPricingOptions([
                'pricings' => $pricings
            ])
        );
`

when dumping `$pricing` 

`[
    {
        "tstNumber": 1,
        "tsmNumber": null,
        "passengerReferences": []
    },
    {
        "tstNumber": 2,
        "tsmNumber": null,
        "passengerReferences": []
    }
]`

**Comment by therealartz** [comment]
Ok, first, you can see your request logs when using some logger instance.

Second, you have only one TST which is clearly seen in `Fare_PricePNRWithBookingClassReply`. The TST is one per each passenger type. E.g. if you had adult and children, then you have TST 1 and TST 2. In your current case there only 1 TST.
Your correct pricing options:
```php
$pricings = [
    new Pricing([
        'tstNumber' => 1,
    ]),
];

$opt = new TicketCreateTstFromPricingOptions([
    'pricings' => $pricings,
]);
```

**Comment by baraayyash** [comment]
Many thanks! its working now.
