### ISSUE TITLE
 Flight Booking

### ISSUE THREAD

**Issue by ketan0777** [amabnl/amadeus-ws-client#287]
Hi 

I'm  new with this amadeus webservice.

can any body help which are the things required to book a flight ?

I can able to search flights using FareMasterPricerTbSearch.

For Book a flight what are the things required ? 
do you have any documentation flow to book a flight?

**Comment by DerMika** [comment]
Hi, 

as @therealartz  already said, Amadeus should be able to provide you with documents explaining the booking flow. Depending on what you want to implement and support, the answers could vary. 

If you have a project with Amadeus, you have dedicated support staff that you are paying for, so you best make use of them!

If you have specific questions about how to implement a flow using this library, don't hesitate to open a ticket if you can't find the answer.

**Comment by ketan077** [comment]
Thanks for Support. for booking flow I got to know while exploring your repo. 
one Help
------------
while switching to state full session getting below error

**0 /home/ketan/php_amadues/php_pro/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/Session/Handler/SoapHeader4.php(171): Amadeus\Client\Session\Handler\SoapHeader4->getSessionDataFromHeader('<?xml version="...')
#1 /home/ketan/php_amadues/php_pro/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/Session/Handler/Base.php(202): Amadeus\Client\Session\Handler\SoapHeader4->handlePostMessage('PNR_AddMultiEle...', '<?xml version="...', Array, Object(Amadeus\Client\Session\Handler\SendResult))
#2 /home/ketan/php_amadues/php_pro/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client.php(1534): Amadeus\Client\Session\Handler\Base->sendMessage('PNR_AddMultiEle...', Object(Amadeus\Client\Struct\Pnr\AddMultiElements), Array)
#3 /home/ketan/php_amadues/php_pro/vendor/amabnl/amadeus-ws-client/src/Amade in /home/ketan/php_amadues/php_pro/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/Session/Handler/SoapHeader4.php**

making call right after "airSellFromRecommendation"
$client->setStateful(true);

#0 /home/ketan/php_amadues/php_pro/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/Session/Handler/SoapHeader4.php(171): Amadeus\Client\Session\Handler\SoapHeader4->getSessionDataFromHeader('<?xml version="...')
#1 /home/ketan/php_amadues/php_pro/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/Session/Handler/Base.php(202): Amadeus\Client\Session\Handler\SoapHeader4->handlePostMessage('PNR_AddMultiEle...', '<?xml version="...', Array, Object(Amadeus\Client\Session\Handler\SendResult))
#2 /home/ketan/php_amadues/php_pro/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client.php(1534): Amadeus\Client\Session\Handler\Base->sendMessage('PNR_AddMultiEle...', Object(Amadeus\Client\Struct\Pnr\AddMultiElements), Array)
#3 /home/ketan/php_amadues/php_pro/vendor/amabnl/amadeus-ws-client/src/Amade in /home/ketan/php_amadues/php_pro/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/Session/Handler/SoapHeader4.php on line 201


one more thing while making this "$info = $client->getSessionData();" call ,array is empty 

can you help me regarding this
