### ISSUE TITLE
Production WSDL SOAP Error

### ISSUE THREAD

**Issue by fayax** [amabnl/amadeus-ws-client#288]
Hi,
I have switched to production WSDL files, which Amadeus provided. But I'm having issues parsing it with SOAP client.
I get the following error:

Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing Schema: can't import schema from 'Amadeus/wsdl/AMA/2012B/AMA_WS_Session.xsd' in /www/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/SoapClient.php:59 Stack trace: #0 /www/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/SoapClient.php(59): SoapClient->SoapClient('/www...', Array) #1 /www/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/Session/Handler/Base.php(402): Amadeus\Client\SoapClient->__construct('/www...', Array, Object(Monolog\Logger)) #2 /www/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/Session/Handler/Base.php(380): Amadeus\Client\Session\Handler\Base->initSoapClient('14f85d17') #3 /www/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/Session/Handler/SoapHeader4.php(148): Amadeus\Client\Session\Handler\Base->getSoapClient('Fare_MasterPric...') #4 /www/vendor/amabnl/amadeus in /www/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/SoapClient.php on line 59

I have no issues with test WSDL files.

Thanks,

**Comment by DerMika** [comment]
Have you tried re-downloading the prod WSDL? Sometimes the download is corrupted...

**Comment by fayax** [comment]
Yeah, still same issue. I was able to load the files into SoapUI app.

**Comment by DerMika** [comment]
I would suggest checking the XSD file mentioned in the error, see if it's a valid XML doc

**Comment by fayax** [comment]
permission on some xsd files causing the issue.
