### ISSUE TITLE
Multiple type of TST

### ISSUE THREAD

**Issue by MyDcode** [amabnl/amadeus-ws-client#289]
Hi @DerMika,

What is the correct way of creating multiple type TST with the library?

**1.**
```
$createTstResponse = $client->ticketCreateTSTFromPricing(
            new TicketCreateTstFromPricingOptions([
                'pricings' => [
                    new Pricing([
                        'tstNumber' => [1,2]
                    ])
                ]
            ])
        );
```

or

**2.**
```
$createTstResponse = $client->ticketCreateTSTFromPricing(
            new TicketCreateTstFromPricingOptions([
                'pricings' => [
                    new Pricing([
                        'tstNumber' => 1
                    ]),
                 'pricings' => [
                    new Pricing([
                        'tstNumber' => 2
                    ])
                ]
            ])
        );
```

Or is there any different approach needs to be done than above samples? I checked the issue #199, please do clarify briefly about your concern on multiple pricing for a pax type. When we do the _ticketCreateTSTFromPricing_ it will save in the created PNR right?

I am following below structure,

> MPTB->PNR_M(0)->Air_Sell->PNR_M->Fare_PNR->TST->PNR_M(11)

Once again thanks in advance.

**Comment by DerMika** [comment]
https://github.com/amabnl/amadeus-ws-client/blob/master/tests/Amadeus/Client/Struct/Ticket/CreateTSTFromPricingTest.php#L68 

this is the correct format for multi tst pricings
