### ISSUE TITLE
SessionId and timestamp issue in flight search

### ISSUE THREAD

**Issue by sainitawgt** [amabnl/amadeus-ws-client#296]
Hello , we have used this package for implementing flight search module. Now we need to fill in an excel file send from amadeus for certification where we need to put session Id and timestamp details for each request. Can you please tell me how to get these session Id and timestamp details?

**Comment by DerMika** [comment]
The easiest is to add a logger to your client, which will log all requests & responses to a logfile. Then you'll have to look at the SOAP header to get the session ID. Timestamp is the time when your test are being executed, and will also be logged to the logfile...

See the docs: [logging-request-and-response](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#logging-request-and-response)

**Comment by sainitawgt** [comment]
Thank you so much. Got the details from the log file.
