### ISSUE TITLE
Nonce base

### ISSUE THREAD

**Issue by humanyu** [amabnl/amadeus-ws-client#299]
May i ask what is the value of $params->authParams->nonceBase

Please help me Out A.S.A.P
Thanks in advance

**Comment by therealartz** [comment]
```php
// Amadeus\Client\Params\AuthParams

/**
 * Custom Nonce base to use when generating nonces for authentication
 *
 * Only applies to Soap Header V4
 *
 * If you do not provide one, the Session HandlerFactory will generate a random string.
 *
 * @var string
 */
public $nonceBase;
```

**Comment by DerMika** [comment]
Perhaps it would be better if you told us what you're trying to do. This library already does nonce generation. So when you're using this library, you don't need to worry about it. 

As to what the exact value of the nonce is, it's an implementation of the required nonce calculation as can be found on the Amadeus extranet when implementing a SoapHeader 4 client.

**Comment by DerMika** [comment]
Usually you don't need to worry about the nonceBase. 

Originally I had the idea of reusing a nonce base, but later I decided it doesn't really matter and made it a randomly generated string.

**Comment by humanyu** [comment]
Now I am using library. Can you guide me which wsdl would be able to search flight. I am trying to use air multi availability. But this wsdl is not added in my amadeus account. Is there any other wsdl to search flight with passenger type and count.

Thank you in advance

**Comment by humanyu** [comment]
Can anyone tell me how to add airline class like economy, business, first etc. In fare_masterpricetravelboardsearch

**Comment by DerMika** [comment]
> Now I am using library. Can you guide me which wsdl would be able to search flight. I am trying to use air multi availability. But this wsdl is not added in my amadeus account. Is there any other wsdl to search flight with passenger type and count.

You should ask these questions to your Amadeus support contact. You should be able to get a document that explains the entire booking flow using web services. And you can ask them to add the messages you need to your WSDL.

**Comment by DerMika** [comment]
> Can anyone tell me how to add airline class like economy, business, first etc. In fare_masterpricetravelboardsearch

This question was answered by @therealartz [here](https://github.com/amabnl/amadeus-ws-client/issues/298#issuecomment-474347401).
