### ISSUE TITLE
Large XML response causes backtrack limit error

### ISSUE THREAD

**Issue by therealartz** [amabnl/amadeus-ws-client#302]
When getting large XML reply everything is failing on step of extracting Soap Envelope Body's content.

It happens exactly on this line: 

https://github.com/amabnl/amadeus-ws-client/blob/master/src/Amadeus/Client/Util/MsgBodyExtractor.php#L58

when preg_match returns error code 2 - which stands for `PREG_BACKTRACK_LIMIT_ERROR` and it means that backtrack limit was exhausted.

I can escape this error only when set in `php.ini` `pcre.backtrack_limit=10000000` but I don't think it is smart solution.

@DerMika maybe have some suggestions about how to optimize it?

Attaching xml response in archive:
[res.zip](https://github.com/amabnl/amadeus-ws-client/files/2988910/res.zip)

**Comment by DerMika** [comment]
Auch, this was bound to happen once. It was never a particularly good idea to use a regexp there... 

Perhaps we should switch to a simpler `substr` bases solution?
