### ISSUE TITLE
Doc Issuance Country and Nationality

### ISSUE THREAD

**Issue by XYNOMEX** [amabnl/amadeus-ws-client#304]
Hey,

when sending freeText in the service request, the document issuance country and nationality should be 2 letters or 3 ?

I was using 3 letters like LBN for Lebanon, but today I hade an error "XX ETKT: PASSENGER SECURITY IDENTIFICATION MISSING/INCOMPLETE", so I contacted Amadeus and they told me that country should be 2 letters, not 3. if that's the case then why all my previous bookings with 3 letters country identification were successful?

**Comment by rifkydj** [comment]
@XYNOMEX . See here . [link](https://github.com/amabnl/amadeus-ws-client/issues/195#issuecomment-389520926) . it should be 3 Letter code for both (issuingCountry and citizenship)

**Comment by humanyu** [comment]
I cannot see raw soap xml request or response. Please guide me. I need to send request and response to our amadeus product manager.

Another question is I am unable to search multicity in  fareMasterPriceTravelTbSearch. May I ask is there any other WSDL for multiCity


Thank you in advance

**Comment by rifkydj** [comment]
u can refer #179 issue and get an idea of it.

There is no need another WSDL for muilticity i guess. fareMasterPriceTravelTbSearch can search multiciytity. you just have to pass itenary  objects as many as u wanted.

**Comment by XYNOMEX** [comment]
Thank you for your help, the only problem that I was booking successfully with 3 letters before but this time I didn't succeed and when I asked Amadeus about it, this is what they said:

We have two locations for LB/LBN,
May you please update the  “Passport Issuing Country“ to be 2 Letters Code and
Keep “ Nationality “ as 3 Letter code.

If that true then everyone who is using 3 letters in the issuing country should fail to book a flight.
@DerMika

**Comment by DerMika** [comment]
This library doesn't do any pre-validation before sending something to Amadeus. 

This is something that could be a useful addition to the library, but a feature that would require constant maintenance, so I don't really feel like implementing such a thing...
