### ISSUE TITLE
Echo soap xml request and response?

### ISSUE THREAD

**Issue by humanyu** [amabnl/amadeus-ws-client#305]
I cannot see raw soap xml request or response. Please guide me. I need to send request and response to our amadeus product manager.

Thank you in advance

**Comment by DerMika** [comment]
I've already [told you](https://github.com/amabnl/amadeus-ws-client/issues/298#issuecomment-474811526) where you can find that info! Direct link: https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#logging-request-and-response

**Comment by humanyu** [comment]
I can't see requestresponse.log

**Comment by humanyu** [comment]
I am sorry to disturb you. It is very Important for me. I am getting fatal error. There is Monolog Logger. Please explain in breif how to use this to see soap xml request and response

Please help me out. I will very grateful to you.

**Comment by humanyu** [comment]
Can we see soap xml request and response in another way. Thats mean print with die at any function or any page where soap request created. Is there any page which convert/made soap request.

May I ask about that page or function

**Comment by DerMika** [comment]
Either you setup a monolog logger (as explained in the docs), or you could also use ad hoc requests and responses like this: https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#getting-individual-requests-and-responses

**Comment by rifkydj** [comment]
@humanyu if u using laravel u could do something like this.

`public function get_header(){

        $storagePath  = Storage::disk('wsdl')->getDriver()->getAdapter()->getPathPrefix();
        $log_path=Storage::disk('mono_logs')->getDriver()->getAdapter()->getPathPrefix();
        $file_name=Carbon::now()->toDateTimeString();
        $msgLog = new Logger('RequestResponseLogs');
        $msgLog->pushHandler(new StreamHandler($log_path.$file_name.'.xml', Logger::INFO));

        $params = new Params([
          'returnXml' => false,

            'authParams' => [
                'officeId' => "",
                'userId' => "",
                //'passwordLength' => 8,
                'passwordData' => "="
            ],
            'sessionHandlerParams' => [
                'soapHeaderVersion' => Client::HEADER_V4,                
                'wsdl' => $storagePath.'/etc....wsdl',
                'logger' => $msgLog
            ],
            'requestCreatorParams' => [
                'receivedFrom' => ''
            ]
        ]);

        return $params;
    }`

This will save all logs to a new file. so u could get logs easily.
