### ISSUE TITLE
Unable to search multicity in fareMasterPriceTbSearch

### ISSUE THREAD

**Issue by humanyu** [amabnl/amadeus-ws-client#306]
I am unable to search flight with multi-city in fareMasterPriceTbSearch. Is there any other wsdl use for multicity
Like DEL TO BOM, BOM TO HYD, HYD TO MAA, MAA TO DEL

**Comment by DerMika** [comment]
The MasterPricer request options contains an `itinerary` property, which is an array. You can just keep adding itinerary objects, so in your case you'll have to add 4 itinerary objects in that array. 

Like the example below, but with 4 `Amadeus\Client\RequestOptions\Fare\MPItinerary` objects:

https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/masterpricertravelboard.rst#return-flight-multiple-passengers-date-range

**Comment by humanyu** [comment]
I had alredy check with 4 itinerary it's saying "Too many requested segments"

Working fine with 3 itinerary

**Comment by therealartz** [comment]
It is default Amadeus limit for requested segments.

You must contact them to increase this limit if you want.

**Comment by DerMika** [comment]
I did not know that :)
