### ISSUE TITLE
Alternate Dates & Alternate Airports

### ISSUE THREAD

**Issue by humanyu** [amabnl/amadeus-ws-client#307]
I want to use alternate dates and alternate airports, which WSDL would be use for alternate dates and alternate airport.

Another question is how can we use alternate dates, altermate airports and fareMasterPriceTravelTbSearch together.

Thank you in advance

**Comment by therealartz** [comment]
I guess Fare_MasterPricerCalender is what you want for "alternate" dates.

What you calling "alternate airport", I guess it is multi city search. Example: https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/masterpricertravelboard.rst#multi-city-airline-exclusion

**Comment by humanyu** [comment]
Alternate Dates-: If I search flight for 12 June 2019 then ALTERNATE DATES response would be for 13 June, 14 June, 17 June etc. You know flexible dates results.

Alternate Airport-: If I search flight DEL(Delhi) to EWR(New york), New york city has lot of airports. Then ALTERNATE AIRPORTS response would be for DEL to JFK, DEL to LGA etc.

**Comment by DerMika** [comment]
These  functional questions you're asking. 

You should ask Amadeus if a certain message supports a certain feature _(or look it up in the Amadeus documentation)_. Once you know what you need to do, you probably won't have a lot of trouble finding out if this library has already implemented that feature or not. They are all listed in the [sample docs](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples.rst).
