### ISSUE TITLE
facing error while calling set session data before pnr addmultielements

### ISSUE THREAD

**Issue by sainitawgt** [amabnl/amadeus-ws-client#309]
I am getting different session id in air sell recommendation and pnr add multielements.To fix this issue i have fetched current session details from getsessiondata and used setsessiondata before calling pnr addmultielements. But after making this change i am getting "duplicate segment" error from pnr add multielement response. Please help me out with this

**Comment by DerMika** [comment]
These are two separate issues. Restoring the session with `getSessionData` and `setSessionData` is the correct way to persist Amadeus sessions between requests. 

You now probably just have some kind of error in your PNR_AddMultiElements...

**Comment by sainitawgt** [comment]
yes, I again declared segment details in pnr_addmultielements after defining the segments in air_sellfromrecommendation.That's why  we got duplicate segment error. Now everything is working fine
