### ISSUE TITLE
Fare Families in Fare_MasterPricerTravelBoardSearch

### ISSUE THREAD

**Issue by bimusiek** [amabnl/amadeus-ws-client#31]
Hey, I just wonder because I see some basic implementation of Fare Families but as I understand it is only for response right?

If I would like to send parameterized Fare Families with request, it is not yet possible right? :)

**Comment by DerMika** [comment]
Are you asking if Amadeus supports it or if my library supports it?

I haven't looked much into fare families yet, so I couldn't yet tell you what Amadeus supports so far. But if you tell me what kind of message you'd like to send with what kind of option, I can implement it - or at least investigate.

**Comment by bimusiek** [comment]
They do support them, it is matter of sending it in the request. 

```xml
<fareFamilies>
        <familyInformation>
          <fareFamilyname>ECO</fareFamilyname>
          <hierarchy>200</hierarchy>
        </familyInformation>
        <familyCriteria>
          <cabinProduct>
            <cabinDesignator>Y</cabinDesignator>
          </cabinProduct>
        </familyCriteria>
      </fareFamilies>
      <fareFamilies>
        <familyInformation>
          <fareFamilyname>BIS</fareFamilyname>
          <hierarchy>100</hierarchy>
        </familyInformation>
        <familyCriteria>
          <cabinProduct>
            <cabinDesignator>C</cabinDesignator>
          </cabinProduct>
        </familyCriteria>
      </fareFamilies>
```
[Fare_MasterPricerTravelBoardSearch - AFF - Combining Cabin classes - SOAP 4.0.txt](https://github.com/amabnl/amadeus-ws-client/files/603687/Fare_MasterPricerTravelBoardSearch.-.AFF.-.Combining.Cabin.classes.-.SOAP.4.0.txt)

You could also give me some hints and I could try to imlement it, however I started coding in php only few days ago to implement your lib to translate soap into json for our internal project.

**Comment by DerMika** [comment]
Ok, I see. For `Fare_MasterPricerTravelBoardSearch` it could be implemented by providing a new array property `fareFamilies` in `Amadeus\Client\RequestOptions\FareMasterPricerTbSearch` - and then in `Amadeus\Client\Struct\Fare\MasterPricerTravelBoardSearch` we'd have to construct the correct message structure when the fareFamilies property is being used. 

But that will only be step one I assume. There is an _Amadeus Web Services Implementation Guide_ for Fare Families which explains the booking process: implementing a booking flow with Fare Families requires more than just adapting the MasterPricer call: See this screenshot from the guide:
![farefamiliesscreen](https://cloud.githubusercontent.com/assets/2979463/20484901/b40ffda2-aff9-11e6-849d-45817c5d210b.png)

So yeah, I can implement the MasterPricer changes, but it'll take me a little more time to implement all these extra messages. But if I know people are interested in using those messages, I don't mind adding support for them.

**Comment by DerMika** [comment]
Can you check if you'll be needing all the messages above (or not), so that I can prioritize implementing them?

**Comment by bimusiek** [comment]
There are 2 things, what I am talking about I believe is parameterized Fare Families and it is only in MasterPricecTBSearch. What you posted is probably implementation for Airlines fare families.

Also, about Upsell option, I asked our Amadeus contact and they said it is still experimental and the wouldn't recommend it but rather using parameterized Fare Families.

When you send in request content that I posted before, it will return you just more specific recommendations and link them together.

So if you got L class and asked for fare families with parameters, it will return you other fares connected to this recommendation.

**Comment by bimusiek** [comment]
@DerMika Thanks for helping with it :) If we would get master search to support it, would be great!

**Comment by DerMika** [comment]
Ok, thanks for explaining it to me, that saves me some time in researching :)

I'll try to implement the option in the MasterPricer call as soon as possible - probably some time this week.

**Comment by bimusiek** [comment]
If you would have some question about parameterized fare families, please shoot :) I read it already few times to see if we can achieve upselling with it 👍 
And thanks again!

**Comment by DerMika** [comment]
Hi @bimusiek 

I've now added support for parametrized Fare Families. Please see the samples at https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/masterpricertravelboard.rst#parametrized-fare-families

You can test it out by composer-installing `dev-master` until I release v.1.2.0. 

If you encounter any issues with it, feel free to open a new issue!
