### ISSUE TITLE
child short code issue in Amadeus certification

### ISSUE THREAD

**Issue by sainitawgt** [amabnl/amadeus-ws-client#310]
I have used child type CH in travelboard search as mentioned in the package.But there are asking to change the code CNN for child type. I need to know will there be any issue if we change the value in the package?

**Comment by therealartz** [comment]
Can you be more concrete? Who asking and when?

**Comment by sainitawgt** [comment]
@therealartz for certification, we have send the logs where travelboard search xml is there.Our amadeus assigned tech person asked us to send CNN instead of CH for child passenger in master pricer service.

**Comment by therealartz** [comment]
Never heard about it. Passed certification twice using `CH` code.

Anyway, just hardcode for your project this value.

No need to change the code in the library, at least for now.

**Comment by DerMika** [comment]
https://servicehub.amadeus.com/c/portal/view-solution/4303822/fr_FR/liste-des-passenger-types-codes-ptc- it seems to be a real thing. 

Should be no problem, like @therealartz said. You can just use your own string instead of a contant provided by the library.

**Comment by sainitawgt** [comment]
okay I will do that. Thank you so much

**Comment by DerMika** [comment]
Closing - you can re-open if you're still having this problem.
