### ISSUE TITLE
Mis match group of flights in each flight index

### ISSUE THREAD

**Issue by humanyu** [amabnl/amadeus-ws-client#315]
If I trying to get return flight from delhi to mumbai. It's response has coming mis match group of flights in each flight index like following.

First index from DEL to BOM has 10 group of flights

Second index from BOM to DEL has 9 group of flights

Recommendation has 11 price items

Can any one guide me how can I manage that things. Or get equal index of group flights

Thank you

**Comment by therealartz** [comment]
This answer should help you to understand how `recommendation` and `groupOfFlights` works: https://github.com/amabnl/amadeus-ws-client/issues/235#issuecomment-425126326

**Comment by humanyu** [comment]
I got it how to manage flights, but problem is when search one way flight then flight index does not create array. How to manage that things.

**Comment by therealartz** [comment]
```php
if (is_array($response->flightIndex)) {
    //
} else {
    //
}
```
