### ISSUE TITLE
help required for PnrCreatePnr

### ISSUE THREAD

**Issue by anwesha8** [amabnl/amadeus-ws-client#316]
How to define air segments for multiple one way serach?

**Comment by rifkydj** [comment]
**For Pnr Creation You Should use 6 Amadeus APIs.**

1. MasterpriceTravelBoardSearch or MasterpriceCalander Search. - Must use Stateless Session.
2. After Selecting Flights using one of Above API You Should call airSellFromRecommendation Api - Must Use Stateful Session .
3 . pnrCreatePnr - Must Use Stateful Session . with option ACTION_NO_PROCESSING
4. Fare_PricePNRWithBookingClass - Must Use Stateful Session .
5 ticketCreateTSTFromPricing 
finally u should use pnrAddMultiElements Api to save your pnr.
This is the basic way of creating PNR.

**for your question** when you call MasterpriceTravelBoardSearch or MasterpriceCalander API you get set of flights. you should pass those flight info to airSellFromRecommendation with stateful session. it will save those info in amadeus session.

**Comment by anwesha8** [comment]
ok thank you :)
