### ISSUE TITLE
PnrCreatePnr

### ISSUE THREAD

**Issue by humanyu** [amabnl/amadeus-ws-client#318]
Hi There,

Can any one tell me about pnrcreatepnr. They ask me company, date, citycode...

Company is airline company ?
Date is journey of date ?
Citycode is departue city or else.?

They are not asking about flight itinerary.
Please help me out to create pnr 

Thank you

**Comment by therealartz** [comment]
First, you should spend some time reading Amadeus user guides for `PNR_AddMultiElements` web service.

It's not recommended to add itineraries through `AddMultiElements`, instead itineraries should be handled with `Air_SellFromRecommendation` and `Fare_PricePNR...`. 

Amadeus implementation guide is fully contains such information, so go learn it.

Second, there are a lot of samples for this here: https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples

**Comment by rifkydj** [comment]
hi @therealartz ,
You helped me alot in this project. thanks very much. i have completed my project.

@humanyu  you can refer this #316

**Comment by humanyu** [comment]
Hii there, 

I am getting error while create pnr. Please have a look my RQ and RS. 

One more thing in amadeus pnr is controlNumber in response?



//////////////////////start Request///////////////////////////////



$client = new Client($params);
use Amadeus\Client\RequestOptions\AirSellFromRecommendationOptions;
use Amadeus\Client\RequestOptions\Air\SellFromRecommendation\Itinerary;
use Amadeus\Client\RequestOptions\Air\SellFromRecommendation\Segment;

$opt = new AirSellFromRecommendationOptions([
    'itinerary' => [
        new Itinerary([
            'from' => 'DEL',
            'to' => 'BOM',
            'segments' => [
                new Segment([
                    'departureDate' => \DateTime::createFromFormat('Ymd','20190419', new \DateTimeZone('UTC')),
                    'from' => 'DEL',
                    'to' => 'BOM',
                    'companyCode' => 'UK',
                    'flightNumber' => '975',
                    'bookingClass' => 'Y',
                    'nrOfPassengers' => 1,
                    'statusCode' => Segment::STATUS_SELL_SEGMENT
                ])
            ]
        ])
    ]
]);

$sellResult = $client->airSellFromRecommendation($opt);
//echo "<pre>";
//print_r($sellResult);


use Amadeus\Client\RequestOptions\PnrCreatePnrOptions;
use Amadeus\Client\RequestOptions\Pnr\Traveller;
use Amadeus\Client\RequestOptions\Pnr\Segment\Miscellaneous;
use Amadeus\Client\RequestOptions\Pnr\Element\Ticketing;
use Amadeus\Client\RequestOptions\Pnr\Element\Contact;
$opt = new PnrCreatePnrOptions();
$opt->actionCode = PnrCreatePnrOptions::ACTION_NO_PROCESSING; //0 Do not yet save the PNR and keep in context.
$opt->travellers[] = new Traveller([
    'number' => 1,
    'firstName' => 'Humanyu',
    'lastName' => 'Malik'
]);
$opt->itineraries[] = new Itinerary([
    'segments' => [
        new Miscellaneous([
            'status ' => Segment::STATUS_CONFIRMED,
            'company' => '1A',
            'date' => \DateTime::createFromFormat('Ymd', '20190419', new \DateTimeZone('UTC')),
            'cityCode' => 'DEL',
            'freeText' => 'DUMMY MISCELLANEOUS SEGMENT'
        ])
    ]
]);
$opt->elements[] = new Amadeus\Client\RequestOptions\Pnr\Element\Ticketing([
    'ticketMode' => Ticketing::TICKETMODE_OK
]);
$opt->elements[] = new Contact([
    'type' => Contact::TYPE_PHONE_MOBILE,
    'value' => '+3222222222'
]);



$createdPnr = $client->pnrCreatePnr($opt);


//echo "<pre>";
//print_r($createdPnr);die;

use Amadeus\Client\RequestOptions\PnrAddMultiElementsOptions;

$pnrReply = $client->pnrAddMultiElements(
    new PnrAddMultiElementsOptions([
        'actionCode' => PnrAddMultiElementsOptions::ACTION_END_TRANSACT_RETRIEVE //ET: END AND RETRIEVE
    ])
);
echo "<pre>";
print_r($pnrReply);die;

////////////////////////////////End Request//////////////////////////////////










/////////////////////////////Start Response//////////////////
Notice: Undefined property: Amadeus\Client\RequestOptions\Air\SellFromRecommendation\Itinerary::$origin in C:\xampp\htdocs\amadeus2\vendor\amabnl\amadeus-ws-client\src\Amadeus\Client\Struct\Pnr\AddMultiElements.php on line 189

Notice: Undefined property: Amadeus\Client\RequestOptions\Air\SellFromRecommendation\Itinerary::$destination in C:\xampp\htdocs\amadeus2\vendor\amabnl\amadeus-ws-client\src\Amadeus\Client\Struct\Pnr\AddMultiElements.php on line 190
Amadeus\Client\Result Object
(
    [status] => OK
    [messages] => Array
        (
        )

    [response] => stdClass Object
        (
            [pnrHeader] => stdClass Object
                (
                    [reservationInfo] => stdClass Object
                        (
                            [reservation] => stdClass Object
                                (
                                    [companyId] => 1A
                                    [controlNumber] => RG6MZV
                                    [date] => 080419
                                    [time] => 0550
                                )

                        )

                )

            [securityInformation] => stdClass Object
                (
                    [responsibilityInformation] => stdClass Object
                        (
                            [typeOfPnrElement] => RP
                            [agentId] => WSSU
                            [officeId] => YTOQK2100
                            [iataCode] => 67502794
                        )

                    [queueingInformation] => stdClass Object
                        (
                            [queueingOfficeId] => YTOQK2100
                        )

                    [cityCode] => YTO
                    [secondRpInformation] => stdClass Object
                        (
                            [creationOfficeId] => YTOQK2100
                            [agentSignature] => 9998WS
                            [creationDate] => 080419
                            [creatorIataCode] => 67502794
                            [creationTime] => 0550
                        )

                )

            [freetextData] => stdClass Object
                (
                    [freetextDetail] => stdClass Object
                        (
                            [subjectQualifier] => 3
                            [type] => P12
                        )

                    [longFreetext] => --- RLR ---
                )

            [pnrHeaderTag] => stdClass Object
                (
                    [statusInformation] => stdClass Object
                        (
                            [indicator] => RLR
                        )

                )

            [sbrPOSDetails] => stdClass Object
                (
                    [sbrUserIdentificationOwn] => stdClass Object
                        (
                            [originIdentification] => stdClass Object
                                (
                                    [originatorId] => 67502794
                                    [inHouseIdentification1] => YTOQK2100
                                )

                            [originatorTypeCode] => T
                        )

                    [sbrSystemDetails] => stdClass Object
                        (
                            [deliveringSystem] => stdClass Object
                                (
                                    [companyId] => 1A
                                    [locationId] => YTO
                                )

                        )

                    [sbrPreferences] => stdClass Object
                        (
                            [userPreferences] => stdClass Object
                                (
                                    [codedCountry] => CA
                                )

                        )

                )

            [sbrCreationPosDetails] => stdClass Object
                (
                    [sbrUserIdentificationOwn] => stdClass Object
                        (
                            [originIdentification] => stdClass Object
                                (
                                    [originatorId] => 67502794
                                    [inHouseIdentification1] => YTOQK2100
                                )

                            [originatorTypeCode] => T
                        )

                    [sbrSystemDetails] => stdClass Object
                        (
                            [deliveringSystem] => stdClass Object
                                (
                                    [companyId] => 1A
                                    [locationId] => YTO
                                )

                        )

                    [sbrPreferences] => stdClass Object
                        (
                            [userPreferences] => stdClass Object
                                (
                                    [codedCountry] => CA
                                )

                        )

                )

            [sbrUpdatorPosDetails] => stdClass Object
                (
                    [sbrUserIdentificationOwn] => stdClass Object
                        (
                            [originIdentification] => stdClass Object
                                (
                                    [originatorId] => 67502794
                                    [inHouseIdentification1] => YTOQK2100
                                )

                            [originatorTypeCode] => T
                        )

                    [sbrSystemDetails] => stdClass Object
                        (
                            [deliveringSystem] => stdClass Object
                                (
                                    [companyId] => 1A
                                    [locationId] => YTO
                                )

                        )

                    [sbrPreferences] => stdClass Object
                        (
                            [userPreferences] => stdClass Object
                                (
                                    [codedCountry] => CA
                                )

                        )

                )

            [technicalData] => stdClass Object
                (
                    [enveloppeNumberData] => stdClass Object
                        (
                            [sequenceDetails] => stdClass Object
                                (
                                    [number] => 1
                                )

                        )

                    [lastTransmittedEnvelopeNumber] => stdClass Object
                        (
                            [currentRecord] => 0
                        )

                    [purgeDateData] => stdClass Object
                        (
                            [dateTime] => stdClass Object
                                (
                                    [year] => 2019
                                    [month] => 4
                                    [day] => 23
                                )

                        )

                )

            [travellerInfo] => stdClass Object
                (
                    [elementManagementPassenger] => stdClass Object
                        (
                            [reference] => stdClass Object
                                (
                                    [qualifier] => PT
                                    [number] => 2
                                )

                            [segmentName] => NM
                            [lineNumber] => 1
                        )

                    [passengerData] => stdClass Object
                        (
                            [travellerInformation] => stdClass Object
                                (
                                    [traveller] => stdClass Object
                                        (
                                            [surname] => MALIK
                                            [quantity] => 1
                                        )

                                    [passenger] => stdClass Object
                                        (
                                            [firstName] => HUMANYU
                                            [type] => ADT
                                        )

                                )

                        )

                    [enhancedPassengerData] => stdClass Object
                        (
                            [enhancedTravellerInformation] => stdClass Object
                                (
                                    [travellerNameInfo] => stdClass Object
                                        (
                                            [quantity] => 1
                                            [type] => ADT
                                        )

                                    [otherPaxNamesDetails] => stdClass Object
                                        (
                                            [nameType] => UN
                                            [referenceName] => Y
                                            [displayedName] => Y
                                            [surname] => MALIK
                                            [givenName] => HUMANYU
                                        )

                                )

                        )

                )

            [originDestinationDetails] => stdClass Object
                (
                    [originDestination] => stdClass Object
                        (
                        )

                    [itineraryInfo] => Array
                        (
                            [0] => stdClass Object
                                (
                                    [elementManagementItinerary] => stdClass Object
                                        (
                                            [reference] => stdClass Object
                                                (
                                                    [qualifier] => ST
                                                    [number] => 2
                                                )

                                            [segmentName] => RU
                                            [lineNumber] => 2
                                        )

                                    [travelProduct] => stdClass Object
                                        (
                                            [product] => stdClass Object
                                                (
                                                    [depDate] => 190419
                                                )

                                            [boardpointDetail] => stdClass Object
                                                (
                                                    [cityCode] => DEL
                                                )

                                            [companyDetail] => stdClass Object
                                                (
                                                    [identification] => 1A
                                                )

                                        )

                                    [itineraryMessageAction] => stdClass Object
                                        (
                                            [business] => stdClass Object
                                                (
                                                    [function] => 32
                                                )

                                        )

                                    [relatedProduct] => stdClass Object
                                        (
                                            [quantity] => 1
                                            [status] => HK
                                        )

                                    [itineraryFreetext] => stdClass Object
                                        (
                                            [freetextDetail] => stdClass Object
                                                (
                                                    [subjectQualifier] => 3
                                                )

                                            [longFreetext] => -DUMMY MISCELLANEOUS SEGMENT
                                        )

                                    [markerRailTour] => stdClass Object
                                        (
                                        )

                                )

                            [1] => stdClass Object
                                (
                                    [elementManagementItinerary] => stdClass Object
                                        (
                                            [reference] => stdClass Object
                                                (
                                                    [qualifier] => ST
                                                    [number] => 1
                                                )

                                            [segmentName] => AIR
                                            [lineNumber] => 3
                                        )

                                    [travelProduct] => stdClass Object
                                        (
                                            [product] => stdClass Object
                                                (
                                                    [depDate] => 190419
                                                    [depTime] => 0600
                                                    [arrDate] => 190419
                                                    [arrTime] => 0805
                                                )

                                            [boardpointDetail] => stdClass Object
                                                (
                                                    [cityCode] => DEL
                                                )

                                            [offpointDetail] => stdClass Object
                                                (
                                                    [cityCode] => BOM
                                                )

                                            [companyDetail] => stdClass Object
                                                (
                                                    [identification] => UK
                                                )

                                            [productDetails] => stdClass Object
                                                (
                                                    [identification] => 975
                                                    [classOfService] => Y
                                                )

                                            [typeDetail] => stdClass Object
                                                (
                                                    [detail] => ET
                                                )

                                        )

                                    [itineraryMessageAction] => stdClass Object
                                        (
                                            [business] => stdClass Object
                                                (
                                                    [function] => 1
                                                )

                                        )

                                    [itineraryReservationInfo] => stdClass Object
                                        (
                                            [reservation] => stdClass Object
                                                (
                                                    [companyId] => UK
                                                    [controlNumber] => RG6MZV
                                                )

                                        )

                                    [relatedProduct] => stdClass Object
                                        (
                                            [quantity] => 1
                                            [status] => HK
                                        )

                                    [flightDetail] => stdClass Object
                                        (
                                            [productDetails] => stdClass Object
                                                (
                                                    [equipment] => 320
                                                    [numOfStops] => 0
                                                    [weekDay] => 5
                                                )

                                            [departureInformation] => stdClass Object
                                                (
                                                    [departTerminal] => 3
                                                )

                                            [arrivalStationInfo] => stdClass Object
                                                (
                                                    [terminal] => 2
                                                )

                                            [timeDetail] => stdClass Object
                                                (
                                                    [checkinTime] => 0515
                                                )

                                            [facilities] => stdClass Object
                                                (
                                                    [entertainement] => M
                                                )

                                        )

                                    [selectionDetails] => stdClass Object
                                        (
                                            [selection] => stdClass Object
                                                (
                                                    [option] => P2
                                                )

                                        )

                                    [carbonDioxydeInfo] => stdClass Object
                                        (
                                            [carbonDioxydeAmount] => stdClass Object
                                                (
                                                    [quantityDetails] => stdClass Object
                                                        (
                                                            [qualifier] => COE
                                                            [value] => 109.266488
                                                            [unit] => KPP
                                                        )

                                                )

                                            [carbonDioxydeInfoSource] => stdClass Object
                                                (
                                                    [freeTextDetails] => stdClass Object
                                                        (
                                                            [textSubjectQualifier] => 3
                                                            [source] => S
                                                            [encoding] => 7
                                                        )

                                                    [freeText] => SOURCE:ICAO CARBON EMISSIONS CALCULATOR
                                                )

                                        )

                                    [markerRailTour] => stdClass Object
                                        (
                                        )

                                )

                        )

                )

            [dataElementsMaster] => stdClass Object
                (
                    [marker2] => stdClass Object
                        (
                        )

                    [dataElementsIndiv] => Array
                        (
                            [0] => stdClass Object
                                (
                                    [elementManagementData] => stdClass Object
                                        (
                                            [reference] => stdClass Object
                                                (
                                                    [qualifier] => OT
                                                    [number] => 2
                                                )

                                            [segmentName] => AP
                                            [lineNumber] => 4
                                        )

                                    [otherDataFreetext] => stdClass Object
                                        (
                                            [freetextDetail] => stdClass Object
                                                (
                                                    [subjectQualifier] => 3
                                                    [type] => 7
                                                )

                                            [longFreetext] => +3222222222
                                        )

                                )

                            [1] => stdClass Object
                                (
                                    [elementManagementData] => stdClass Object
                                        (
                                            [reference] => stdClass Object
                                                (
                                                    [qualifier] => OT
                                                    [number] => 3
                                                )

                                            [segmentName] => TK
                                            [lineNumber] => 5
                                        )

                                    [ticketElement] => stdClass Object
                                        (
                                            [passengerType] => PAX
                                            [ticket] => stdClass Object
                                                (
                                                    [indicator] => OK
                                                    [date] => 080419
                                                    [officeId] => YTOQK2100
                                                )

                                        )

                                )

                            [2] => stdClass Object
                                (
                                    [elementManagementData] => stdClass Object
                                        (
                                            [reference] => stdClass Object
                                                (
                                                    [qualifier] => OT
                                                    [number] => 4
                                                )

                                            [segmentName] => OPW
                                            [lineNumber] => 6
                                        )

                                    [optionElement] => stdClass Object
                                        (
                                            [optionElementInfo] => stdClass Object
                                                (
                                                    [mainOffice] => YTOQK2100
                                                    [date] => 080419
                                                    [queue] => 1
                                                    [category] => 7
                                                    [freetext] => UK TICKET TIME LIMIT WILL BE GIVEN LATER
                                                    [time] => 0300
                                                )

                                        )

                                    [referenceForDataElement] => stdClass Object
                                        (
                                            [reference] => stdClass Object
                                                (
                                                    [qualifier] => ST
                                                    [number] => 1
                                                )

                                        )

                                )

                        )

                )

        )

    [responseXml] => 1ARG6MZV0804190550RPWSSUYTOQK210067502794YTOQK2100YTOYTOQK21009998WS0804196750279405503P12--- RLR ---RLR67502794YTOQK2100T1AYTOCA67502794YTOQK2100T1AYTOCA67502794YTOQK2100T1AYTOCA102019423PT2NM1MALIK1HUMANYUADT1ADTUNYYMALIKHUMANYUST2RU2190419DEL1A321HK3-DUMMY MISCELLANEOUS SEGMENTST1AIR319041906001904190805DELBOMUK975YET1UKRG6MZV1HK32005320515MCOE109.266488KPP3S7SOURCE:ICAO CARBON EMISSIONS CALCULATOROT2AP437+3222222222OT3TK5PAXOK080419YTOQK2100OT4OPW6YTOQK210008041917UK TICKET TIME LIMIT WILL BE GIVEN LATER0300ST1
)

/////////////////////End Response///////////////////////////

**Comment by therealartz** [comment]
Your logs in unreadable. Who else want to waste time to format you text instead of you?

**Comment by humanyu** [comment]
Ignore my response just look at my following errors while creating PNR

Notice: Undefined property: Amadeus\Client\RequestOptions\Air\SellFromRecommendation\Itinerary::$origin in C:\xampp\htdocs\amadeus2\vendor\amabnl\amadeus-ws-client\src\Amadeus\Client\Struct\Pnr\AddMultiElements.php on line 189


Notice: Undefined property: Amadeus\Client\RequestOptions\Air\SellFromRecommendation\Itinerary::$destination in C:\xampp\htdocs\amadeus2\vendor\amabnl\amadeus-ws-client\src\Amadeus\Client\Struct\Pnr\AddMultiElements.php on line 190

**Comment by humanyu** [comment]
Anyone help me with this above error while creating PNR

**Comment by therealartz** [comment]
You are using wrong `Itinerary` object.

Look that there are a lot of different similar objects, but they differ in some fields, that's why they belogs to different namespaces. You must useobject from namespace of function that you wan't call.

Amadeus\Client\RequestOptions\\**AirSellFromRecommendationOptions** and 
Amadeus\Client\RequestOptions\\**Air\SellFromRecommendation**\Itinerary

or

Amadeus\Client\RequestOptions\\**PnrAddMultiElementsOptions** and 
Amadeus\Client\RequestOptions\\**Pnr**\Itinerary

This is clearly seen in the examples: [here](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/pnr-create-modify.rst#adding-a-single-air-segment) `use Amadeus\Client\RequestOptions\Pnr\Itinerary;` and [here ](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples.rst#air-sellfromrecommendation) `use Amadeus\Client\RequestOptions\Air\SellFromRecommendation\Itinerary;`.

**Comment by humanyu** [comment]
Ohh! I am using both things in same page without using separete function thats why this error occurred.

**Comment by therealartz** [comment]
Yes.
