### ISSUE TITLE
Can we call multicity & normal return/oneway flight together in FareMasterPriceTbSearch

### ISSUE THREAD

**Issue by humanyu** [amabnl/amadeus-ws-client#319]
Hii There,

Can we call multicity & normal return/oneway flight together in FareMasterPriceTbSearch

**Comment by therealartz** [comment]
What exactly you mean? Can you provide example of what you want?

**Comment by humanyu** [comment]
let's see eg- I am looking flight from DEL to EWR with date range using FareMasterPriceTbSearch 

2nd is flight search using multicity like DEL to EWR and DEL to JFK etc.

So I need to call both above api together.

**Comment by therealartz** [comment]
Date range is `Fare_MasterPricerCalendar` feature. If you want use both, you must call `MasterPricerCalendar` and `MasterPricerTravelboard` sequently.

**Comment by therealartz** [comment]
It is not possible with PHP.
Except in CLI mode it's possible with `pthreads` and PCNTL extension. But not in fpm or apache.

**Comment by humanyu** [comment]
Curl multi request does used in php.

**Comment by therealartz** [comment]
This library implements PHP's `\SoapClient`, not `curl_multi`.

**Comment by DerMika** [comment]
Perhaps something could be done with an async event loop, but I have no experience with this kind of technology in PHP. I also don't know what would need to be done to adapt this library to work in such an event loop.
