### ISSUE TITLE
Ticket_CreateTSTFromPricing for 3 passenger type( ADT, CH and INF)

### ISSUE THREAD

**Issue by anwesha8** [amabnl/amadeus-ws-client#320]
$createTstResponse = $client->ticketCreateTSTFromPricing(
    new TicketCreateTstFromPricingOptions([
        'pricings' => [
            new Pricing([
                'tstNumber' => 1
            ])
        ]
    ])
);

With this I am creating only one TST, the adult one.But in my scenario I have 3 passenger type, ADT, CH and INF,so I have to create 1 TST per passenger type. E. e., If I have 3 ADT, I have to create 1 TST. If I have 3 ADT and 2 CHD, then I have to create 2 TST and so on.

**Comment by rifkydj** [comment]
please Refer #289

**Comment by anwesha8** [comment]
Thank you :)
