### ISSUE TITLE
Trying to find availability by specific Class of Service only

### ISSUE THREAD

**Issue by bnhall** [amabnl/amadeus-ws-client#322]
Hi, I am trying to find availability for specific classes of service only on a specific airline.
The following code returns "NO FLIGHT FOR THIS CITY PAIR - ENTER A CONNECT POINT /X.."
However the actual availability (in T) DOES exist. Thoughts?

$opt = new AirMultiAvailabilityOptions([
    'actionCode' => AirMultiAvailabilityOptions::ACTION_AVAILABILITY,
    'requestOptions' => [
        new RequestOptions([
            'departureDate' => \DateTime::createFromFormat('Ymd-His', '20190705-000000', new \DateTimeZone('UTC')),
            'from' => 'AUS',
            'to' => 'LAX',
            'includedAirlines' => ['AA'],
            'bookingClasses' => ['T', 'Z', 'U'],
            'requestType' => RequestOptions::REQ_TYPE_NEUTRAL_ORDER
        ])
    ]
]);

**Comment by therealartz** [comment]
Ask Amadeus support.

**Comment by bnhall** [comment]
As a followup, it appears the Air_MultiAvailability API only covers a subset of classes.

For examples:
1) looking at AA flights, I can see availability in classes J, D, I, Y, B, H, K, M, L, G, V, S, N, Q, O but never classes T, Z, U.
2) looking at UA flights, I can see availability in classes J, C, D, Z, P, Y, B, M, E, U, H, Q, V, W, S, T, L, K, G, N but never classes I, X
3) looking at DL flights, I can see availability in classes J, C, D, I, Z, W, Y, B, M H, Q, K, L, U, T, X, V, E but never classes R, N

The classes that AREN'T showing are all Award Travel classes. Is this search not supported with Air_MultiAvailability?

**Comment by therealartz** [comment]
I don't know. Maybe they unavailable in sandbox environment.

It's nothing I can help here.

**Comment by bnhall** [comment]
It turns out that the fare classes shown vary by office ID, more are available to Amadeus than with some office IDs.

**Comment by DerMika** [comment]
Yes, there is a LOT that can be configured on specific Office ID's, not only by Amadeus: As a travel agency you can also make deals with airlines (negotiated fares for example) which would only appear on your office after you have made such deals with airlines.
