### ISSUE TITLE
Use multiple itinerary with foreach

### ISSUE THREAD

**Issue by humanyu** [amabnl/amadeus-ws-client#325]
How can I use foeach in this code for multiple itinerary

$opt = new FareMasterPricerTbSearch([
    'nrOfRequestedResults' => 200,
    'nrOfRequestedPassengers' => 1,
    'passengers' => [
        new MPPassenger([
            'type' => MPPassenger::TYPE_ADULT,
            'count' => 1
        ])
    ],
    'itinerary' => [
        new MPItinerary([
            'departureLocation' => new MPLocation(['city' => 'BRU']),
            'arrivalLocation' => new MPLocation(['city' => 'LON']),
            'date' => new MPDate([
                'dateTime' => new \DateTime('2017-01-15T00:00:00+0000', new \DateTimeZone('UTC'))
            ])
        ])
    ]
]);

**Comment by rifkydj** [comment]
Its Simple;
foreach($YourArray as $key => $value){
	$itenary[] = new MPItinerary([
	'departureLocation' => new MPLocation(['city' => $value['from']]),
	'arrivalLocation' => new MPLocation(['city' => $value['to']]),
	'date' => new MPDate([
	'dateTime' => new \DateTime($value['DateTime'], new \DateTimeZone('UTC'))
		])
	]);
}
$passanger [] = new MPPassenger([
				'type' => MPPassenger::TYPE_ADULT,
				'count' => 1
				]);
After U can use Those Instances Like These.
	$opt = new FareMasterPricerTbSearch([
		'nrOfRequestedResults' => 200,
		'nrOfRequestedPassengers' => 1,
		'passengers' => $passanger,
		'itinerary' => $itenary
	]);

**Comment by DerMika** [comment]
Providing PHP support is not in the scope of this library. You shouldn't open tickets for such issues on this repository.
