### ISSUE TITLE
Problem with the requesting queueList by the degree of urgency(timeMode)

### ISSUE THREAD

**Issue by poltaev1993** [amabnl/amadeus-ws-client#326]
Queue consists from categories. Category has the degree of urgency of the message. The problem is requesting queue messages by the degree of urgency. It has 4 degrees of urgency.

In another words, I need to pass new `Queue` option in a `queueList` request method, which name is `timeMode`(Now the value is equal to 1 by default). In addition, `QueueList` class should be corrected with `date` attribute initialization.

**Comment by DerMika** [comment]
Can you provide a PR (with tests) for the change you need?

**Comment by poltaev1993** [comment]
@DerMika Yeah, of course.
