### ISSUE TITLE
What is actual Cabin here

### ISSUE THREAD

**Issue by humanyu** [amabnl/amadeus-ws-client#328]
What cabin code would be use for creating pnr

[groupOfFares] => Array
                                                        (
                                                            [0] => stdClass Object
                                                                (
                                                                    [productInformation] => stdClass Object
                                                                        (
                                                                            [cabinProduct] => stdClass Object
                                                                                (
                                                                                    [rbd] => P
                                                                                    [cabin] => M
                                                                                    [avlStatus] => 9
                                                                                )

                                                                            [fareProductDetail] => stdClass Object
                                                                                (
                                                                                    [fareBasis] => E2ZRCS2
                                                                                    [passengerType] => ADT
                                                                                    [fareType] => RP
                                                                                )

                                                                            [breakPoint] => N
                                                                        )

                                                                )

                                                            [1] => stdClass Object
                                                                (
                                                                    [productInformation] => stdClass Object
                                                                        (
                                                                            [cabinProduct] => stdClass Object
                                                                                (
                                                                                    [rbd] => E
                                                                                    [cabin] => M
                                                                                    [avlStatus] => 9
                                                                                )

                                                                            [fareProductDetail] => stdClass Object
                                                                                (
                                                                                    [fareBasis] => E2ZRCS2
                                                                                    [passengerType] => ADT
                                                                                    [fareType] => RP
                                                                                )

                                                                            [breakPoint] => Y
                                                                        )

                                                                )

                                                        )

                                                    [majCabin] => stdClass Object
                                                        (
                                                            [bookingClassDetails] => stdClass Object
                                                                (
                                                                    [designator] => M
                                                                )

                                                        )

                                                )

**Comment by therealartz** [comment]
rbd is booking class
cabin is cabin class

You must ask these questions to your Amadeus support manager and learn their user guides

**Comment by humanyu** [comment]
Thanks
