### ISSUE TITLE
Add Client setup parameter that determines if we fill the 'responseXml' property of the Result object

### ISSUE THREAD

**Issue by DerMika** [amabnl/amadeus-ws-client#33]
[As requested](https://github.com/amabnl/amadeus-ws-client/issues/32) by @tommiehansen, we'll add a parameter on client instantiation to determine if we want to fill the `responseXml` property of the message result object `Amadeus\Client\Result`.

Here's the proposal:
- Parameter at Client instantiation that enables or disables filling responseXml by default
- An extra key in the optional `$messageOptions` parameter when calling a message that can override the default behaviour above for an individual message.

That gives you the ability to enable or disable the behaviour by default, but still activate (or deactivate) the behaviour for a specific call when needed.

**Comment by DerMika** [comment]
@tommiehansen, does this sound good to you?

**Comment by tommiehansen** [comment]
Yes -- sounds really good because of the choices one can make which adds some flexibility for specific usecases etc.

**Comment by DerMika** [comment]
I've pushed a fix for this. Explanation and sample can be found in the docs at: https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#disabling-xml-as-string-in-result

Dont' hesitate to open a new issue if you're experiencing any problems!
