### ISSUE TITLE
Release 1.7.2?

### ISSUE THREAD

**Issue by laurentiuc** [amabnl/amadeus-ws-client#331]
Hello, 

Can you please have a new release made? the seatmap options (companyId, date) are not present in #1.7.1 

Thanks,
/laurentiu

**Comment by DerMika** [comment]
For now you can use ´dev-master´ in ´composer.json´, but I plan to release 1.8.0 soon - which is long overdue.

**Comment by DerMika** [comment]
Ah, yes, for got to say, I released 1.8.0 :)
