### ISSUE TITLE
How to Request Multiple Seats With Single PNR_AddMultiElements Request

### ISSUE THREAD

**Issue by EugeneBilenko** [amabnl/amadeus-ws-client#334]
Does this library provide an ability to add the tag "`<seatRequest>`" with 2 or more child tags "`<special>`" in the request "PNR_AddMultiElements"?
```xml
<seatGroup>
    <seatRequest>
        <special>
            <data>5A</data>
        </special>
        <special>
            <data>5B</data>
        </special>
    </seatRequest>
</seatGroup>
```

**Comment by therealartz** [comment]
Not implemented.
I could add this feature or you may open PR by yourself. Which way do you prefer?

**Comment by EugeneBilenko** [comment]
It would be great if you added this feature. Thanks
