### ISSUE TITLE
What is the simplest way to modify a ticketing element duration?

### ISSUE THREAD

**Issue by skills-up** [amabnl/amadeus-ws-client#337]
I am trying to modify the duration for a ticketing element for an existing PNR (saved but not ticketed yet). Amadeus support has recommended using PNR_Cancel for removing existing Ticketing Element and adding a new Ticketing element.

However, I'm not able to figure out the option for PNR_Cancel request to remove ticketing element.

So, my question is 2-pronged:
1. What option can be used to remove only the ticketing element from PNR? An example would be really appreciated.
2. Is there an alternate way to modify just the duration, when the ticketing element already exists on PNR?

**Comment by rifkydj** [comment]
hi @skills-up ,

for your 1st question Cancel The PNR is the recommended option as Amadeus Support says,
for your 2nd question you mean travelling duration or the ticketing duration ??? im not clear.

**Comment by skills-up** [comment]
I was struggling to find the appropriate option for cancellation, and then realised that something like the below may work:
```
$client->pnrCancel(
    new PnrCancelOptions([
        'actionCode' => PnrCancelOptions::ACTION_END_TRANSACT_RETRIEVE,
        'elementsByTattoo' => $tkxlTattoo,
    ])
);
```

For the second question, I meant the timestamp for ticketing element action. I'm now using this:
```
$client->pnrAddMultiElements(
    new PnrAddMultiElementsOptions([
        'actionCode' => PnrCancelOptions::ACTION_END_TRANSACT_RETRIEVE,
        'elements' => new Ticketing([
            'ticketMode' => Ticketing::TICKETMODE_CANCEL,
            'date' => $tkxlTime,
        ])
    ])
);
```

**Comment by therealartz** [comment]
You actually found answer for your questions. This is the correct way.

Retrieve PNR and get `ref`number  of desired element (in this case "ticketing") then cancel with yours snippet from message above. A small amendment - `elementsByTattoo` should be an array.

**Comment by skills-up** [comment]
Thanks!

I did use an array after posting the snippets here, as I realised it is elements[]. Closing this.
