### ISSUE TITLE
InitRefund does not support stockProviderDetails

### ISSUE THREAD

**Issue by poltaev1993** [amabnl/amadeus-ws-client#340]
`InitRefund` does not support `stockProviderDetails`. It's necessary to specify stock provider details during `DocRefundInitRefund`, when stock provider of issued ticket is airline.

**Comment by poltaev1993** [comment]
This pull request solves this problem #341

**Comment by DerMika** [comment]
Fixed by merging your PR, which has been released with 1.9.0
