### ISSUE TITLE
RU fareType verify in Response

### ISSUE THREAD

**Issue by humanyu** [amabnl/amadeus-ws-client#348]
Hello Guys,
I am using RU fareType and getting discounted fares, but could not verify RU fareType in response. Please help me out to verify that is discounted fares in response.

Thank you

**Comment by humanyu** [comment]
Please help me...How to verify RU fares in response(MPTB)

**Comment by humanyu** [comment]
Is there anybody to solve this issue??

**Comment by DerMika** [comment]
Have you asked Amadeus Support? 

This is -again- a functional question...

**Comment by humanyu** [comment]
I asked him but amadeus taken more time to reply.. Please help me about this..
