### ISSUE TITLE
PNR issue wit multiple traveller

### ISSUE THREAD

**Issue by solitaireinfosys** [amabnl/amadeus-ws-client#349]
When we are adding 
[createPnrFunction.txt](https://github.com/amabnl/amadeus-ws-client/files/3415716/createPnrFunction.txt)

multiple travellers to create a PNR .So i can't get any response from Amadeus. Please share a method or function then I able to implement a PNR with multiple travellers.

**Comment by bimusiek** [comment]
Adding travellers up to 9 is same as adding 2 travellers. In case of issues with the WebServices, you have to contact Amadeus for help. 

As there was no more activity on the issue, I am closing it.
