### ISSUE TITLE
Operating carrier

### ISSUE THREAD

**Issue by yuriyfroloff** [amabnl/amadeus-ws-client#350]
Hi Dieter,

As far as I see PNR_Retrieve does not return the operating carrier if the flight is codeshare. Is this really so, and maybe there are ways to know the operating carrier?

Thanks!

**Comment by gabrythe23** [comment]
Sane problem here! I’ve Just open a ticket with Amadeus. I’ll let you know

**Comment by gabrythe23** [comment]
from amadeus reply:

in order to view the operating carrier we have to update a params of yours office id. 

so it's just an amadeus feature that have to be enable from amadeus.

**Comment by bimusiek** [comment]
As this issue is resolved, I am closing it 👍
