### ISSUE TITLE
Pagination of results

### ISSUE THREAD

**Issue by montenegroraabe** [amabnl/amadeus-ws-client#351]
Hi!

First, thanks for the support and quick development responses, the library is of great help.

I did the development, based on the library, but was asked to have the results paginated, ie: 10, 20, 30 items per page, a call to "see more results" and then load the rest.

Is it possible with this library? If so, are there any examples? If not, would it be possible to perform with Node.js, or even PHP, separately?

**Comment by therealartz** [comment]
No. Amadeus does not provide pagination of results.

You should get all results from Amadeus and paginate them on front-end. Search in google about client side pagination

**Comment by montenegroraabe** [comment]
@therealartz sorry for the late reply. 

I found a good plugin for pagination results, but I have another question: is there any recommended way, or do you have a known plugin, to load the results faster, without being too slow for the client?
