### ISSUE TITLE
Type Qualifier

### ISSUE THREAD

**Issue by XYNOMEX** [amabnl/amadeus-ws-client#353]
Dear @DerMika ,

Where can i find a definition for a type qualifier code?
"miniRulesRefund": [
            {
                "amount": "25.00",
                "currency": "USD",
                "typeQualifier": "BDM"
            },
            {
                "amount": "25.00",
                "currency": "USD",
                "typeQualifier": "BDX"
            },
            {
                "amount": "25.00",
                "currency": "USD",
                "typeQualifier": "BDF"
            },
            {
                "amount": "25.00",
                "currency": "USD",
                "typeQualifier": "BDG"
            },
            {
                "amount": "25.00",
                "currency": "USD",
                "typeQualifier": "BDT"
            },
            {
                "amount": "50.00",
                "currency": "USD",
                "typeQualifier": "BNM"
            },

**Comment by therealartz** [comment]
In Amadeus docs for certain message you could open "Browse response structure" and then find this field there.
But unfortunately not every field have such descriptions. In that case you must contact to Amadeus support if you really need.

**Comment by XYNOMEX** [comment]
So if i asked Amadeus support they should know what "BDM" or "BDX" stands for ?

**Comment by XYNOMEX** [comment]
In the example above there is 25$ and 50$ this is what i'm getting, but when i called the agency they told me that there is no 50$ there is only 25$ as a fee in case of change. so what i need is to understand what each "TypeQualifier" stands for so i can know what to display for my clients.

**Comment by therealartz** [comment]
Exactly. You should ask send them XML response and ask what means each type qualifier.

**Comment by XYNOMEX** [comment]
Thank you.
