### ISSUE TITLE
Error Session Code 11

### ISSUE THREAD

**Issue by konorws** [amabnl/amadeus-ws-client#354]
Good day. This ticket is more for documentation of errors that may occur.

Recently I encountered a problem described in the ticket #154 .

The problem was that after deploying to a test server, the code stopped working. Amadeus refused to authorize. A few days of searching solved my problem and it ended up in "Date"

Although this library sets the time zone on the server, the hour may not be correct. In my case, the difference was -5 hours, which is why the request time was always wrong.

**Comment by therealartz** [comment]
So which solution was in your case?

**Comment by konorws** [comment]
> So which solution was in your case?

In my cases, the problem was solved by setting the time on the server side.

Also a temporary solution but the bad thing was to modify the date
`$cerated->modify("+5 hours");`

**Comment by bimusiek** [comment]
As it was answered and resolve, I am closing the issue 👍
