### ISSUE TITLE
Getting Penalties, change fees, no show.

### ISSUE THREAD

**Issue by XYNOMEX** [amabnl/amadeus-ws-client#356]
Dears,

What funcs should we use to get the penalties, change fees, no show.. for a specific flight?
Thank you.
@DerMika

**Comment by DerMika** [comment]
Fare_CheckRules or one of the MiniRules calls, I suppose.

**Comment by bimusiek** [comment]
If you want structured data, use MiniRules calls. It will give you information about what Amadeus thinks the rules about the flight are in simple terms.

If you want full text rules, you have to use Fare_CheckRules after pricing or Fare_GetFareRules to get those based on fare basis info.
