### ISSUE TITLE
How to create an Individual PNR security (ES Element) in AddMultiElements

### ISSUE THREAD

**Issue by travelusvn** [amabnl/amadeus-ws-client#357]
Dear @DerMika  & Gentlemen,
I searched hard but couldn't figure out how to create an ES element, please help. Element i need to generate like that:

`<PNR_AddMultiElements xmlns="http://xml.amadeus.com/PNRADD_17_1_1A">
    <pnrActions>
        <optionCode>0</optionCode>
    </pnrActions>
    <dataElementsMaster>
        <marker1/>
        <dataElementsIndiv>
            <elementManagementData>
                <segmentName>ES</segmentName>
            </elementManagementData>
            <pnrSecurity>
                <security>
                    <identification>OFFICE-ID</identification>
                    <accessMode>R</accessMode>
                </security>
                <indicator>G</indicator> 
            </pnrSecurity>
        </dataElementsIndiv>
        </dataElementsMaster>
</PNR_AddMultiElements>`
thank you very much
Doan

**Comment by therealartz** [comment]
Unfortunately there are not implemented this element.
You can create a PR or if you can't I could.

**Comment by travelusvn** [comment]
hi @therealartz , please help me to create a PR

thanks alot
Doan

**Comment by therealartz** [comment]
@travelusvn there's a contribution guide https://github.com/amabnl/amadeus-ws-client/blob/master/CONTRIBUTING.md

**Comment by therealartz** [comment]
I really want to help by creating PR but now I don't have access to Amadeus SOAP API and I can't create correct class without docs.

**Comment by suiram2010** [comment]
@travelusvn already implemented see docs https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/pnr-create-modify.rst#security-element-es

**Comment by therealartz** [comment]
Solved by https://github.com/amabnl/amadeus-ws-client/pull/421
