### ISSUE TITLE
DocIssuance_IssueMiscellaneousDocuments got SOAP-ERROR issue

### ISSUE THREAD

**Issue by onepiece0122** [amabnl/amadeus-ws-client#358]
Hi,

I got a SOAP-ERROR when I try to issue miscellaneous docs by line numbers, here is my code:
```
$requestOptions = new DocIssuanceIssueMiscDocOptions([
    'options' => [
        DocIssuanceIssueMiscDocOptions::OPTION_EMD_ISSUANCE,
        new Option([
            'indicator' => 'ITR',
            'subCompoundType' => 'EMPR',
            'subCompoundDescription' => 'example@example.com'
        ])
    ],
    'lineNumbers' => [8]
]);
$result = $client->docIssuanceIssueMiscellaneousDocuments($requestOptions);
```
and the error:
```
SOAP-ERROR: Encoding: object has no 'type' property
```
I also try issue docs with tsmNumbers or tsmTattoos, but got the same error.
WSDL is DocIssuance_IssueMiscellaneousDocuments_15_1_1A
And here is my log
[wbs.log](https://github.com/amabnl/amadeus-ws-client/files/3620697/wbs.log)

Thanks.

**Comment by therealartz** [comment]
It's something wrong with you request object.

I guess you can't pass both object `Option` and string `DocIssuanceIssueMiscDocOptions::OPTION_EMD_ISSUANCE` into `'options'` array.

**Comment by onepiece0122** [comment]
Hi @DerMika ,
Could you help me to solve this problem?
Thanks

**Comment by onepiece0122** [comment]
I make some changes on DocIssuanceBaseMsg.php, and it works...
```
protected function addSelectionItem(ReferenceDetails $ref)
{
    if (is_null($this->selection) || empty($this->selection)) {
        $this->selection = new Selection();
    }
    $this->selection->referenceDetails[] = $ref;
}
```

**Comment by DerMika** [comment]
Can you make a pull request?

**Comment by onepiece0122** [comment]
Hi

Sorry I don't have many time to follow the contributing guide.
Maybe someone can help me to create PR.

**Comment by therealartz** [comment]
@onepiece0122 it's easy:
Create a fork of this repository;
Commit change to your fork-repository;
After that open page of this repo and you'll see yellow message that you able to create PR from your latest push.
