### ISSUE TITLE
Response for security token giving error code 16002.

### ISSUE THREAD

**Issue by Wizard2436829** [amabnl/amadeus-ws-client#360]
While making a request to Amadeus for LowFareSearch, more precisely while getting the security token for authentication we getting the error code in the response with code 16002. Can you please look into this and revert back by what that means.

**Comment by Wizard2436829** [comment]
So in the response I am getting a session ID but with an error code. Ultimately we are getting the session details, that we wanna use in the main code, as null.

**Comment by DerMika** [comment]
If you look in the docs of LowFareSearch, you I'll probably find this error code. If not, ask Amadeus Support.

**Comment by Wizard2436829** [comment]
ya, that issue is now resolved as a base 64 encoded value of session ID was required. Was a Security requirement for authentication.

**Comment by DerMika** [comment]
Did you have to modify the library? If so, can you make a pull request with that option?
