### ISSUE TITLE
How to copy PNRs from queue A to queue B

### ISSUE THREAD

**Issue by abelardolg** [amabnl/amadeus-ws-client#361]
Hi there!

I wonder where I can find about how to generate a request to the API of Amadeus to COPY a PNR from queue A to queue B.

I have found this Utility page from Amadeus: https://developers.amadeus.com/enterprise/category/queue-management/api/utilities

where they offer a service to place a PNR in queue but I don't know how to do it. 

Any help would be welcome.

Sorry if this message is considered spam.

Best regards.

**Comment by therealartz** [comment]
> they offer a service to place a PNR in queue but I don't know how to do it.

https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples.rst#queue-placepnr

> request to the API of Amadeus to COPY a PNR from queue A to queue B

https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples.rst#queue-moveitem

**Comment by abelardolg** [comment]
Thanks, @therealartz :) 
Have a nice day!
