### ISSUE TITLE
Message "Queue_PlacePNR" is not in WDSL

### ISSUE THREAD

**Issue by abelardolg** [amabnl/amadeus-ws-client#364]
Hi there,

I am using the above method but Amadeus API returns this message.

Could anybody help to me, please?

Any help would be welcome.

Kindest regards.

**Comment by therealartz** [comment]
This error means that your account doesn't have access to requested message. You must ask Amadeus to provide access to this service.

**Comment by abelardolg** [comment]
Thank so much for your help, Artem Zakharchenko.


Best regards.
