### ISSUE TITLE
fareInformativePricingWithoutPnr NumberOfUnits

### ISSUE THREAD

**Issue by konorws** [amabnl/amadeus-ws-client#366]
Faced a problem that I get an error 

> Number of passengers must be a positive integer, in this case: 0 was g - iven.

I looked at all the options for **FareInformativePricingWithoutPnrOptions**, **Client\RequestOptions\Fare\InformativePricing\Segment** and **Amadeus\Client\RequestOptions\Fare\InformativePricing\Passenger**

But I did not find where you can specify the number of passengers.

I send this code 
`$segmentItem = [
                        'departureDate' => \DateTime::createFromFormat('Y-m-d H:i', $segmentInfo['dateStart']. " 
                        ".$segmentInfo['timeStart'], new \DateTimeZone('UTC')),
                'arrivalDate' => \DateTime::createFromFormat('Y-m-d H:i', $segmentInfo['dateEnd']. " 
    ".$segmentInfo['timeEnd'], new \DateTimeZone('UTC')),
                'from' => $segmentInfo['location_from'],
                'to' => $segmentInfo['location_to'],
                'flightNumber' => $segmentInfo['flightOrTrainNumber'],
                'bookingClass' => $recordService->searchData['cabinClass'],
                'operatingCompany' => $segmentInfo['operatingCarrierCode'],
                'marketingCompany' => $segmentInfo['marketingCarrierCode'],
            ];

            $segments[] = new 
   Client\RequestOptions\Fare\InformativePricing\Segment($segmentItem);`
`
// use Amadeus\Client\RequestOptions\Fare\InformativePricing\Passenger as InformativePricingPassenger;
$passengers[] = new InformativePricingPassenger([
                'type' => InformativePricingPassenger::TYPE_ADULT,
            ]);`

`        $result = $this->client->fareInformativePricingWithoutPnr(new FareInformativePricingWithoutPnrOptions(
            [
                'passengers' => $passengers,
                'segments' => $segments
            ]
        ));`

**Comment by bimusiek** [comment]
`Amadeus\Client\RequestOptions\Fare\InformativePricing\Passenger` requires you to specify `tattoos`, which will count as each unique reference per passenger.

So you can do
```php
$passengers[] = new Passenger([
    'type' => Passenger::TYPE_ADULT,
    'tattoos' => range(1, $noOfAdults + 1)
]);
```
