### ISSUE TITLE
Client result not OK 11 | session

### ISSUE THREAD

**Issue by humanyu** [amabnl/amadeus-ws-client#367]
I am getting following error while using FareMasterPricerTbSearch in production WSDL. but working fine in test environment
Addtional information- This wsdl Fare_InformativeBestPricingWithoutPNR_15_1_1A is not available in production folder but test folder have this. I think this not be reason for error

Error-------------------

Amadeus\Client\Result Object ( [status] => FATAL [messages] => Array ( [0] => Amadeus\Client\Result\NotOk Object ( [code] => 11 [text] => [level] => Session ) ) [response] => [responseXml] => soap:Client 11|Session| )

Please help me out.
Thanks in advance

**Comment by tolya1984a** [comment]
Hi.
I also had the same problem.
Most likely the authorization data is not correct.

**Comment by humanyu** [comment]
@tolya1984a 
Had you solve after adding  Fare_InforrativeBestPricingWithoutPNR_15_1_1A in production environment??

**Comment by tolya1984a** [comment]
1   Authorization data for production mode must be correct
  new Params([
                'authParams' => [
                    'officeId' => '*****',
                    'userId' => '****',
                    'passwordData' => base64_encode('****')
                ],
                'sessionHandlerParams' => [ 
                    'soapHeaderVersion' => Client::HEADER_V4, 
                    'wsdl' => 'name.wsdl',
                    'logger' => new Psr\Log\NullLogger() 
                ],
                'requestCreatorParams' => [ 
                    'receivedFrom' => '***' 
                ]
            ]);
2 If that your account doesn't have access to requested message (Fare_InforrativeBestPricingWithoutPNR) in prodaction mode.
You must ask Amadeus to provide access to this service.

**Comment by humanyu** [comment]
Ok I will ask them
