### ISSUE TITLE
Getting the outgoing XML message

### ISSUE THREAD

**Issue by grzpab** [amabnl/amadeus-ws-client#37]
Hello all,

I need to get the outgoing XML message for every request that is send to the Amadeus API. I am able to gather the incoming XML message from the aforementioned API (using `$response->responseXml`) but I wasn't able to locate a similar functionality for getting the request XML. Is it possible to get that XML without using a workaround with loggers?

**Comment by DerMika** [comment]
Sure, you can do this by providing a logger object on instantiation. This is explained in the docs [here](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#logging-request-and-response). 

Let me know if that's sufficient for you!

**Comment by grzpab** [comment]
Thank you! I didn't realise that was hidden in the client class. I will update you if I happen to have any further problems.

**Comment by DerMika** [comment]
Added this information to the How-to docs: https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#getting-individual-requests-and-responses
