### ISSUE TITLE
Doc Expansion - Map Cryptic Commands to SOAP Endpoints

### ISSUE THREAD

**Issue by m0veax** [amabnl/amadeus-ws-client#370]
Hi there,

it would help a lot, having a map of Cryptic Commands and their equivalents in the SOAP API. When you are converting Command Cryptic Applications to Web Service Usage that would be very helpfull.

Maybe anyone who knows some equivalents could drop them here and i will create a new Section in the docs for it?

**Comment by DerMika** [comment]
I agree, and Amadeus Support should be able to provide you with this information. I don't know if Amadeus wants that to be public though, you should probably ask them.
