### ISSUE TITLE
FARE FAMILY OPTION NOT PERMITTED

### ISSUE THREAD

**Issue by tolya1984a** [amabnl/amadeus-ws-client#374]
Hi.

"FARE FAMILY OPTION NOT PERMITTED"
What does it mean ?

**Comment by DerMika** [comment]
You should probably check with Amadeus Support and perhaps look up that error message in the documentation of Amadeus.

**Comment by bimusiek** [comment]
This means, your OID settings do not have Fare Families enabled. 
If you are using this feature on MasterPricer, you have to ask Amadeus to enable this feature for MasterPricer specifically. 

Same applies to any other feature for MasterPricer like MiniRules, FBA option etc.
