### ISSUE TITLE
Date and time of ticket issuance

### ISSUE THREAD

**Issue by yuriyfroloff** [amabnl/amadeus-ws-client#375]
Hi,

Do you know any ways to get the date and time (hours and minutes) of ticket issuance? As far as I can see Ticket_ProcessETicket doesn't return them but maybe there is some solution?

Thanks,
Yuriy

**Comment by therealartz** [comment]
I didn't work with Amadeus WS a long time but guess this data could be stored in PNR. Just perform `PNR_Retrieve` and try to search through `dataElementsIndiv`?

**Comment by yuriyfroloff** [comment]
Thank you for the proposed solution. PNR_Retrieve does contain a date of ticketing which is stored in the FA element, but it's just a date, there's no time specified(

**Comment by yuriyfroloff** [comment]
Hi all, this information can be obtained through the service [Ticket_ProcessEDoc](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples.rst#ticket-processedoc) using e-ticket number and option ACTION_ETICKET_HISTORY. `validityDates` will contain the date and time of ticket issuance also in the `originator` you can find who (agent sign) issued the ticket.
