### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Zee65** [amabnl/amadeus-ws-client#376]
Hello, How can I integrate The Amadeus API to  my website?

**Comment by therealartz** [comment]
Could you clarify what exactly is the problem?

**Comment by Zee65** [comment]
@therealartz I have got my API key and secret, and want to connect Amadeus services to my website, but don't know how to do it.

**Comment by therealartz** [comment]
@Zee65 this repository is not about REST (json) API

**Comment by zakrian07** [comment]
whats the technical difference between the REST API and SOAP API
also whats the latest updates on the library how many new SOAP API calls are available
how can i check the new Calls which added latest
Thanks in advance

**Comment by DerMika** [comment]
Please check the documentation.

This is a library built by volunteers, please do your own research.

If you have a question on how to use this library, you can open a new ticket.
