### ISSUE TITLE
How can we use Amadeus Car WSDL

### ISSUE THREAD

**Issue by humanyu** [amabnl/amadeus-ws-client#379]
Hi Every One,
I want to use Amadeus Car WSDL.
how can create nonse password in core php.
Please help me about Amadeus Car WSDL.

Thank you

**Comment by DerMika** [comment]
You could just implement the Car_* messages in this library and contribute your development? ;)

If that's not possible, here is where the authentication headers are built in this library: 
https://github.com/amabnl/amadeus-ws-client/blob/master/src/Amadeus/Client/Session/Handler/SoapHeader4.php#L306

**Comment by humanyu** [comment]
Hi @DerMika 

I am trying to use amadeus with curl request..please have a look my request code and response. 
Also check action url and action
Please help me out .If it's work then I will do Amadeus Car Apis

Request Code///////^
$password = base64_decode($Pass);
            $creation = new \DateTime('now', new \DateTimeZone('UTC'));
            $t = microtime(true);
            $micro = sprintf("%03d", ($t - floor($t)) * 1000);
            $creationString = createDateTimeStringForAuth($creation, $micro);
            $messageNonce = generateUniqueNonce($nonceBase, $creationString);
            $encodedNonce = base64_encode($messageNonce);
            $digest = generatePasswordDigest($password, $creationString, $messageNonce);

            
		$SOAP_API_URL='https://nodeD2.test.webservices.amadeus.com/1ASIWQTC1QI';	
			
			$soapXML='<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://xml.amadeus.com/FMPTBQ_14_3_1A" xmlns:ns2="http://www.w3.org/2005/08/addressing" xmlns:ns3="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wsswssecurity-secext-1.0.xsd" xmlns:ns4="http://xml.amadeus.com/2010/06/Session_v3" xmlns:ns5="http://xml.amadeus.com/2010/06/Security_v1"><SOAP-ENV:Header><ns2:MessageID>'.$messageId.'</ns2:MessageID><ns2:Action>http://webservices.amadeus.com/FMPTBQ_14_3_1A</ns2:Action><ns2:To>https://nodeD2.test.webservices.amadeus.com/1ASIWQTC1QI</ns2:To><oas:Security xmlns:oas="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
	<oas:UsernameToken xmlns:oas1="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" oas1:Id="UsernameToken-1">
		<oas:Username>'.$userId.'</oas:Username>
		<oas:Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">'.$encodedNonce.'</oas:Nonce>
		<oas:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">'.$digest.'</oas:Password>
		<oas1:Created>'.$creationString.'</oas1:Created>
	</oas:UsernameToken>
</oas:Security><ns4:Session TransactionStatusCode="Start"><ns4:SessionId/><ns4:SequenceNumber/><ns4:SecurityToken/></ns4:Session><ns5:AMA_SecurityHostedUser><ns5:UserID POS_Type="1" PseudoCityCode="'.$officeId.'" AgentDutyCode="SU" RequestorType="U"/></ns5:AMA_SecurityHostedUser></SOAP-ENV:Header><SOAP-ENV:Body><ns1:Fare_MasterPricerTravelBoardSearch><ns1:numberOfUnit><ns1:unitNumberDetail><ns1:numberOfUnits>1</ns1:numberOfUnits><ns1:typeOfUnit>PX</ns1:typeOfUnit></ns1:unitNumberDetail><ns1:unitNumberDetail><ns1:numberOfUnits>200</ns1:numberOfUnits><ns1:typeOfUnit>RC</ns1:typeOfUnit></ns1:unitNumberDetail></ns1:numberOfUnit><ns1:paxReference><ns1:ptc>ADT</ns1:ptc><ns1:traveller><ns1:ref>1</ns1:ref></ns1:traveller></ns1:paxReference><ns1:fareOptions><ns1:pricingTickInfo><ns1:pricingTicketing><ns1:priceType>RP</ns1:priceType><ns1:priceType>RU</ns1:priceType><ns1:priceType>RW</ns1:priceType><ns1:priceType>CUC</ns1:priceType></ns1:pricingTicketing></ns1:pricingTickInfo><ns1:corporate><ns1:corporateId><ns1:corporateQualifier>RW</ns1:corporateQualifier><ns1:identity>123456</ns1:identity></ns1:corporateId></ns1:corporate><ns1:conversionRate><ns1:conversionRateDetail><ns1:currency>USD</ns1:currency></ns1:conversionRateDetail></ns1:conversionRate></ns1:fareOptions><ns1:travelFlightInfo><ns1:cabinId><ns1:cabinQualifier>MD</ns1:cabinQualifier><ns1:cabin>Y</ns1:cabin></ns1:cabinId><ns1:flightDetail/></ns1:travelFlightInfo><ns1:itinerary><ns1:requestedSegmentRef><ns1:segRef>1</ns1:segRef></ns1:requestedSegmentRef><ns1:departureLocalization><ns1:departurePoint><ns1:locationId>LAX</ns1:locationId><ns1:airportCityQualifier>C</ns1:airportCityQualifier></ns1:departurePoint></ns1:departureLocalization><ns1:arrivalLocalization><ns1:arrivalPointDetails><ns1:locationId>NYC</ns1:locationId><ns1:airportCityQualifier>C</ns1:airportCityQualifier></ns1:arrivalPointDetails></ns1:arrivalLocalization><ns1:timeDetails><ns1:firstDateTimeDetail><ns1:timeQualifier>TD</ns1:timeQualifier><ns1:date>300120</ns1:date><ns1:time>1000</ns1:time><ns1:timeWindow>5</ns1:timeWindow></ns1:firstDateTimeDetail><ns1:rangeOfDate><ns1:rangeQualifier>C</ns1:rangeQualifier><ns1:dayInterval>0</ns1:dayInterval></ns1:rangeOfDate></ns1:timeDetails></ns1:itinerary><ns1:itinerary><ns1:requestedSegmentRef><ns1:segRef>2</ns1:segRef></ns1:requestedSegmentRef><ns1:departureLocalization><ns1:departurePoint><ns1:locationId>NYC</ns1:locationId><ns1:airportCityQualifier>C</ns1:airportCityQualifier></ns1:departurePoint></ns1:departureLocalization><ns1:arrivalLocalization><ns1:arrivalPointDetails><ns1:locationId>LAX</ns1:locationId><ns1:airportCityQualifier>C</ns1:airportCityQualifier></ns1:arrivalPointDetails></ns1:arrivalLocalization><ns1:timeDetails><ns1:firstDateTimeDetail><ns1:timeQualifier>TD</ns1:timeQualifier><ns1:date>310120</ns1:date><ns1:time>1000</ns1:time><ns1:timeWindow>5</ns1:timeWindow></ns1:firstDateTimeDetail><ns1:rangeOfDate><ns1:rangeQualifier>C</ns1:rangeQualifier><ns1:dayInterval>0</ns1:dayInterval></ns1:rangeOfDate></ns1:timeDetails></ns1:itinerary></ns1:Fare_MasterPricerTravelBoardSearch></SOAP-ENV:Body></SOAP-ENV:Envelope>';
$action='';
$headers = [
        "Content-type: text/xml;charset=\"utf-8\"",
        'Content-Length: ' . strlen($soapXML),
        'Accept: text/xml',
        'Keep-Alive: 300',
        'Connection: keep-alive',
        'Cache-Control: no-cache',
        'Pragma: no-cache',
        'SOAPAction: "' . $action . '"'
    ];

    $ch = curl_init();
	curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: text/xml'));
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_URL,$SOAP_API_URL);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_TIMEOUT, 60);
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $soapXML);
    $data = curl_exec($ch);
	
$your_xml_response = html_entity_decode($data);
print_r($your_xml_response);

Response/////////
soap:Client 12|Presentation|soap message header incorrectSI:muxDZ1
