### ISSUE TITLE
Need Data in response of FareMasterPricerTbSearch API

### ISSUE THREAD

**Issue by zakrian07** [amabnl/amadeus-ws-client#384]
Hello,
We are unable to find the data

1. Number of stops and stop over details as somewhere in Amadeus doc reply its coming as techStopNumber 
2. We need data with group search and our data always come in single search.
how can We parse such data in response or should we use other API calss
Below is my result I'm getting data from fareMasterPricerCalendar 
 "technicalStop": [
                            {
                                "stopDetails": [
                                    {
                                        "dateQualifier": "AA",
                                        "date": "290220",
                                        "firstTime": "0928",
                                        "locationId": "XDB"
                                    },
                                    {
                                        "dateQualifier": "AD",
                                        "date": "290220",
                                        "firstTime": "0930"
                                    }
                                ]
                            },
                            {
                                "stopDetails": [
                                    {
                                        "dateQualifier": "AA",
                                        "date": "290220",
                                        "firstTime": "0959",
                                        "locationId": "XFF"
                                    },
                                    {
                                        "dateQualifier": "AD",
                                        "date": "290220",
                                        "firstTime": "1001"
                                    }
                                ]
                            }
                        ]
this data not come with specif cities
when we set city => BRU Deprature
            city => LON Location This data coming Nicely
however other Cities data like 
 city => LHR Deprature
 city => DUB Location This data not com in response
we have issue this in fareMasterPricerTravelBoardSearch 

any help will appreciated more over any reference link for parse the data 

Thanks in advance

**Comment by bimusiek** [comment]
Hey @zakrian07,
I am not sure if I understand correctly but it looks like you are asking to get data grouped by legs? 
If thats the case, MasterPricer already returns recommendations with options grouped by legs that have sections inside. 

So Recommendation -> many Options -> segment ID per each leg searched
Then you can find what kind of a flight it is in flights list using segment id from the option.

All of this is explained in documentation and in case of having issues understanding some Amadeus quirks I recommend contacting your Amadeus support.

**Comment by zakrian07** [comment]
Hello,
i have parse this data actually technical stop data mean plane will not change only fuel or other weather condition stop will come .But Thanks for reply
