### ISSUE TITLE
Can some one provide me a sample code of the full flight booking flow??

### ISSUE THREAD

**Issue by sushov-thunder** [amabnl/amadeus-ws-client#386]
I know its a long shot but i am really in need of help.I would be very grateful if someone could provide me with a sample code of the full airline booking flow from travel board search to the pnrmulti add elements options.

**Comment by DerMika** [comment]
I don't think you'll find that information unless someone is willing to share their code. 

If you do come across something similar, i'll gladly link to it in the docs. For now I'm closing this ticket.
