### ISSUE TITLE
Sync Amadeus With My System

### ISSUE THREAD

**Issue by alaskaenterprises** [amabnl/amadeus-ws-client#387]
Hello,
Can anybody explain or help me how can i sync my Booking Engine  Mysql database with my Amadeus Selling Plateform system.
Like if my travel agent update passenger name on  Amadeus selling platform system we need update our local database.(Mysql on my Server).So same like if we cancel/issue/confirm ticket on selling platform we need some action so we update our database.
PS: I don't want call Amadeus API again and again to keep my database updated.
Is there any cron job from Amadeus selling platform which hit my URL and tell me method name or send me json data/

**Comment by DerMika** [comment]
You will not have a choice but to keep your system synced through regular requests on the Amadeus API to get the latest status for a PNR.

I know that Amadeus also has possibilities to stream PNR updates through a queueing system, but they only implement these kinds of systems for large customers (like airlines). 

Depending on your financial resources and throughput volume, you may ask Amadeus if they can setup such a queue for you to consume. But I don't think they will do that easily.

**Comment by therealartz** [comment]
Setup cron on your side is not so bad idea. You could retrieve pnr at least once a day (at midnight). Or maybe twice a day

**Comment by DerMika** [comment]
Closing - re-open if you have any follow-up questions
