### ISSUE TITLE
Getting error 696 back from Amadeus for MultiSingle_Hotel_Availability

### ISSUE THREAD

**Issue by inodeas** [amabnl/amadeus-ws-client#389]
Hi Anyone knows what error 696 stands for?

My Multi Single Hotel Availability request was working fine before however I am getting that error today.

        "Body": {
            "OTA_HotelAvailRS": {
                "@attributes": {
                    "xsi": "http:\/\/www.w3.org\/2001\/XMLSchema-instance",
                    "xsi:schemaLocation": "http:\/\/www.opentravel.org\/OTA\/2003\/05 OTA_HotelAvailRS.xsd",
                    "EchoToken": "MultiSingle",
                    "Version": "6.001",
                    "PrimaryLangID": "EN"
                },
                "Errors": {
                    "Error": {
                        "@attributes": {
                            "Type": "1",
                            "Code": "696",
                            "Status": "1A"
                        }
                    }
                }
            }
        }
    }
}

**Comment by DerMika** [comment]
Have you checked if you can find this error code in the documentation? If not, Amadeus Support is probably the way to go.
