### ISSUE TITLE
ATC Shopper flow support

### ISSUE THREAD

**Issue by bimusiek** [amabnl/amadeus-ws-client#39]
Hey, any plans to support ATC flow? 

There are few new endpoints required, the hardest one being `Ticket_ATCShopperMasterPricerCalendar` and `Ticket_ATCShopperMasterPricerTravelBoard`.

We are in process of getting access to the second round of Amadeus certification for ATC and I was wondering if you could help us with it. :)

**Comment by DerMika** [comment]
I had not yet thought of supporting the ATC flow, no. 

About the MasterPricer messages you mention: it looks like you can re-use much of the logic built for `Fare_MasterPricerTravelBoardSearch` to implement those messages - except for the `ticketChangeInfo` node.

I can implement them, but do not expect them within a few weeks as I'm quite busy with other responsibilities at the moment. I can't really give you an estimated time right now.

What are the other messages you looking at implementing besides these two?

**Comment by bimusiek** [comment]
We have also applied for LCC support, but I see most of the messages are already integrated (the ones around DocIssuance)

About ATC, here is the list that is required to build whole flow and not yet supported:
- Ticket_CheckEligibility
- Ticket_ATCShopperMasterPricerCalendar (probably similar to MPCalendar)
- Ticket_ATCShopperMasterPricerTravelBoard (as you said, similar to MPTravelBoardSearch)
- [optional] Air_RebookAirSegment (similar to Air_SellFromRecommendation and is optional, it can be achieved by PNR_Cancel + Air_SellFromRecommendation, just saves 1 request to Amadeus)
- Ticket_RepricePNRWithBookingClass (probably similar to informative pricing)
- Ticket_ReissueConfirmedPricing
-  [optional] FOP_CreateFormOfPayment (I am not sure about this one, looks like you can achieve the same with AddMultiElements...)
- Ticket_CreateTSMFareElement 

Thats theoretically everything required for ATC support. 
I skipped Doc Issuance part for ATC, as we are not ticketing agent so we will put PNR on special queue to re-issue ticket.

**Comment by bimusiek** [comment]
@DerMika we decided to skip calendar for now, just to have some basic features working.
So just to start working on ATC, `Ticket_CheckEligibility` and `Ticket_ATCShopperMasterPricerTravelBoard` are enough. 
I could probably start working on it beginning of next month, just my PHP skills are quite rusty and obviously my Amadeus knowledge on scale 1-10 is probably at around 2 now. 🤕 

And later only `Ticket_RepricePNRWithBookingClass` `Ticket_ReissueConfirmedPricing` and `Ticket_CreateTSMFareElement`. 

I would love to buy you a beer at one point for all the help you provided, for Amadeus newbies this lib is much more understandable than Amadeus docs. 🍺 If you would ever visit Berlin, just drop me a message for 🍻 (we have one of the best beer in the world 🙉 )

**Comment by DerMika** [comment]
I will reply to the rest of your post later, but did you just tell a Belgian guy that the best beer in the world is in Berlin? What an insult! :p

**Comment by bimusiek** [comment]
Haha, I always try to play safe, that's why `one of the best` 🇩🇪  🇧🇪

**Comment by DerMika** [comment]
... I started with an easy message first ...

**Comment by DerMika** [comment]
I've started with the `Ticket_CheckEligibility` message. No promises on when it'll be ready though!

**Comment by DerMika** [comment]
2 more messages to go: `Ticket_RepricePNRWithBookingClass` and `Ticket_ReissueConfirmedPricing`.

**Comment by bimusiek** [comment]
We were supposed to get access at 27th Feb, but as we expected it is taking much longer :( Thanks for your amazing work @DerMika ! I am in ave.

**Comment by bimusiek** [comment]
We will finally get access to ATC in few days so I hope next week I will be able to play with first endpoints :) Thanks for help again!

**Comment by DerMika** [comment]
Ok, great. I'm still implementing the repricing message, which is sadly a bit like the Fare_* pricing messages but not quite the same, which means I have more work than expected to implement it :(

**Comment by DerMika** [comment]
So, I've implemented the messages you [requested](https://github.com/amabnl/amadeus-ws-client/issues/39#issuecomment-281345970). Enjoy!

If you encounter any issues, don't hesitate to re-open this case or open a new one.

I haven't implemented `Ticket_ATCShopperMasterPricerCalendar` or `Air_RebookAirSegment` for now. If you have a need for them, let me know.
