### ISSUE TITLE
Seats and prices in all classes

### ISSUE THREAD

**Issue by zafercelik** [amabnl/amadeus-ws-client#390]
Hello,

Is there a service on Amadeus where I can make a query like below and see the remaining seats and prices in all classes?

I want to get the content api like command line
![image](https://user-images.githubusercontent.com/25120180/76599801-c363b980-6516-11ea-89d0-340056d799fd.png)

**Comment by DerMika** [comment]
The soap equivalent of the AN entry is Air_Availability

**Comment by zafercelik** [comment]
Thanks for your help, @DerMika 

Air_Availability service is not included in my WSDL file, could it be a different service for the newly created WSDL?

Do you have any information on this subject?

**Comment by DerMika** [comment]
I haven't had inside Amadeus info since a few years now.

If Air_Availability is not in your wsdl, you should ask Amadeus to add it. It seems very unlikely that they would have changed the name of the operation.

**Comment by zafercelik** [comment]
Thank you @DerMika , as you mentioned, I talked to the Amadeus team and they added.
