### ISSUE TITLE
How to maintain the session throughout all the api calls

### ISSUE THREAD

**Issue by singhanil221** [amabnl/amadeus-ws-client#391]
I am using this api for Amadeus soap air apis, but I have to generate the session everytime which occurs the error, I did not find how I can manage the session throughout all the apis calls.

**Comment by DerMika** [comment]
1. use a stateful session : https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#switching-between-stateful-stateless-messages-soap-header-4

2. persist and restore the session between messages to the API: https://github.com/amabnl/amadeus-ws-client/blob/f27ddbc91e1e23d7f7cc8647d55dfedbb6eeb3ba/docs/how-to.rst#handling-sessions-with-soap-header-2
