### ISSUE TITLE
Code Not Working Someting Missing

### ISSUE THREAD

**Issue by alaskaenterprises** [amabnl/amadeus-ws-client#393]
I need pass Special parameters (FeeIds) but the code is not working.can someone check what is missing ?
PS: I'm using same code as given in sample

https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/masterpricertravelboard.rst#special-parameters-feeids

here is the response
{
    "status": "FATAL",
    "messages": [
        {
            "code": "18",
            "text": "Serializing/Deserializing error: [type = Segment] [name = pricingTickInfo] [Error = Missing mandatory item]",
            "level": "Presentation"
        }
    ],
    "response": null,
    "responseXml": "<soap:Fault xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\"><faultcode>soap:Client</faultcode><faultstring>18|Presentation|Serializing/Deserializing error: [type = Segment] [name = pricingTickInfo] [Error = Missing mandatory item]</faultstring><faultactor>SI:APA</faultactor></soap:Fault>"
}

**Comment by mohammedfarook** [comment]
Hi @alaskaenterprises I'm also getting the same error. Were you able to fix it?
