### ISSUE TITLE
Fop in details

### ISSUE THREAD

**Issue by MetaiR** [amabnl/amadeus-ws-client#396]
Hi,
this question may be not fully related to this repository
I had to implement Amadeus APIs recently for the company I am working in.

there is a concept called FOP = Form Of Payment

I am bit confused about it. what is it exactly, is it the way we declare for paying to the airlines? or it is just the way we got money from our customers?

and what are the option means? for example, there is an option called CA  standing for cash. does it mean that my customer will be charged before the flight? or the Amadeus will deal with our company by cash later on?

the real thing, I want to implement is: want to pay flights with certain options by our agency and charge them, and for the other flights by credit card? can I achieve that with fop? please help

**Comment by MetaiR** [comment]
anyone?

**Comment by DerMika** [comment]
Hi,

These kinds of functional questions are beyond the scope of this library. You are should already be paying Amadeus Support to answer these questions. 

But FOP is to declare the way you get your money from the customer. 

You can declare multiple FOP's in one PNR, so if you want the customer to only pay partially by credit card, that's certainly possible.

In the Web Services support pages, the possible options should be mentioned. If not, ask Amadeus support. 

I don't know enough about FOP to help you any more than this.

**Comment by MetaiR** [comment]
so I am a bit confused, how Amadeus will be paid? is it related to a deal and happening out of the APIs?

**Comment by DerMika** [comment]
You are working in the context of Amadeus' platform. You can be sure that they know how many segments you book and how much fee you need to pay them. 

I don't know for sure, but I assume they will just send your agency invoices. I don't know how airlines are paid.

Again, you'd better contact Amadeus Support to ask these questions, they will be able to answer you better.

**Comment by MetaiR** [comment]
thanks for ur help.
