### ISSUE TITLE
Amadeus SOAP API integration with Java

### ISSUE THREAD

**Issue by Gaurav191** [amabnl/amadeus-ws-client#397]
We are trying to integrate Amadeus SOAP web services with Java. Can anyone help us out? How to call and make headers 4.0 and requests in Java? Thanks in advance.

**Comment by rifkydj** [comment]
use this
https://github.com/amadeus4dev/amadeus-java

**Comment by Gaurav191** [comment]
Hello Thanks for your reply but it is for Self Service JSON APIs and I am looking for looking for SOAP based XML APIs solution. As I have XML and all other WSDL files regarding the project. I just want to know how we will build soap header 4 and the body request in Java. If someone can provide these details. I have spend lots of time on it but no success yet. Any help will be appreciated. Thanks in advance.

**Comment by rifkydj** [comment]
Hi, this library is made by php. As I can say u can make api s using this library in php . Then u can use it for java. And there are lots of amedias apis and you have to use them as per your business needs.

**Comment by Gaurav191** [comment]
Thanks for suggestion. I have successfully implemented APIs in Java. So now one more technology added. If anyone need help in Java and angular, I am here to help.

**Comment by bensonbenny021** [comment]
> Thanks for suggestion. I have successfully implemented APIs in Java. So now one more technology added. If anyone need help in Java and angular, I am here to help.

Hi Gaurav, I am trying to integrate amadeus APIs in Java. How can I contact you?

**Comment by sundhar-perumal** [comment]
> Thanks for suggestion. I have successfully implemented APIs in Java. So now one more technology added. If anyone need help in Java and angular, I am here to help.

Hi Gavurav, I also require this in JAVA for AMADEUS integration. Can you please assist me on the util/jar ?

**Comment by sundhar-perumal** [comment]
> > Thanks for suggestion. I have successfully implemented APIs in Java. So now one more technology added. If anyone need help in Java and angular, I am here to help.
> 
> Hi Gaurav, I am trying to integrate amadeus APIs in Java. How can I contact you?

Hi ben, Did you get any info from Gavurav regarding this. It would be helpful , if i get the util jar for AMADEUS SOAPJ JAVA

**Comment by Gaurav191** [comment]
Hi Sundhar and Ben,

Please tell me what help you need regarding Amadeus in Java. Please drop an email to gauravyadav333@gmail.com for any help. And I am extremely sorry foe late reply as I was on a vacation.

Pleaae feel free to contact me.

**Comment by Gaurav191** [comment]
> > Thanks for suggestion. I have successfully implemented APIs in Java. So now one more technology added. If anyone need help in Java and angular, I am here to help.
> 
> Hi Gaurav, I am trying to integrate amadeus APIs in Java. How can I contact you?

Contact me over gauravyadav333@gmail.com and any kind of help regarding Amadeus in Java
