### ISSUE TITLE
Enable compression

### ISSUE THREAD

**Issue by tommiehansen** [amabnl/amadeus-ws-client#4]
How do one enable compression? Can't see or find any references to it in any headers within any of the classes?

**Comment by DerMika** [comment]
I've never needed compression before. I assume you're talking about the `\SoapClient` compression option?

**Comment by DerMika** [comment]
Let me know if the commit above fixes your problem. If I understood your question, you can now set the compression by providing 'soapClientOptions' in the Session Handler parameters. 

I'll merge this to master soon-ish.

**Comment by DerMika** [comment]
Until reported otherwise, I'll assume the development mentioned above is the solution to the problem. So I'm closing this issue.

If not, please open a new issue!
