### ISSUE TITLE
PHP 7.4 tests throw deprecation warnings

### ISSUE THREAD

**Issue by DerMika** [amabnl/amadeus-ws-client#400]
Basically we need to upgrade PHPUnit, which means we need to drop support for old PHP versions. 

I don't really want to do that as I don't really have the time, but if anyone is interested in developing a 2.0 release, this should definitely be part of it.

**Comment by DerMika** [comment]
https://github.com/sebastianbergmann/phpunit/issues/3728

**Comment by therealartz** [comment]
Solved by https://github.com/amabnl/amadeus-ws-client/pull/481
