### ISSUE TITLE
issue in adding the commission element in add PNR

### ISSUE THREAD

**Issue by ahmedeltokhy** [amabnl/amadeus-ws-client#406]
Hello All
I added the Manual Commission element in the PnrCreatePnrOptions as follows
new ManualCommission([
                'passengerType' => ManualCommission::PAXTYPE_PASSENGER,
                'indicator' => 'FM',
                'percentage' => 0
            ])

but I am getting the following error when cal the function docIssuanceIssueTicket
 {
        "status": 0,
        "message": [
            {
                "code": "374",
                "text": "CMC RJT : NEED COMMISSION",
                "level": null
            }
        ],
        "data": {
            "processingStatus": {
                "statusCode": "X"
            },
            "errorGroup": {
                "errorOrWarningCodeDetails": {
                    "errorDetails": {
                        "errorCode": "374"
                    }
                },
                "errorWarningDescription": {
                    "freeTextDetails": {
                        "textSubjectQualifier": "3",
                        "source": "M",
                        "encoding": "1"
                    },
                    "freeText": "CMC RJT : NEED COMMISSION"
                }
            }
        }
    }

and when asked the Amadeus Support they told me to need to add the commission as follows:
<ns1:dataElementsIndiv>

     <ns1:elementManagementData>

         <ns1:reference>

             <ns1:qualifier>OT</ns1:qualifier>

             <ns1:number>5</ns1:number>

         </ns1:reference>

         <ns1:segmentName>FM</ns1:segmentName>

     </ns1:elementManagementData>

     <ns1:commission>

         <ns1:commissionInfo>

             <ns1:amount>5</ns1:amount>

         </ns1:commissionInfo>

     </ns1:commission>

</ns1:dataElementsIndiv>

Kindly help me add the commission as the support recommended

**Comment by DerMika** [comment]
Do you have a request log of what request message is being generated?

**Comment by ahmedeltokhy** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
                   xmlns:ns1="http://xml.amadeus.com/PNRADD_17_2_1A" xmlns:ns2="http://www.w3.org/2005/08/addressing"
                   xmlns:ns3="http://xml.amadeus.com/2010/06/Session_v3">
    <SOAP-ENV:Header>
        <ns2:MessageID>8160F627-B377-0879-073B-DA310970F7AD</ns2:MessageID>
        <ns2:Action>http://webservices.amadeus.com/PNRADD_17_2_1A</ns2:Action>
        <ns2:To>https://nodeD2.test.webservices.amadeus.com/1ASIWHES2HA</ns2:To>
        <ns3:Session TransactionStatusCode="InSeries">
            <ns3:SessionId>018K1VB0XX</ns3:SessionId>
            <ns3:SequenceNumber>2</ns3:SequenceNumber>
            <ns3:SecurityToken>2YBFXAC1Q7YEV3EYGI6B9ZKL0A</ns3:SecurityToken>
        </ns3:Session>
    </SOAP-ENV:Header>
    <SOAP-ENV:Body>
        <ns1:PNR_AddMultiElements>
            <ns1:pnrActions>
                <ns1:optionCode>0</ns1:optionCode>
            </ns1:pnrActions>
            <ns1:travellerInfo>
                <ns1:elementManagementPassenger>
                    <ns1:reference>
                        <ns1:qualifier>PR</ns1:qualifier>
                        <ns1:number>1</ns1:number>
                    </ns1:reference>
                    <ns1:segmentName>NM</ns1:segmentName>
                </ns1:elementManagementPassenger>
                <ns1:passengerData>
                    <ns1:travellerInformation>
                        <ns1:traveller>
                            <ns1:surname>HASSAN</ns1:surname>
                            <ns1:quantity>2</ns1:quantity>
                        </ns1:traveller>
                        <ns1:passenger>
                            <ns1:firstName>AHMED</ns1:firstName>
                            <ns1:type>ADT</ns1:type>
                            <ns1:infantIndicator>3</ns1:infantIndicator>
                        </ns1:passenger>
                    </ns1:travellerInformation>
                    <ns1:dateOfBirth>
                        <ns1:dateAndTimeDetails>
                            <ns1:qualifier>706</ns1:qualifier>
                            <ns1:date>04FEB87</ns1:date>
                        </ns1:dateAndTimeDetails>
                    </ns1:dateOfBirth>
                </ns1:passengerData>
                <ns1:passengerData>
                    <ns1:travellerInformation>
                        <ns1:traveller>
                            <ns1:surname>HASSAN</ns1:surname>
                        </ns1:traveller>
                        <ns1:passenger>
                            <ns1:firstName>HLA</ns1:firstName>
                            <ns1:type>INF</ns1:type>
                        </ns1:passenger>
                    </ns1:travellerInformation>
                    <ns1:dateOfBirth>
                        <ns1:dateAndTimeDetails>
                            <ns1:qualifier>706</ns1:qualifier>
                            <ns1:date>19JUL19</ns1:date>
                        </ns1:dateAndTimeDetails>
                    </ns1:dateOfBirth>
                </ns1:passengerData>
            </ns1:travellerInfo>
            <ns1:travellerInfo>
                <ns1:elementManagementPassenger>
                    <ns1:reference>
                        <ns1:qualifier>PR</ns1:qualifier>
                        <ns1:number>3</ns1:number>
                    </ns1:reference>
                    <ns1:segmentName>NM</ns1:segmentName>
                </ns1:elementManagementPassenger>
                <ns1:passengerData>
                    <ns1:travellerInformation>
                        <ns1:traveller>
                            <ns1:surname>HASSAN</ns1:surname>
                        </ns1:traveller>
                        <ns1:passenger>
                            <ns1:firstName>WIFE</ns1:firstName>
                            <ns1:type>ADT</ns1:type>
                        </ns1:passenger>
                    </ns1:travellerInformation>
                    <ns1:dateOfBirth>
                        <ns1:dateAndTimeDetails>
                            <ns1:qualifier>706</ns1:qualifier>
                            <ns1:date>14JUL89</ns1:date>
                        </ns1:dateAndTimeDetails>
                    </ns1:dateOfBirth>
                </ns1:passengerData>
            </ns1:travellerInfo>
            <ns1:travellerInfo>
                <ns1:elementManagementPassenger>
                    <ns1:reference>
                        <ns1:qualifier>PR</ns1:qualifier>
                        <ns1:number>4</ns1:number>
                    </ns1:reference>
                    <ns1:segmentName>NM</ns1:segmentName>
                </ns1:elementManagementPassenger>
                <ns1:passengerData>
                    <ns1:travellerInformation>
                        <ns1:traveller>
                            <ns1:surname>HASSAN</ns1:surname>
                        </ns1:traveller>
                        <ns1:passenger>
                            <ns1:firstName>CHILD</ns1:firstName>
                            <ns1:type>CHD</ns1:type>
                        </ns1:passenger>
                    </ns1:travellerInformation>
                    <ns1:dateOfBirth>
                        <ns1:dateAndTimeDetails>
                            <ns1:qualifier>706</ns1:qualifier>
                            <ns1:date>21DEC15</ns1:date>
                        </ns1:dateAndTimeDetails>
                    </ns1:dateOfBirth>
                </ns1:passengerData>
            </ns1:travellerInfo>
            <ns1:dataElementsMaster>
                <ns1:marker1/>
                <ns1:dataElementsIndiv>
                    <ns1:elementManagementData>
                        <ns1:reference>
                            <ns1:qualifier>OT</ns1:qualifier>
                            <ns1:number>1</ns1:number>
                        </ns1:reference>
                        <ns1:segmentName>AP</ns1:segmentName>
                    </ns1:elementManagementData>
                    <ns1:freetextData>
                        <ns1:freetextDetail>
                            <ns1:subjectQualifier>3</ns1:subjectQualifier>
                            <ns1:type>7</ns1:type>
                        </ns1:freetextDetail>
                        <ns1:longFreetext>009666597859955</ns1:longFreetext>
                    </ns1:freetextData>
                </ns1:dataElementsIndiv>
                <ns1:dataElementsIndiv>
                    <ns1:elementManagementData>
                        <ns1:reference>
                            <ns1:qualifier>OT</ns1:qualifier>
                            <ns1:number>2</ns1:number>
                        </ns1:reference>
                        <ns1:segmentName>AP</ns1:segmentName>
                    </ns1:elementManagementData>
                    <ns1:freetextData>
                        <ns1:freetextDetail>
                            <ns1:subjectQualifier>3</ns1:subjectQualifier>
                            <ns1:type>P02</ns1:type>
                        </ns1:freetextDetail>
                        <ns1:longFreetext>aaa.computerscience@gmail.com</ns1:longFreetext>
                    </ns1:freetextData>
                </ns1:dataElementsIndiv>
                <ns1:dataElementsIndiv>
                    <ns1:elementManagementData>
                        <ns1:reference>
                            <ns1:qualifier>OT</ns1:qualifier>
                            <ns1:number>3</ns1:number>
                        </ns1:reference>
                        <ns1:segmentName>FP</ns1:segmentName>
                    </ns1:elementManagementData>
                    <ns1:formOfPayment>
                        <ns1:fop>
                            <ns1:identification>CA</ns1:identification>
                        </ns1:fop>
                    </ns1:formOfPayment>
                </ns1:dataElementsIndiv>
                <ns1:dataElementsIndiv>
                    <ns1:elementManagementData>
                        <ns1:reference>
                            <ns1:qualifier>OT</ns1:qualifier>
                            <ns1:number>4</ns1:number>
                        </ns1:reference>
                        <ns1:segmentName>TK</ns1:segmentName>
                    </ns1:elementManagementData>
                    <ns1:ticketElement>
                        <ns1:passengerType>PAX</ns1:passengerType>
                        <ns1:ticket>
                            <ns1:indicator>OK</ns1:indicator>
                        </ns1:ticket>
                    </ns1:ticketElement>
                </ns1:dataElementsIndiv>
                <ns1:dataElementsIndiv>
                    <ns1:elementManagementData>
                        <ns1:reference>
                            <ns1:qualifier>OT</ns1:qualifier>
                            <ns1:number>5</ns1:number>
                        </ns1:reference>
                        <ns1:segmentName>FM</ns1:segmentName>
                    </ns1:elementManagementData>
                    <ns1:commission>
                        <ns1:passengerType>PAX</ns1:passengerType>
                        <ns1:indicator>FM</ns1:indicator>
                        <ns1:commissionInfo>
                            <ns1:percentage>0</ns1:percentage>
                        </ns1:commissionInfo>
                    </ns1:commission>
                </ns1:dataElementsIndiv>
                <ns1:dataElementsIndiv>
                    <ns1:elementManagementData>
                        <ns1:reference>
                            <ns1:qualifier>OT</ns1:qualifier>
                            <ns1:number>6</ns1:number>
                        </ns1:reference>
                        <ns1:segmentName>SSR</ns1:segmentName>
                    </ns1:elementManagementData>
                    <ns1:serviceRequest>
                        <ns1:ssr>
                            <ns1:type>DOCS</ns1:type>
                            <ns1:status>HK</ns1:status>
                            <ns1:quantity>1</ns1:quantity>
                            <ns1:freetext>P-EGY-1312312312-EGY-04FEB87-M-09Mar22-HASSAN-AHMED-</ns1:freetext>
                        </ns1:ssr>
                    </ns1:serviceRequest>
                    <ns1:referenceForDataElement>
                        <ns1:reference>
                            <ns1:qualifier>PR</ns1:qualifier>
                            <ns1:number>1</ns1:number>
                        </ns1:reference>
                    </ns1:referenceForDataElement>
                </ns1:dataElementsIndiv>
                <ns1:dataElementsIndiv>
                    <ns1:elementManagementData>
                        <ns1:reference>
                            <ns1:qualifier>OT</ns1:qualifier>
                            <ns1:number>7</ns1:number>
                        </ns1:reference>
                        <ns1:segmentName>SSR</ns1:segmentName>
                    </ns1:elementManagementData>
                    <ns1:serviceRequest>
                        <ns1:ssr>
                            <ns1:type>DOCS</ns1:type>
                            <ns1:status>HK</ns1:status>
                            <ns1:quantity>1</ns1:quantity>
                            <ns1:freetext>P-EGY-1312312312-EGY-19JUL19-FI-10Aug24-HASSAN-HLA-</ns1:freetext>
                        </ns1:ssr>
                    </ns1:serviceRequest>
                    <ns1:referenceForDataElement>
                        <ns1:reference>
                            <ns1:qualifier>PR</ns1:qualifier>
                            <ns1:number>1</ns1:number>
                        </ns1:reference>
                    </ns1:referenceForDataElement>
                </ns1:dataElementsIndiv>
                <ns1:dataElementsIndiv>
                    <ns1:elementManagementData>
                        <ns1:reference>
                            <ns1:qualifier>OT</ns1:qualifier>
                            <ns1:number>8</ns1:number>
                        </ns1:reference>
                        <ns1:segmentName>SSR</ns1:segmentName>
                    </ns1:elementManagementData>
                    <ns1:serviceRequest>
                        <ns1:ssr>
                            <ns1:type>DOCS</ns1:type>
                            <ns1:status>HK</ns1:status>
                            <ns1:quantity>1</ns1:quantity>
                            <ns1:freetext>P-EGY-1312312312-EGY-14JUL89-F-09Mar22-HASSAN-WIFE-</ns1:freetext>
                        </ns1:ssr>
                    </ns1:serviceRequest>
                    <ns1:referenceForDataElement>
                        <ns1:reference>
                            <ns1:qualifier>PR</ns1:qualifier>
                            <ns1:number>3</ns1:number>
                        </ns1:reference>
                    </ns1:referenceForDataElement>
                </ns1:dataElementsIndiv>
                <ns1:dataElementsIndiv>
                    <ns1:elementManagementData>
                        <ns1:reference>
                            <ns1:qualifier>OT</ns1:qualifier>
                            <ns1:number>9</ns1:number>
                        </ns1:reference>
                        <ns1:segmentName>SSR</ns1:segmentName>
                    </ns1:elementManagementData>
                    <ns1:serviceRequest>
                        <ns1:ssr>
                            <ns1:type>DOCS</ns1:type>
                            <ns1:status>HK</ns1:status>
                            <ns1:quantity>1</ns1:quantity>
                            <ns1:freetext>P-EGY-1312312312-EGY-21Dec15-F-09Mar22-HASSAN-CHILD-</ns1:freetext>
                        </ns1:ssr>
                    </ns1:serviceRequest>
                    <ns1:referenceForDataElement>
                        <ns1:reference>
                            <ns1:qualifier>PR</ns1:qualifier>
                            <ns1:number>4</ns1:number>
                        </ns1:reference>
                    </ns1:referenceForDataElement>
                </ns1:dataElementsIndiv>
                <ns1:dataElementsIndiv>
                    <ns1:elementManagementData>
                        <ns1:reference>
                            <ns1:qualifier>OT</ns1:qualifier>
                            <ns1:number>11</ns1:number>
                        </ns1:reference>
                        <ns1:segmentName>RF</ns1:segmentName>
                    </ns1:elementManagementData>
                    <ns1:freetextData>
                        <ns1:freetextDetail>
                            <ns1:subjectQualifier>3</ns1:subjectQualifier>
                            <ns1:type>P22</ns1:type>
                        </ns1:freetextDetail>
                        <ns1:longFreetext>my test project amabnl-amadeus-ws-client-1.9.0</ns1:longFreetext>
                    </ns1:freetextData>
                </ns1:dataElementsIndiv>
            </ns1:dataElementsMaster>
        </ns1:PNR_AddMultiElements>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>`

**Comment by DerMika** [comment]
It looks like the ManualCommission element in this library does not yet support the `amount` property.

**Comment by DerMika** [comment]
It is supported, it's just not mentioned in the sample docs: 

```
new ManualCommission([
    'passengerType' => ManualCommission::PAXTYPE_PASSENGER,
    'indicator' => 'FM',
    'amount' => 5
])
```

**Comment by ahmedeltokhy** [comment]
Hello 
I tried it but the generated XML is different than the Amadeus support suggest as follows:
`         <ns1:dataElementsIndiv>
                    <ns1:elementManagementData>
                        <ns1:reference>
                            <ns1:qualifier>OT</ns1:qualifier>
                            <ns1:number>5</ns1:number>
                        </ns1:reference>
                        <ns1:segmentName>FM</ns1:segmentName>
                    </ns1:elementManagementData>
                    <ns1:commission>
                        <ns1:passengerType>PAX</ns1:passengerType>
                        <ns1:indicator>FM</ns1:indicator>
                        <ns1:commissionInfo>
                            <ns1:amount>5</ns1:amount>
                        </ns1:commissionInfo>
                    </ns1:commission>
                </ns1:dataElementsIndiv>`

Amadeus support recommended XML:
`<ns1:dataElementsIndiv>

     <ns1:elementManagementData>

         <ns1:reference>

             <ns1:qualifier>OT</ns1:qualifier>

             <ns1:number>5</ns1:number>

         </ns1:reference>

         <ns1:segmentName>FM</ns1:segmentName>

     </ns1:elementManagementData>

     <ns1:commission>

         <ns1:commissionInfo>

             <ns1:amount>5</ns1:amount>

         </ns1:commissionInfo>

     </ns1:commission>

</ns1:dataElementsIndiv>`

**Comment by DerMika** [comment]
Have you tried with providing only the "amount" property in the `ManualCommission` element?

**Comment by ahmedeltokhy** [comment]
I tried and it works
thanks a lot.
