### ISSUE TITLE
Adding Title before passenger name When creating PNR

### ISSUE THREAD

**Issue by XYNOMEX** [amabnl/amadeus-ws-client#410]
Dear,

Some Airlines like TK now require a specific title to be added in front of the passenger name when creating PNR.
In my case TK (Turkish Airline) require the following:
Message from TK: It is mandatory to insert the title next to the passengers name mentioned below >
- MS > Female passenger traveling alone, marital status unknown.
- MRS > Married female passenger older than 12.
- MR > Male passenger older than 12.
- MSTR > Male child or infant between ages 0-12.
- MISS > Female child or infant between ages 0-12.

I would like to know how this can be implemented in your API?

thank you. @DerMika

**Comment by DerMika** [comment]
I think that's the `travellerType` option in https://github.com/amabnl/amadeus-ws-client/blob/master/src/Amadeus/Client/RequestOptions/Pnr/Traveller.php

You can use one of the defined constants or supply your own traveller type.

**Comment by XYNOMEX** [comment]
Thank you for your help.
