### ISSUE TITLE
two tickets in one transaction

### ISSUE THREAD

**Issue by tolya1984a** [amabnl/amadeus-ws-client#411]
Good afternoon.

Does anyone know if it is possible to get a statement (docIssuanceIssueTicket) two tickets in one transaction?
That is, there are two bookings with different PNRs, is it possible to complete them in one transaction?
This is necessary in order if one of the booking is canceled, in order to cancel both without finishing the process

**Comment by rifkydj** [comment]
i guess it can be done by PNR Split. 
After Issuing The Ticket or before issuing Ticket You Can SPLIT them. 
For More Info Contact Amadeus.

**Comment by DerMika** [comment]
Closing ticket - you can re-open if you have further questions
