### ISSUE TITLE
Basic fare and total fare in Fare_MasterPricerTravelBoardSearch

### ISSUE THREAD

**Issue by Gaurav191** [amabnl/amadeus-ws-client#412]
guys can you help me, I am implementing Amadeus and I want to know that how to get base fare and total fare in the search response. As I am getting total fare and total tax in the response. I want to know that :

 PaxFareDetails contains totalFareAmount and totalTaxAmount. And also YQ, YR and Q fares.

Should I add these all components to get total fare or totalFareAmount  contains total fare?

In above code, it is the total fare or I have to add tax in this fare? what is the base fare in this as I want to show fare break up as well. Its urgent. Please help me.

Thanks in advance. @DerMika

**Comment by Gaurav191** [comment]
Got the answer thanks

**Comment by DerMika** [comment]
It would be great if you described the answer here, for future reference
