### ISSUE TITLE
Passenger Type Request Generated Wrong

### ISSUE THREAD

**Issue by deep12650** [amabnl/amadeus-ws-client#414]
Hello Team,

I am sending a request with following passengers parameter:
`[passengers] => Array
        (
            [0] => Amadeus\Client\RequestOptions\Fare\MPPassenger Object
                (
                    [type] => ADT
                    [count] => 1
                )

            [1] => Amadeus\Client\RequestOptions\Fare\MPPassenger Object
                (
                    [type] => CNN
                    [count] => 0
                )

            [2] => Amadeus\Client\RequestOptions\Fare\MPPassenger Object
                (
                    [type] => INF
                    [count] => 0
                )
        )`

BUT the request is sending CNN 2 where requested 0 and INF 1 instead of 0 :

`<ns1:paxReference>
<ns1:ptc>ADT</ns1:ptc>
<ns1:traveller>
<ns1:ref>1</ns1:ref>
</ns1:traveller>
</ns1:paxReference>
<ns1:paxReference>
<ns1:ptc>CNN</ns1:ptc>
<ns1:traveller>
<ns1:ref>2</ns1:ref>
</ns1:traveller>
</ns1:paxReference>
<ns1:paxReference>
<ns1:ptc>INF</ns1:ptc>
<ns1:traveller>
<ns1:ref>1</ns1:ref>
<ns1:infantIndicator>1</ns1:infantIndicator>
</ns1:traveller>
</ns1:paxReference>` 

I am using the following code to request MasterPricerTravelBoardSearch:
`
$noOfPassengers = 0;
        $passengers = [];
        foreach ($request['passenger'] as $passenger) {
            $passengers[] = new MPPassenger([
                'type' => $passenger["type"],
                'count' => intval($passenger["count"])
            ]);

            if ($passenger["type"] != "INF" && intval($passenger["count"] !=0)) {
                $noOfPassengers = $noOfPassengers + 1;
            }
        }
        foreach ($request['itinerary'] as $item) {
            $itinerary[] = new MPItinerary([
                'departureLocation' => new MPLocation(['city' => $item["departureLocation"]]),
                'arrivalLocation' => new MPLocation(['city' => $item["arrivalLocation"]]),
                'date' => new MPDate([
                    'dateTime' => Carbon::parse($item['departureDate']),
                    'range' => 1
                ])
            ]);
        }
        $opt = new FareMasterPricerTbSearch([
            'nrOfRequestedResults' => $request['nrOfRequestedResults'],
            'nrOfRequestedPassengers' => $noOfPassengers,
            'passengers' => $passengers,
            'itinerary' => $itinerary,
            'currencyOverride' => $request['currency'],
            'requestedFlightTypes' => $request['flightType'],
            'flightOptions' => [
                FareMasterPricerTbSearch::FLIGHTOPT_PUBLISHED,
                FareMasterPricerTbSearch::FLIGHTOPT_UNIFARES,
                FareMasterPricerTbSearch::FLIGHTOPT_ELECTRONIC_TICKET,
            ],
            'feeIds' => [
                new MPFeeId(['type' => MPFeeId::FEETYPE_FARE_FAMILY_INFORMATION, 'number' => 2])
            ],
            'cabinClass' => ["Y"],
        ]);
        $resultXml = new FareMasterPricerTbSearch($opt);
        $response = $client->fareMasterPricerTravelBoardSearch($resultXml);
        return $response;
`
I couldn't able to figure out why is this happening, please help needed in this urgent issue. Thanks

**Comment by DerMika** [comment]
I don't really understand what you're trying to do. 

`nrOfRequestedPassengers` should contain the total amount of passengers you're doing the masterpricer request for.

`passengers` array should contain the types of passengers and the amounts for each type. The total should match the amount in `nrOfRequestedPassengers`.

I have never tried to see what happens if you provide a count of `0` in the passengers array. You should probably not add an entry to the passengers array if the count is 0.

**Comment by deep12650** [comment]
@DerMika I could able to solve that by not passing 0 value in the request. I need one more help with Mini Rules with travel board recommendation, I am receiving following response with refQualifier 'M' which stands for MiniRulesGroup. Which Minirules option will be applicable to get information with reference ID:
![Screen Shot 2020-09-21 at 8 28 33 PM](https://user-images.githubusercontent.com/12050549/93746368-19918200-fc49-11ea-920e-a2484099c336.png)
![Screen Shot 2020-09-21 at 8 28 56 PM](https://user-images.githubusercontent.com/12050549/93746372-1bf3dc00-fc49-11ea-8461-4793aedc22b7.png)

**Comment by DerMika** [comment]
If your initial problem is solved, please close this ticket and create a new one.
