### ISSUE TITLE
MiniRule_GetFromRec is missing

### ISSUE THREAD

**Issue by deep12650** [amabnl/amadeus-ws-client#415]
Hi there,

MiniRule_GetFromRec 18.01 Webservice is missing. it is the latest one which will get all future updates, rest of the seams like abandoned.

"Mini Rules provides a short and easy to read summary of the most important rules and restrictions in a structured output so that they can be clearly understood by end-users and customers. This service is used to retrieve the Mini Rules data from: - PNR Record Locator - Offer Notice - Offer ID - TST (Transitional Stored Ticket) - PQR (Quotation Record for Amadeus Offer). - Pricing context - Upsell Context - TKT (eTicket) - Cart (Shopping cart)"

Thanks,
<img width="1408" alt="Screen Shot 2020-09-23 at 11 23 33 PM" src="https://user-images.githubusercontent.com/12050549/94006407-e4756300-fdf3-11ea-98f0-0d9f8acc312b.png">
<img width="1413" alt="Screen Shot 2020-09-23 at 11 23 43 PM" src="https://user-images.githubusercontent.com/12050549/94006417-e808ea00-fdf3-11ea-9d35-1fe3473c6a42.png">

**Comment by DerMika** [comment]
I suggest you provide a PR to implement this message. I no longer have access to the docs (plus I don't have the time).

**Comment by deep12650** [comment]
Documentation related to this topic: 
[User guide _ Amadeus for Developers.pdf](https://github.com/amabnl/amadeus-ws-client/files/5267868/User.guide._.Amadeus.for.Developers.pdf)

**Comment by gregsparrow** [comment]
I also working on this matter. So I already implemented this message and create a pull request. Just need to do some fix, coz tests failing.

**Comment by gregsparrow** [comment]
@DerMika Сan you please rollout new release based on this #417 PR, may be during this week? Our project is heavily dependent on this new functionality. Thanks in advance!

**Comment by gregsparrow** [comment]
@DerMika Hello. When you will have a time, please merge this PR #417

**Comment by DerMika** [comment]
Allright, I finally got around to it. Looks like the PR includes everything needed, thanks a lot!

**Comment by gregsparrow** [comment]
> Allright, the PR added some style issues, can you fix them please? https://github.styleci.io/analyses/WN0yMJ

Done
