### ISSUE TITLE
Mini Rules with Travel Board Search

### ISSUE THREAD

**Issue by deep12650** [amabnl/amadeus-ws-client#416]
I need help with Mini Rules with travel board recommendation, I am receiving following response with refQualifier 'M' which stands for MiniRulesGroup. Which Mini rules option will be applicable to get information with reference ID:
![Screen Shot 2020-09-21 at 8 28 33 PM](https://user-images.githubusercontent.com/12050549/93746368-19918200-fc49-11ea-920e-a2484099c336.png)
![Screen Shot 2020-09-21 at 8 28 56 PM](https://user-images.githubusercontent.com/12050549/93746372-1bf3dc00-fc49-11ea-8461-4793aedc22b7.png)

**Comment by gregsparrow** [comment]
@deep12650 Can you give a hint how you get this mini rules at MasterPrice response ? I've tried to use MNR option without luck...

**Comment by deep12650** [comment]
> @deep12650 Can you give a hint how you get this mini rules at MasterPrice response ? I've tried to use MNR option without luck...

Just pass this `FareMasterPricerTbSearch::FLIGHTOPT_MINIRULES,` in flightOptions. But the free text is not coming only code.

**Comment by DerMika** [comment]
You should ask Amadeus. I don't know either.
