### ISSUE TITLE
$client->SecuritySignOut() is creating a new session instead of closing existing one.

### ISSUE THREAD

**Issue by dil-hf** [amabnl/amadeus-ws-client#428]
No, a Signout has to be implemented by you yourself. Otherwise you will have problems when trying to get the application certified by Amadeus (which is needed for production access). That is because an active session uses server resources on Amadeus' infrastructure. 

[Session signout is explained here](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#ending-a-stateful-session-soap-header-4)

_Originally posted by @DerMika in https://github.com/amabnl/amadeus-ws-client/issues/151#issuecomment-367333636_

Hi @DerMika
Following your thought above, I was trying to implement the SecuritySignOut message to release the current session but instead of that it is creating a new session and ending this one only. So then I had always a session unclosed.
Please help me, I need it for UAT.
[log.txt](https://github.com/amabnl/amadeus-ws-client/files/5965101/log.txt)

**Comment by DerMika** [comment]
I can only imagine that at the moment you do your signout call, you no longer have the session in context.

You should review when the client gets initialized in your code, and what its lifespan is.

I can assure you this is working just fine - this library has been around 5 years now.

**Comment by dil-hf** [comment]
Hi,
Thank you for fast reply.

I have edited my questiong by adding a log file.
Also see how I am doing in my code.

I have a trait class with this: 

`
 public $params;
 public function sendPnrRetrieveCall($pnr)
    {
            $client = new Client($this->params);
            $pnrResult =  $client->pnrRetrieve(
                new PnrRetrieveOptions(['recordLocator' => $pnr])
            );
            if ($pnrResult->status === Result::STATUS_OK) {
                $pnrResult = $this->sendDisplayTstCall($client); // send TSTrequest for price
            }else{
                $pnrResult = $client->securitySignOut(); //Terminates an active stateful session.
            }
    }


    public function sendDisplayTstCall(Client $client)
    {
        // $client = new Client($this->params);
        return $client->ticketDisplayTST(
            new TicketDisplayTstOptions([
                'displayMode' => TicketDisplayTstOptions::MODE_ALL
            ]),
            ['endSession' => true]
        );
    }`

**Comment by dil-hf** [comment]
> You should review when the client gets initialized in your code, and what its lifespan is.

Yes, I checked this too.
I just made a test by calling SecuritySignOut() directly after a PNR retrieve call and having the same issue.
I am maybe doing something wrong.

**Comment by dil-hf** [comment]
Hi @DerMika 

Please have a look at the below comments.
I have tested in all manner but SecuritySignOut still creates a new session without closing the previous one.

Thank you for your help.

**Comment by DerMika** [comment]
Make sure you validate that your initial call actually succeeds in signing in. 

If your initial call fails to sign in, i'm not sure what the result will be.

**Comment by dil-hf** [comment]
Thank you for your reply @DerMika .

I just tested when pnr_retrieve call succeed and SecuritySignOut call work perfectly by closing the session.
But when the pnr_retrieve call failed, I mean by sending a wrong PNR, the SecuritySignOut call creates a new session by sending TransactionStatusCode="start".

So my problem is when the previous call failed. I still have session ID and I want to close that session by sending a SecuritySignOut call.
I am dealing with only three messages: pnrRetrieve ,ticketDisplayTST and SecuritySignOut .

**Comment by DerMika** [comment]
Since it's been years i've worked with PHP and no longer have access to Amadeus, I suggest the best course of action is for you to either avoid this problem by checking if you have an active session before sending a signout (check `$client->getSessionData();`) or by investigating yourself and providing a PR that fixes the problem.

**Comment by dil-hf** [comment]
> I suggest the best course of action is for you to either avoid this problem by checking if you have an active session before sending a signout (check `$client->getSessionData();`)

I checked that but it still sending a TransactionStatusCode="start".

I will try to investigate the library. 

Thank you @DerMika for your time.

**Comment by DerMika** [comment]
Closing this as you've created a new issue for the same problem
