### ISSUE TITLE
HotelDescriptiveInfoRQ

### ISSUE THREAD

**Issue by stevensoe0524** [amabnl/amadeus-ws-client#435]
Any chance of sample php for integrating HotelDescriptiveInfoRQ WSAP please? 
Appreciate very much!

**Comment by DerMika** [comment]
I'd suggest you look at previous PR's where new messages were implemented.

https://github.com/amabnl/amadeus-ws-client/blob/master/CONTRIBUTING.md#when-adding-a-new-message

**Comment by stevensoe0524** [comment]
thanks much.
