### ISSUE TITLE
CTCE,  CTCM

### ISSUE THREAD

**Issue by tolya1984a** [amabnl/amadeus-ws-client#437]
Good afternoon, colleagues.

Do you know, how correctly implement the following:
Airlines began to require the passenger's phone number and email at the SSR point:

10 SSR CTCE SU HK1 TEMP // MAIL.RU
11 SSR CTCM SU HK1 7915XXXXXXX

How is this implemented through the API?

Thank you.

**Comment by rifkydj** [comment]
https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples.rst#pnr_addmultielements

**Comment by tolya1984a** [comment]
how correctly implement request should be?

I.e:
use Amadeus\Client\RequestOptions\PnrCreatePnrOptions;
use Amadeus\Client\RequestOptions\Pnr\Element\ServiceRequest;
use Amadeus\Client\RequestOptions\Pnr\Reference;

$opt = new PnrCreatePnrOptions([
    'elements' => [
        new ServiceRequest([
            'type' => 'CTCE',
            'references' => [
                new Reference([
                    'type' => Reference::TYPE_PASSENGER_TATTOO,
                    'id' => 1
                ])
            ]
        ])
    ]
]);

**Comment by rifkydj** [comment]
$opt->elements[] = new Contact([
    'type' => Contact::TYPE_PHONE_MOBILE,
    'value' => '+3222222222'
]);

**Comment by tolya1984a** [comment]
it's not that.

It will be:

_3 APE temp@mail.ru
4 APM +7921*******_

Airlines began to require the passenger's phone number and email at the **SSR** point:

_10 SSR CTCE SU HK1 TEMP // MAIL.RU
11 SSR CTCM SU HK1 7915*******_




> $opt->elements[] = new Contact([
> 'type' => Contact::TYPE_PHONE_MOBILE,
> 'value' => '+3222222222'
> ]);

**Comment by rifkydj** [comment]
Im not sure this ServiceRequest Class has  Such Parameters as phone number and email,  but in that u can pass a Free text field,
try that .
u can see supported parameters in
amabnl/amadeus-ws-client/src/Amadeus/Client/RequestOptions/Pnr/Element/ServiceRequest.php file

**Comment by tolya1984a** [comment]
You write what I think.
 But one detail is missing is the two-digit code for the 'freeText' field.
 I mean for SSR DOCS:
 'freeText' => [
   **P-**<PASSPORT_ISSUING_COUNTRY> - <PASSPORT_NR> - <NATIONALITY> - <BIRTHDAY> - <GENDER> - <PASSPORT_EXPIRATION_DATE> - <LAST_NAME> - <FIRST_NAME> _ <MIDDLE_NAME>
 ],
 for SSR FOID:
 'freeText' => [
   **PP**<DocumentNumber>
 ].

 I was tried without this code at the beginning of the record is not entered.
 What is the code for the **phone number** and **email**?

**Comment by rifkydj** [comment]
`if($data_array['traveler_type'][$key]=="ADT") {
				$travllers[]= new Traveller([
					'number' => $key+1,
					'lastName' => $traveler_lname,
					'firstName' => $fname,
					'travellerType' => Traveller::TRAV_TYPE_ADULT,
				]);

				$person_array=array('traveler_name_number'=>$data_array['traveler_name_number'][$key],'key'=>$key+1,'gender'=>$data_array['traveler_type'][$key]);
				array_push($ref_array,$person_array);
				
					if(!empty($traveler_passport_no)){
					//passport
					$elements[]= new ServiceRequest([
		            'type' => 'DOCS',
		            'status' => ServiceRequest::STATUS_HOLD_CONFIRMED,
		            //'company' => '1A',
		            'quantity' => 1,
		            'freeText' => [
		               'P-'.$traveler_passport_name.'-'.$traveler_passport_no.'-'.$traveler_passport_name.'-'.$this->convertDate($traveler_dob).'-'.$traveler_gender.'-'.$this->convertDate($traveler_passport_expire).'-'.$traveler_lname.'-'.$fname
		            ],
		            'references' => [
		                new Reference([
		                    'type' => Reference::TYPE_PASSENGER_REQUEST,
		                    'id' => $ref
		                ])
		            ]
		        ]);
		        }`

this is what i did for SSR Docs

**Comment by rifkydj** [comment]
this is the documentation
https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/pnr-create-modify.rst#special-service-requests-sr

**Comment by rifkydj** [comment]
` $elements[] = new ServiceRequest([
                        'type' => 'DOCS',
                        'status' => ServiceRequest::STATUS_HOLD_CONFIRMED,
                        //'company' => '1A',
                        'quantity' => 1,
                        'freeText' => [
                            'P-' . $traveler_passport_name . '-' . $traveler_passport_no . '-' . $traveler_passport_name . '-' . $this->convertDate($traveler_dob) . '-' . $traveler_gender . '-' . $this->convertDate($traveler_passport_expire) . '-' . $traveler_lname . '-' . $fname
                        ],
                        'references' => [
                            new Reference([
                                'type' => Reference::TYPE_PASSENGER_REQUEST,
                                'id' => $ref
                            ])
                        ]
                    ]);`

**Comment by tolya1984a** [comment]
"E-mail address

To add an e-mail address to an SSR, enter:

(example for xxx_yyy@work.com)

SR CTCE-BA HK1/XXX..YYY//WORK.COM
Entry 	Description
// 	(double slash) instead of @ (at sign)
.. 	(double dot) instead of _ (underscore)
./ 	(dot slash) instead of - (dash)


    For more information, refer to the Amadeus Help pages HE SR and scroll for E-mail"

How to implement this?

https://servicehub.amadeus.com/c/portal/view-solution/968144/en_US/how-to-add-ssr-elements-to-a-pnr-cryptic-

**Comment by rifkydj** [comment]
$elements[] = new ServiceRequest([
                        'type' => 'DOCS',
                        'status' => ServiceRequest::STATUS_HOLD_CONFIRMED,
                        //'company' => '1A',
                        'quantity' => 1,
                        'freeText' => [
                            'P-' . $traveler_passport_name . '-' . $traveler_passport_no . '-' . $traveler_passport_name . '-' . $this->convertDate($traveler_dob) . '-' . $traveler_gender . '-' . $this->convertDate($traveler_passport_expire) . '-' . $traveler_lname . '-' . $fname
                        ],
                        'references' => [
                            new Reference([
                                'type' => Reference::TYPE_PASSENGER_REQUEST,
                                'id' => $ref
                            ])
                        ]
                    ]);

**Comment by tolya1984a** [comment]
"E-mail address

To add an e-mail address to an SSR, enter:

(example for xxx_yyy@work.com)

SR CTCE-BA HK1/XXX..YYY//WORK.COM
Entry Description
// (double slash) instead of @ (at sign)
.. (double dot) instead of _ (underscore)
./ (dot slash) instead of - (dash)

For more information, refer to the Amadeus Help pages HE SR and scroll for E-mail"
How to implement this?

https://servicehub.amadeus.com/c/portal/view-solution/968144/en_US/how-to-add-ssr-elements-to-a-pnr-cryptic-

**Comment by rifkydj** [comment]
$elements[] = new Ticketing([
            'ticketMode' => Ticketing::TICKETMODE_OK
        ]);
        $elements[] = new Contact([
            'type' => Contact::TYPE_PHONE_BUSINESS,
            'value' => '0772323232323-H',
        ]);
        $elements[] = new Contact([
            'type' => Contact::TYPE_PHONE_MOBILE,
            'value' => '0777777777-M',
        ]);
        $elements[] = new Address([
            'type' => Address::TYPE_MAILING_UNSTRUCTURED,
            'freeText' => ''
        ]);

        $elements[] = new Contact([
            'type' => Contact::TYPE_EMAIL,
            'value' => ''
        ]);

**Comment by tolya1984a** [comment]
"E-mail address

To add an e-mail address to an SSR, enter:

(example for xxx_yyy@work.com)

SR CTCE-BA HK1/XXX..YYY//WORK.COM
Entry Description
// (double slash) instead of @ (at sign)
.. (double dot) instead of _ (underscore)
./ (dot slash) instead of - (dash)

For more information, refer to the Amadeus Help pages HE SR and scroll for E-mail"
How to implement this?
**Airlines began to require the passenger's phone number and email at the SSR point.**

https://servicehub.amadeus.com/c/portal/view-solution/968144/en_US/how-to-add-ssr-elements-to-a-pnr-cryptic-

**Comment by rifkydj** [comment]
` $elements[] = new ServiceRequest([
                                    'type' => 'E-MAIL',
                                    'status' => ServiceRequest::STATUS_HOLD_CONFIRMED,
                                    'freeText' => [
                                                    'XXX..YYY//WORK.COM'
                                                ],
                                    'references' => [
                                        new Reference([
                                            'type' => Reference::TYPE_PASSENGER_REQUEST,
                                            'id' => $ref
                                        ]),
                                    ]
                                ]);`
`

**Comment by joseayram** [comment]
@tolya1984a Hello! I added the CTCE and CTCM information to PNR_AddMultiElements. It's something like this:

`$email = str_replace('@', '//', $passenger['email'] );
$email = str_replace('_', '..', $email );
$email = str_replace('-', './', $email );

$opt->elements[] = new ServiceRequest([
    'type' => 'CTCE',
    'company' => 'AA',
    'indicator' => 'P01',
    'freeText' => $email,
    'references' => [
        new Reference([
            'type' => Reference::TYPE_PASSENGER_REQUEST,
            'id' => $number+1,
        ])
    ],
]);

$opt->elements[] = new ServiceRequest([
    'type' => 'CTCM',
    'company' => 'AA',
    'indicator' => 'P01',
    'freeText' => $phone,
    'references' => [
        new Reference([
            'type' => Reference::TYPE_PASSENGER_REQUEST,
            'id' => $number+1,
        ])
    ],
]);`
