### ISSUE TITLE
How can I make requests to be stateful?

### ISSUE THREAD

**Issue by evil1** [amabnl/amadeus-ws-client#442]
Hello!
Thansk for the great library!
Tell me please, how can I make requests to be stateful?

**Comment by DerMika** [comment]
That's explained in the docs: https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#switching-between-stateful-stateless-messages-soap-header-4

**Comment by evil1** [comment]
@DerMika Thank you! I will check and close the issue if no futher questions.
