### ISSUE TITLE
psr/log version conflict with Laravel 10

### ISSUE THREAD

**Issue by skills-up** [amabnl/amadeus-ws-client#461]
Hello,

I've been using this library for my earlier project since 2019. Recently, I've started a new related project, this time with Laravel 10.x.

When I'm trying to install this library, I'm getting an error, as the psr/log version is locked at 3.0, whereas this library only supports upto psr/log 1.1.4
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires amabnl/amadeus-ws-client 1.13.0 -> satisfiable by amabnl/amadeus-ws-client[v1.13.0].
    - amabnl/amadeus-ws-client v1.13.0 requires psr/log ^1.0 -> found psr/log[1.0.0, ..., 1.1.4] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
```

Is there a way to quickly resolve this by bumping the psr/log version in dependencies?

Thanks!

**Comment by puggan** [comment]
I see that Mustafagoda have tried to bump it, think I'll try his branch https://github.com/mustafagoda/amadeus-ws-client

**Comment by therealartz** [comment]
Solved by https://github.com/amabnl/amadeus-ws-client/pull/475, https://github.com/amabnl/amadeus-ws-client/pull/476
Should work fine now in v1.14 or v2.0
