### ISSUE TITLE
Unable to install Amadeus library

### ISSUE THREAD

**Issue by teckgeekz** [amabnl/amadeus-ws-client#470]
Problem 1
    - amabnl/amadeus-ws-client[v1.0.0, ..., v1.3.0] require psr/log 1.0.0 -> found psr/log[1.0.0] but it conflicts with your root composer.json require (^3.0).
    - amabnl/amadeus-ws-client[v1.3.1, ..., v1.13.0] require psr/log ^1.0 -> found psr/log[1.0.0, ..., 1.1.4] but it conflicts with your root composer.json require (^3.0).
    - Root composer.json requires amabnl/amadeus-ws-client * -> satisfiable by amabnl/amadeus-ws-client[v1.0.0, ..., v1.13.0].

 Problem 2
    - Root composer.json requires amabnl/amadeus-ws-client 1.13.0 -> satisfiable by amabnl/amadeus-ws-client[v1.13.0].
    - amabnl/amadeus-ws-client v1.13.0 requires psr/log ^1.0 -> found psr/log[1.0.0, ..., 1.1.4] but it conflicts with your root composer.json require (^3.0).

Tried Methods:
   - Tried installing with PSR log 1.0.0
   - Tried installing with PSR log 3.0.0

Also tried installing satisfiable versions, still failing with errors.

**Comment by DerMika** [comment]
If you can fix it with a PR, I can merge it.

**Comment by danieladarve** [comment]
Hello @DerMika I have bumped the library in this PR https://github.com/amabnl/amadeus-ws-client/pull/475
