### ISSUE TITLE
This package does not support in laravel 10 

### ISSUE THREAD

**Issue by Riwash-thamsarku** [amabnl/amadeus-ws-client#474]
I am using laravel 8 and this package i try to upgrade to laravel 10 but facing error of requires psr/log ^1.0  but laravel 10 support  v 3

**Comment by therealartz** [comment]
Solved by https://github.com/amabnl/amadeus-ws-client/pull/475, https://github.com/amabnl/amadeus-ws-client/pull/476
Should work fine now in v1.14 or v2.0
