### ISSUE TITLE
Payload for Security Authenticate

### ISSUE THREAD

**Issue by dvaynshteyn** [amabnl/amadeus-ws-client#49]
I was curious if you had an example payload of how to make a Security Authenticate call.  I am getting this error about my headers for the SOAP call: '12|Presentation|soap message header incorrect'.  I am attempting to implement this call with python and need an example payload.  I understand that for all other calls headers required are: SequenceNumber, Session, and SequenceNumber but cannot find documentation on headers/payload for Security_Authenticate.  Here is an example payload with errors.  Any help would be greatly appreciated.

```<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://xml.amadeus.com/VLSSLQ_06_1_1A" xmlns:ns2="http://webservices.amadeus.com/definitions">
   <SOAP-ENV:Header>
      <ns2:SessionId></ns2:SessionId>
      <ns2:SequenceNumber></ns2:SequenceNumber>
      <ns2:SecurityToken></ns2:SecurityToken>
   </SOAP-ENV:Header>
   <SOAP-ENV:Body>
       <Security_Authenticate>
           <userIdentifier>
               <originIdentification>
                   <sourceOffice>{{office_id}}</sourceOffice>
               </originIdentification>
               <originatorTypeCode>{{originator_type_code}}<originatorTypeCode>
               <originator>{{user}}<originator>
           </userIdentifier>
           <passwordInfo>
               <binaryData>{{password}}</binaryData>
               <dataLength>{{password_length}}</dataLength>
               <dataType>{{data_type}}</dataType>
           </passwordInfo>
           <dutyCode>
               <dutyCodeDetails>
                   <referenceQualifier>{{ref_qualifier}}</referenceQualifier>
                   <referenceIdentifier>{{ref_identifier}}</referenceIdentifier>
               </dutyCodeDetails>
           </dutyCode>
           <systemDetails>
               <organizationDetails>
                   <organizationId>{{organization}}</organizationId>
               </organizationDetails>
           </systemDetails>
       </Security_Authenticate>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

**Comment by DerMika** [comment]
Hi, 

First of all, you need to know the "Soap Header version" for the WSAP (the access point to the Amadeus web services) that is enabled for the application you're developing.

What you've posted here is (almost) how a `Security_Authenticate` message would look when sending it to a Soap Header 2 WSAP.

I have a sample of a working _(it has dummy credentials of course, so you can't actually authenticate with it)_ `Security_Authenticate` message for Soap Header 2: See [this file](https://github.com/amabnl/amadeus-ws-client/blob/master/tests/Amadeus/Client/Session/Handler/testfiles/soapheader2/dummySecurityAuth.txt). As you can see, for the `Security_Authenticate` call you don't need to send _any_ headers at all.


Now, if you find out that your WSAP is using Soap Header 4, it's going to be a bit more complicated. That uses an Amadeus-adapted version of [WS-Security](https://en.wikipedia.org/wiki/WS-Security) which requires a bunch more headers as well as a specific way to deal with sending the password. 

If that's the case, you should look for the Amadeus web services extranet and look for the Soap Header 4 implementation guide. It will explain all the headers needed and how to send the password with code samples _(sadly not for Python though)_. You can find it under "Technical doc ->WBS -> SOAP header 4.0 Implementation Guide.

By the way, are you planning to open source this python library of yours? Please send me the link, I might consider contributing ;)

**Comment by DerMika** [comment]
Hi, do you have an update for me? If not, I'm going to close this issue...

**Comment by dvaynshteyn** [comment]
Hi, sorry about the late response.  Thanks so much for your help!  After downloading SoapUI and using that tool I was able to use your payloads with some modified headers =).  Thanks again!
