### ISSUE TITLE
Support for multiple WSDL's

### ISSUE THREAD

**Issue by DerMika** [amabnl/amadeus-ws-client#5]
New information from Amadeus, they now provide WSAP's with multiple WSDL's:

> There are multiple WSDL files inside a WSAP and this is actually one of the new things to handle. Because what happened is the new native XML web services within Amadeus have been created as “interfaces” and split in several WSDL files by area (one per interfaces). 

We will have to find an easy way to handle multiple WSDL files *(multiple `\SoapClient` objects?)* and select the correct SoapClient depending on which message is being sent.

**Comment by fayax** [comment]
Are you able to add support for Fare_InformativePricingWithoutPNR function?

**Comment by DerMika** [comment]
Sure, but could you please report that as a separate issue?

**Comment by DerMika** [comment]
With the merging of the PR above, this feature is now implemented.
