### ISSUE TITLE
problem add farepricing

### ISSUE THREAD

**Issue by DaoCastro** [amabnl/amadeus-ws-client#52]
hi ,
I have a problem when I want to add a fare to an existing pnr that I just created. This is the code I'm using. I do not know if I'm doing something wrong

private function ticketCreateTST($pnr,$client)
    {
        $pnrResult = $client->pnrRetrieve(
            new PnrRetrieveOptions(['recordLocator' => $pnr]),
            ['endSession' => true]
        );
        $pricingResponse = $client->farePricePnrWithBookingClass(
            new FarePricePnrWithBookingClassOptions([
                'overrideOptions' => [
                    FarePricePnrWithBookingClassOptions::OVERRIDE_RETURN_ALL
                ]
            ])
        );
        $createTstResponse =  $client->ticketCreateTSTFromPricing(
                                    new TicketCreateTstFromPricingOptions([
                                    'pricings' => [
                                        new Pricing([
                                            'tstNumber' =>1
                                        ])
                                    ]
                                ])
                            );
        $client->pnrAddMultiElements(
                new PnrAddMultiElementsOptions([
                    'actionCode' => PnrAddMultiElementsOptions::ACTION_END_TRANSACT //ET: END AND RETRIEVE
                ])
            );
    }

**Comment by DerMika** [comment]
And what is the problem you're having?
