### ISSUE TITLE
not add SR DOCS 

### ISSUE THREAD

**Issue by DaoCastro** [amabnl/amadeus-ws-client#53]
I have a problem when I want to add a sr docs to a passenger since when I query it in amadeus it does not appear I am using this to add it

>$Elements=array();
        array_push($Elements,new Ticketing([
                    'ticketMode' => Ticketing::TICKETMODE_OK
                ]));
        array_push($Elements,new Contact([
            'type' => Contact::TYPE_PHONE_GENERAL,
            'value' => $numerocelular
        ]));
        array_push($Elements,new FormOfPayment([
            'type' => FormOfPayment::TYPE_CASH
        ]));
        $index=0;
        foreach($pasajeros as $pasajero){
            array_push($Elements,
                new ServiceRequest([
                        'type' => 'DOCS',
                        'status' => ServiceRequest::STATUS_HOLD_CONFIRMED,
                        'quantity' => 1,
                        'freeText' => [
                            '-----'.str_pad($dianacimiento[$index], 2, "0", STR_PAD_LEFT).''.$this->returnMonths($mesnacimiento[$index]).''.substr($anonacimiento[$index], -2).'-'.$generoPasjeros[$index].'--'.$pasajero.'-'.$pasajerosApellidos[$index].''
                    ],
                    'references' => [
                        new Reference([
                            'type' => Reference::TYPE_PASSENGER_REQUEST,
                            'id' => ($index+1)
                        ])
                    ]
                ])
            );
            $index++;
        }
        //dd($Elements);
        return $Elements;

**Comment by DerMika** [comment]
I'm not sure how I can help you solve this. I don't know what's the message being sent to Amadeus, I don't know whether or not you're doing an End Transact after adding SRDOCS, I don't know whether your Passenger ID's match with the reference you provide in this sample code. 

If you want me to be able to help you, you have tell me about the workflow surrounding this call, and you have to provide me some logs about what is being sent to Amadeus and what result you're getting versus what you expect.

**Comment by DaoCastro** [comment]
my problem is no save srdoc for traveller


$pnrResult = $client->pnrRetrieve(
            new PnrRetrieveOptions(['recordLocator' => "6EJRYC"]),
            ['endSession' => true]
        );

$opt=new PnrCreatePnrOptions([
                'elements' =>[ 
                    new ServiceRequest([
                            'type' => 'DOCS',
                            'status' => ServiceRequest::STATUS_HOLD_CONFIRMED,
                            'quantity' => 1,
                            'company' => 'AV',
                            'freeText' => [
                                '-----01APR93-F--TERESA-CAMPOS'
                        ],
                        'references' => [
                            new Reference([
                                'type' => Reference::TYPE_PASSENGER_REQUEST,
                                'id' => 1
                            ])
                        ]
                    ])
                ]
            ]);
            $createdPnr = $client->pnrCreatePnr($opt);

$pnrReply =$client->pnrAddMultiElements(
                        new PnrAddMultiElementsOptions([
                            'actionCode' => PnrAddMultiElementsOptions::ACTION_END_TRANSACT_RETRIEVE //ET: END AND RETRIEVE
                        ])
                    );

**Comment by DerMika** [comment]
Have you checked if you get any kind of error?

**Comment by DaoCastro** [comment]
Yes and does not have any errors

**Comment by DaoCastro** [comment]
this is the result

{"pnrHeader":{"reservationInfo":{"reservation":{"companyId":"1A","controlNumber":"6EJRYC","date":"220317","time":"1803"}}},"securityInformation":{"responsibilityInformation":{"typeOfPnrElement":"RP","agentId":"WSSU","officeId":"JFK1S210L","iataCode":"33598482"},"queueingInformation":{"queueingOfficeId":"JFK1S210L"},"cityCode":"JFK","secondRpInformation":{"creationOfficeId":"JFK1S210L","agentSignature":"9998WS","creationDate":"220317","creatorIataCode":"33598482","creationTime":"1654"}},"freetextData":{"freetextDetail":{"subjectQualifier":"3","type":"P12"},"longFreetext":"--- RLR SFP ---"},"pnrHeaderTag":{"statusInformation":[{"indicator":"RLR"},{"indicator":"SFP"}]},"sbrPOSDetails":{"sbrUserIdentificationOwn":{"originIdentification":{"originatorId":"33598482","inHouseIdentification1":"JFK1S210L"},"originatorTypeCode":"T"},"sbrSystemDetails":{"deliveringSystem":{"companyId":"1A","locationId":"JFK"}},"sbrPreferences":{"userPreferences":{"codedCountry":"US"}}},"sbrCreationPosDetails":{"sbrUserIdentificationOwn":{"originIdentification":{"originatorId":"33598482","inHouseIdentification1":"JFK1S210L"},"originatorTypeCode":"T"},"sbrSystemDetails":{"deliveringSystem":{"companyId":"1A","locationId":"JFK"}},"sbrPreferences":{"userPreferences":{"codedCountry":"US"}}},"sbrUpdatorPosDetails":{"sbrUserIdentificationOwn":{"originIdentification":{"originatorId":"33598482","inHouseIdentification1":"JFK1S210L"},"originatorTypeCode":"T"},"sbrSystemDetails":{"deliveringSystem":{"companyId":"1A","locationId":"JFK"}},"sbrPreferences":{"userPreferences":{"codedCountry":"US"}}},"technicalData":{"enveloppeNumberData":{"sequenceDetails":{"number":"53"}},"lastTransmittedEnvelopeNumber":{"currentRecord":"52"},"purgeDateData":{"dateTime":{"year":"2017","month":"6","day":"1"}}},"travellerInfo":{"elementManagementPassenger":{"reference":{"qualifier":"PT","number":"2"},"segmentName":"NM","lineNumber":"1"},"passengerData":{"travellerInformation":{"traveller":{"surname":"HERNANDEZ","quantity":"1"},"passenger":{"firstName":"PEDRO","type":"ADT"}},"dateOfBirth":{"dateAndTimeDetails":{"qualifier":"706","date":"01021991"}}},"enhancedPassengerData":{"enhancedTravellerInformation":{"travellerNameInfo":{"quantity":"1","type":"ADT"},"otherPaxNamesDetails":{"nameType":"UN","referenceName":"Y","displayedName":"Y","surname":"HERNANDEZ","givenName":"PEDRO"}},"dateOfBirthInEnhancedPaxData":{"dateAndTimeDetails":{"qualifier":"706","date":"01021991"}}}},"originDestinationDetails":{"originDestination":{},"itineraryInfo":{"elementManagementItinerary":{"reference":{"qualifier":"ST","number":"1"},"segmentName":"AIR","lineNumber":"2"},"travelProduct":{"product":{"depDate":"010617","depTime":"1945","arrDate":"020617","arrTime":"0220","dayChangeIndicator":"1"},"boardpointDetail":{"cityCode":"SAL"},"offpointDetail":{"cityCode":"JFK"},"companyDetail":{"identification":"AV"},"productDetails":{"identification":"670","classOfService":"K"},"typeDetail":{"detail":"ET"}},"itineraryMessageAction":{"business":{"function":"1"}},"itineraryReservationInfo":{"reservation":{"companyId":"AV","controlNumber":"6EJRYC"}},"relatedProduct":{"quantity":"1","status":"HK"},"elementsIndicators":{"statusInformation":{"indicator":"TSA"}},"flightDetail":{"productDetails":{"equipment":"320","numOfStops":"0","weekDay":"4"},"arrivalStationInfo":{"terminal":"4"},"facilities":{"entertainement":"M","entertainementDescription":"D"}},"selectionDetails":{"selection":{"option":"P2"}},"markerRailTour":{}}},"dataElementsMaster":{"marker2":{},"dataElementsIndiv":[{"elementManagementData":{"reference":{"qualifier":"OT","number":"3"},"segmentName":"AP","lineNumber":"3"},"otherDataFreetext":{"freetextDetail":{"subjectQualifier":"3","type":"5"},"longFreetext":"755224114"}},{"elementManagementData":{"reference":{"qualifier":"OT","number":"17"},"segmentName":"AP","lineNumber":"4"},"otherDataFreetext":{"freetextDetail":{"subjectQualifier":"3","type":"5"},"longFreetext":"55555555555"}},{"elementManagementData":{"reference":{"qualifier":"OT","number":"5"},"segmentName":"TK","lineNumber":"5"},"ticketElement":{"passengerType":"PAX","ticket":{"indicator":"OK","date":"220317","officeId":"JFK1S210L"}}},{"elementManagementData":{"reference":{"qualifier":"OT","number":"16"},"segmentName":"SSR","lineNumber":"6"},"serviceRequest":{"ssr":{"type":"OTHS","status":{"0":" "},"companyId":"1A","freeText":"PLEASE SEND AVTA TKNA BY 1654\/25MAR GMT USING ATN ENTRY"}}},{"elementManagementData":{"reference":{"qualifier":"OT","number":"15"},"segmentName":"SK","lineNumber":"7"},"serviceRequest":{"ssr":{"freeText":"RESTRICTED"}},"referenceForDataElement":{"reference":{"qualifier":"PT","number":"2"}}},{"elementManagementData":{"reference":{"qualifier":"OT","number":"2"},"segmentName":"RM","lineNumber":"8"},"miscellaneousRemarks":{"remarks":{"type":"RM","freetext":"NOTIFY PASSENGER PRIOR TO TICKET PURCHASE & CHECK-IN: FEDERAL LAWS FORBID THE CARRIAGE OF HAZARDOUS MATERIALS - GGAMAUSHAZ"}},"extendedRemark":{"structuredRemark":{"type":"RM","freetext":"NOTIFY PASSENGER PRIOR TO TICKET PURCHASE & CHECK-IN: FEDERAL LAWS FORBID THE CARRIAGE OF HAZARDOUS MATERIALS - GGAMAUSHAZ"}},"referenceForDataElement":{"reference":{"qualifier":"ST","number":"1"}}},{"elementManagementData":{"reference":{"qualifier":"OT","number":"4"},"segmentName":"FP","lineNumber":"9"},"otherDataFreetext":{"freetextDetail":{"subjectQualifier":"3","type":"16"},"longFreetext":"CASH"}}]}}

**Comment by DaoCastro** [comment]
{"elementManagementData":{"status":"ERR","reference":{"qualifier":"OT","number":"18"},"segmentName":"SSR","lineNumber":"3"},"serviceRequest":{"ssr":{"type":"DOCS","status":"HK","quantity":"1","companyId":"AV","freeText":"-----01APR93-F--TERESA-CAMPOS"}},"elementErrorInformation":{"errorInformation":{"errorDetail":{"errorCode":"1949","qualifier":"EC","responsibleAgency":"1A"}},"elementErrorText":{"freetextDetail":{"subjectQualifier":"3"},"text":"PASSENGER AND\/OR SEGMENT DATA NOT VALID"}}}]}}
