### ISSUE TITLE
FareInformativePricingWithoutPnr Error

### ISSUE THREAD

**Issue by fayax** [amabnl/amadeus-ws-client#54]
Hi,

I get the following error when I made fareInformativePricingWithoutPnr call.

Notice: Undefined property: Amadeus\Client\RequestOptions\Air\SellFromRecommendation\Segment::$marketingCompany in /vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/Struct/Fare/InformativePricing13/SegmentGroup.php on line 63

Notice: Undefined property: Amadeus\Client\RequestOptions\Air\SellFromRecommendation\Segment::$arrivalDate in /vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/Struct/Fare/InformativePricing13/SegmentGroup.php on line 84

Notice: Undefined property: Amadeus\Client\RequestOptions\Air\SellFromRecommendation\Segment::$airplaneCode in /vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/Struct/Fare/InformativePricing13/SegmentGroup.php on line 92

Notice: Undefined property: Amadeus\Client\RequestOptions\Air\SellFromRecommendation\Segment::$nrOfStops in /vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/Struct/Fare/InformativePricing13/SegmentGroup.php on line 92

Notice: Undefined property: Amadeus\Client\RequestOptions\Air\SellFromRecommendation\Segment::$inventory in /vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/Struct/Fare/InformativePricing13/SegmentGroup.php on line 70

if I specify `use Amadeus\Client\RequestOptions\Fare\InformativePricing\Segment;` I get the following error `Cannot use Amadeus\Client\RequestOptions\Fare\InformativePricing\Segment as Segment because the name is already in use`
I'm sure I didn't specify it any other place in my code.

**Comment by fayax** [comment]
This happens if I have specified
`use Amadeus\Client\RequestOptions\Air\SellFromRecommendation\Segment` 
And
`use Amadeus\Client\RequestOptions\Fare\InformativePricing\Segment` together.

So if I use full name space in  `FareInformativePricingWithoutPnrOptions`  segments part it works fine.

`segments' => [
                    new  \Amadeus\Client\RequestOptions\Fare\InformativePricing\Segment([ ])
]
`

**Comment by DerMika** [comment]
This is a class name collision, you can solve it by specifying an alias as described [here](
http://php.net/manual/en/language.namespaces.importing.php): 
‘use Amadeus\Client\RequestOptions\Fare\InformativePricing\Segment as PricingSegment;‘

**Comment by fayax** [comment]
Solved it
