### ISSUE TITLE
Fare_MasterPricerTravelBoardSearch maximum number of stops?

### ISSUE THREAD

**Issue by joakim-malmquist** [amabnl/amadeus-ws-client#55]
In FareMasterPricerTbSearch I can use:
'requestedFlightTypes' => [Client\RequestOptions\FareMasterPricerTbSearch::FLIGHTTYPE_NONSTOP,];
if I don't want any stops at all.

Is it possible to search for example maximum 2 stops?

**Comment by DerMika** [comment]
I believe MasterPricer supports it, but my library doesn't support this option yet. I'm currently investigating how to do this in `Fare_MasterPricerTravelBoardSearch`. I'll keep you informed!

**Comment by joakim-malmquist** [comment]
I asked my collegues (who work in Amadeus Selling Platform).
The closest thing to a MasterPricer-search is FXD in cryptic mode.
With FXD it isn't possible search by stop, but they have:
/FN for non-stop
/FD for direct
/FC for connecting
i.e. the same thing as in MasterPricer.

**Comment by DerMika** [comment]
I found an option in MasterPricer in the docs called "progressive legs": 

> Progressive legs enables to request a range of number of connections relative to the minimum connections that exist on Journey Server. This range of number of connections is the progressive legs range.
> 
> Progressive legs is triggered by input options:
> 
> - Minimum number of progressive connections (MIC).
> - Maximum number of progressive connections (MAC).
> 
> The minimum and maximum number are numeric values from 0 to n.

Is this what you need?

**Comment by joakim-malmquist** [comment]
I'll test MIC & MAC. See this as solved if I don't come back. :)

**Comment by DerMika** [comment]
No, the library doesn't support these options yet, I was just asking if these were the options you were looking for - so I could implement them! _(in fact, I'm going to implement them anyway, just wanted to hear if these would solve your problem)_

**Comment by joakim-malmquist** [comment]
Ah, sorry!
Yes please, I would be grateful if you implemented them.
I just thought I could test if it was what I was looking for first - it isn't that hard hack just one option to the xml-code if everything else is already done. :)

**Comment by DerMika** [comment]
Done! You can test it by setting the branch `dev-master` in your `composer.json` and doing a `composer update`.

This feature will be added to the upcoming 1.3.0 release.

See a sample here: https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/masterpricertravelboard.rst#progressive-legs

If this doesn't solve your problem, don't hesitate to re-open or create a new issue.
