### ISSUE TITLE
ATC Refunds

### ISSUE THREAD

**Issue by bimusiek** [amabnl/amadeus-ws-client#56]
Hey,
I just checked `Ticket_Checkeligiblity` and it works, slowly going to implement rest of the endpoints in our system. Thanks a lot for your work!

I only realized now, there are 2 endpoints missing to be able to support ATC Refunds:
- `DocRefund_InitRefund`
- `DocRefund_UpdateRefund`

There is also last endpoint that process the refund, but we are not IATA licensed so our consolidator will be taking care of it. (thus, we dont need it)

Thanks. 👍

**Comment by DerMika** [comment]
I'm confused. Do you mean that you still need the 2 DocRefund messages mentioned?

**Comment by bimusiek** [comment]
Yes

**Comment by DerMika** [comment]
One down, one to go. [Samples for DocRefund_InitRefund here](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples.rst#docrefund-initrefund)

**Comment by DerMika** [comment]
Oh god, the next one seems like a lot of work. Tell me when it becomes urgent, because I don't have the time right now!

**Comment by bimusiek** [comment]
@DerMika I will focus on ATC and LCCs and then I will work on DocRefund, so no hurry. We will probably need it in a month or something.

**Comment by DerMika** [comment]
DocRefund_UpdateRefund is now also implemented. See [sample](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples.rst#docrefund-updaterefund)

**Comment by DerMika** [comment]
I've added `DocRefund_ProcessRefund` too. I know you said you didn't need it, but since I was working on the refunds anyway...

**Comment by DerMika** [comment]
FYI: Version 1.4.0 has just been released with the 3 new DocRefund messages included.

**Comment by bimusiek** [comment]
Thanks! Still waiting for ATC activation 😞 Amadeus people have some issues with enabling it since weeks.
