### ISSUE TITLE
SalesReports_DisplayQueryReport unwanted conversion to integer

### ISSUE THREAD

**Issue by ktechadmin** [amabnl/amadeus-ws-client#59]
, when initializing SalesReportsDisplayQueryReportOptions we have to give parameters and one of them is 'agencyIataNumber' => "03430953"  , so when give my iata like that , what happens is leading zero gets removed when generated the xml. so response comes "NO PRIMARY OFFICE ID. FOUND FOR THIS IATA",

Actual output:

				<ns1:originatorDetails>
					<ns1:originatorId>3430953</ns1:originatorId>
				</ns1:originatorDetails>

expected output : 

				<ns1:originatorDetails>
					<ns1:originatorId>03430953</ns1:originatorId>
				</ns1:originatorDetails>
can you please fix this ?

**Comment by DerMika** [comment]
Yeah. I see the problem.

The thing is that this node "originatorId" is defined in the XSD as an integer `NumericInteger_Length1To9` which causes PHP's SOAP extension to do a conversion to an integer. I'm not really aware of a way to influence this behaviour, so I'm not sure if anything can be done besides modifying the XSD in question and defining that node as a string.

![Original definition](https://cloud.githubusercontent.com/assets/2979463/24582577/27dafa2a-1733-11e7-98ff-7a84492d40b6.png)

I just tested a workaround, and you can redefine that node as an `AlphaNumericString_Length1To9` and save the updated XSD file. If you do that, the conversion to integer no longer happens:

![Hacked definition](https://cloud.githubusercontent.com/assets/2979463/24582594/7deba662-1733-11e7-9a87-c1deb0c95db9.png)

XML query after change to AlphaNumericString_Length1To9:
```xml
<ns1:SalesReports_DisplayQueryReport>
	<ns1:agencyDetails>
		<ns1:sourceType>
			<ns1:sourceQualifier1>REP</ns1:sourceQualifier1>
		</ns1:sourceType>
		<ns1:originatorDetails>
			<ns1:originatorId>03430953</ns1:originatorId>
		</ns1:originatorDetails>
	</ns1:agencyDetails>
	<ns1:requestOption>
		<ns1:selectionDetails>
			<ns1:option>SAN</ns1:option>
		</ns1:selectionDetails>
	</ns1:requestOption>
</ns1:SalesReports_DisplayQueryReport>
```

Please let me know if this workaround fixes your problem. I don't know how else to solve it.

**Comment by ktechadmin** [comment]
Hi DerMika ,

yeah above workaround fixed the issue , thanks a lot, your really developing great library to the community .

quick question off topic, are you employed by Amadeus to develop this library or doing as hobby ?

**Comment by DerMika** [comment]
This is a personal hobby project.
