### ISSUE TITLE
Implement Fare_PricePnrWithBookingClass message version 13 and up

### ISSUE THREAD

**Issue by DerMika** [amabnl/amadeus-ws-client#6]
Received a request to implement Fare_PricePnrWithBookingClass version 14.1. Currently only version 12.x and lower is implemented (version 13 and higher have a completely different request XML structure)

**Comment by jcarriquiry** [comment]
Thanks a lot for your contribution. This library has all the necesary to implement any integration with Amadeus. The examples of use that you provide in the test folder are very useful. I'm working with it to implement fligths booking and to this moment I haven't any problem,

**Comment by DerMika** [comment]
Thanks for your comments!

I will assume that the message is working fine and close this issue. If you test it and experience any problems with it, feel free to open a bug report!
