### ISSUE TITLE
Which Request to use for multi city search

### ISSUE THREAD

**Issue by nikhildeshmukh** [amabnl/amadeus-ws-client#60]
Hi 
I really thankyou for this WS Client class truly appreciated
i have a doubt on the question  below
Can i get an example how to use multi city search ?

**Comment by DerMika** [comment]
I have a sample in the docs [here](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/masterpricertravelboard.rst#multi-city-airline-exclusion)

Is this what you're looking for?

**Comment by nikhildeshmukh** [comment]
Thank you !!  Probably this might be the one but how do i use this for my below example

1 april 2017 - BOM -> DXB
5 april 2017  DXB -> BKK
10 april 2017 BKK -> BOM

**Comment by DerMika** [comment]
That's not the same as multicity, that's an itinerary of 3 flights. 

You can request that in Fare_MasterPricerTravelBoardSearch by making an itinerary consisting of 3 elements, like the example [here](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/masterpricertravelboard.rst#return-flight-multiple-passengers-date-range) *(there are only 2 itinerary elements in this example, but you can add as many as you like)*

**Comment by nikhildeshmukh** [comment]
Thank you Dermika !!!

**Comment by DerMika** [comment]
Please keep in mind that it's not my goal to give every user of this library support to find the right call to make etc. 

I provide the library with documentation, but you should talk to your Amadeus support contact to find the correct messages to send for the functionality you want to achieve. I can give you a hand to "translate" the information provided by Amadeus' to using this library.

**Comment by DerMika** [comment]
Is your problem solved now? If so, I'd like to close this issue.

**Comment by nikhildeshmukh** [comment]
yes please close this issue
