### ISSUE TITLE
Fare_CheckRules

### ISSUE THREAD

**Issue by nikhildeshmukh** [amabnl/amadeus-ws-client#61]
Any idea why i am getting this ?
What am i doing wrong with this

Amadeus\Client\Result Object ( [status] => FATAL [messages] => Array ( [0] => Amadeus\Client\Result\NotOk Object ( [code] => Function ("Fare_CheckRules") is not a valid method for this service [text] => [level] => ) ) [response] => [responseXml] => )

**Comment by DerMika** [comment]
Are you sure you have the `Fare_CheckRules` message in your WSDL?

**Comment by nikhildeshmukh** [comment]
Please close this issue
I have one more doubt regarding this request which i will start a new topic

**Comment by DerMika** [comment]
You know, as issue creator, you can close your own issues ;) But I'll do it for you now.
