### ISSUE TITLE
FareCheckRulesOptions after FareMasterPricerTbSearch

### ISSUE THREAD

**Issue by nikhildeshmukh** [amabnl/amadeus-ws-client#62]
Can we use FareCheckRulesOptions after FareMasterPricerTbSearch
Can i have an example ? I spent hours on this and am unable to do so ?
this is what i am using after FMPT

`$rulesResponse = $client->fareCheckRules(
        new FareCheckRulesOptions([
            'recommendations' => [1]       
        ])
    );`

Also i was unable to search GetFareRules example in the repository ?

**Comment by DerMika** [comment]
Hi, 

According to the `Amadeus WBS Implementation Guide - Internet Booking Engine with Master Pricer` (which you can download on the web services extranet), a Fare_CheckRules can be done after a _pricing_ or Fare Display entry, it doesn't say anything about after a MasterPricer entry:

> Fare_CheckRules (FQN) is used to display fare notes after Fare Display or after Pricing transactions. (This PSP service provides the same information as the cryptic FQN transaction.)  

Now, I'm not 100% sure if you can't do a `Fare_CheckRules` after a Fare_MasterPricerTravelBoardSearch, but to really get to the bottom of this, I suggest you get in touch with the Amadeus support contact which should be assigned to your project.

**Comment by bimusiek** [comment]
I can help because I was investigating this topic. How to get rules for search. 

There are 3 endpoints to get all rules (also mini rules, so parsed standardized data):
- `MiniRule_GetFromPricing` - this has to be called just after pricing call
- `MiniRule_GetFromPricingRec` - this has to be called in stateful session after retrieving PNR
- `Fare_CheckRules` - this has to be called after Fare Display or after Pricing transactions

If you need rules for the recommendation, what we do is:
- Call `Fare_InformativePricingWithoutPNR`
- Then call `MiniRule_GetFromPricing` or `Fare_CheckRules`

If you want to get mini rules for all recommendations, there is flag `MRI` (if I am not mistaken) than would return additional xml node in recommendations. However, it requires special Amadeus functionality to be added to your OID.

**Comment by nikhildeshmukh** [comment]
Cool !!! 
I will give a shot and will let you know on the same.

**Comment by bimusiek** [comment]
> BTW what about GetFareRules ? how can i get that ?
What do you mean?

**Comment by nikhildeshmukh** [comment]
In WSDL there is one more service called GetFareRules and i did not find any sample code in this repository for that..

**Comment by DerMika** [comment]
Such a service does not exist on the Amadeus Web Services, as far as I am aware. 

Are you sure you're looking at a proper (unmodified) WSDL from Amadeus?

**Comment by nikhildeshmukh** [comment]
These options are in the Fare options on https://webservices.amadeus.com i am talking about the 2nd one

Fare_CheckRules
Fare_GetFareRules
Fare_InformativeBestPricingWithoutPNR
Fare_InformativePricingWithoutPNR
Fare_MasterPricerCalendar
Fare_MasterPricerTravelBoardSearch
Fare_PricePNRWithBookingClass

**Comment by bimusiek** [comment]
I have no access to this endpoint also.

**Comment by nikhildeshmukh** [comment]
do you both want me to give you the xsd ?

**Comment by DerMika** [comment]
No, I just found it on the extranet. 

I hadn't heard of it yet _(and it's not implemented in this library)_ but it seems to support getting fare rules for a fare defined by ticketing time, fare basis, airline, departure, arrival, and maybe a few others. 

I suppose you could use that message after a MasterPricer call if you can get the necessary parameters from the `Fare_MasterPricerTravelBoardSearchReply`. Although I suggest checking with Amadeus if this message actually works before deciding to use it. The latest version they've released it 10.1, which makes me a bit suspicious.

**Comment by nikhildeshmukh** [comment]
ok so before closing this issue here 
can i use this as my flow as @bimusiek  suggested
my first request will be FareMasterPricerTbSearch then to get more specific i will use FareInformativePricingWithoutPnrOptions and then i will use Fare_CheckRules 
does this sounds ok ?

**Comment by DerMika** [comment]
Yes, this sounds OK. An Informative Pricing call can be followed by a Fare_CheckRules call, so that should work just fine.

But again, you should be asking these kinds of questions to your Amadeus support contact. That's why you pay them for support.

**Comment by nikhildeshmukh** [comment]
Confirmed on Amadeus that Fare_GetFareRules message works. 
Can you please add this message in this library i am sure this will be usefull for others too.

**Comment by nikhildeshmukh** [comment]
> If you need rules for the recommendation, what we do is:

    Call Fare_InformativePricingWithoutPNR
    Then call MiniRule_GetFromPricing or Fare_CheckRules

Hi according to this i got an response on Fare_InformativePricingWithoutPNR
but how to link the message for Fare_CheckRules
i am always getting 

`[errorFreeText] => stdClass Object
                        (
                            [freeText] => ENTRY REQUIRES PREVIOUS PRICING/FARE DISPLAY REQUEST
                        )
`

**Comment by DerMika** [comment]
Are you using a stateful session? If not, that error is to be expected.

**Comment by nikhildeshmukh** [comment]
yes i am using stateful 
some times i am getting 
CHECK SEQUENCE NUMBER and ENTRY REQUIRES PREVIOUS PRICING/FARE DISPLAY REQUEST
randomly. 
i believe i have to send as this for fareCheckRules 
`use Amadeus\Client\RequestOptions\FareCheckRulesOptions;

$previousSessionData = [
        'sessionId' => '01JXF4MNCY',
        'sequenceNumber' => 4,
        'securityToken' => '3QSLT5HYGT3ZO2AKLAT2HFWAC8'
    ];
    
$client->setSessionData($previousSessionData);

    $rulesResponse = $client->fareCheckRules(
     new FareCheckRulesOptions([
            'recommendations' => [2],
            'fareComponents' => [2],
            'categoryList' => true
        ])
    );`

**Comment by nikhildeshmukh** [comment]
sorry my bad 
selected fare component does not exist (ex: 50 fare
components are returned if we ask
information about the 51st)

**Comment by DerMika** [comment]
So will you still need `Fare_GetFareRules`? If so, can you please open a separate issue for that?

**Comment by nikhildeshmukh** [comment]
yes sure
