### ISSUE TITLE
Fare_GetFareRules missing in the library

### ISSUE THREAD

**Issue by nikhildeshmukh** [amabnl/amadeus-ws-client#63]
Hi 
i am unable to find Fare_GetFareRules in the library.
Can we have an example for the same ?

**Comment by nikhildeshmukh** [comment]
@DerMika Cool i am waiting for 1.4.0

**Comment by DerMika** [comment]
`Fare_GetFareRules` is now implemented on the master branch. You can test by switching your `composer.json` to `dev-master`. See samples [here](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples.rst#fare-getfarerules)

Will be released in the 1.4.0 release.

**Comment by nikhildeshmukh** [comment]
Thanks a lot @DerMika 
Will check on this

**Comment by DerMika** [comment]
FYI: Version 1.4.0 has just been released.
