### ISSUE TITLE
How to Request Seat with PNR_AddMultiElements

### ISSUE THREAD

**Issue by oualid13** [amabnl/amadeus-ws-client#64]
Hi,

In the documentation we couldn't find an exemple of how to make a Seat Request using this library.
Is it implemented??

Thank you in advance.

**Comment by DerMika** [comment]
No, it's not supported yet. I'll add that feature.

**Comment by DerMika** [comment]
Hi, 

Support for seat requests is implemented. It will be released when I release version 1.4.0. but you can already test it out by setting `dev-master` in your composer.json and doing a `composer update`.

See an example here: https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/pnr-create-modify.rst#seat-request

**Comment by oualid13** [comment]
Thanks a lot. It was very fast!!

Thank you again.

**Comment by DerMika** [comment]
Apologies, I only implemented the example on the User Guide page. I'll add seat selection soon.

**Comment by DerMika** [comment]
Selecting seat number is now supported too. I've added a second sample: https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/pnr-create-modify.rst#seat-request

**Comment by oualid13** [comment]
Thank you very much for your efforts, I do really appreciate.

**Comment by DerMika** [comment]
FYI: Version 1.4.0 has just been released

**Comment by oualid13** [comment]
Thank you very much
