### ISSUE TITLE
SOAP Requests Not Retrieving Group PNR info

### ISSUE THREAD

**Issue by chris206** [amabnl/amadeus-ws-client#66]
Hi Deiter,

We have no trouble requesting individual passenger records, but Group space fails to retrieve any data whatsoever. This is a problem for us. Are we missing something simple?

@bradatkins

**Comment by DerMika** [comment]
Hi, 

Can you tell me which message you're calling, what expected to get, and what's missing?

Assuming you're talking about `PNR_Retrieve`, I can find the following information in the PNR retrieve guide on the Extranet: 

> The following operations are not available within this service: 
> 
> - ...  
> - Retrieval of group PNRs with individual names returned
> - ...
> 

Does this answer your question?

**Comment by chris206** [comment]
Apparently, Amadeus is sending us the information based on order numbers entered into a remark (rm)
It is just not sending us anything for group booking

**Comment by DerMika** [comment]
> Amadeus is sending us the information based on our order numbers entered into a remark (rm)

What you are describing here is not "standard" behavior of the Amadeus Web Services (nor of this library), so my guess is you need to dig into your own code a little deeper.

If you want me to be able to help you, I need more detailed information about what _this library_ is doing and where it doesn't work as you expected.

**Comment by DerMika** [comment]
Hi @chris206, do you have an update for me? If not, I'm going to close this issue.

**Comment by chris206** [comment]
Hi Deiter - sorry, I answered you in my head without typing...

We use something totally different. Apparently ACSP is what we should be using. Sorry about that

**Comment by DerMika** [comment]
It happens :)

No problem.
