### ISSUE TITLE
RF element added many times

### ISSUE THREAD

**Issue by bimusiek** [amabnl/amadeus-ws-client#68]
Hey, I see from the code that RF element is being added automatically. 
https://github.com/amabnl/amadeus-ws-client/blob/c16cd0dad34ea23c78716406f8e1b226c2fec225/src/Amadeus/Client/RequestCreator/Converter/PNR/AddMultiElementsConv.php#L46

However, if you use AddMultiElements many times, then it should only be added once, thus I would suggest to allow users to specify when to send it and not add it automatically as you do it only on PNR creation. 

I got warning from Amadeus when we do new certification that it should only be sent once. 

What do you think? I can prepare PR for it.

**Comment by DerMika** [comment]
Well, the first problem I see now is backwards compatibility. Removing this now will cause things to break.

**Comment by bimusiek** [comment]
Then maybe 

```php
"receivedFrom" => IgnoreElement()
```
? 

This way we could check while creating request to not include received from. 

Or there could be another param `ignoreReceivedFrom`, no idea what is the best approach here.

**Comment by DerMika** [comment]
Did this issue cause you problems with your certification? Does Amadeus ask that you change this?

**Comment by DerMika** [comment]
I'll have to think about the best way to solve this.

**Comment by DerMika** [comment]
Ok, so maybe we could change the automagic of it to only add an RF when the actioncode is any kind of save action? 

I don't think that would result in a BC break.

**Comment by DerMika** [comment]
But... The problem I see with that solution is that you don't know if an RF was added manually in a previous PNR_AddMultiElements while the PNR was still in context.

**Comment by bimusiek** [comment]
Plus, I can imagine using PNR_AddMultiElements while changing existing PNR, which would add RF element again. I understand the point of making API as easy to use for new users but it won't fly in certification 🏅

**Comment by DerMika** [comment]
So what I'm thinking of now - for backwards compatibility - is a second parameter when calling the message:

```php
$client->pnrAddMultiElements($admultiopt, ['noAutoRf' => true]);
```

And then we can decide for version 2.0 of we want to continue the automatic adding of RF elements or if the user of the library is completely responsible for it.

**Comment by DerMika** [comment]
Ok, I've implemented a fix to override the automatic addition of an RF element when doing a PNR_AddMultiElement. I made it a property in the request options after all, because it made more sense.

Sample here: https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/pnr-create-modify.rst#disable-automatically-adding-a-received-from-rf-element

**Comment by bimusiek** [comment]
Thanks a lot! 🎉
