### ISSUE TITLE
Message DocIssuance_IssueTicket

### ISSUE THREAD

**Issue by jcarriquiry** [amabnl/amadeus-ws-client#7]
Dieter: Have you plans to develop the DocIssuance_IssueTicket message?  Thanks.

**Comment by DerMika** [comment]
Yes, it is on my to-do list. If you have a need for it, I'll add it to the library shortly, when I can find the time.

**Comment by DerMika** [comment]
Hello @jcarriquiry, I've implemented DocIssuance_IssueTicket in #fe20c14. Please see the examples at https://github.com/amabnl/amadeus-ws-client/blob/develop/docs/samples.rst#docissuance_issueticket.

I'm considering this issue closed. If you come across any problems with it, please open a new ticket!

**Comment by jcarriquiry** [comment]
Hello Dieter. Thanks again!!! I'll use it and then I'll coment you the results.

How I said in previous messages, excellent job! 

Best regards!
