### ISSUE TITLE
Fare_InformativePricingWithoutPNR - Sending FOP 

### ISSUE THREAD

**Issue by bimusiek** [amabnl/amadeus-ws-client#72]
Hey, while working on LCC I realized one thing, there is no way to get CC fee before payment. 

Amadeus support told me that the best way to get CC fee for LCC is to ask `Fare_InformativePricingWithoutPNR` together with FOP, which should return price with CC fee included.

I checked sources and it is not yet implemented by the lib. 
How it looks like:
```xml
<pricingOptionGroup>
    <pricingOptionKey>
        <pricingOptionKey>FOP</pricingOptionKey>
    </pricingOptionKey>
    <formOfPaymentInformation>
        <formOfPayment>
            <type>CC</type>
            <amount>10</amount>
            <creditCardNumber>400000</creditCardNumber>
        </formOfPayment>
        <otherFormOfPayment>
            <type>CA</type>
        </otherFormOfPayment>
    </formOfPaymentInformation>
</pricingOptionGroup>
```
``` Can contain up to 3 forms of payment```
```Note: if 1 FOP is sent, amount is conditional. If 2 are sent, amount must be provided for 1 or 2 of them. If 3 are sent, amount must be provided for exactly 2 of them.```

Any plans on supporting it? 😈 
Cheers, Mike.

**Comment by DerMika** [comment]
Ehh, I guess so. I was just working on UpdateRefund now. I'll put this on the list ;)

**Comment by DerMika** [comment]
I've added support for Form of Payment override in all `Fare_*` pricing messages: 

* `Fare_PricePNRWithBookingClass`
* `Fare_PricePNRWithLowerFares`
* `Fare_PricePNRWithLowestFare`
* `Fare_InformativePricingWithoutPNR`
* `Fare_InformativeBestPricingWithoutPNR`

As well as in `Service_IntegratedPricing`

Here is a [sample](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/pricepnr.rst#form-of-payment-override).

**Comment by bimusiek** [comment]
Hey, thanks a lot! :) 

Btw, example is wrong, FOP should be on `new PricingOptions` level ;)

**Comment by bimusiek** [comment]
And I love Amadeus <3 
```"[911] UNEXPECTED ERROR IN AIRLINE'S SERVER"``` 😂 
Just when I send FOP...

**Comment by DerMika** [comment]
> Btw, example is wrong, FOP should be on new PricingOptions level ;)

What do you mean? The sample I provided is how you have to enter FOP data in the `Fare_PricePNRWithBookingClass` (and other pricing) messages. Is it not working for you?

**Comment by bimusiek** [comment]
@DerMika Ah, I did not look on what kind of method is in example. My bad.
