### ISSUE TITLE
psr/log dependency conflict with Yii2 advanced

### ISSUE THREAD

**Issue by kh-mirzaev** [amabnl/amadeus-ws-client#73]
Help! I can't install (downoad) amadeus ws client to my Yii2 advanced project.
![default](https://cloud.githubusercontent.com/assets/9079935/25734610/46a47f7a-317e-11e7-8e9b-89fce4f2c3a0.PNG)

**Comment by DerMika** [comment]
I have released a bugfix release 1.3.1 which should fix your problem. Please try again and let me know if it's fixed now!

**Comment by kh-mirzaev** [comment]
Worked ! Thanks you!
