### ISSUE TITLE
Use of the Project

### ISSUE THREAD

**Issue by DaoCastro** [amabnl/amadeus-ws-client#75]
To use this project would need to give recognition to the creator could use if doing that?

**Comment by DerMika** [comment]
Hi, Sorry for the delay in my answer.

I've open sourced this library under the Apache 2 license, so all you have to do is uphold the rules in the Apache 2 license. 

You can find some info here: 

- http://oss-watch.ac.uk/resources/apache2
- https://softwareengineering.stackexchange.com/questions/56927/what-are-the-real-life-implications-for-an-apache-2-license
- https://www.whitesourcesoftware.com/whitesource-blog/top-10-apache-license-questions-answered

**Comment by DerMika** [comment]
Hi, is your question answered? If so, can this issue be closed?

**Comment by DerMika** [comment]
Closing due to lack of feedback. Feel free to reopen if you have any more questions.
