### ISSUE TITLE
Session / Not authenticated Issue.

### ISSUE THREAD

**Issue by sucl** [amabnl/amadeus-ws-client#77]
I tried the securityAuthenticate() and returned response with status **ok**  and statuscode **p**,

but after that, when I call fareMasterPricerTravelBoardSearch() it returns response with **soap:Client** **99|Session|Not authenticated** 

Kindly suggest us, if I am missing something here?

**Comment by DerMika** [comment]
Did you configure the client to use a stateful session? [See this section](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#switching-between-stateful-stateless-messages-soap-header-4) in the documentation.

**Comment by sucl** [comment]
No, client is configured for stateless.

$params = new Params([
			'authParams' => [
				'officeId' => 'xxxxxxxxxx',
				'userId'   => 'xxxxxxxxxx', 
				'passwordData' => base64_encode('xxxxxxx'), 
				'passwordLength' => strlen('xxxxxxx')
			],
			'sessionHandlerParams' => [
				'soapHeaderVersion' => Client::HEADER_V4, 
				'wsdl' => site_url().'assets/wsdl/AmadeusWebServices.wsdl', 
				'stateful' => false, 
				'logger' => new Psr\Log\NullLogger()
			],
			'requestCreatorParams' => [
				'receivedFrom' => 'company' 
			]
		]);

**Comment by sucl** [comment]
Its working now. I was using wrong WSDL. After using correct one, it working. Thank you DerMika

**Comment by DerMika** [comment]
No problem!
