### ISSUE TITLE
DocIssuance_IssueTicket : INVALID FORM OF PAYMENT

### ISSUE THREAD

**Issue by zakch17** [amabnl/amadeus-ws-client#78]
Hi,

We are having a very strange issue while issuing a ticket and calling DocIssuance_IssueTicket with IB, AF, MS, and AT. we are getting the following error: INVALID FORM OF PAYMENT from the DocIssuance_IssueTicket service. 

Do you have any idea of what's happening?
I was thinking that these airlines companies require a different structure for cash payment for example: instead of sending 'CA' in the form of payment we send something else.

**<ns1:formOfPayment>
	<ns1:fop>
	    <ns1:identification>CA</ns1:identification>
	</ns1:fop>
</ns1:formOfPayment>**

Best,

**Comment by DerMika** [comment]
This could be a lot of things, but you should really talk to your Amadeus support contact to help you check out what's wrong. 

At ticket issuance, the system will check the FP element present in the PNR (if any), and it could be denied for many many reasons. 

To get to the bottom of this, you need someone to check your exact situation at that time, which is something I can't do. You need someone with access to the Web Services logs: your Amadeus support. You'll have to give them your Session ID, GMT timestamp of when your session happened, and explain your situation to them. 

I provide the library, but I can't provide support for these kinds of issues, I'm afraid.

**Comment by zakch17** [comment]
Thank you very much, however, the issue is clear, for example, IB accepts form of payment (FOP) as 'CASH,' and the system is sending 'CASH' (without the float), thus this will cause the error. Is there any way from the library to send the FOP as freeText?

Thank you very much indeed,

**Comment by DerMika** [comment]
How was the the FP element created in the first place?

There are 2 messages in this library that can be used to create FP elements: `FOP_CreateFormOfPayment` (see [sample docs](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/fop-createfop.rst)) and `PNR_AddMultiElements` (see [sample docs](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/pnr-create-modify.rst#form-of-payment-fp)).

I saw in the Amadeus Extranet that this is a way to create a FP Cash with a given amount: 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<PNR_AddMultiElements>
	<pnrActions>
		<optionCode>0</optionCode>
	</pnrActions>
	<dataElementsMaster>
		<marker1/>
		<dataElementsIndiv>
			<elementManagementData>
				<segmentName>FP</segmentName>
			</elementManagementData>
			<formOfPayment>
				<fop>
					<identification>CA</identification>
					<amount>96.46</amount>
				</fop>
			</formOfPayment>
		</dataElementsIndiv>
	</dataElementsMaster>
</PNR_AddMultiElements>
```

However the "amount" option isn't implemented in this library yet. Is that what you need to do? If so, I can implement it for you.
