### ISSUE TITLE
Question about using service request

### ISSUE THREAD

**Issue by zhaonan0218** [amabnl/amadeus-ws-client#79]
First of all, thank you very much for your effort and dedication to this project, it helped me a lot to get started and have a better understanding of how each request works. However, when I was trying to use the Service_IntegratedPricing, I always got "NEED ITINERARY" error message, I tried using PNR retrieve before this request but still the same result. Could you let me know how can I get the proper result? Error message is attached.

Also could you give me a hint about implementing Service_IntegratedCatalogue? We are trying to get the includes services from that request.

Thank you again 👍 
![screen shot 2017-06-24 at 5 48 10 pm](https://user-images.githubusercontent.com/7049324/27512157-5547ffb2-5905-11e7-8759-75f4aeaf739b.png)

**Comment by DerMika** [comment]
Hi, about using `Service_IntegratedPricing`, you need to use this message in a [stateful session](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#switching-between-stateful-stateless-messages-soap-header-4) with a PNR in context (some [more explanation of placing a PNR in context here](https://github.com/amabnl/amadeus-ws-client/issues/67#issuecomment-295650747)).

As long as you have AIR segments in the PNR, you shouldn't get the `NEED ITINERARY` error. For further support debugging this error, I can only recommend you contact your Amadeus support contact who should have been assigned to your project.

I haven't implemented `Service_IntegratedCatalogue` but it is on the [to-do list](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/list-of-supported-messages.rst). However I don't have a lot of time on my hands right now so I can't give you any promises as to when it could be included. If you want to do it yourself, check for example the [Pull Request I made to implement DocRefund_UpdateRefund](https://github.com/amabnl/amadeus-ws-client/pull/74/files) as an example of what needs to be done to implement a new message into the library.

Basically what you need to do:
- Add a method to call the message to `Amadeus\Client`
- Add a Request Options object where a user of the library can provide parameters to be sent to the message (`Amadeus\Client\RequestOptions\ServiceIntegratedCatalogueOptions`)
- Add the necessary Request structure which is a PHP-copy of the XML structure to be sent to the Amadeus Web Services (`Amadeus\Client\Struct\Service\IntegratedCatalogue`)
- Add a Request Creator which converts the Request Options object to the Structure object (`Amadeus\Client\RequestCreator\Converter\Service\IntegratedCatalogueConv`)
- Add a Response Handler which looks for error messages in the response from the Amadeus Web Services server (`Amadeus\Client\ResponseHandler\Service\HandlerIntegratedCatalogue`)
- Add unit tests keeping the coverage to 100%
- Add documentation to `docs/samples.rst` of how to use the message.

If you want to wait for me to implement the message (again, I can't say when I'll find the time), please open a separate issue requesting its implementation.

**Comment by zhaonan0218** [comment]
Thank you very much for the detailed reply, I will definitely give the new class a try, also a request for it. Again thank you for this great project and your help.

**Comment by DerMika** [comment]
I'll be closing this issue since your original question seems to be solved.
