### ISSUE TITLE
Response as XML

### ISSUE THREAD

**Issue by ldjvc** [amabnl/amadeus-ws-client#8]
Hi Dieter, for pnrRetrieve (and others) there is the option to receive the response "asString". Would it be difficult to to have an option "asXML" so that we can store the PNR_reply body as raw XML? Thanks.

**Comment by DerMika** [comment]
I'm not sure what you mean, Isn't the "asString" option providing you with the raw PNR_Reply XML message? That's exactly what this option is for?

If this option is not sufficient for you, can you tell me what you're missing when using that option?

Also keep in mind that on the dev branch, I'm implementing a Result object which will provide both the SoapClient result object as well as the XML string at the same time (as well as a success/error/warning status).

**Comment by ldjvc** [comment]
Dieter, I do owe you an apology. It works as you describe. The problem was in my debug script which was stripping tags. Sorry about that. I'll take a look at the DEV branch as well, a return object would be good to make return errors a bit easier to process.

**Comment by DerMika** [comment]
No problem, glad to hear it's working for you.
