### ISSUE TITLE
Facing problem while calling Fare_PricePNRWithBookingClass. 

### ISSUE THREAD

**Issue by sucl** [amabnl/amadeus-ws-client#83]
I am using stateless method.

After calling PNR_Retrieve, I called Fare_PricePNRWithBookingClass for pricing PNR. But when called, it get error message from API.

[code] => 1383
[text] => PNR NOT PRESENT

**Comment by DerMika** [comment]
Hi, 

This message cannot be used statelessly. You need a PNR in context to issue a pricing on. 

Switch to a stateful session and make sure a PNR is active in the session.

**Comment by sucl** [comment]
Thanks a lot @DerMika 

You made my day :)
