### ISSUE TITLE
soap:client issue in amadeus 

### ISSUE THREAD

**Issue by kunwarali** [amabnl/amadeus-ws-client#84]
Hi team,
we are facing problem in fare travel board search.
it gives error please check below XML response.
<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:awsse="http://xml.amadeus.com/2010/06/Session_v3" 

xmlns:wsa="http://www.w3.org/2005/08/addressing">
<soap:Header><wsa:To>http://www.w3.org/2005/08/addressing/anonymous</wsa:To>
<wsa:From>
<wsa:Address>https://nodeD1.test.webservices.amadeus.com/1ASIWMFPWRE</wsa:Address></wsa:From>
<wsa:Action>http://webservices.amadeus.com/FMPTBQ_14_3_1A</wsa:Action>
<wsa:MessageID>urn:uuid:d4296416-7649-5884-b544-946a6bea4606</wsa:MessageID>
<wsa:RelatesTo RelationshipType="http://www.w3.org/2005/08/addressing/reply">0ddb1d9f-8891-2f53-b824-c4bf5fbb0932</wsa:RelatesTo>
<awsse:Session TransactionStatusCode="End"><awsse:SessionId>01K97B3CM4</awsse:SessionId>
<awsse:SequenceNumber>1</awsse:SequenceNumber><awsse:SecurityToken>1ODPYEI2MX7F91LO7D4ZG4HVF6</awsse:SecurityToken></awsse:Session>
</soap:Header>
<soap:Body>
<soap:Fault>
<faultcode>soap:Client</faultcode>
<faultstring> 11|Session|</faultstring>
</soap:Fault>
</soap:Body>
</soap:Envelope>

Regards,
-Kunwar Ali

**Comment by DerMika** [comment]
Hi, have you been able to do any other message using this library? This error is the error you also get when you send faulty authentication credentials. 

Please double-check your password, and make sure you provide the password in a base64 encoded format, as the [docs](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/about-get-started.rst#set-up-a-test-client) explain.

**Comment by kunwarali** [comment]
Hi Der Mika,

Greeting of the day.
Yes I have checked.
Yesterday it was working fine.

Regards,
-Kunwar Ali

**Comment by DerMika** [comment]
Ok, in that case I suggest you contact Amadeus and ask them to investigate why you're getting this error. 

The 11 Session error is not related to any particular message, it's on the session & authentication level. So whatever you're trying to do with your masterpricer message is irrelevant to this error.

**Comment by kunwarali** [comment]
Hi Der Mika,

Greeting of the day.
thanks u so much for your great support.

Regards,
-kunwar Ali
