### ISSUE TITLE
xml request latest version of web service

### ISSUE THREAD

**Issue by ktechadmin** [amabnl/amadeus-ws-client#89]
HI,

when we use the PNR Retrieve its using version 10 as shown below even though version 14.2 is available in WSDL, so how to make this library  latest version or predefined version of xml request version. where do i need to change ? 

-------------------------------
`<?xml version="1.0" encoding="UTF-8"?> <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://xml.amadeus.com/PNRRET_10_1_1A" xmlns:ns2="http://www.w3.org/2005/08/addressing" xmlns:ns3="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wsswssecurity-secext-1.0.xsd" xmlns:ns4="http://xml.amadeus.com/2010/06/Session_v3" xmlns:ns5="http://xml.amadeus.com/2010/06/Security_v1"><REMOVED><SOAP-ENV:Body><ns1:PNR_Retrieve><ns1:retrievalFacts><ns1:retrieve><ns1:type>2</ns1:type></ns1:retrieve><ns1:reservationOrProfileIdentifier><ns1:reservation><ns1:controlNumber>??????</ns1:controlNumber></ns1:reservation></ns1:reservationOrProfileIdentifier></ns1:retrievalFacts></ns1:PNR_Retrieve></SOAP-ENV:Body></SOAP-ENV:Envelope> `

**Comment by DerMika** [comment]
You have to remove the old versions from the WSDL. 

Currently the library can't deal with multiple versions of the same message in the WSDL.

**Comment by DerMika** [comment]
Did manually removing fix the problem? If so, I'll close this issue.

**Comment by DerMika** [comment]
Closing due to lack of feedback
