### ISSUE TITLE
Adding Tour code (FT element)

### ISSUE THREAD

**Issue by XYNOMEX** [amabnl/amadeus-ws-client#90]
Hello,

is there any way to add tourCode element to PNR_AddMultiElements.

```xml
<PNR_AddMultiElements xmlns="http://xml.amadeus.com/PNRADD_17_1_1A">
    <pnrActions>
        <optionCode>0</optionCode>
    </pnrActions>
    <dataElementsMaster>
        <marker1></marker1>
        <dataElementsIndiv>
            <elementManagementData>
                <reference>
                    <qualifier>OT</qualifier>
                    <number>1</number>
                </reference>
                <segmentName>FT</segmentName>
            </elementManagementData>
            <tourCode>
                <passengerType>PAX</passengerType>
                <freeFormatTour>
                    <indicator>FF</indicator>
                    <freetext>TOUR CODE</freetext>
                </freeFormatTour>
            </tourCode>
        </dataElementsIndiv>
    </dataElementsMaster>
</PNR_AddMultiElements>
```

thanks,

**Comment by DerMika** [comment]
As you say, the `FT` element is not supported yet in this library. 

I just put it on my to-do list. I can't give any guarantees, but I'll try to do it this week...

**Comment by XYNOMEX** [comment]
Thanks, i really appreciate your help.

**Comment by DerMika** [comment]
Hi, 

I've implemented Tour Code element support in PNR_AddMultiElements. Check out [the sample in the documentation](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/pnr-create-modify.rst#tour-code-ft-free-flow-format). 

If you run into any problems using this, don't hesitate to re-open this issue!

**Comment by DerMika** [comment]
I just wanted to add: it's currently available on the master branch so you can try it by putting the `dev-master` as version in your `composer.json`. 

The feature will be included in the upcoming 1.5.0 release.

**Comment by XYNOMEX** [comment]
Thank you for your help.

**Comment by XYNOMEX** [comment]
Hi,
what files should I update/download to use this feature, I already downloaded "tourcode.php".
thanks,

**Comment by DerMika** [comment]
If you're not using composer, you'll need to update all the files I've modified in the commits that are linked above (well, all the php files anyway) but I really recommend you start using Composer ;)

**Comment by XYNOMEX** [comment]
Sure, and one other thing, if I want to log the XML sent by the API to Amadeus, what should I do is there any option or setting to do that easily?

Thanks,

**Comment by DerMika** [comment]
https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#logging-request-and-response

**Comment by XYNOMEX** [comment]
Hi,
I'm now using monolog, but I'm facing the following error:
.....
$params = new Params([
    'sessionHandlerParams' => [
        'logger' => $msgsLog
        // Other parameters omitted in this example
    ]
]);
try {
	$client = new Client($params);
} catch (Exception $e) {
	var_dump($e);
}

Result: 

object(InvalidArgumentException)#8 (7) { ["message":protected]=> string(18) "Invalid parameters" ["string":"Exception":private]=> string(0) "" ["code":protected]=> int(0) ["file":protected]=> string(100) "C:\Inetpub\vhosts\trippering.info\httpdocs\api\src\Amadeus\Client\Session\Handler\HandlerFactory.php" ["line":protected]=> int(46) ["trace":"Exception":private]=> array(4) { [0]=> array(6) { ["file"]=> string(74) "C:\Inetpub\vhosts\trippering.info\httpdocs\api\src\Amadeus\Client\Base.php" ["line"]=> int(136) ["function"]=> string(13) "createHandler" ["class"]=> string(45) "Amadeus\Client\Session\Handler\HandlerFactory" ["type"]=> string(2) "::" ["args"]=> array(1) { [0]=> object(Amadeus\Client\Params\SessionHandlerParams)#6 (8) { ["wsdl"]=> array(0) { } ["soapHeaderVersion"]=> string(1) "4" ["authParams"]=> NULL ["stateful"]=> bool(true) ["logger"]=> NULL ["soapClientOptions"]=> array(0) { } ["overrideSoapClient"]=> NULL ["overrideSoapClientWsdlName"]=> NULL } } } [1]=> array(6) { ["file"]=> string(74) "C:\Inetpub\vhosts\trippering.info\httpdocs\api\src\Amadeus\Client\Base.php" ["line"]=> int(105) ["function"]=> string(18) "loadSessionHandler" ["class"]=> string(19) "Amadeus\Client\Base" ["type"]=> string(2) "->" ["args"]=> array(2) { [0]=> NULL [1]=> object(Amadeus\Client\Params\SessionHandlerParams)#6 (8) { ["wsdl"]=> array(0) { } ["soapHeaderVersion"]=> string(1) "4" ["authParams"]=> NULL ["stateful"]=> bool(true) ["logger"]=> NULL ["soapClientOptions"]=> array(0) { } ["overrideSoapClient"]=> NULL ["overrideSoapClientWsdlName"]=> NULL } } } [2]=> array(6) { ["file"]=> string(69) "C:\Inetpub\vhosts\trippering.info\httpdocs\api\src\Amadeus\Client.php" ["line"]=> int(170) ["function"]=> string(16) "loadClientParams" ["class"]=> string(19) "Amadeus\Client\Base" ["type"]=> string(2) "->" ["args"]=> array(3) { [0]=> object(Amadeus\Client\Params)#5 (7) { ["requestCreator"]=> NULL ["sessionHandler"]=> NULL ["responseHandler"]=> NULL ["authParams"]=> NULL ["sessionHandlerParams"]=> object(Amadeus\Client\Params\SessionHandlerParams)#6 (8) { ["wsdl"]=> array(0) { } ["soapHeaderVersion"]=> string(1) "4" ["authParams"]=> NULL ["stateful"]=> bool(true) ["logger"]=> NULL ["soapClientOptions"]=> array(0) { } ["overrideSoapClient"]=> NULL ["overrideSoapClientWsdlName"]=> NULL } ["requestCreatorParams"]=> NULL ["returnXml"]=> bool(true) } [1]=> string(24) "amabnl-amadeus-ws-client" [2]=> string(9) "1.5.0-dev" } } [3]=> array(6) { ["file"]=> string(56) "C:\Inetpub\vhosts\trippering.info\httpdocs\api\test1.php" ["line"]=> int(63) ["function"]=> string(11) "__construct" ["class"]=> string(14) "Amadeus\Client" ["type"]=> string(2) "->" ["args"]=> array(1) { [0]=> object(Amadeus\Client\Params)#5 (7) { ["requestCreator"]=> NULL ["sessionHandler"]=> NULL ["responseHandler"]=> NULL ["authParams"]=> NULL ["sessionHandlerParams"]=> object(Amadeus\Client\Params\SessionHandlerParams)#6 (8) { ["wsdl"]=> array(0) { } ["soapHeaderVersion"]=> string(1) "4" ["authParams"]=> NULL ["stateful"]=> bool(true) ["logger"]=> NULL ["soapClientOptions"]=> array(0) { } ["overrideSoapClient"]=> NULL ["overrideSoapClientWsdlName"]=> NULL } ["requestCreatorParams"]=> NULL ["returnXml"]=> bool(true) } } } } ["previous":"Exception":private]=> NULL } string

Regards,

**Comment by DerMika** [comment]
Can you give me a snippet of your total code constructing your client object?

**Comment by XYNOMEX** [comment]
I did solve it, now don't have any error but still, the log file is not created, if I use the example of monolog-->
{
$msgsLog->addWarning('Foo');
$msgsLog->addError('Bar');
}
the log file is created, so I think I might be missing something

$msgsLog = new Logger('RequestResponseLogs');
        $msgsLog->pushHandler(new StreamHandler('C:\....\httpdocs\api\src\Amadeus\Client\requestresponse.log', Logger::INFO));

        $params = new Params([
                'sessionHandlerParams' => [
                'soapHeaderVersion' => Client::HEADER_V4, 
                'wsdl' => 'wsdl/1ASIWBEYIEB_PDT_20170424_074534.wsdl',
                'stateful' => false,
                'logger' =>  $msgsLog,
                'authParams' => [
                'officeId' => 'xxxxx',
                    'userId' => 'xxxxx',
                    'passwordData' => 'xxxxxx'
                ]
            ],
            'requestCreatorParams' => [
                'receivedFrom' => 'xxxxxx'
            ]
        ]);

        $client = new Client($params);

        return $client;

**Comment by DerMika** [comment]
I think we're going beyond the scope of this library here... I'm not really in a position to provide support for Monolog.

**Comment by XYNOMEX** [comment]
Yes, I understand, but the thing is that monolog is working fine alone, the log file is created when I call the log command, but when I send it through the client object nothing happens, I tried several booking.

Can you please help me with this?
thanks in advance,

**Comment by DerMika** [comment]
And what response object are you getting from the library when you try to send the message? 

If the library is somehow unable to do the call due to incorrect configuration, it will not try to send a message but throw an exception earlier. In that case it won't log anything.

**Comment by XYNOMEX** [comment]
let's take this example

        $msgsLog = new Logger('RequestResponseLogs');
        $msgsLog->pushHandler(new StreamHandler('C:\...\httpdocs\api\src\Amadeus\Client\requestresponse.log', Logger::WARNING));

        $params = new Params([
                'sessionHandlerParams' => [
                'soapHeaderVersion' => Client::HEADER_V4, 
                'wsdl' => 'wsdl/1ASIWBEYIEB_PDT_20170424_074534.wsdl',
                'stateful' => false,
                'logger' =>  $msgsLog,
                'authParams' => [
                'officeId' => 'xxxxx',
                    'userId' => 'xxxxx',
                    'passwordData' => 'xxxxxx'
                ]
            ],
            'requestCreatorParams' => [
                'receivedFrom' => 'Trippering'
            ]
        ]);

        $client = new Client($params);
        $pnrResult = $client->pnrRetrieve(
             new PnrRetrieveOptions(['recordLocator' => 'ABC123'])
        );

Is there anything else i should add or any other call i should make to get the log file for the above action.

**Comment by DerMika** [comment]
Well, I'm not sure if a relative path to your WSDL file will work, so that could be one reason why it fails. Apart from that, you could get an error if you don't have the PNR_Retrieve message in your WSDL. 

Those are the two main reasons why it's possible that nothing gets logged to the logfile.

What do you actually get when you try?

**Comment by XYNOMEX** [comment]
I'm trying to log my booking request so i could find out if my request contains the FM commission and tourCode nodes, I'm getting a successful booking with a Valid PNR but I'm unable to send the FM and TourCode, that's why I'm trying to log my booking request to see if the "FM / TourCode" XML nodes exist.

**Comment by XYNOMEX** [comment]
Now I'm able to log $client->getLastRequest() so for this point, i got what I'm looking for but, it seems like my request is missing the FM commission and the TourCode.

**Comment by DerMika** [comment]
Did you add the Tour Code FT element as shown in the docs? https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/pnr-create-modify.rst#tour-code-ft-free-flow-format

And did you add the manual commission element as shown in the docs? https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/pnr-create-modify.rst#manual-commission-fm

**Comment by XYNOMEX** [comment]
Yes I did, and I tried to log the create PNR XML of a successful booking I got the following:

	                           <ns1:dataElementsIndiv>
					<ns1:elementManagementData>
						<ns1:reference>
							<ns1:qualifier>OT</ns1:qualifier>
							<ns1:number>6</ns1:number>
						</ns1:reference>
						<ns1:segmentName>FM</ns1:segmentName>
					</ns1:elementManagementData>
					<ns1:commission>
						<ns1:passengerType>PAX</ns1:passengerType>
						<ns1:indicator>FM</ns1:indicator>
						<ns1:commissionInfo>
							<ns1:percentage>5</ns1:percentage>
						</ns1:commissionInfo>
					</ns1:commission>
				</ns1:dataElementsIndiv>
				<ns1:dataElementsIndiv>
					<ns1:elementManagementData>
						<ns1:reference>
							<ns1:qualifier>OT</ns1:qualifier>
							<ns1:number>7</ns1:number>
						</ns1:reference>
						<ns1:segmentName>FT</ns1:segmentName>
					</ns1:elementManagementData>
					<ns1:tourCode>
						<ns1:passengerType>PAX</ns1:passengerType>
						<ns1:freeFormatTour>
							<ns1:indicator>FF</ns1:indicator>
							<ns1:freetext>BEYAGT05</ns1:freetext>
						</ns1:freeFormatTour>
					</ns1:tourCode>
				</ns1:dataElementsIndiv>

 Booking is successful ticket has been issued TourCode is well received as we checked on the system, but commission still 0 % on the system. is there anything missing in my call / XML.

**Comment by DerMika** [comment]
1. Is there an FM element at all in the PNR in the central system?

2. Can you provide (a snippet of) a PNR_Reply you receive when saving the PNR when you're adding the FM and FT elements? I'm specifically interested to see if the element status is `ERR` or if the central system accepted these elements.

**Comment by XYNOMEX** [comment]
Hey, sorry I was contacting Amadeus, it seems that commission on our account was set to automatic, they switch it to manual, now everything is working as expected.

I'm sorry for wasting your time, and thanks again.

**Comment by DerMika** [comment]
No problem, good to hear it's solved

**Comment by DerMika** [comment]
Version 1.5.0 is released now. You can use this feature on a stable release now by `composer upgrade`-ing  to version 1.5.
