### ISSUE TITLE
Creating multiple instances of clients will result in multiple session?

### ISSUE THREAD

**Issue by MyDcode** [amabnl/amadeus-ws-client#92]
Hi, once again thank you very much for your support.

I wanted clarify few points with the library, as per the Amadeus document I have to use the same session for the entire process of a transaction, by process I mean

Search for recommendation -> Select & Check availability -> Apply PNR Information -> PNR Pricing ->....

now, in all of the above instances I am using following to create instances of the client because they are in different controllers.

```
$params = $this->library->AmadeusHeader->get_header();  //setting security headers
$client = new Client($params);
```

get_header() has the header create information such as responseXml, authParams, sessionHandlerParams, requestCreatorParams (which I extracted and have as a separate source).

So my doubt is,I guess I am creating different session each time and my requests are not linked to each others... if that the case if I store the client data in a cookie when I create it first time will it be a problem? or the library handles it and use the same session all the time whenever I create new instance for client??

Please clear my doubt.

Thank you.

**Comment by DerMika** [comment]
No, one instance of the client will be initialized without session context. When you start sending messages, it will by default create a new session (when running in stateful mode). 

It is however possible to extract session context from the Client after a message has been made. That way you can store the information from the active session for example in your PHP session. When you initialize another client, you can provide the previously used session information to continue a previously started stateful conversation with the Amadeus server. 

See [this section](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#handling-sessions-with-soap-header-2) of the docs, which mentions: 

You can get a current session's info (for later re-use) by calling

```php
    $client->getSessionData();
````

You can restore a previous current session after you retrieved it from your session pool for later re-use:

```php
    $previousSessionData = [
        'sessionId' => 'XFHZEKLRZHREJ',
        'sequenceNumber' => 5,
        'securityToken' => 'RKLERJEZLKRHZEJKLRHEZJKLREZRHEZK'
    ];

    $client->setSessionData($previousSessionData);
```

This is the only way to continue a stateful conversation between different `Amadeus\Client` instances.

**Comment by MyDcode** [comment]
As always, to the point and clarified my doubt.

Thank you very much, and I guess I can close this issue.
