### ISSUE TITLE
class not found error

### ISSUE THREAD

**Issue by ahmedeltokhy** [amabnl/amadeus-ws-client#95]
Hello sir,
I cloned the repo. and created a file to test the connection to the WS I got this error:

> Fatal error: Uncaught Error: Class 'Amadeus\Client\Params' not found in /var/www/html/amadeus/amadeus-ws-client/index.php:10 Stack trace: #0 {main} thrown in /var/www/html/amadeus/amadeus-ws-client/index.php on line 10

the code I used to test the connection is :
```
<?php

use Amadeus\Client;
use Amadeus\Client\Params;
use Amadeus\Client\Result;
use Amadeus\Client\RequestOptions\PnrRetrieveOptions;

//Set up the client with necessary parameters:

$params = new Params([
    'authParams' => [
        'officeId' => 'BRUXX1111', //The Amadeus Office Id you want to sign in to - must be open on your WSAP.
        'userId' => 'WSBENXXX', //Also known as 'Originator' for Soap Header 1 & 2 WSDL's
        'passwordData' => 'dGhlIHBhc3N3b3Jk' // **base 64 encoded** password
    ],
    'sessionHandlerParams' => [
        'soapHeaderVersion' => Client::HEADER_V4, //This is the default value, can be omitted.
        'wsdl' => '/home/user/mytestproject/data/amadeuswsdl/1ASIWXXXXXX_PDT_20160101_080000.wsdl', //Points to the location of the WSDL file for your WSAP. Make sure the associated XSD's are also available.
        'stateful' => false, //Enable stateful messages by default - can be changed at will to switch between stateless & stateful.
        'logger' => new Psr\Log\NullLogger()
    ],
    'requestCreatorParams' => [
        'receivedFrom' => 'my test project' // The "Received From" string that will be visible in PNR History
    ]
]);

$client = new Client($params);

$pnrResult = $client->pnrRetrieve(
    new PnrRetrieveOptions(['recordLocator' => 'ABC123'])
);

if ($pnrResult->status === Result::STATUS_OK) {
    echo "Successfully retrieved PNR, no errors in PNR found!";
    echo "PNR XML string received: <pre>" . $pnrResult->responseXml . "</pre>";
}

```
hope to be easy to be solved

Thanks
Ahmed Atyya

**Comment by DerMika** [comment]
This library is supposed to be installed through [Composer](https://getcomposer.org/). 

If you don't do that, you'll have to make sure that whatever class loader you are using is properly loading the PSR-4 namespaces defined in the library's [composer.json](https://github.com/amabnl/amadeus-ws-client/blob/master/composer.json). 

I strongly advise you use Composer to manage your package dependencies. If you do that, [installation is easy](https://github.com/amabnl/amadeus-ws-client#installation). 

If for some reason you are not able to use Composer, perhaps [this stackoverflow question](https://stackoverflow.com/questions/39571391/psr4-auto-load-without-composer) could be useful for you. _(use this at your own risk!)_

**Comment by DerMika** [comment]
Was your problem solved? If so, can you please close this issue?

**Comment by ahmedeltokhy** [comment]
sorry for the delay of the closing, yes it is solved.
thanks for your support and fast response.

**Comment by vTrip** [comment]
Trying to run this on my AWS ec2 instance. Having trouble requiring the amadeus-ws-client due to missing extension `ext-soap`.

Any tips/instructions besides that in README?
