### ISSUE TITLE
Map flight segment with Price with Amdeus

### ISSUE THREAD

**Issue by munna316** [amabnl/amadeus-ws-client#96]
![image](https://user-images.githubusercontent.com/25523794/30579120-e89817a2-9d34-11e7-9a45-46ef336c589f.png)

**Comment by DerMika** [comment]
Hi, 

This library was built to provide a connection to the Amadeus Web Services, but I do not represent Amadeus. I also don't provide support for interpreting the web services responses. For that you should talk to your Amadeus Support contact which should have been assigned to your project. 

Besides your support contact, you should also look at the [Fare_MasterPricerTravelBoardSearch user guide](https://webservices.amadeus.com/extranet/kdbViewDocument.do?externalId=HTML_UG_WBS_Fare_MasterPricerTravelBoardSearch_FMPTBQ_17.4&docStatus=Published&mpId=se__581_1__5_functional&serviceVersionId=4949) on the Amadeus Web Services Extranet as well as the document _"Amadeus WBS Implementation Guide - Internet Booking Engine with Master Pricer"_ which can also be found on the Extranet.

That said, there has been some previous discussion about interpreting Fare_MasterPricerTravelBoardSearchResponse in issues #46 and #22. Perhaps you can check those out and see if they answer your question.
