### ISSUE TITLE
NEED TICKETING ARRANGEMENT and NEED TELEPHONE Errors

### ISSUE THREAD

**Issue by mostafaahamidmanon** [amabnl/amadeus-ws-client#98]
Hello,
I have the following error:
as attached in the xml file

And my opts are attached in the .php file

May I know the problem and how to get around this?
![screenshot from 2017-10-05 12 30 22](https://user-images.githubusercontent.com/6308541/31222934-10c4081c-a9c9-11e7-837a-d4666b0007db.png)
![screenshot from 2017-10-05 12 32 05](https://user-images.githubusercontent.com/6308541/31223008-45f93584-a9c9-11e7-8288-63dd5cda5f3d.png)

**Comment by DerMika** [comment]
Your "elements" object should be an array, and you also need to add a "Contact" element to that array. That should fix both errors.

**Comment by mostafaahamidmanon** [comment]
That is quick

**Comment by DerMika** [comment]
If your problem is solved, you can close the issue :)

**Comment by mostafaahamidmanon** [comment]
Solved

**Comment by mostafaahamidmanon** [comment]
Thanks
